### ISSUE TITLE
调度日志里查看执行日志时,执行器端后台报错 xxl-rpc provider invokeService error

### ISSUE THREAD

**Issue by kayz666** [xuxueli/xxl-job#1001]
版本 2.0.1  2.1.0 
调度中心查看执行日志时,查看不到日志 仅打印 [Load Log Finish]
使用提供的demo里执行器查看执行日志正常
自己的业务执行器后端打印错误如下
2019-07-11 16:05:02.370 ERROR 23012 --- [Pool-1028609399] c.x.r.r.provider.XxlRpcProviderFactory   : xxl-rpc provider invokeService error.

java.lang.NoSuchMethodException: com.xxl.job.core.biz.impl.ExecutorBizImpl.log(long, int, int)
	at java.lang.Class.getMethod(Class.java:1786)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:217)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:84)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:25)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，版本要保持一致。
