### ISSUE TITLE
spring boot 2.1.6 xxl-rpc provider netty server caught exception

### ISSUE THREAD

**Issue by wind05408** [xuxueli/xxl-job#1013]
spring boot 2.1.6
mysql:5.7 
xxljob 2.0.2
server_client
019-07-16 19:44:53.555 [nioEventLoopGroup-5-1] ERROR c.x.r.r.n.i.n.server.NettyHttpServerHandler - >>>>>>>>>>> xxl-rpc provider netty server caught exception
java.lang.NoSuchMethodError: io.netty.buffer.ByteBufUtil.getBytes(Lio/netty/buffer/ByteBuf;)[B
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.channelRead0(NettyHttpServerHandler.java:43)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.channelRead0(NettyHttpServerHandler.java:27)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

xxl-admin
2019-07-16 19:44:58,541 ERROR [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-610853466] c.x.j.a.core.trigger.XxlJobTrigger [XxlJobTrigger.java : 198] >>>>>>>>>>> xxl-job trigger error, please check if the executor[10.168.105.36:9998] is running.
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1563277498541, request:XxlRpcRequest{requestId='c33a4db8-31c5-4ac4-8238-9067c292237c', createMillisTime=1563277493526, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=3, executorHandler='userLeaderJobHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=5, logDateTim=1563277493517, glueType='BEAN', glueSource='', glueUpdatetime=1563261807000, broadcastIndex=0, broadcastTotal=1}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
	at com.sun.proxy.$Proxy81.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wind05408** [comment]
自动注册的时候：
![image](https://user-images.githubusercontent.com/12081066/61293730-ecf10780-a806-11e9-89d0-35270ff52a0d.png)
online 机器地址为空

**Comment by xuxueli** [comment]
你好，从日志 “NoSuchMethodError: io.netty.buffer.ByteBufUtil.getBytes” 来看，应该是Netty版本冲突导致，Netty版本保持和执行器示例中一致即可。

**Comment by wind05408** [comment]
right!
xxl-job netty:4.1.36 Final
cat netty:4.0.25 Final

**Comment by hikrpz** [comment]
请问您这边问题解决了吗？我这边也遇到同样的问题了

**Comment by eanfs** [comment]
请问您这边问题解决了吗？我这边也遇到同样的问题了
