### ISSUE TITLE
调度中心 https的问题

### ISSUE THREAD

**Issue by zjh-coder** [xuxueli/xxl-job#1014]
### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
执行器 调度中心 正常交互
### Actual behavior
执行器访问调度中心出错
### Steps to reproduce the behavior
将调度中心地址配置成https就会出现问题，http则正常
### Other information
com.xxl.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: gscheduler-nonprod.garmin.com/10.124.0.73:80
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227) ~[xxl-rpc-core-1.4.1.jar:?]
	at com.sun.proxy.$Proxy135.registry(Unknown Source) ~[?:?]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) [xxl-job-core-2.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

报错信息如上，执行器会强行连接调度中心的80端口，而调度中心明明配置了https，应该是443端口。用wireshake抓包也可以看出直接走的是http，没有走https，不知道为什么

**Comment by xuxueli** [comment]
建议配置成http格式，加密可以借助提供的AccessToken

**Comment by zjh-coder** [comment]
不使用https不符合公司IT部门的安全规范，而且我已经完成了开发工作。。。

请问有计划支持吗？如果我想自己修改一下的话，有什么建议吗？
