### ISSUE TITLE
c.x.j.core.thread.TriggerCallbackThread  : java.io.EOFException: readObject: unexpected end of file

### ISSUE THREAD

**Issue by LHC087** [xuxueli/xxl-job#1018]
一个放xxl-job-admin 一个放xxl-job-executor-sample-springboot
定时任务是执行成功了，但是总是报如下错误？？？30秒一次
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52) ~[xxl-rpc-core-1.4.1.jar!/:na]
        at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238) ~[xxl-job-core-2.1.0.jar!/:na]
        at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24) ~[xxl-job-core-2.1.0.jar!/:na]
        at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111) ~[xxl-job-core-2.1.0.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.io.EOFException: readObject: unexpected end of file
        at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2173) ~[hessian-4.0.60.jar!/:3.1.0]
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49) ~[xxl-rpc-core-1.4.1.jar!/:na]
        ... 4 common frames omitted

**Comment by xuxueli** [comment]
问题无法复现。
上述问题是回调请求参数序列化失败，应该是网络问题或者回调地址配错了。

**Comment by luckyhlq** [comment]
重试的时候callbacklog 文件解析错误，把callbacklog目录下文件删一下就好了。具体是什么原因导致解析失败，不清楚，没去细看代码。
我是同一台机器，配置了多个执行器，并且执行器的日志目录是一样的情况下出现了

**Comment by TanZhuo1** [comment]
xxl.job.executor.logpath 下的运行日志文件损坏或多个执行器有冲突  删了就行了
