### ISSUE TITLE
xxl-job-admin启动加载i18n报空指针问题

### ISSUE THREAD

**Issue by ltyeamin** [xuxueli/xxl-job#1029]
00:23:10.244 logback [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'requestContextFilter' to: [/*]
00:23:11.177 logback [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobScheduler' defined in URL [jar:file:/root/server/xxl-job-admin-2.1.1-SNAPSHOT/xxl-job-admin-2.1.1-SNAPSHOT-xxl-job.0_test/xxl-job-admin-2.1.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/xxl/job/admin/core/conf/XxlJobScheduler.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
00:23:11.181 logback [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
00:23:11.240 logback [main] INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
00:23:11.252 logback [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobScheduler' defined in URL [jar:file:/root/server/xxl-job-admin-2.1.1-SNAPSHOT/xxl-job-admin-2.1.1-SNAPSHOT-xxl-job.0_test/xxl-job-admin-2.1.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/xxl/job/admin/core/conf/XxlJobScheduler.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.xxl.job.admin.XxlJobAdminApplication.main(XxlJobAdminApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException: null
	at com.xxl.job.admin.core.util.I18nUtil.loadI18nProp(I18nUtil.java:32)
	at com.xxl.job.admin.core.util.I18nUtil.getString(I18nUtil.java:53)
	at com.xxl.job.admin.core.conf.XxlJobScheduler.initI18n(XxlJobScheduler.java:83)
	at com.xxl.job.admin.core.conf.XxlJobScheduler.afterPropertiesSet(XxlJobScheduler.java:43)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 24 common frames omitted

**Comment by xuxueli** [comment]
你好，这只bean加载顺序导致的一个偶发问题。
问题已修复并推送master分支，可以参考master分支，在 XxlJobScheduler 加上：@DependsOn("xxlJobAdminConfig") 即可。

**Comment by ltyeamin** [comment]
好的，非常感谢





------------------ 原始邮件 ------------------
发件人: "许雪里"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午9:12
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com>;
抄送: "꧁꫞꯭P꯭a꯭r꯭i꯭s꯭°꫞"<1301015490@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuxueli/xxl-job] xxl-job-admin启动加载i18n报空指针问题 (#1029)




你好，这只bean加载顺序导致的一个偶发问题。
 问题已修复并推送master分支，可以参考master分支，在 XxlJobScheduler 加上：@DependsOn("xxlJobAdminConfig") 即可。

**Comment by ltyeamin** [comment]
我已经pull最新的源代码没问题，但是我有一个疑问，还请您解答一下，之前报出这个问题的时候是在测试服气启动时候出现的，在本地用IntelliJ IDEA启动为什么不报错，本地一切正常？还请指教,谢谢

**Comment by xuxueli** [comment]
启动加载顺利随机的，IDE应该做了调优。
