### ISSUE TITLE
任务调度持续异常信息

### ISSUE THREAD

**Issue by kervin521** [xuxueli/xxl-job#1048]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.1.0
### Actual behavior
08:06:13.767 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-2076753120] ERROR c.x.j.a.core.trigger.XxlJobTrigger - >>>>>>>>>>> xxl-job trigger error, please check if the executor[172.18.0.32:65534] is running.,
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1564992373767, request:XxlRpcRequest{requestId='d4eddad5-e206-4dbc-be7b-591eb1264a02', createMillisTime=1564992370723, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=829, executorHandler='indexCalculateHandler', executorParams='NGYGXLTBPC', executorBlockStrategy='DISCARD_LATER', executorTimeout=3600, logId=244, logDateTim=1564992370253, glueType='BEAN', glueSource='null', glueUpdatetime=1563267844000, broadcastIndex=0, broadcastTotal=1}], version='null'},
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117),
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219),
	at com.sun.proxy.$Proxy80.run(Unknown Source),
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196),
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149),
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74),
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:76),
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
	at java.lang.Thread.run(Thread.java:748),
08:09:33.075 logback [http-nio-7072-exec-1] ERROR c.x.j.a.controller.JobLogController - java.lang.NoSuchMethodException: com.xxl.job.core.biz.impl.ExecutorBizImpl.log(long, long, int),
	at java.lang.Class.getMethod(Class.java:1786),
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:217),
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:84),
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:25),
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:49),
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
	at java.lang.Thread.run(Thread.java:748),
,
com.xxl.rpc.util.XxlRpcException: java.lang.NoSuchMethodException: com.xxl.job.core.biz.impl.ExecutorBizImpl.log(long, long, int),
	at java.lang.Class.getMethod(Class.java:1786),
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:217),
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:84),
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:25),
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:49),
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
	at java.lang.Thread.run(Thread.java:748),
,
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:221),
	at com.sun.proxy.$Proxy80.log(Unknown Source),
	at com.xxl.job.admin.controller.JobLogController.logDetailCat(JobLogController.java:140),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:498),
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205),
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133),
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97),
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854),
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765),
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85),
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967),
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901),
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970),
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872),
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661),
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846),
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197),
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193),
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166),
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199),
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96),
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493),
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137),
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81),
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87),
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343),
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798),
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66),
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808),
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498),
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49),
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61),
	at java.lang.Thread.run(Thread.java:748),
### Other information

**Comment by xuxueli** [comment]
你好，确认执行器服务是否启动，应该未启动或者网络不通。

**Comment by menglongzhizi** [comment]
我是用的docker启动的xxl-job
命令如下:
docker run -e PARAMS="--spring.datasource.url=jdbc:mysql://192.168.3.12:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 \
--spring.datasource.username=remoteuser \
--spring.datasource.password=Zmma0301! \
--xxl.job.accessToken=1234567890zmma" \
-p 8010:8080 -v /tmp/xxl-job-data:/data/applogs \
--name xxl-job-admin --restart=always  -d xuxueli/xxl-job-admin:2.1.2

php环境跑在宿主机上ip地址为192.168.3.12 监听端口为9000

注意：该docker就跑在这台宿主机上，当任务调度时，抛出如下异常：
请问这是啥问题呢？是因为网络不通么？ 如果是网络不通的话，那读取mysql的数据时可以的哇

2020-09-01 18:45:49,729 ERROR [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-335577197] c.x.job.core.util.XxlJobRemotingUtil [XxlJobRemotingUtil.java : 139] no protocol: 192.168.3.12:9000/run
java.net.MalformedURLException: no protocol: 192.168.3.12:9000/run
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:69)
	at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:83)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
