### ISSUE TITLE
无法终止任务

### ISSUE THREAD

**Issue by gxweigl** [xuxueli/xxl-job#1049]
io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /ip:port
![image](https://user-images.githubusercontent.com/3138613/62452594-1caa8400-b7a3-11e9-88ca-81e832760e4f.png)

**Comment by xuxueli** [comment]
你好，确认对应的执行器是不是未启动，应该未启动。

**Comment by zdd10010806** [comment]
2.0.1 版本终止任务没反应，也没调用destroy() 方法

com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP@369939aa(l:/10.52.101.99:41023 <-> r:/10.1.38.62:9999,closed=false)[HttpChannelOverHTTP@385ec109(exchange=HttpExchange@3c6152da req=TERMINATED/null@null res=PE
NDING/null@null)[send=HttpSenderOverHTTP@7963cb32(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@6c8e9dd(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1305)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
