### ISSUE TITLE
xxl-job-admin服务器启动报错 版本V2.1.0

### ISSUE THREAD

**Issue by luhong327** [xuxueli/xxl-job#1060]
ebk1-xxl-job-admin|main|ERROR|org.springframework.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobScheduler' defined in URL [jar:file:/home/ad/service/ebk-xxl-job-admin-1.0.0.jar!/BOOT-INF/classes!/com/xxl/job/admin/core/conf/XxlJobScheduler.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at com.xxl.job.admin.XxlJobAdminApplication.main(XxlJobAdminApplication.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException: null
        at com.xxl.job.admin.core.util.I18nUtil.loadI18nProp(I18nUtil.java:36)
        at com.xxl.job.admin.core.util.I18nUtil.getString(I18nUtil.java:57)
        at com.xxl.job.admin.core.conf.XxlJobScheduler.initI18n(XxlJobScheduler.java:88)
        at com.xxl.job.admin.core.conf.XxlJobScheduler.afterPropertiesSet(XxlJobScheduler.java:48)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
        ... 24 common frames omitted

**Comment by luhong327** [comment]
com.xxl.job.admin.core.conf.XxlJobAdminConfig和com.xxl.job.admin.core.conf.XxlJobScheduler都实现了InitializingBean接口，但服务器上会先加载XxlJobScheduler的实现方法afterPropertiesSet()；从而报空指针

**Comment by xuxueli** [comment]
你好，这只bean加载顺序导致的一个偶发问题。
问题已修复并推送master分支，可以参考master分支，在 XxlJobScheduler 加上：@DependsOn("xxlJobAdminConfig") 即可。或者等待下个版本发布升级修复。

**Comment by luhong327** [comment]
已解决，com.xxl.job.admin.core.conf.XxlJobScheduler实现了CommandLineRunner接口代替了InitializingBean接口，InitializingBean接口实现方法afterPropertiesSet()里的相应代码放到了 CommandLineRunner接口的实现run()方法里，项目已成功启动，暂时没有发现其他错误
