### ISSUE TITLE
同一台服务器的第二个 executor 启动时报错

### ISSUE THREAD

**Issue by imsuperman0920** [xuxueli/xxl-job#1072]
com.xxl.rpc.util.XxlRpcException: java.lang.InterruptedException
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227)
        at com.sun.proxy.$Proxy53.registry(Unknown Source)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
        at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:108)
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
        ... 3 common frames omitted

**Comment by xuxueli** [comment]
你好，从日志看是注册线程报错，应该是回调地址配置有问题。
