### ISSUE TITLE
执行器重连，导致应用内存溢出

### ISSUE THREAD

**Issue by Spring3Coke** [xuxueli/xxl-job#1086]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Other information
你好，使用的XXL-JOB 2.0.2 版本，在执行器应用中，若调度中心未启动，则会每30秒发起重连操作，这时若一直重连，会导致内存溢出。
观察线程dump，会发现dump日志中，基本都是这样的线程：
`"nioEventLoopGroup-1929-1" #3274 prio=10 os_prio=0 tid=0x00007f85c7385800 nid=0x58d runnable [0x00007f85bfbba000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000e9524280> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000e9514080> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000e9513fa8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:791)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:439)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by oursy** [comment]
@Spring3Coke 遇到同样的问题了，您这边是怎么解决的？

**Comment by xuxueli** [comment]
你好，这个问题新版本已经做了修复，可以参考迭代日志。升级新版本可以解决。

**Comment by oursy** [comment]
@xuxueli  那个版本进行修复的？

**Comment by oursy** [comment]
@xuxueli  那个版本进行修复的？

**Comment by breakenknife** [comment]
@xuxueli  @Spring3Coke @oursy    同样2.0.2 我也遇到这个内存溢出了, 看升级日志后面的版本进行了大重构,不敢升级,请问该怎么解决?
