### ISSUE TITLE
java.lang.IllegalStateException: expected integer at 0x74

### ISSUE THREAD

**Issue by wangyanna13** [xuxueli/xxl-job#1095]
用的1.9.2版本的调度中心，新单独建项目xxl-job-executor-sample-springboot，报错如下：
java.lang.IllegalStateException: expected integer at 0x74
at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:47)
at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:37)
at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
at com.sun.proxy.$Proxy55.registry(Unknown Source)
at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2943)
at com.caucho.hessian.io.Hessian2Input.expect(Hessian2Input.java:2891)
at com.caucho.hessian.io.Hessian2Input.readInt(Hessian2Input.java:825)
at com.caucho.hessian.io.Hessian2Input.readType(Hessian2Input.java:2438)
at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2115)
at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:44)
... 5 common frames omitted

经过尝试发现xxl-job-core 这个引用的版本需要是1.9.1的，这是版本的bug么?

**Comment by xuxueli** [comment]
你好，确认调度中心与执行器版本保持一致。
