### ISSUE TITLE
java.io.EOFException: readObject: unexpected end of file

### ISSUE THREAD

**Issue by guanzhenxing** [xuxueli/xxl-job#1115]
XXL-JOB 2.0.2 版本

“执行器项目”报：

2019-09-02 17:29:34.420 [c.x.j.c.t.TriggerCallbackThread][Thread-6] [2388633] [    ][ERROR] java.io.EOFException: readObject: unexpected end of file
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:233)
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: readObject: unexpected end of file
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2173)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 4 common frames omitted

这个是啥原因？

**Comment by AndyMeng2017** [comment]
+1 遇到同样的问题

**Comment by guanzhenxing** [comment]
解决问题了。跟踪后发现，任务中心和 执行器 部署在同一台服务器上，应该是日志串了。分开部署就没事了。

**Comment by Xxf9126** [comment]
我也同样碰到了 难道不能部署到一台服务器上吗

**Comment by ll-jump** [comment]
callbacklog日志目录下存在大小为0的文件，删掉就可以了
