### ISSUE TITLE
引入consul后xxl-job 客户端注册失败，报xxl-job, executor ExecutorRegistryThread" java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.allocateUninitializedArray(I)异常

### ISSUE THREAD

**Issue by lhdyesok** [xuxueli/xxl-job#1150]
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-consul-all</artifactId>
        </dependency>
项目在引用 consul 后，xxl-job客户端无法启动，异常信息如下：
 [Thread-7] INFO  com.xxl.rpc.remoting.net.Server - >>>>>>>>>>> xxl-rpc remoting server start success, nettype = com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServer, port = 5000
Exception in thread "xxl-job, executor ExecutorRegistryThread" java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.allocateUninitializedArray(I)[B
	at io.netty.util.AsciiString.<init>(AsciiString.java:222)
	at io.netty.util.AsciiString.<init>(AsciiString.java:209)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:47)
	at io.netty.handler.codec.http.HttpHeaderNames.<clinit>(HttpHeaderNames.java:31)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:104)
	at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
	at com.sun.proxy.$Proxy160.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)

请问这是不兼容吗

**Comment by lhdyesok** [comment]
<dependency>
      <groupId>com.corundumstudio.socketio</groupId>
      <artifactId>netty-socketio</artifactId>
      <version>1.7.17</version>
    </dependency>

引入这个jar包后，问题解决了，jar包依赖问题，方法找不到。
有点懵逼，具体问题没找到。
