### ISSUE TITLE
2.1.0版本 admin项目启动方式问题

### ISSUE THREAD

**Issue by ensean** [xuxueli/xxl-job#1170]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
能够通过 java -jar xxl-job-admin-2.1.0.jar 命令启动admin项目
### Actual behavior
java -jar  xxl-job-admin-2.1.0.jar启动时报错( mvn spring-boot:run却可以正常运行）
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
10:36:08.674 logback [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobScheduler' defined in URL [jar:file:/home/vagrant/xxl-job-2.1.0/xxl-job-admin/target/xxl-job-admin-2.1.0.jar!/BOOT-INF/classes!/com/xxl/job/admin/core/conf/XxlJobScheduler.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.xxl.job.admin.XxlJobAdminApplication.main(XxlJobAdminApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException: null
	at com.xxl.job.admin.core.util.I18nUtil.loadI18nProp(I18nUtil.java:32)
	at com.xxl.job.admin.core.util.I18nUtil.getString(I18nUtil.java:53)
	at com.xxl.job.admin.core.conf.XxlJobScheduler.initI18n(XxlJobScheduler.java:83)
	at com.xxl.job.admin.core.conf.XxlJobScheduler.afterPropertiesSet(XxlJobScheduler.java:43)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 24 common frames omitted
```
### Steps to reproduce the behavior
cd xxl-job-admin
mvn clean package
cd target
java -jar xxl-job-admin-2.1.0.jar
### Other information
```
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Private Build
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-119-generic", arch: "amd64", family: "unix"
```

**Comment by ensean** [comment]
duplicate with #1060
