### ISSUE TITLE
查看执行日志报错

### ISSUE THREAD

**Issue by wuhendadi** [xuxueli/xxl-job#1204]
使用镜像部署的xxl-job的2.1.0版本，executor使用的是springboot。任务调度执行都正常，但是查看日志一片空白。查看后台，查看的时候会报错：
2019-10-24 16:15:46,422 ERROR [http-nio-8080-exec-14] c.x.j.a.controller.JobLogController [JobLogController.java : 152] java.lang.NoSuchMethodException: com.xxl.job.core.biz.impl.ExecutorBizImpl.log(long, long, int)
        at java.lang.Class.getMethod(Class.java:1786)
        at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:196)
        at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServerHandler.handle(JettyServerHandler.java:60)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，从日志看是调度中心和执行器测底层依赖不一致导致，确认下。

**Comment by LeroyPine** [comment]
不同的依赖 但是有相同的方法。也会报这个异常
