### ISSUE TITLE
数据库重启以后，就不能调度，看日志,一直在报错 v2.1.0

### ISSUE THREAD

**Issue by wchappygood** [xuxueli/xxl-job#1214]
02:32:18.000 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper#scheduleThread error:{}
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:767)
	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:713)
	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy75.setAutoCommit(Unknown Source)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:62)
	at java.lang.Thread.run(Thread.java:748)
02:32:18.000 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - This connection has been closed.
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:767)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:753)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy75.commit(Unknown Source)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:161)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，这个问题在master分支已经修复，可以pull master体验下。将会在下个版本一同发布。

**Comment by wchappygood** [comment]
> 你好，这个问题在master分支已经修复，可以pull master体验下。将会在下个版本一同发布。

我pull master以后 没有报错日志了 但是任务调度停止问题没有解决

**Comment by shmilyah** [comment]
> > 你好，这个问题在master分支已经修复，可以pull master体验下。将会在下个版本一同发布。
> 
> 我pull master以后 没有报错日志了 但是任务调度停止问题没有解决

你好，这个问题解决了吗？
