### ISSUE TITLE
2.1.0出现连接池满，导致无法调度的问题

### ISSUE THREAD

**Issue by nicygan** [xuxueli/xxl-job#1215]
我使用2.1.0，一共4个任务在调度，近两天发现admin不进行调度，数据库info表中的执行时间停在失效前最后一次执行时间。
重启服务后，又能正常工作了。
查询日志发现以下错误，看起来是连接池满了，但是我就4个调度任务，没道理造成连接池满的，到底是如何造成这个现象的，我没找到。
-------------------------------------------------------------
`        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.tomcat.jdbc.pool.PoolExhaustedException: [http-nio-8090-exec-48] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:30; busy:29; idle:0; lastwait:10000].
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
        at com.sun.proxy.$Proxy58.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:294)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
        at com.sun.proxy.$Proxy70.registryUpdate(Unknown Source)
        at com.xxl.job.admin.service.impl.AdminBizImpl.registry(AdminBizImpl.java:169)
        ... 60 common frames omitted`

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供操作步骤。
可以考虑使用master分支，这个分支调度组件做了调整，自测一段时间很稳当了。
