### ISSUE TITLE
调度中心(HA)-死锁

### ISSUE THREAD

**Issue by chunyingli** [xuxueli/xxl-job#1223]
XXL-JOB version:2.0.1
按照说明搭建两台调度中心机器HA，其中一台宕机后，在另一台机器后出现死锁，从而导致某个任务一直无法调度和执行。（备注：此任务当时已是定时任务，且通过admin管理端手动执行任务也不行）
错误日志如下：
2019-10-30 08:36:38.030 [getSchedulerFactoryBean_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger:2401 - An error occurred while org.quartz.impl.jdbcjobstore.JobStoreSupport$43@3c426f2f
org.quartz.JobPersistenceException: Couldn't release acquired trigger: Lock wait timeout exceeded; try restarting transaction
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2944)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$43.executeVoid(JobStoreSupport.java:2931)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3765)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3763)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3849)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3804)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2927)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:385)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy73.executeUpdate(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTriggerStateFromOtherState(StdJDBCDelegate.java:1439)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2940)
	... 7 common frames omitted

**Comment by xuxueli** [comment]
你好，这个版本底层依靠quartz，quartz底层问题没办法做调整和优化。
高版本已经移除了quartz，规避了quartz的这个问题。建议升级最新版本，可以 pull master分支体验下。
