### ISSUE TITLE
单元测试中，主线程关闭的情况下，ExecutorRegistryThread尝试join方法导致空指针异常

### ISSUE THREAD

**Issue by azraelee** [xuxueli/xxl-job#1251]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
希望不要抛出异常，正常的关闭
### Actual behavior
 [Thread-11] c.x.j.core.thread.TriggerCallbackThread                : null

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:65)
	at java.lang.Thread.run(Thread.java:748)

 [Thread-13] c.x.j.c.thread.ExecutorRegistryThread                  : null

java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:106)
	at com.xxl.job.core.executor.XxlJobExecutor$ExecutorServiceRegistry.stop(XxlJobExecutor.java:167)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory$2.run(XxlRpcProviderFactory.java:105)
	at com.xxl.rpc.remoting.net.Server.onStoped(Server.java:63)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer.stop(JettyServer.java:86)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer$1.run(JettyServer.java:58)
	at java.lang.Thread.run(Thread.java:748)
### Steps to reproduce the behavior
跑单元测试的时候：
初始化XxlJobSpringExecutor
### Other information

**Comment by xuxueli** [comment]
你好，跑单侧之前确定XxlJobSpringExecutor已经被Spring扫描并初始化。
