### ISSUE TITLE
执行器启动报错

### ISSUE THREAD

**Issue by dushuke** [xuxueli/xxl-job#1256]
我把我自己的spring cloud项目改成了执行器，配置没有错，但是启动时报一下错误，请问怎么解决啊
Exception in thread "xxl-job, executor ExecutorRegistryThread" java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.allocateUninitializedArray(I)[B
	at io.netty.util.AsciiString.<init>(AsciiString.java:222)
	at io.netty.util.AsciiString.<init>(AsciiString.java:209)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:47)
	at io.netty.handler.codec.http.HttpHeaderNames.<clinit>(HttpHeaderNames.java:31)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:104)
	at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
	at com.sun.proxy.$Proxy167.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xuxueli** [comment]
重复问题，合并至：https://github.com/xuxueli/xxl-job/issues/1255
