### ISSUE TITLE
执行器下线时报DeadlockLoserDataAccessException异常

### ISSUE THREAD

**Issue by lxl-cm** [xuxueli/xxl-job#1258]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.1.0
### Expected behavior
执行器下线时，可以正常下线
### Actual behavior
- 下线时代码报该异常：
```09:27:54.457 logback [xxl-job, admin JobRegistryMonitorHelper] ERROR c.x.j.a.c.t.JobRegistryMonitorHelper - >>>>>>>>>>> xxl-job, job registry monitor thread error:{}
org.springframework.dao.DeadlockLoserDataAccessException: 
### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
### The error may involve com.xxl.job.admin.dao.XxlJobRegistryDao.removeDead-Inline
### The error occurred while setting parameters
### SQL: DELETE FROM xxl_job_registry   WHERE update_time   <   DATE_ADD(NOW(),INTERVAL -? SECOND)
### Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; SQL []; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:262)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
        at com.sun.proxy.$Proxy57.delete(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.delete(SqlSessionTemplate.java:310)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
        at com.sun.proxy.$Proxy61.removeDead(Unknown Source)
        at com.xxl.job.admin.core.thread.JobRegistryMonitorHelper$1.run(JobRegistryMonitorHelper.java:41)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:391)
        at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy78.execute(Unknown Source)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:213)
        at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
        ... 7 common frames omitted
```
- mysql日志：
```
LATEST DETECTED DEADLOCK
------------------------
2019-11-08 10:10:30 0x7fcebfd71700
*** (1) TRANSACTION:
TRANSACTION 43488574, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 5878986, OS thread handle 140528322774784, query id 136525158 1.1.1.1 root updating
DELETE FROM xxl_job_registry
		WHERE update_time   <   DATE_ADD(NOW(),INTERVAL -90 SECOND)
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 165 page no 4 n bits 72 index PRIMARY of table `xxl_job`.`xxl_job_registry` trx id 43488574 lock_mode X locks rec but not gap waiting
Record lock, heap no 2 PHYSICAL RECORD: n_fields 7; cnpact format; info bits 0
 0: len 4; hex 8000006b; asc    k;;
 1: len 6; hex 00000297953f; asc      ?;;
 2: len 7; hex 01000003be0442; asc       B;;
 3: len 8; hex 4558454355544f52; asc EXECUTOR;;
 4: len 22; hex 78786c2d6a6f622d6578656375746f722d6c6f63616c; asc xxl-job-executor-local;;
 5: len 20; hex 6a6f622e657870656e73652e636f6d3a39393939; asc job.test.cn:9999;;
 6: len 4; hex 5dc4c49a; asc ]   ;;

*** (2) TRANSACTION:
TRANSACTION 43488575, ACTIVE 0 sec updating or deleting, thread declared inside InnoDB 4999
mysql tables in use 1, locked 1
4 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 1
MySQL thread id 5882598, OS thread handle 140525958534912, query id 136525156 1.1.1.1 root updating
UPDATE xxl_job_registry
        SET `update_time` = NOW()
        WHERE `registry_group` = 'EXECUTOR'
          AND `registry_key` = 'xxl-job-executor-local'
          AND `registry_value` = 'job.test.cn:9999'
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 165 page no 4 n bits 72 index PRIMARY of table `xxl_job`.`xxl_job_registry` trx id 43488575 lock_mode X locks rec but not gap
Record lock, heap no 2 PHYSICAL RECORD: n_fields 7; cnpact format; info bits 0
 0: len 4; hex 8000006b; asc    k;;
 1: len 6; hex 00000297953f; asc      ?;;
 2: len 7; hex 01000003be0442; asc       B;;
 3: len 8; hex 4558454355544f52; asc EXECUTOR;;
 4: len 22; hex 78786c2d6a6f622d6578656375746f722d6c6f63616c; asc xxl-job-executor-local;;
 5: len 20; hex 6a6f622e657870656e73652e636f6d3a39393939; asc job.test.cn:9999;;
 6: len 4; hex 5dc4c49a; asc ]   ;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 165 page no 6 n bits 80 index i_u of table `xxl_job`.`xxl_job_registry` trx id 43488575 lock_mode X locks rec but not gap waiting
Record lock, heap no 6 PHYSICAL RECORD: n_fields 2; cnpact format; info bits 0
 0: len 4; hex 5dc4c47c; asc ]  |;;
 1: len 4; hex 8000006b; asc    k;;

*** WE ROLL BACK TRANSACTION (1)
------------
```
### Steps to reproduce the behavior
暂时未找到重现方式
### Other information

**Comment by xuxueli** [comment]
你好，这个问题master分支已经优化，可以参考master分支相关代码修复。会在下个分支一同发布。
