### ISSUE TITLE
quartz总是报连接失败

### ISSUE THREAD

**Issue by mxz668** [xuxueli/xxl-job#1264]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1-SNAPSHOT
### Expected behavior
目前我的项目配置放在阿里nacos配置中心上，连接池用的阿里 Druid，项目启动一段时间以后就会报连接错误，而且连接池IP还会指向本地，请问xxl_job是不是不支持从配置中心读取配置，报错如下：
11-12 14:30:34.893 |-INFO  o.s.s.quartz.SchedulerFactoryBean:721 - Starting Quartz Scheduler now, after delay of 20 seconds
11-12 14:30:34.917 |-INFO  o.s.s.quartz.LocalDataSourceJobStore:866 - Freed 0 triggers from 'acquired' / 'blocked' state.
11-12 14:30:34.922 |-INFO  o.s.s.quartz.LocalDataSourceJobStore:876 - Recovering 0 jobs that were in-progress at the time of the last shut-down.
11-12 14:30:34.923 |-INFO  o.s.s.quartz.LocalDataSourceJobStore:889 - Recovery complete.
11-12 14:30:34.925 |-INFO  o.s.s.quartz.LocalDataSourceJobStore:896 - Removed 0 'complete' triggers.
11-12 14:30:34.927 |-INFO  o.s.s.quartz.LocalDataSourceJobStore:901 - Removed 0 stale fired job entries.
11-12 14:30:34.930 |-INFO  org.quartz.core.QuartzScheduler:547 - Scheduler getSchedulerFactoryBean_$_NON_CLUSTERED started.
11-12 14:30:34.969 |-ERROR c.alibaba.druid.pool.DruidDataSource:2471 - create connection SQLException, url: jdbc:mysql://10.108.10.31:3306/collect?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8, errorCode 1045, state 28000
java.sql.SQLException: Access denied for user 'monitor'@'127.0.0.1' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)

**Comment by xuxueli** [comment]
你好，这是quartz底层的问题。
新版本已经移除了quartz，不会有上述问题，可以升级体验下。
