### ISSUE TITLE
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]

### ISSUE THREAD

**Issue by strongant** [xuxueli/xxl-job#1265]
xxl-job版本： 1.9.1 任务在调度过程中，偶尔不间断出现以下异常,请教下这种异常一般什么场景下产生。 @xuxueli 

Job (104.2450 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException

**Comment by xuxueli** [comment]
你好，这是quartz底层的问题。
新版本已经移除了quartz，不会有上述问题，可以升级体验下。
