### ISSUE TITLE
[超时错误，然后整个应用宕机，已经出现了两次整个问题，从十月份更换成2.2版本之后]com.xxl.rpc.util.XxlRpcException

### ISSUE THREAD

**Issue by zhanzhenguang** [xuxueli/xxl-job#1266]
2019-11-12 09:44:42.103 [xxl-job, executor ExecutorRegistryThread] INFO  com.xxl.job.core.thread.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='download-service-job-executor', registryValue='192.168.0.111:9978'}
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1573523082100, request:XxlRpcRequest{requestId='8111fdc3-992e-4776-b00a-eaacd028c3c4', createMillisTime=1573523079100, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='download-service-job-executor', registryValue='192.168.0.111:9978'}], version='null'}
        at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
        at com.sun.proxy.$Proxy400.registry(Unknown Source)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
        at java.lang.Thread.run(Thread.java:748)

**Comment by 15036900300** [comment]
现在大佬我看了好多issue都不回复，也不知道最终是个什么结果

**Comment by xuxueli** [comment]
你好，从日志看是执行器心跳注册失败，一次心跳失败不影响，后续会重试的。
应用宕机，这个没有复现，建议为应用添加监控。需要提供完成的复现步骤才能处理。
