### ISSUE TITLE
调度任务终止，日志狂刷

### ISSUE THREAD

**Issue by haorendashu** [xuxueli/xxl-job#1271]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

2.1.1-SNAPSHOT

### Actual behavior

调度任务中断了，日志提示数据库连不上

```
The last packet successfully received from the server was 1,000 milliseconds ago.  The last packet sent successfully to the server was 2 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3905)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4807)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
	at com.sun.proxy.$Proxy76.setAutoCommit(Unknown Source)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:62)
	... 1 common frames omitted
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3014)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472)
	... 17 common frames omitted
```

### Steps to reproduce the behavior

其实服务一段时间之后，调度中心会出现调度任务停掉，日志狂刷

### Other information

**Comment by huangst2016** [comment]
的确会出现调度失败（比如数据库连接失败，假设数据库异常崩掉）后，日志狂刷，一天就产生几百个G的日志文件，希望能针对此异常做一些处理，避免服务器磁盘资源耗尽

**Comment by xuxueli** [comment]
这个下个版本会优化，精简日志信息。

**Comment by baobeidaodao** [comment]
> 这个下个版本会优化，精简日志信息。

急切需要！迫切期待啊！

**Comment by syukayo** [comment]
运行后一段时间都会任务挂起，报数据库连接不上。重启后也必定出现，这个是大问题，用不了。

**Comment by zhipingwu** [comment]
能发一下当时虚拟机的栈信息吗。

**Comment by xuxueli** [comment]
数据库重连问题，日志刷新问题，最新版本已经优化，可以升级体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.1.2
