### ISSUE TITLE
Admin注册死锁和执行器请求注册超时

### ISSUE THREAD

**Issue by kuguobing** [xuxueli/xxl-job#1274]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1-SNAPSHOT ： github上最新代码

### Other information
应该同一问题：放在本地PC电脑，开启Admin和2个执行器，让其跑一晚上，一早看到如下日志：
Caused by: org.springframework.dao.DeadlockLoserDataAccessException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; SQL []; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction

22:29:55.251 logback [xxl-job, executor ExecutorRegistryThread] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:http://127.0.0.1:8080/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='2ce5a929-ccc7-4c10-9262-d23e8fe0b794', createMillisTime=1573741792241, accessToken='null', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='10.241.80.60:9995'}], version='null'}
22:29:55.253 logback [xxl-job, executor ExecutorRegistryThread] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='10.241.80.60:9995'}
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1573741795251, request:XxlRpcRequest{requestId='2ce5a929-ccc7-4c10-9262-d23e8fe0b794', createMillisTime=1573741792241, accessToken='null', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='10.241.80.60:9995'}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)

详见附件：
[Running执行日志异常2019-11-15.txt](https://github.com/xuxueli/xxl-job/files/3849476/Running.2019-11-15.txt)

**Comment by kuguobing** [comment]
找到原因了：
https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans

**Comment by kuguobing** [comment]
@xuxueli  其实有解决方案，建议如下：
1、xxl_job_registry 这张表加一个字段register_md5 【= md5（reigister_group + register_key +register_value）】，该摘要值全局唯一
2、执行器心跳刷新updatetime时，用上面的md5摘要信息进行定位更新，比如条件SQL变成：UPDATE xxl_job_registry SET update_time = NOW() WHERE registry_md5 = ?
这样就不存在多列的Where的死锁问题。

**Comment by xuxueli** [comment]
master 分支已优化，可以pull master体验下。

**Comment by kuguobing** [comment]
更新了最新的版本， 让其跑2天2夜，现在报如下的错误：
2019-11-23 16:53:16 xxl-job-executor-sample-frameless [com.xxl.job.core.util.XxlJobRemotingUtil]-[xxl-job, executor ExecutorRegistryThread]-[postBody]-[106]-[ERROR] Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:72)
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:41)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)


@xuxueli
