### ISSUE TITLE
Cannot parse JSON

### ISSUE THREAD

**Issue by JiangZian** [xuxueli/xxl-job#1289]
java.lang.IllegalArgumentException: Cannot parse JSON
	at com.xxl.registry.client.util.json.BasicJsonReader.parseMap(BasicJsonReader.java:25)
	at com.xxl.registry.client.util.json.BasicJson.parseMap(BasicJson.java:35)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:88)
	at com.xxl.job.core.biz.client.AdminBizClient.callback(AdminBizClient.java:36)
	at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:166)
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:241)
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111)
	at java.lang.Thread.run(Thread.java:745)

不知名原因出现，
初步判断   
1.是否是  “客户端和client的链接超时导致？生成的页面无法解析？“
2.注册表的存储

**Comment by xuxueli** [comment]
你好，这是任务回调失败导致，确认下回调地址是不是配错，或者回调服务没启动。

**Comment by JiangZian** [comment]
> 你好，这是任务失败失败的原因，确认下替代地址是不是配错，或者某些服务没启动。

雪里，那么就应该是符合我说的第一点，链接超时导致的，是否应该修改这个返回行驶，失败页面的json解析？
