### ISSUE TITLE
数据库地址被替换成了内网IP

### ISSUE THREAD

**Issue by mahuaibo** [xuxueli/xxl-job#1290]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2 & 2.1.0

### Expected behavior
xxl-job-admin.jar 正常运行
### Actual behavior
Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'root'@'172.31.47.133' (using password: YES)

172.31.47.133 是我服务器内网地址，和我实际配置的rds地址不同，被替换了。。。

### Steps to reproduce the behavior
1. 配置数据库链接
2.编译xxl-job-admin.jar 
3.运行xxl-job-admin.jar 

### Other information
spring.datasource.url=jdbc:mysql://xxx.xxxx.ap-east-1.rds.amazonaws.com:3306/xxl-job?Unicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

**Comment by mahuaibo** [comment]
数据库地址必须填IP，不能使用 域名地址

**Comment by lwx57280** [comment]
我的在本地启动xxl-job-v2.3.0 版本时总是提示拒绝访问数据库，我的配置如下：

### xxl-job, datasource
spring.datasource.url=jdbc:mysql://192.168.110.106:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
spring.datasource.username=yxw01
spring.datasource.password=ywx@123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## 当前环境如下：
1、数据库8.0+x
2、jdk1.8
3、xxl-job-v2.3.0
4、Maven 3.6

我的客户端工具都可以正常访问数据库的，每次进行maven install 之后，启动XxlJobAdminApplication 控制台过一会就输出日志如下：

 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.2)

22:53:32.534 logback [main] INFO  c.x.job.admin.XxlJobAdminApplication - Starting XxlJobAdminApplication using Java 1.8.0_171 on DESKTOP-T2J8P0O with PID 19180 (D:\OpenSource\Tags\xxl-job\xxl-job-admin\target\classes started by MI in D:\OpenSource\Tags\xxl-job)
22:53:32.539 logback [main] INFO  c.x.job.admin.XxlJobAdminApplication - No active profile set, falling back to default profiles: default
22:53:34.125 logback [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
22:53:34.133 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
22:53:34.133 logback [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
22:53:34.134 logback [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.41]
22:53:34.232 logback [main] INFO  o.a.c.c.C.[.[.[/xxl-job-admin] - Initializing Spring embedded WebApplicationContext
22:53:34.232 logback [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1363 ms
22:53:34.430 logback [main] DEBUG com.zaxxer.hikari.HikariConfig - Driver class com.mysql.cj.jdbc.Driver found in Thread context class loader sun.misc.Launcher$AppClassLoader@18b4aac2
22:53:34.825 logback [main] INFO  c.x.j.a.c.scheduler.XxlJobScheduler - >>>>>>>>> init xxl-job admin success.
22:53:34.838 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - HikariCP - configuration:
22:53:34.840 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
22:53:34.840 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
22:53:34.840 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
22:53:34.840 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
22:53:34.841 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery............."SELECT 1"
22:53:34.841 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............10000
22:53:34.841 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
22:53:34.841 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
22:53:34.841 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
22:53:34.842 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
22:53:34.842 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................."com.mysql.cj.jdbc.Driver"
22:53:34.842 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - exceptionOverrideClassName......none
22:53:34.842 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
22:53:34.842 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
22:53:34.843 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................30000
22:53:34.843 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
22:53:34.843 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
22:53:34.843 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:mysql://192.168.110.106:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
22:53:34.844 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
22:53:34.844 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................900000
22:53:34.844 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................30
22:53:34.845 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
22:53:34.845 logback [xxl-job, admin JobFailMonitorHelper] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none


从控制台输出日志看，获取的就是配置applicaton.properties配置参数这没问题，接着一直在输出如下信息 数据ip 无端被替换张 本机网络 ip '192.168.110.3，为啥会这样，没搞懂很奇怪，我别的项目都没遇到这样问题

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	at com.sun.proxy.$Proxy75.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
	at com.sun.proxy.$Proxy78.findFailJobLogIds(Unknown Source)
	at com.xxl.job.admin.core.thread.JobFailMonitorHelper$1.run(JobFailMonitorHelper.java:41)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'yxw01'@'192.168.110.3' (using password: YES)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
