### ISSUE TITLE
xxl启动报错 com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'

### ISSUE THREAD

**Issue by 59471032** [xuxueli/xxl-job#1311]
``
[ERROR] 14:59:40.409 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted
[ERROR] 14:59:40.585 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted
[ERROR] 14:59:43.346 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted
[ERROR] 14:59:43.581 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted
[ERROR] 14:59:46.351 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'

``

**Comment by 59471032** [comment]
```
[root@iZbp1ioqjurm725uj4k3plZ logs]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)
[root@iZbp1ioqjurm725uj4k3plZ logs]# java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
[root@iZbp1ioqjurm725uj4k3plZ logs]# 

```

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现步骤。
确认执行器回调地址配置正确。

**Comment by 59471032** [comment]
配置都是正确的是，任务调度也能跑起来。方便的话远程看下。qq：59471032

**Comment by yu-si-jia** [comment]
请问下如何解决的，同有上述问题

**Comment by FredaZhang338** [comment]
报错+1

**Comment by luyuanx2** [comment]
同样的报错，升级了2.2.0-release 就出现了
