### ISSUE TITLE
任务服务器不停报错日志文件把磁盘撑满了：An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception

### ISSUE THREAD

**Issue by chf-gh** [xuxueli/xxl-job#1315]
调度中心用的最新版2.1.1版本
执行器引用的xxl-job-core 2.1.1版本
然后将执行器嵌入到当前springcloud中（版本Camden.SR2）当调度中心调用任务时，任务的服务器不停的包警告异常。几分钟就把磁盘撑满了，下面是异常信息。大神帮忙看下。
神奇的是我本地跑是没有问题的，一旦用jenkins部署到开发环境就不行了。
```
[LSV/01][WARN][2019-11-28T19:28:53.687]An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServer$1$1.handlerAdded() has thrown an exception; removed.
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:628)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1475)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1127)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:654)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: io.netty.buffer.ByteBufUtil.hexDump([BII)Ljava/lang/String;
        at io.netty.channel.DefaultChannelId.asShortText(DefaultChannelId.java:210)
        at io.netty.channel.AbstractChannel.toString(AbstractChannel.java:380)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at io.netty.channel.ChannelInitializer.exceptionCaught(ChannelInitializer.java:97)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:133)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:613)
        ... 14 common frames omitted
[LSV/01][WARN][2019-11-28T19:28:53.714]An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoClassDefFoundError: Could not initialize class io.netty.buffer.UnpooledUnsafeDirectByteBuf
        at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:50)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by xuxueli** [comment]
你好，从日志看netty版本冲突导致，需要保障两端netty版本一致。

**Comment by chf-gh** [comment]
> 你好，从日志看netty版本冲突导致，需要保障两端netty版本一致。

你好。我的调度中心和任务服务器用的是一致xxl-core-job 2.1.1 。那两端默认使用netty版本应该是一样的吧。我看ribbon也使用了netty，那会不会是xxl-core-job引用的netty版本和ribbon的netty版本冲突了呢？
