### ISSUE TITLE
xxl-job注册时出现状态码 302

### ISSUE THREAD

**Issue by TailFishZ** [xuxueli/xxl-job#1320]
许老师，您好，我在使用xxl-job时出现了一个奇怪的问题，向您请教！

xxl-job-admin 部署完成，页面可以正常访问，执行器在向admin服务注册时出现了 302 的状态码，以下是启动错误日志

2019-11-29 20:16:49.463 TID: N/A INFO  [main] io.undertow.servlet:313 - jolokia: No access restrictor found, access to any MBean is allowed
2019-11-29 20:16:49.531 TID: N/A INFO  [main] org.eclipse.jetty.util.log:192 - Logging initialized @15372ms
2019-11-29 20:16:58.314 TID: N/A INFO  [main] c.s.u.r.e.h.RestExceptionResolver:269 - Detected @ExceptionHandler methods in bingExceptionHandler
2019-11-29 20:16:58.385 TID: N/A INFO  [main] com.htjc.config.XxlJobConfig:39 - >>>>>>>>>>> xxl-job config init.
2019-11-29 20:16:58.396 TID: N/A INFO  [main] c.x.job.core.executor.XxlJobExecutor:210 - >>>>>>>>>>> xxl-job register jobhandler success, name:commonJobHandler, jobHandler:com.htjc.invoice.job.CommonJobHandler@7f6c85c4
2019-11-29 20:16:58.430 TID: N/A INFO  [main] c.x.r.r.p.XxlRpcProviderFactory:151 - >>>>>>>>>>> xxl-rpc, provider factory add service success. serviceKey = com.xxl.job.core.biz.ExecutorBiz, serviceBean = class com.xxl.job.core.biz.impl.ExecutorBizImpl
2019-11-29 20:16:58.479 TID: N/A INFO  [Thread-10] org.eclipse.jetty.server.Server:345 - jetty-9.3.11.v20160721
2019-11-29 20:16:58.519 TID: N/A INFO  [Thread-10] o.e.jetty.server.AbstractConnector:270 - Started ServerConnector@766989b7{HTTP/1.1,[http/1.1]}{0.0.0.0:9999}
2019-11-29 20:16:58.519 TID: N/A INFO  [Thread-10] org.eclipse.jetty.server.Server:403 - Started @24360ms
2019-11-29 20:16:58.519 TID: N/A INFO  [Thread-10] com.xxl.rpc.remoting.net.Server:50 - >>>>>>>>>>> xxl-rpc remoting server start success, nettype = com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer, port = 9999
2019-11-29 20:16:58.836 TID: N/A INFO  [qtp638577383-48] o.e.jetty.client.ResponseNotifier:197 - Exception while notifying listener com.xxl.rpc.remoting.net.impl.jetty.client.JettyClient$1@49aa6d93
com.xxl.rpc.util.XxlRpcException: xxl-rpc remoting request fail, http HttpStatus[302] invalid.
	at com.xxl.rpc.remoting.net.impl.jetty.client.JettyClient$1.onComplete(JettyClient.java:72)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:457)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:404)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:269)
	at org.eclipse.jetty.http.HttpParser.parseHeaders(HttpParser.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1317)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:159)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:120)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:115)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
2019-11-29 20:16:59.606 TID: N/A WARN  [main] c.n.c.sources.URLConfigurationSource:121 - No URLs will be polled as dynamic configuration sources.
2019-11-29 20:16:59.607 TID: N/A INFO  [main] c.n.c.sources.URLConfigurationSource:122 - To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2019-11-29 20:16:59.617 TID: N/A WARN  [main] c.n.c.sources.URLConfigurationSource:121 - No URLs will be polled as dynamic configuration sources.

**Comment by xuxueli** [comment]
你好，问题无法复现，可以检查下两端通讯网络状况。
