### ISSUE TITLE
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by etertal** [xuxueli/xxl-job#1322]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
I'm using xxl-job with version is  XXL-JOB 2.1.1-SNAPSHOT
### Expected behavior
When I was using xxl-job, I encountered the following problems:
```
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:583)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:211)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at com.xxl.job.admin.controller.resolver.WebExceptionResolver.resolveException(WebExceptionResolver.java:51)
	at org.springframework.web.servlet.DispatcherServlet.processHandlerException(DispatcherServlet.java:1222)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1034)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
```
### Actual behavior
I look at the source code section with com.xxl.job.admin.controller.resolver.WebExceptionResolver
```
public ModelAndView resolveException(HttpServletRequest request,
			HttpServletResponse response, Object handler, Exception ex) {
		if (!(ex instanceof XxlJobException)) {
			logger.error("WebExceptionResolver:{}", ex);
		}
		// if json
		boolean isJson = false;
		HandlerMethod method = (HandlerMethod)handler;
		ResponseBody responseBody = method.getMethodAnnotation(ResponseBody.class);
		if (responseBody != null) {
			isJson = true;
		}

		// error result
		ReturnT<String> errorResult = new ReturnT<String>(ReturnT.FAIL_CODE, ex.toString().replaceAll("\n", "<br/>"));

		// response
		ModelAndView mv = new ModelAndView();
		if (isJson) {
			try {
				response.setContentType("application/json;charset=utf-8");
				response.getWriter().print(JacksonUtil.writeValueAsString(errorResult));
			} catch (IOException e) {
				logger.error(e.getMessage(), e);
			}
			return mv;
		} else {

			mv.addObject("exceptionMsg", errorResult.getMsg());
			mv.setViewName("/common/common.exception");
			return mv;
		}
	}
```
### Steps to reproduce the behavior
I think this response is used.
### Other information

**Comment by xuxueli** [comment]
建议使用正式Release版本：https://github.com/xuxueli/xxl-job/releases

**Comment by 550204633** [comment]
已经升级到2.1.2 还是会有大量此错误
