### ISSUE TITLE
io.netty.channel.ExtendedClosedChannelException

### ISSUE THREAD

**Issue by HD-Sheng** [xuxueli/xxl-job#1326]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.1-SNAPSHOT
### Expected behavior
在原基础上添加了些自己写的功能，在整个任务流中任一节点可以缓存数据，也可以获取其它节点缓存的数据，为了能使各个执行器都可以获取到这些数据，所以把缓存数据缓存在了控制台，在原来AdminBizImpl中新增了类似与缓存方法和获取缓存的方法。但是在频繁调用的情况下会出现ExtendedClosedChannelException。
### Other information

**Comment by HD-Sheng** [comment]
是在执行器报的错误

`08:48:25.894 logback [Thread-337] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:http://127.0.0.1:8080/zyc-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='276198ba-ae02-4995-bb38-f27418d0f260', createMillisTime=1575247705893, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='getCommParam', parameterTypes=[int], parameters=[2], version='null'}
com.xxl.rpc.util.XxlRpcException: io.netty.channel.ExtendedClosedChannelException
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227)
	at com.sun.proxy.$Proxy62.getCommParam(Unknown Source)
	at com.xxl.job.core.util.CommonParamCacheUtil.getParam(CommonParamCacheUtil.java:25)
	at com.xxl.job.executor.service.jobhandler.ProcedureJobHandler.execute(ProcedureJobHandler.java:59)
	at com.xxl.job.core.thread.JobThread$1.call(JobThread.java:137)
	at com.xxl.job.core.thread.JobThread$1.call(JobThread.java:134)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.ExtendedClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)`

**Comment by xuxueli** [comment]
你好，建议用Release版本。
另外，ExtendedClosedChannelException问题由底层通讯长连关闭导致，可以确认下网络和服务状况。
