### ISSUE TITLE
关于trigger pool 1000大小的疑惑 

### ISSUE THREAD

**Issue by tidapeng** [xuxueli/xxl-job#1327]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
能同时调度1000个以上任务
### Actual behavior
会因task 太多被丢弃
### Steps to reproduce the behavior
同时启动1000个以上任务
### Other information

异常：

2019-11-15 14:44:00,100 ERROR [xxl-job, admin JobScheduleHelper#ringThread] c.x.j.a.c.thread.JobScheduleHelper [JobScheduleHelper.java : 247] >>>>>>>>>>> xxl-job, JobScheduleHelper#ringThread error:{}
java.util.concurrent.RejectedExecutionException: Task com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3@61650994 rejected from java.util.concurrent.ThreadPoolExecutor@74aa996a[Running, pool size = 200, active threads = 200, queued tasks = 1000, completed tasks = 344]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper.addTrigger(JobTriggerPoolHelper.java:68)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper.trigger(JobTriggerPoolHelper.java:126)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$2.run(JobScheduleHelper.java:240)
	at java.lang.Thread.run(Thread.java:748)

相关配置参数 ：

    // ---------------------- trigger pool ----------------------

    // fast/slow thread pool
    private ThreadPoolExecutor fastTriggerPool = new ThreadPoolExecutor(
            50,
            200,
            60L,
            TimeUnit.SECONDS,
            new LinkedBlockingQueue<Runnable>(1000),
            new ThreadFactory() {
                @Override
                public Thread newThread(Runnable r) {
                    return new Thread(r, "xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-" + r.hashCode());
                }
            });

    private ThreadPoolExecutor slowTriggerPool = new ThreadPoolExecutor(
            10,
            100,
            60L,
            TimeUnit.SECONDS,
            new LinkedBlockingQueue<Runnable>(2000),
            new ThreadFactory() {
                @Override
                public Thread newThread(Runnable r) {
                    return new Thread(r, "xxl-job, admin JobTriggerPoolHelper-slowTriggerPool-" + r.hashCode());
                }
            });

疑问：
是否可以将fast/slow的thread pool 的最大容量调大，比如1万？这样会有哪些影响或者收益？

**Comment by zhipingwu** [comment]
单机，1000个线程没有必要，而且这里已经有队列2000个来缓冲任务了。

**Comment by xuxueli** [comment]
正常来说，单机情况下，单次任务调度耗时在5ms以内，这样单线程可以1s触发100个任务。200个线程可以调度4000个任务，线程正常来说都是够用的。而且存在对接做缓冲。
如果还不支持，建议调大调度线程或者做集群。

**Comment by wenhsh** [comment]
@xuxueli 做集群是把xxl-job-admin部署成集群，然后通过nginx来配域名就可以了吗？
