### ISSUE TITLE
2.1.1版本 Exception in thread "Thread-11" java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by Chen-Y-P** [xuxueli/xxl-job#1339]
Exception in thread "Thread-11" java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

问题原因可能是：spring-boot-starter-data-redis里的netty和xxl-job里的netty原因把

**Comment by Chen-Y-P** [comment]
已经切换到2.0.2没有此问题

**Comment by sundylgz** [comment]
你这个错误是地址被绑定了，就是注册的服务端口被占用

**Comment by linzehuan** [comment]
+1 回退到2.1.0正常

**Comment by xuxueli** [comment]
这个问题只需要修改以下注解即可解决。

因为从 2.1.1 版本开始，XxlJobSpringExecutor 组件初始化的Bean参数已经不需要，可以参考执行器sample项目，去掉参数只保留 Bean 注解即可。如下图。

![image](https://user-images.githubusercontent.com/10633817/70618903-d8e2f200-1c4e-11ea-830b-b39c3f7fe97c.png)

**Comment by garyyeh** [comment]
为什么图片看不到？我也遇到同样问题。

**Comment by garyyeh** [comment]
原来是被墙挡了。已经看到了。谢谢

**Comment by slieer** [comment]
注意@Bean 不要带参数即可！

    @Bean
    public XxlJobSpringExecutor xxlJobExecutor() {
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppName(appName);
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

        return xxlJobSpringExecutor;
    }
