### ISSUE TITLE
通过xxl-job定时检查kibana

### ISSUE THREAD

**Issue by dreamscyk** [xuxueli/xxl-job#1348]
通过xxl-job检查并重启kibana的时候，报以下错误：
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite (net.js:788:14)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:690:12)
    at Socket.emit (events.js:187:15)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite (net.js:790:10)

**Comment by xuxueli** [comment]
你好，问题无法复现。
