### ISSUE TITLE
2.1.1 任务管理报空指针

### ISSUE THREAD

**Issue by maokf** [xuxueli/xxl-job#1353]
java.lang.NullPointerException: null
	at com.xxl.job.admin.controller.JobInfoController.filterJobGroupByRole(JobInfoController.java:72)
	at com.xxl.job.admin.controller.JobInfoController.index(JobInfoController.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by xuxueli** [comment]
你好，问题无法复现。
