### ISSUE TITLE
2.0.2 调度调执行器一半概率会失败,500。日志中发现CancelledKeyException异常

### ISSUE THREAD

**Issue by MrWho0** [xuxueli/xxl-job#1354]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2
### Expected behavior
执行器中发现以下一个异常，之后admin调度一半会报
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout
日志：
[WARN]	2019-12-10 06:00:30	qtp1260595686-197914	org.eclipse.jetty.util.thread.strategy.EatWhatYouKill	
java.nio.channels.CancelledKeyException: null
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:428)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:318)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:342)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:189)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供稳定复现步骤。
