### ISSUE TITLE
覆盖之前调度时任务不会停止

### ISSUE THREAD

**Issue by HeIsRicky** [xuxueli/xxl-job#1362]
版本：2.1.1 

任务日志现象：
2019-12-12 10:32:38 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[190]-[Thread-3] 
----------- xxl-job job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
2019-12-12 10:33:08 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[190]-[Thread-3] 
----------- xxl-job job callback fail, callbackResult:ReturnT [code=500, msg=The request data invalid., content=null]
......

后台异常：
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 26)): has to be escaped using backslash to be included in string value
 at [Source: [{"logId":4515,"logDateTim":1576117020006,"executeResult":{"code":500,"msg":"block strategy effectCover Early [job running, killed]","content":null}}]; line: 1, column: 100]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwUnquotedSpace(ParserMinimalBase.java:522)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2059)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2030)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:276)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)

预估原因：
"block strategy effect："里面的中文冒号导致解析json失败
```
if (ExecutorBlockStrategyEnum.DISCARD_LATER == blockStrategy) {
    // discard when running
    if (jobThread.isRunningOrHasQueue()) {
        return new ReturnT<String>(ReturnT.FAIL_CODE, "block strategy effect："+ExecutorBlockStrategyEnum.DISCARD_LATER.getTitle());
    }
} else if (ExecutorBlockStrategyEnum.COVER_EARLY == blockStrategy) {
    // kill running jobThread
    if (jobThread.isRunningOrHasQueue()) {
        removeOldReason = "block strategy effect：" + ExecutorBlockStrategyEnum.COVER_EARLY.getTitle();
        jobThread = null;
    }
} else {
    // just queue trigger
}
```

**Comment by xuxueli** [comment]
master分支已优化，可以 pull master体验下。
