### ISSUE TITLE
任务执行成功后报异常

### ISSUE THREAD

**Issue by fengqingyuns** [xuxueli/xxl-job#1370]
2019-12-13 11:30:47 [com.xxl.job.core.thread.JobThread#run]-[164]-[Thread-20] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=200, msg=null, content=null]
2019-12-13 11:30:47 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[190]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.
2019-12-13 11:31:31 [com.xxl.job.core.thread.JobThread#run]-[175]-[Thread-20] 
----------- JobThread toStop, stopReason:web container destroy and kill the job.
2019-12-13 11:31:31 [com.xxl.job.core.thread.JobThread#run]-[183]-[Thread-20] 
----------- JobThread Exception:java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:112)

----------- xxl-job job execute end(error) -----------

**Comment by xuxueli** [comment]
你好，下面日志可以忽略。这是任务线程空闲回收的相关日志，会记录到最后一次调度的日志尾部。

**Comment by fengqingyuns** [comment]
好的谢谢
