### ISSUE TITLE
TriggerCallbackThread - java.io.EOFException: readObject: unexpected end of file (没有那个文件或目录)

### ISSUE THREAD

**Issue by yuweiming2016** [xuxueli/xxl-job#1378]
升级为2.1.1之后，老报文件找不到错误，我查过，目录是存在的，文件的确不存在。
admin配置如下：
![image](https://user-images.githubusercontent.com/22490427/70960720-c63b4380-20ba-11ea-9e3c-31ddc4e43776.png)

执行器配置如下：
![image](https://user-images.githubusercontent.com/22490427/70960746-df43f480-20ba-11ea-9a1a-b798e55072a9.png)

实际不影响使用，但是一天下来报上千次的错误，受不了……，请雪里帮忙看看

2019-12-17 10:43:54.161 [Thread-11][] ERROR com.xxl.job.core.util.FileUtil - /data/logs/tomcat/apps/callbacklog/xxl-job-callback-1576550604133.log (没有那个文件或目录)
java.io.FileNotFoundException: /data/logs/tomcat/apps/callbacklog/xxl-job-callback-1576550604133.log (没有那个文件或目录)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.xxl.job.core.util.FileUtil.readFileContent(FileUtil.java:84)
        at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:237)
        at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
        at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111)
        at java.lang.Thread.run(Thread.java:745)
2019-12-17 10:43:54.161 [Thread-11][] ERROR com.xxl.job.core.thread.TriggerCallbackThread - java.io.EOFException: readObject: unexpected end of file
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
        at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238)
        at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
        at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: readObject: unexpected end of file
        at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2147)
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
        ... 4 common frames omitted

**Comment by yuweiming2016** [comment]
有人帮忙看看吗？我用的是双admin

**Comment by etertal** [comment]
callbacklog日志目录下的日志删了，重新启动就可以了

**Comment by JanYunkai** [comment]
callbacklog 在什么位置
