### ISSUE TITLE
初始化项目一直报错

### ISSUE THREAD

**Issue by zhangjing007** [xuxueli/xxl-job#1380]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
运行后一直报错！
![Snipaste_2019-12-17_18-47-21](https://user-images.githubusercontent.com/24825020/70988943-ada04d00-20fd-11ea-945e-cdccc3fb4d39.png)

**Comment by zhangjing007** [comment]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('h' (code 104)): was expecting comma to separate Object entries
 at [Source: [{"logId":16651,"logDateTim":1576631855002,"executeResult":{"code":500,"msg":"java.lang.reflect.InvocationTargetException\r\n\tat sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)\r\n\tat com.xxl.job.core.thread.JobThread.run(JobThread.java:152)\r\nCaused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://127.0.0.1:8080/xxl-job-admin/jobinfo/stop2": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out\r\n\tat org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:675)\r\n\tat org.springframework.web.client.RestTemplate.execute(RestTemplate.java:622)\r\n\tat org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:540)\r\n\tat com.xxl.job.executor.service.jobhandler.ModelsTransProgressJobsHandler.stopJob(ModelsTransProgressJobsHandler.java:113)\r\n\tat com.xxl.job.executor.service.jobhandler.ModelsTransProgressJobsHandler.modelsTransProgressJobsHandler(ModelsTransProgressJobsHandler.java:61)\r\n\t... 5 more\r\nCaused by: java.net.SocketTimeoutException: Read timed out\r\n\tat java.net.SocketInputStream.socketRead0(Native Method)\r\n\tat java.net.SocketInputStream.socketRead(SocketInputStream.java:116)\r\n\tat java.net.SocketInputStream.read(SocketInputStream.java:171)\r\n\tat java.net.SocketInputStream.read(SocketInputStream.java:141)\r\n\tat java.io.BufferedInputStream.fill(BufferedInputStream.java:246)\r\n\tat java.io.BufferedInputStream.read1(BufferedInputStream.java:286)\r\n\tat java.io.BufferedInputStream.read(BufferedInputStream.java:345)\r\n\tat sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)\r\n\tat sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)\r\n\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)\r\n\tat java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)\r\n\tat org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:52)\r\n\tat org.springframework.http.client.AbstractClientHttpResponse.getStatusCode(AbstractClientHttpResponse.java:33)\r\n\tat org.springframework.web.client.MessageBodyClientHttpResponseWrapper.getStatusCode(MessageBodyClientHttpResponseWrapper.java:126)\r\n\tat org.springframework.web.client.MessageBodyClientHttpResponseWrapper.hasMessageBody(MessageBodyClientHttpResponseWrapper.java:60)\r\n\tat org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:82)\r\n\tat org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:934)\r\n\tat org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:918)\r\n\tat org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:664)\r\n\t... 9 more\r\n","content":null}}]; line: 1, column: 600]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2285)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:912)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:283)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	... 74 common frames omitted

**Comment by xuxueli** [comment]
日志目录清空即可。
