### ISSUE TITLE
执行任务1小超时？是否有超时设置

### ISSUE THREAD

**Issue by toalaska** [xuxueli/xxl-job#1385]
2019-12-18 16:18:23 [com.xxl.job.core.thread.JobThread#run]-[124]-[Thread-31217] 
----------- xxl-job job execute start -----------
----------- Param:
update ybjh.ac43 set aac066='1111',aaa149='2222' where aaa027='350200' and  aab001='1111'
2019-12-18 17:19:20 [com.xxl.job.core.thread.JobThread#run]-[175]-[Thread-31217] 
----------- JobThread toStop, stopReason:web container destroy and kill the job.
2019-12-18 17:19:20 [com.xxl.job.core.thread.JobThread#run]-[183]-[Thread-31217] 
----------- JobThread Exception:java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
	at ch.qos.logback.classic.spi.LoggingEvent.(LoggingEvent.java:119)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:144)
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:308)
	at org.mybatis.spring.transaction.SpringManagedTransaction.close(SpringManagedTransaction.java:121)
	at org.apache.ibatis.executor.BaseExecutor.close(BaseExecutor.java:90)
	at org.apache.ibatis.executor.CachingExecutor.close(CachingExecutor.java:64)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.close(DefaultSqlSession.java:263)
	at org.mybatis.spring.SqlSessionUtils.closeSqlSession(SqlSessionUtils.java:179)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:454)
	at com.sun.proxy.$Proxy34077.selectOne(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:89)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:62)
	at com.sun.proxy.$Proxy34078.query(Unknown Source)
	at com.xxl.job.executor.service.jobhandler.SqlHandler.execute(SqlHandler.java:22)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [ch.qos.logback.classic.spi.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1224)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186)
	... 19 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [ch.qos.logback.classic.spi.ThrowableProxy]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1383)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1371)
	... 21 more

----------- xxl-job job execute end(error) -----------

**Comment by toalaska** [comment]
报错后，任务仍然处于正在运行状态，这时任务是否还在运行？
![image](https://user-images.githubusercontent.com/6500094/71080063-61b9da80-21c7-11ea-8147-46efc4dbaebc.png)

**Comment by xuxueli** [comment]
你好，高版本支持甚至超时时间。

@toalaska 任务超时控制通过线程中断实现，不能catch住，这个确认下。
