### ISSUE TITLE
更新版本后异常

### ISSUE THREAD

**Issue by marchi1986** [xuxueli/xxl-job#1396]
换了新版本后报错，请问怎么解决
2019-12-19 19:00:49,028 ERROR [xxl-rpc, NettyHttpServer-serverHandlerPool-810385314] c.x.r.r.n.i.n.s.NettyHttpServerHandler [NettyHttpServerHandler.java : 93] com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:80)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:25)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2952)
	at com.caucho.hessian.io.Hessian2Input.expect(Hessian2Input.java:2900)
	at com.caucho.hessian.io.Hessian2Input.readInt(Hessian2Input.java:834)
	at com.caucho.hessian.io.Hessian2Input.readType(Hessian2Input.java:2447)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2124)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted

**Comment by qingc1996** [comment]
我也是这样，怎么解决呢

**Comment by marchi1986** [comment]
我在本地测试是可以的，打包放上去服务器不行，换台服务器又可以，就是生产环境的服务器出问题，我也是一头雾水

**Comment by qingc1996** [comment]
嗯嗯 我的情况和你一样 主要不知道调度中心 发了什么消息给了执行器  让执行器反序列化失败

**Comment by xuxueli** [comment]
推测是版本不一致导致，排查下确认调度中心和执行器版本一致。

**Comment by umi-soft** [comment]
我得调度中心和执行器版本一致的，也有这个问题

**Comment by qingc1996** [comment]
> 我得调度中心和执行器版本一致的，也有这个问题

可以排查一下，环境上的执行器端口是否没有配置firewall，导致此端口暴露给了外界！
