### ISSUE TITLE
调度中心执行时报错: com.caucho.hessian.io.HessianProtocolException: Illegal object reference #46

### ISSUE THREAD

**Issue by hanbeikai** [xuxueli/xxl-job#1443]
作者你好,今天在使用xxl-job时调度中心执行项目执行器时一直报错:
其中 调度中心报错 : 
19:51:27.661 logback [nioEventLoopGroup-3-1] ERROR c.x.r.r.n.i.n.c.NettyHttpClientHandler - >>>>>>>>>>> xxl-rpc netty_http client caught exception
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: Illegal object reference #46
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: Illegal object reference #46
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2131)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 34 common frames omitted

执行器 端 报错 : 
2020-01-07 19:51:27.588 ERROR 16476 --- [Pool-2049065764] c.x.r.r.n.i.n.s.NettyHttpServerHandler   : com.caucho.hessian.io.HessianProtocolException: readObject: unknown code 0x43 C

com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: readObject: unknown code 0x43 C
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52) ~[xxl-rpc-core-1.5.0.jar:na]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81) [xxl-rpc-core-1.5.0.jar:na]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26) [xxl-rpc-core-1.5.0.jar:na]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50) [xxl-rpc-core-1.5.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]
Caused by: com.caucho.hessian.io.HessianProtocolException: readObject: unknown code 0x43 C
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:3421) ~[hessian-3.3.6.jar:na]
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2691) ~[hessian-3.3.6.jar:na]
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49) ~[xxl-rpc-core-1.5.0.jar:na]
	... 6 common frames omitted

执行器端配置信息为 
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    accessToken: uz6crV5PdhT6JCvN
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: jiuweiplus
      ip:
      port: 7081
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

请问一下为什么?

**Comment by 91wangmeng** [comment]
我这边今天也遇到了 目前解决了发现是因为hessain版本冲突了, 因为引入了rpc-sofa-boot-starter,把冲突的版本exclusion掉就好了

**Comment by hanbeikai** [comment]
> 我这边今天也遇到了 目前解决了发现是因为hessain版本冲突了, 因为引入了rpc-sofa-boot-starter,把冲突的版本exclusion掉就好了

好的 我看看我这边是不是也有冲突

**Comment by xuxueli** [comment]
推测版本冲突了。
