### ISSUE TITLE
 V1.8.1  Client-error:unknown code for readObject at 0x3c (<)

### ISSUE THREAD

**Issue by chenxofhit** [xuxueli/xxl-job#145]
2017-08-22 10:59:00,360 - xxl-job-admin - ERROR [com.nt.job.core.rpc.netcom.jetty.client.JettyClient] - <unknown code for readObject at 0x3c (<)>
java.lang.IllegalStateException: unknown code for readObject at 0x3c (<)
        at com.nt.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:33)
        at com.nt.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:38)
        at com.nt.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:52)
        at com.sun.proxy.$Proxy708.run(Unknown Source)
        at com.nt.job.admin.core.trigger.TalkeerJobTrigger.runExecutor(TalkeerJobTrigger.java:193)
        at com.nt.job.admin.core.route.strategy.ExecutorRouteFirst.routeRun(ExecutorRouteFirst.java:26)
        at com.nt.job.admin.core.trigger.TalkeerJobTrigger.trigger(TalkeerJobTrigger.java:162)
        at com.nt.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:30)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x3c (<)
        at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
        at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
        at com.nt.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:31)
        ... 10 more
2017-08-22 10:59:00,362 - xxl-job-admin - ERROR [com.nt.job.admin.core.trigger.TalkeerJobTrigger] - <Client-error:unknown code for readObject at 0x3c (<)>
java.lang.RuntimeException: Client-error:unknown code for readObject at 0x3c (<)
        at com.nt.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:60)
        at com.sun.proxy.$Proxy708.run(Unknown Source)
        at com.nt.job.admin.core.trigger.TalkeerJobTrigger.runExecutor(TalkeerJobTrigger.java:193)
        at com.nt.job.admin.core.route.strategy.ExecutorRouteFirst.routeRun(ExecutorRouteFirst.java:26)
        at com.nt.job.admin.core.trigger.TalkeerJobTrigger.trigger(TalkeerJobTrigger.java:162)
        at com.nt.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:30)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

哪里出问题了？ 执行器回调地址与admin地址确认一致。

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"

talkeer.job.admin.addresses=http://192.168.0.123:8080/talkeer-job-admin-1.0.0

### xxl-job executor address
talkeer.job.executor.appname=xxl-job-executor-example
talkeer.job.executor.ip=
talkeer.job.executor.port=9999

### xxl-job log path
talkeer.job.executor.logpath=d:/opt/logs/talkeer-job/jobhandler/

### xxl-job, access token
talkeer.job.accessToken=

**Comment by sosojustdo** [comment]
最后怎么解决的呢？我也遇到了类似的问题？

**Comment by xuxueli** [comment]
@sosojustdo 这种情况，通常应为执行器没有正常响应导致，可以确认下对应的执行器是否正常启动。具体，可以加交流区讨论啊。

**Comment by sosojustdo** [comment]
@xuxueli 我是使用的xxl-job-executor-sample-spring demo启动的xxl-job-core我换做1.8.2稳定版本了

**Comment by sosojustdo** [comment]
@xuxueli 已经解决，忽略该问题

**Comment by xiaosazixian** [comment]
@sosojustdo 怎么解决的？

**Comment by 2298119289** [comment]
> @xuxueli 已经解决，忽略该问题
怎么解决的？求助

**Comment by sosojustdo** [comment]
> @sosojustdo 怎么解决的？
1：检查执行器是否正常启动，正常启动后在job-admin后台能够看到。
2：执行器正常启动后，telnet ip port, 检查是否能通。

**Comment by yu199195** [comment]
@sosojustdo @xuxueli  这个错误在启动的时候注册报的，怎么可能会正常启动执行器呢？
