### ISSUE TITLE
执行器启动的时候扫描spring bean 里的xxljob 报错

### ISSUE THREAD

**Issue by chenwei1048** [xuxueli/xxl-job#1464]
报错信息：
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'request' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:365)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.initJobHandlerMethodRepository(XxlJobSpringExecutor.java:82)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterPropertiesSet(XxlJobSpringExecutor.java:36)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)

源码是XxlJobSpringExecutor 类 initJobHandlerMethodRepository 方法里遍历applicationContext.getBeanDefinitionNames(); 然后无法getBean ,怎么解决

**Comment by SimpleJuly** [comment]
升级2.1.2后，我也遇到同样的错

**Comment by chenwei1048** [comment]
> 升级2.1.2后，我也遇到同样的错

我改成         String[] beanDefinitionNames = applicationContext.getBeanNamesForType(Object.class, false, true);
 好了

**Comment by xuxueli** [comment]
你好，问题已经修复并推送master分支，可以pull master体验下。
