### ISSUE TITLE
2.1.2 NettyHttpServerHandler 偶偶抛异常问题

### ISSUE THREAD

**Issue by 313715295** [xuxueli/xxl-job#1466]
2.1.2 版本，偶偶会发现日志报错。。

报错内容如下：
```
[2020-01-20 05:42:59] [ERROR] [xxl-rpc, NettyHttpServer-serverHandlerPool-950958762] c.x.r.r.n.i.n.s.NettyHttpServerHandler - xxl-rpc request data empty. 
com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:77)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-01-20 05:43:00] [ERROR] [nioEventLoopGroup-9-1] c.x.r.r.n.i.n.s.NettyHttpServerHandler - >>>>>>>>>>> xxl-rpc provider netty_http server caught exception 
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
--
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Debugger failed to attach: handshake failed - received >< - expected >JDWP-Handshake<
[2020-01-20 09:18:23] [ERROR] [xxl-rpc, NettyHttpServer-serverHandlerPool-1261749532] c.x.r.r.n.i.n.s.NettyHttpServerHandler - xxl-rpc request data empty. 
com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:77)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-01-20 09:31:01] [ERROR] [xxl-rpc, NettyHttpServer-serverHandlerPool-482039644] c.x.r.r.n.i.n.s.NettyHttpServerHandler - xxl-rpc request data empty. 
com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:77)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-01-20 09:31:01] [ERROR] [nioEventLoopGroup-9-1] c.x.r.r.n.i.n.s.NettyHttpServerHandler - >>>>>>>>>>> xxl-rpc provider netty_http server caught exception 
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
--
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xuxueli** [comment]
你好，从日志看应该是服务端口被恶意扫描，不影响业务可以忽略。

**Comment by xcw931924821** [comment]
是业务端口被扫描？是那个端口呢？
