### ISSUE TITLE
xxl-job-executor-sample无法正常注册，提示302

### ISSUE THREAD

**Issue by JadeQin** [xuxueli/xxl-job#1469]
执行器报错
```
17:02:01.240 logback [Thread-16] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-job, invoke error, address:http://192.168.10.7:8090/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='e7c5a60f-dd69-436e-94ac-0e3299dd44e9', createMillisTime=1579510921232, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='172.17.0.3:9999'}], version='null'}
17:02:01.240 logback [Thread-16] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='172.17.0.3:9999'}
com.xxl.rpc.util.XxlRpcException: xxl-rpc remoting request fail, http HttpStatus[302] invalid.
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
	at com.sun.proxy.$Proxy56.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)
```

admin报错
```
17:08:01.339 logback [http-nio-8080-exec-4] WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/xxl-job-admin/api] in DispatcherServlet with name 'dispatcherServlet'
```

直接访问http://192.168.10.7:8090/xxl-job-admin/ 是正常的

**Comment by z1413689722** [comment]
请问下楼主怎么解决的

**Comment by ZhouXingma** [comment]
` <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.1.2</version>
        </dependency>`
version 不一致就会出现这个问题，该version和使用的xxl-job-admin 要一致

**Comment by JeremyJK** [comment]
客户端版本号不能低于admin版本号

**Comment by xuxueli** [comment]
+1，调度中心和执行器版本需要一致。

**Comment by xiaomin521309** [comment]
admin中有许多com.xxl.rpc.util.XxlRpcException: xxl-rpc response status invalid.报错，
内网中客户端每天都会存在几条注册超时的错误：>>>>>>>>>>> xxl-job registry fail，报错原因是readTimeOut,
监控内网网络是没有发现问题的
