### ISSUE TITLE
NettyHttpServerHandler.exceptionCaught : java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by astali** [xuxueli/xxl-job#1485]
Please answer some questions before submitting your issue. Thanks!
调度中心调度结果显示成功,执行器执行结果显示成功,
但是执行器后台一直打满这个日志,一直在刷
com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler [136] -|  xxl-rpc provider netty_http server caught exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

望回复,谢谢

**Comment by astali** [comment]
版本是2.1.0 和2.1.2 都是这个异常

**Comment by xuxueli** [comment]
执行器端口服务被扫描导致。确认是否有其他程序在请求执行器执行器端口。

**Comment by demon999** [comment]
我部署在k8s环境也有这个问题
