### ISSUE TITLE
升级2.1.2之后，执行器抛出异常，但是不是所有的都报错

### ISSUE THREAD

**Issue by LynnBlue** [xuxueli/xxl-job#1489]
2020-02-24 09:04:32.099 [xxl-rpc, NettyHttpServer-serverHandlerPool-1765405318] ERROR com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '68'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '68'
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52) ~[xxl-rpc-core-1.5.0.jar:na]
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81) [xxl-rpc-core-1.5.0.jar:na]
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26) [xxl-rpc-core-1.5.0.jar:na]
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50) [xxl-rpc-core-1.5.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '68'
        at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926) ~[hessian-4.0.63.jar:3.1.0]
        at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118) ~[hessian-4.0.63.jar:3.1.0]

**Comment by xuxueli** [comment]
应该是hessian版本冲突。
