### ISSUE TITLE
每2秒报一次错误

### ISSUE THREAD

**Issue by 59471032** [xuxueli/xxl-job#1506]
用nutzboot中集成了xxl-job
每2秒报一次错误

`DEBUG] 13:50:22.608 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - >>>>>>>>>>> xxl-rpc provider netty_http server read beat-ping.
[ERROR] 13:50:23.141 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted
[ERROR] 13:50:23.590 com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler - com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '61'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	... 6 common frames omitted
`

**Comment by 59471032** [comment]
xxl-job版本为2.1.2

**Comment by 59471032** [comment]
服务端与客户端的hessian版本一致。

**Comment by xuxueli** [comment]
你好，应该是执行器端口服务被恶意扫描了，可以排查下调用方屏蔽掉，不影响。
