### ISSUE TITLE
mac 10.10版本启动报错

### ISSUE THREAD

**Issue by zhangkewu58** [xuxueli/xxl-job#1512]
你好，请问：
以下是什么原因？谢谢
macPro版本：10.10.5 Yosemite
springboot版本： 2.2.0.BUILD-SNAPSHOT
xxl版本：2.1.2
启动时报错：
20:35:59.830 [RMI TCP Connection(20)-127.0.0.1] DEBUG i.n.u.internal.NativeLibraryLoader [140] - netty_transport_native_kqueue_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /var/folders/m1/h574vmts0_q61fjtw2x2h54r0000gn/T
java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_x86_64 in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1122)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
at io.netty.channel.kqueue.Native.loadNativeLibrary(Native.java:125)
at io.netty.channel.kqueue.Native.(Native.java:60)
at io.netty.channel.kqueue.KQueue.(KQueue.java:37)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at io.lettuce.core.KqueueProvider.(KqueueProvider.java:55)
at io.lettuce.core.TransportsNativeTransports.isSocketSupported(Transports.java:66)atio.lettuce.core.Transports.eventLoopGroupClass(Transports.java:38)atio.lettuce.core.AbstractRedisClient.getEventLoopGroup(AbstractRedisClient.java:185)atio.lettuce.core.AbstractRedisClient.channelType(AbstractRedisClient.java:173)atio.lettuce.core.RedisClient.getConnectionBuilder(RedisClient.java:343)atio.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:291)atio.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:274)atio.lettuce.core.RedisClient.connect(RedisClient.java:207)atorg.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambdagetConnection1(StandaloneConnectionProvider.java:115)atjava.util.Optional.orElseGet(Optional.java:267)atorg.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)atorg.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.lambdanull0(LettucePoolingConnectionProvider.java:97)atio.lettuce.core.support.ConnectionPoolSupportRedisPooledObjectFactory.create(ConnectionPoolSupport.java:209)
at io.lettuce.core.support.ConnectionPoolSupportRedisPooledObjectFactory.create(ConnectionPoolSupport.java:199)atorg.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:58)atorg.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)atorg.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)atorg.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)atio.lettuce.core.support.ConnectionPoolSupport1.borrowObject(ConnectionPoolSupport.java:122)
at io.lettuce.core.support.ConnectionPoolSupport1.borrowObject(ConnectionPoolSupport.java:117)atorg.springframework.data.redis.connection.lettuce.LettucePoolingConnectionProvider.getConnection(LettucePoolingConnectionProvider.java:103)atorg.springframework.data.redis.connection.lettuce.LettuceConnectionFactorySharedConnection.getNativeConnection(LettuceConnectionFactory.java:1187)
at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactorySharedConnection.getConnection(LettuceConnectionFactory.java:1168)atorg.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:941)atorg.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:352)atorg.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:132)atorg.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:95)atorg.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:82)atorg.springframework.boot.actuate.redis.RedisHealthIndicator.doHealthCheck(RedisHealthIndicator.java:55)atorg.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)atorg.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)atorg.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:80)atorg.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:38)atorg.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:106)atorg.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:116)atorg.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:103)atorg.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:81)atorg.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:68)atorg.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:74)atorg.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:65)atsun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)atsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)atsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)atjava.lang.reflect.Method.invoke(Method.java:498)atorg.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279)atorg.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)atorg.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)atorg.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121)atorg.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96)atcom.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)atcom.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)atjavax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)atjavax.management.remote.rmi.RMIConnectionImpl.access300(RMIConnectionImpl.java:76)
at javax.management.remote.rmi.RMIConnectionImplPrivilegedOperation.run(RMIConnectionImpl.java:1309)atjavax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)atjavax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)atsun.reflect.GeneratedMethodAccessor130.invoke(UnknownSource)atsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)atjava.lang.reflect.Method.invoke(Method.java:498)atsun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)atsun.rmi.transport.Transport1.run(Transport.java:200)
at sun.rmi.transport.Transport1.run(Transport.java:197)atjava.security.AccessController.doPrivileged(NativeMethod)atsun.rmi.transport.Transport.serviceCall(Transport.java:196)atsun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)atsun.rmi.transport.tcp.TCPTransportConnectionHandler.run0(TCPTransport.java:826)
at sun.rmi.transport.tcp.TCPTransportConnectionHandler.lambdarun0(TCPTransport.java:683)atjava.security.AccessController.doPrivileged(NativeMethod)atsun.rmi.transport.tcp.TCPTransportConnectionHandler.run(TCPTransport.java:682)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutorWorker.run(ThreadPoolExecutor.java:624)atjava.lang.Thread.run(Thread.java:748)Suppressed:java.lang.UnsatisfiedLinkError:nonettytransportnativekqueuex8664injava.library.pathatjava.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)atjava.lang.Runtime.loadLibrary0(Runtime.java:870)atjava.lang.System.loadLibrary(System.java:1122)atio.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)atsun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)atsun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)atsun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)atjava.lang.reflect.Method.invoke(Method.java:498)atio.netty.util.internal.NativeLibraryLoader1.run(NativeLibraryLoader.java:369)
at java.security.AccessController.doPrivileged(Native Method)
at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
... 79 common frames omitted
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
Referenced from: /private/var/folders/m1/h574vmts0_q61fjtw2x2h54r0000gn/T/libnetty_transport_native_kqueue_x86_64807846634452625121.dylib
Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
Referenced from: /private/var/folders/m1/h574vmts0_q61fjtw2x2h54r0000gn/T/libnetty_transport_native_kqueue_x86_64807846634452625121.dylib
Expected in: /usr/lib/libSystem.B.dylib

**Comment by zouchengli** [comment]
你这个环境问题吧？

**Comment by xuxueli** [comment]
问题无法复现。
