### ISSUE TITLE
使用TiDB数据库时，多个scheduler实例场景的锁控制问题

### ISSUE THREAD

**Issue by jacobslei** [xuxueli/xxl-job#1514]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0
### Expected behavior
正常调度
### Actual behavior
启动后一直报错
### Steps to reproduce the behavior
使用TiDB数据库作为数据库，启用乐观事务锁模式，部署多个scheduler实例即可重现
### Other information
报错日志：
at com.sun.proxy.$Proxy73.commit(Unknown Source)
at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:161)
at java.lang.Thread.run(Thread.java:748)
09:53:30.208 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - Write conflict, txnStartTS=415298279166967816, conflictStartTS=415298279166967815, conflictCommitTS=415298279180075042, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
java.sql.SQLException: Write conflict, txnStartTS=415298279166967816, conflictStartTS=415298279166967815, conflictCommitTS=415298279180075042, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1555)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
at com.sun.proxy.$Proxy73.commit(Unknown Source)
at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:161)
at java.lang.Thread.run(Thread.java:748)
09:53:31.043 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - Write conflict, txnStartTS=415298279429111834, conflictStartTS=415298279429111833, conflictCommitTS=415298279442219013, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
java.sql.SQLException: Write conflict, txnStartTS=415298279429111834, conflictStartTS=415298279429111833, conflictCommitTS=415298279442219013, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1555)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
at com.sun.proxy.$Proxy73.commit(Unknown Source)
at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:161)
at java.lang.Thread.run(Thread.java:748)
09:53:32.041 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - Write conflict, txnStartTS=415298279691255815, conflictStartTS=415298279691255814, conflictCommitTS=415298279704363011, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
java.sql.SQLException: Write conflict, txnStartTS=415298279691255815, conflictStartTS=415298279691255814, conflictCommitTS=415298279704363011, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1555)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
at com.sun.proxy.$Proxy73.commit(Unknown Source)
at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:161)
at java.lang.Thread.run(Thread.java:748)
09:53:33.042 logback [xxl-job, admin JobScheduleHelper#scheduleThread] ERROR c.x.j.a.c.thread.JobScheduleHelper - Write conflict, txnStartTS=415298279953399817, conflictStartTS=415298279953399815, conflictCommitTS=415298279966507014, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
java.sql.SQLException: Write conflict, txnStartTS=415298279953399817, conflictStartTS=415298279953399815, conflictCommitTS=415298279966507014, key={tableID=125, handle=1} primary={tableID=125, handle=1} [try again later]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1555)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.interceptor.AbstractCreateStatementInterceptor.invoke(AbstractCreateStatementInterceptor.java:79)
at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108)
at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81)
at com.sun.proxy.$Proxy73.commit(Unknown Source)
at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:161)
at java.lang.Thread.run(Thread.java:748)

XXL-JOB在多个调度中心锁控制的时候目前是通过：
```
select * from xxl_job_lock where lock_name = 'schedule_lock' for update

```

**悲观锁的机制控制的， 是否可以调整基于cas的乐观锁机制来避免该问题？**

**Comment by xfworld** [comment]
估计不行，悲观锁和乐观锁的定义都不一样，估计要解决这个问题，只能上分布式锁了

**Comment by xfworld** [comment]
tidb4.0 支持悲观锁了，你可以升级试试

**Comment by xuxueli** [comment]
你好，建议使用最新release版本，上述版本比较低。

+1 可以借鉴该方案 @xfworld
