### ISSUE TITLE
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP

### ISSUE THREAD

**Issue by Jinyanan** [xuxueli/xxl-job#1517]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2-SNAPSHOT
### Expected behavior
希望能在线上正常运行
### Actual behavior
现在是在线上一般情况下可以运行，偶尔会报同一个错误，找不到执行器,xxl-job trigger error, please check if the executor[192.168.20.22:9998] is running.
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP
虽然不影响线上的业务逻辑，但是会偶尔报错，希望能指导我如何解决这个问题
### Steps to reproduce the behavior
2020-03-12 20:04:36,519 ERROR [pool-2-thread-18]-[XxlJobTrigger:190] >>>>>>>>>>> xxl-job trigger error, please check if the executor[192.168.20.22:9998] is running.
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP@27023465::SocketChannelEndPoint@33c0a9dd{/192.168.20.22:9998<->/192.168.20.14:53188,ISHUT,fill=-,flush=-,to=487/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@27023465(l:/192.168.20.14:53188 <-> r:/192.168.20.22:9998,closed=false)=>HttpChannelOverHTTP@37c35dc8(exchange=HttpExchange@2016369c req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@13afea50(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@259737b9{s=START}],recv=HttpReceiverOverHTTP@89703de(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:338)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:209)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:147)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:745)

	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
	at com.sun.proxy.$Proxy158.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:188)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:141)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:75)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
### Other information
没有

**Comment by xuxueli** [comment]
你好，建议使用Release正式版本。
