### ISSUE TITLE
支持docker，日志不在包找不到错误

### ISSUE THREAD

**Issue by sundylgz** [xuxueli/xxl-job#1519]
xxl-job 2.1.2
接入xxl-job 机器会出现日志找不到报错，是因为k8s启动，原先的docker被销毁，找不到日志报错
java.io.FileNotFoundException: /data/logback/xxxx/8080/callbacklog/xxl-job-callback-1584429244334.log (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.xxl.job.core.util.FileUtil.readFileContent(FileUtil.java:84)
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:237)
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111)
	at java.lang.Thread.run(Thread.java:748)
这种查询日志方式能不能去掉

**Comment by xuxueli** [comment]
你好，这是日志回调异常日志。确认是否有改文件读写权限。

**Comment by sundylgz** [comment]
这个问题是docker部署，原来的机器不用了，查询导致的

**Comment by lyhdf** [comment]
> 这个问题是docker部署，原来的机器不用了，查询导致的
您好，可以再详细说明一下原因吗，谢谢。
