### ISSUE TITLE
json解析异常，项目正常启动出现json解析异常，拉取的是2.1.2版本

### ISSUE THREAD

**Issue by 991697456** [xuxueli/xxl-job#1533]
java.lang.IllegalArgumentException: Cannot parse JSON
	at com.xxl.registry.client.util.json.BasicJsonReader.parseMap(BasicJsonReader.java:25)
	at com.xxl.registry.client.util.json.BasicJson.parseMap(BasicJson.java:35)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:128)
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:41)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供操作步骤。

**Comment by 991697456** [comment]
问题已解决，我的管理界面admin那个项目访问路径与我的配置路径不一致导致的：原来：http://localhost:8083/xxl-job-admin，改为http://localhost:8083没有出现json解析异常



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "许雪里"<notifications@github.com&gt;; 
发送时间: 2020年3月29日(星期天) 下午2:37
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "崔宝玉"<991697456@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] json解析异常，项目正常启动出现json解析异常，拉取的是2.1.2版本 (#1533)





 
你好，问题无法复现，需要进一步提供操作步骤。

**Comment by chrisjiangfeng** [comment]
com.xxl.registry.client.util.json.BasicJsonReader#parseMap 收到html  所以导致报错   你改地址好想变成了404
