### ISSUE TITLE
java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by fjc440** [xuxueli/xxl-job#1538]
v 2.1.2

![image](https://user-images.githubusercontent.com/28079195/77885084-e6bd9100-7298-11ea-9ff7-e8589ad0d3bc.png)
 执行任务时报错，jobhandler文件夹已经创建

**Comment by fjc440** [comment]
ava.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
	at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
	at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:124)
[ERROR] [2020-03-30 15:08:58.990] [] [] [com.xxl.job.core.log.XxlJobFileAppender]  [106] - [No such file or directory]
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
	at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
	at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
	at com.jihex.service.ScheduledTasks.execute(ScheduledTasks.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)

**Comment by xuxueli** [comment]
确认下应用是不是对目录没有读写权限

**Comment by dongyun-coder** [comment]
有一个越界的问题
