### ISSUE TITLE
用 docker 运行 xxl-job-admin 一直报错（mysql5.7），我用本地源码运行又是可以的

### ISSUE THREAD

**Issue by aslzl** [xuxueli/xxl-job#1555]
docker run -e PARAMS="--spring.datasource.url=jdbc:mysql://10.104.141.26:3306/xxl_job?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC --spring.datasource.username=root --spring.datasource.password=123456" -p 6080:8080 -v /tmp:/data/applogs --name xxl-job-admin  --privileged=true -d xuxueli/xxl-job-admin:2.1.2

====================================

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor57.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)

**Comment by aslzl** [comment]
后来试过:
升级数据 ->mysql5.7.29
降低软件版本-> xuxueli/xxl-job-admin:2.1.0
换端口号->8080

都还是不行：mysql 连接失败。
但是我把源码下载过来，直接在 idea 上跑 又是可以的，配置文件都是一样的

**Comment by aslzl** [comment]
原因是 我的 mysql 和 xxl-job 都是用容器启动的，两个容器间有通讯问题，贴出例子，希望对大家有帮助（主要是 --link）：
docker run \
--link mysql:tomysql \
-e PARAMS="--spring.datasource.url=jdbc:mysql://tomysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=123456" \
-p 9080:8080 \
-v /root/xxl-job/log:/data/applogs \
--name xxl-job-admin --privileged=true \
-d xuxueli/xxl-job-admin:2.1.2

**Comment by dudiao** [comment]
mysql需要设置下：bind-address = 0.0.0.0
