### ISSUE TITLE
启动好像不能成功

### ISSUE THREAD

**Issue by baiyeGit** [xuxueli/xxl-job#1569]
启动项目报这样的错误，应该是任务执行报错吗？

2020-04-13 14:40:49.837  INFO 2124 --- [rRegistryThread] c.x.r.r.i.reference.XxlRpcReferenceBean  : >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.168.11.226:8090/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='f89f3922-835f-4d65-89ff-7bbd4782797b', createMillisTime=1586760046819, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='nginx-scan-xxljob', registryValue='192.168.199.156:12'}], version='null'}
2020-04-13 14:40:49.837  INFO 2124 --- [      Thread-13] c.x.r.r.i.reference.XxlRpcReferenceBean  : >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.168.11.226:8090/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='4906c6c6-0c3e-427e-a794-56500b204272', createMillisTime=1586760046820, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=41681, logDateTim=1586749980177, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-04-13 14:40:49.837  INFO 2124 --- [rRegistryThread] c.x.j.c.thread.ExecutorRegistryThread    : >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='nginx-scan-xxljob', registryValue='192.168.199.156:12'}

com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1586760049837, request:XxlRpcRequest{requestId='f89f3922-835f-4d65-89ff-7bbd4782797b', createMillisTime=1586760046819, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='nginx-scan-xxljob', registryValue='192.168.199.156:12'}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
	at com.sun.proxy.$Proxy114.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)

2020-04-13 14:41:19.862 ERROR 2124 --- [tLoopGroup-20-1] c.x.r.r.n.i.n.c.NettyHttpClientHandler   : >>>>>>>>>>> xxl-rpc netty_http client caught exception

com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:40)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
回调地址填错，或者回调服务不可用导致的，检查下。
