### ISSUE TITLE
Exception in thread "Thread-81" java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by liubao425** [xuxueli/xxl-job#1590]
版本：2.2.0 

2020-04-17 19:24:57.517  INFO 11108 --- [           main] c.xxl.job.core.executor.XxlJobExecutor   : >>>>>>>>>>> xxl-job register jobhandler success, name:demoJobHandler, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@53ccbc15[class com.xxx.xxx.base.provider.job.DemoJobHandler#execute]
Exception in thread "Thread-81" java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:550)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:504)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:489)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:248)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-04-17 19:24:57.793  INFO 11108 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed

启动时候会报这样的错误, 使用的是nacos, nacos 和xxl-admin 在本机的虚拟机上，本机只启了这一个服务，但是不影响使用，xxl-job可以正常执行，重启机子了很多遍，还是会报这个错误
在 2.1.1 版本上 相同的情况就不会有这个报错

**Comment by liubao425** [comment]
不好意思 问题找到了， 我忘了移除   组件的init和destroy方法

**Comment by aws0me** [comment]
> 不好意思 问题找到了， 我忘了移除 组件的init和destroy方法

你好,我碰到了同样的问题,你说的init和destroy方法是在xxl-job-admin模块里的吗?

**Comment by liubao425** [comment]
> > 不好意思 问题找到了， 我忘了移除 组件的init和destroy方法
> 
> 你好,我碰到了同样的问题,你说的init和destroy方法是在xxl-job-admin模块里的吗?

你看 它这个 2.1.2的版本说明，我当初就大意了，当初从2.1.1直接升级到了2.2.0，2.1.2版本说明最后一句话：   
注意：最新版本 “XxlJobSpringExecutor” 逻辑有调整，历史项目中该组件的配置方式请参考Sample示例项目进行调整，尤其注意需要移除组件的init和destroy方法；

**Comment by aws0me** [comment]
> > > 不好意思 问题找到了， 我忘了移除 组件的init和destroy方法
> > 
> > 
> > 你好,我碰到了同样的问题,你说的init和destroy方法是在xxl-job-admin模块里的吗?
> 
> 你看 它这个 2.1.2的版本说明，我当初就大意了，当初从2.1.1直接升级到了2.2.0，2.1.2版本说明最后一句话：
> 注意：最新版本 “XxlJobSpringExecutor” 逻辑有调整，历史项目中该组件的配置方式请参考Sample示例项目进行调整，尤其注意需要移除组件的init和destroy方法；

看到了,非常感谢!
