### ISSUE TITLE
java.text.ParseException: Unparseable date: "zagk-busi-parent"  这样的错误为什么？

### ISSUE THREAD

**Issue by aileennian** [xuxueli/xxl-job#1598]
2020-04-21 00:30:46.269 ERROR 21968 --- [FileCleanThread] c.x.j.core.thread.JobLogFileCleanThread  : Unparseable date: "zagk-busi-parent"

java.text.ParseException: Unparseable date: "zagk-busi-parent"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.xxl.job.core.thread.JobLogFileCleanThread$1.run(JobLogFileCleanThread.java:69)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，执行器日志目录中写入非法数据导致，需要将执行器日志目录与其他日志目录隔离开。
