### ISSUE TITLE
admin项目使用hikari连接mycat偶尔超时，其它项目是正常的，同样的连接池配置

### ISSUE THREAD

**Issue by caopengcheng-86** [xuxueli/xxl-job#1604]
2020-04-21 17:59:35,612 WARN [xxl-job, admin JobScheduleHelper#scheduleThread] c.zaxxer.hikari.pool.ProxyConnection [ProxyConnection.java : 157] xxljobadmin - Connection com.mysql.jdbc.JDBC4Connection@7ac2670a marked as broken because of SQLSTATE(08S01), ErrorCode(0)
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 20,081 milliseconds ago.  The last packet sent successfully to the server was 20,081 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor260.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3457)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3357)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3797)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2949)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3367)
	... 11 common frames omitted
2020-04-21 17:59:35,612 ERROR [xxl-job, admin JobScheduleHelper#scheduleThread] c.x.j.a.c.thread.JobScheduleHelper [JobScheduleHelper.java : 150] >>>>>>>>>>> xxl-job, JobScheduleHelper#scheduleThread error:{}
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 20,081 milliseconds ago.  The last packet sent successfully to the server was 20,081 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor260.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:983)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3457)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3357)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3797)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:77)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2949)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3367)
	... 11 common frames omitted
2020-04-21 17:59:35,613 ERROR [xxl-job, admin JobScheduleHelper#scheduleThread] c.x.j.a.c.thread.JobScheduleHelper [JobScheduleHelper.java : 160] Connection is closed
java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:494)
	at com.sun.proxy.$Proxy99.commit(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:366)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:157)
	at java.lang.Thread.run(Thread.java:748)
2020-04-21 17:59:35,613 ERROR [xxl-job, admin JobScheduleHelper#scheduleThread] c.x.j.a.c.thread.JobScheduleHelper [JobScheduleHelper.java : 167] Connection is closed
java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:494)
	at com.sun.proxy.$Proxy99.setAutoCommit(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:393)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:164)
	at java.lang.Thread.run(Thread.java:748)
2020-04-21 18:00:34,370 WARN [xxl-job, admin JobRegistryMonitorHelper] com.zaxxer.hikari.pool.PoolBase [PoolBase.java : 179] xxljobadmin - Failed to validate connection com.mysql.jdbc.JDBC4Connection@dd03c94 (Communications link failure

报错代码位置：
at com.xxl.job.admin.core.thread.JobScheduleHelper$1.run(JobScheduleHelper.java:77)：
 preparedStatement = conn.prepareStatement(  "select * from xxl_job_lock where lock_name = 'schedule_lock' for update" );
                        preparedStatement.execute();

**Comment by caopengcheng-86** [comment]
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql:/
spring.datasource.username=
spring.datasource.password=
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.pool-name=xxljobadminPool
spring.datasource.hikari.leak-detection-threshold=25000

**Comment by xuxueli** [comment]
你好，可以调小 spring.datasource.hikari.max-lifetime 配置。
