### ISSUE TITLE
线程处理不支持优雅停机

### ISSUE THREAD

**Issue by liangjf85** [xuxueli/xxl-job#1621]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.1
### Expected behavior
系统中大量的线程处理方式不够优雅，定时后台线程建议调整为ScheduledExecutorService
其他场景建议支持系统优雅停机，避免强制停止线程

### Other information
2020-04-24 14:22:49.774 [RMI TCP Connection(2)-127.0.0.1] [] 341 INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@6604c970{HTTP/1.1,[http/1.1]}{0.0.0.0:9999}
2020-04-24 14:22:49.784 [Thread-22] [] 55 ERROR com.xxl.rpc.remoting.net.Server - >>>>>>>>>>> xxl-rpc remoting server start error.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.join(QueuedThreadPool.java:473)
	at org.eclipse.jetty.server.Server.join(Server.java:556)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer$1.run(JettyServer.java:53)
	at java.lang.Thread.run(Thread.java:745)
2020-04-24 14:22:49.784 [Thread-22] [] 55 ERROR com.xxl.rpc.remoting.net.Server - >>>>>>>>>>> xxl-rpc remoting server start error.
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.join(QueuedThreadPool.java:473)
	at org.eclipse.jetty.server.Server.join(Server.java:556)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer$1.run(JettyServer.java:53)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xuxueli** [comment]
你好，这个问题高版本已经做了优化，建议升级。
