### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.setLength(I)V

### ISSUE THREAD

**Issue by xzy1586** [xuxueli/xxl-job#1623]
spring boot 工程，在调用定时任务时报错，如下：
2020-04-24 16:20:22.593 ERROR 9232 --- [ntLoopGroup-6-3] j.c.s.EmbedServer$EmbedHttpServerHandler : >>>>>>>>>>> xxl-job provider netty_http server caught exception

java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.setLength(I)V
	at io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:893) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]
	at io.netty.handler.codec.http.HttpObjectDecoder$LineParser.process(HttpObjectDecoder.java:941) ~[netty-all-4.1.48.Final.jar:4.1.48.Final]

其实有这个方法，我有两个项目，一个项目不报这个错误，一个会报错误

**Comment by xuxueli** [comment]
你好，从 NoSuchMethodError 来看，应该是netty版本冲突，可以检查下版本信息。
