### ISSUE TITLE
xxl-job2.1 执行器报了找不到ch/qos/logback/classic/spi/ThrowableProxy 是什么问题

### ISSUE THREAD

**Issue by ltjsj** [xuxueli/xxl-job#1647]
`Exception in thread "xxl-rpc, NettyHttpServer-serverHandlerPool-1126297257" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.error(Logger.java:538)
        at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:228)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:86)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.spi.ThrowableProxy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 11 more
2020-04-30 15:46:32.483  INFO 29222 --- [      Thread-22] com.xxl.job.core.thread.JobThread        : >>>>>>>>>>> xxl-job JobThread stoped, hashCode:Thread[Thread-22,10,main]`

**Comment by dudiao** [comment]
检查下执行器和调度器使用的是否是一个版本

**Comment by ltjsj** [comment]
你是说执行器用到的logback 和 xxljob 调度器用到的logback 不一致导致的吗？

**Comment by ltjsj** [comment]
Spring Boot 报错
经过多次测试得出原因： 服务器运行时，不要上传jar包，一定要把服务停止掉，再上传jar。

应该是部署导致的这个错

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
