### ISSUE TITLE
Socket read timed out

### ISSUE THREAD

**Issue by busishe** [xuxueli/xxl-job#1652]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Actual behavior
你好，在使用xxl-job的时候我们遇到如下问题，定时任务均可以成功执行，但是每天凌晨3点、5点多的时候都会出现执行器回调调度中心的超时错误。
目前我们的部署方式是调度中心和执行器均上云集群化，均为内部接入。
### Other information

2020-05-06T05:22:05.081+0800 [xxl-job, executor TriggerCallbackThread] ERROR com.xxl.job.core.util.XxlJobRemotingUtil - Read timed out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:127)
        at java.net.SocketInputStream.read(SocketInputStream.java:181)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:257)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:297)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:356)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1551)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1456)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:491)
        at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115)
        at com.xxl.job.core.biz.client.AdminBizClient.callback(AdminBizClient.java:37)
        at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:167)
        at com.xxl.job.core.thread.TriggerCallbackThread.access$200(TriggerCallbackThread.java:25)
        at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:75)
        at java.lang.Thread.run(Thread.java:785)

**Comment by busishe** [comment]
超时时间看core源码中固定为3秒，我理解可能是通讯时候会偶尔出现异常。但是我们的执行器和调度中心都是云内部调用，网络环境应该是比较稳定的，而且比较奇怪的是每天都是比较相近的时间出现异常。

**Comment by xuxueli** [comment]
你好，问题无法复现，需要进一步提供复现步骤。而且固定每天早上3点发生比较奇怪，可以监控下这个时间端网络情况。

针对回调失败问题，这个不影响业务的，执行器回调存在重试逻辑的。

**Comment by alicgq** [comment]
相同问题我也碰到过，调度日志部分存在较多不合理慢查统计，建议改写或者禁用掉这部分功能，瞬间好转
