### ISSUE TITLE
项目重启过程中抛出InterruptedException异常

### ISSUE THREAD

**Issue by GoldyMark** [xuxueli/xxl-job#166]
### 版本
+ 1.8.2
### 问题
项目在发布重启的过程中抛出以下异常（看起来是`TriggerCallbackThread`第55行代码抛出的异常。）：

```java
2017-09-18 12:33:52,485 ERROR (ExecutorRegistryThread.java:77) - sleep interrupt
ed
java.lang.InterruptedException: sleep interrupted
        at java.lang.Thread.sleep(Native Method) ~[?:1.8.0_65]
        at java.lang.Thread.sleep(Thread.java:340) ~[?:1.8.0_65]
        at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386) ~[?:1.8.0_65]
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistry
Thread.java:75) [xxl-job-core-1.8.2.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
2017-09-18 12:33:52,486 WARN  (XxlJobLogger.java:46) - [2017-09-18/168237.log]:
2017-09-18 12:33:52 [com.xxl.job.core.thread.JobThread]-[run]-[154]-[Thread-18]
<br>----------- xxl-job toStop, stopReason:Web容器销毁终止
2017-09-18 12:33:52,486 WARN  (XxlJobLogger.java:46) - [2017-09-18/168237.log]:
2017-09-18 12:33:52 [com.xxl.job.core.thread.JobThread]-[run]-[160]-[Thread-18]
----------- xxl-job JobThread Exception:java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:99)

2017-09-18 12:33:52,487 INFO  (JobThread.java:174) - >>>>>>>>>>>> xxl-job JobThread stoped, hashCode:Thread[Thread-18,5,main]
2017-09-18 12:33:52,498 INFO  (ExecutorRegistryThread.java:89) - >>>>>>>>>>> xxl-job registry-remove success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='********', registryValue='********'}, registryResult:ReturnT [code=200, msg=null, content=null]
2017-09-18 12:33:52,499 WARN  (ExecutorRegistryThread.java:102) - >>>>>>>>>>>> xxl-job, executor registry thread destory.
2017-09-18 12:33:52,520 ERROR (TriggerCallbackThread.java:69) - null
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_65]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_65]
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442) ~[?:1.8.0_65]
        at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:55) [xxl-job-core-1.8.2.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
2017-09-18 12:33:52,523 WARN  (TriggerCallbackThread.java:83) - >>>>>>>>>>>> xxl-job, executor callback thread destory.
2017-09-18 12:33:52,563 INFO  (AbstractConnector.java:306) - Stopped ServerConnector@16d7f240{HTTP/1.1}{0.0.0.0:9999}
2017-09-18 12:33:52,587 INFO  (JettyServer.java:89) - >>>>>>>>>>> xxl-rpc server destroy success, netcon=com.xxl.job.core.rpc.netcom.jetty.server.JettyServer
```

**Comment by xuxueli** [comment]
你好，感谢关注和反馈。
上述“InterruptedException”是正常现象，可以忽略。
执行器在容器销毁时，需要上报容器销毁事件给调度中心，然后销毁 “心跳注册线程” 和 “执行结果回调线程” 等几个守护线程，心跳注册线程可能正处于休眠状态需要主动线程中断，因此产生上述现象。

**Comment by GoldyMark** [comment]
如果是正常现象的话，那日志级别应该调为WARN级别会比较合理（目前我司会监控日志里面的ERROR信息并自动触发报警）。@xuxueli

**Comment by ljyrains** [comment]
如果是正常现象的话，那日志级别应该调为WARN级别会比较合理+1（不然只能将xxl-job的日志特别处理了），建议：
```java
try{
    // TODO
} catch (Exception e) {
    if (e instanceof InterruptedException) {
      //warn
    }
    //error
}
```

**Comment by gentoo111** [comment]
我也遇到了同样的困惑，项目关闭或重新都有这个错，而且是error级别的
