### ISSUE TITLE
JSON解析异常导致无限回调

### ISSUE THREAD

**Issue by yanzhisishui** [xuxueli/xxl-job#1688]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('2' (code 50)): was expecting comma to separate Object entries
xxl-job    |  at [Source: (String)"[{"logId":174,"logDateTim":1589385600003,"executeResult":{"code":500,"msg":"java.util.concurrent.ExecutionException: org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Unexpected character ('-' (code 45)): Expected space separating root-level values\n at [Source: (byte[])"2020-05-09 16:18:46"; line: 1, column: 6]; nested exception is com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values"[truncated 3245 chars]; line: 1, column: 311]

已经更新到最新版，但是一直报错这个，而且我把数据库里面的174日志删掉了。。。。请求解答，万分感谢

**Comment by Xusq513** [comment]
这个问题有解决吗

**Comment by yanzhisishui** [comment]
已解决。升级版本即可



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael Xu"<notifications@github.com&gt;; 
发送时间: 2020年6月9日(星期二) 上午9:55
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "Never Part Too"<1481232419@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] JSON解析异常导致无限回调 (#1688)





 
这个问题有解决吗

**Comment by Xusq513** [comment]
e ,,我这边只能到2.1.2版本了，升级不了新版本了。

**Comment by ContinueCoding** [comment]
@yanzhisishui 请问需要升级到哪个版本？我用的2.2.0-SNAPSHOT，还有类似报错。

**Comment by qhysjpw** [comment]
@yanzhisishui 请问这个修改具体在哪个地方，我们版本升级不了

**Comment by yanzhisishui** [comment]
@qhysjpw 我就是升级版本解决的，官方也说了是版本问题。我也不知道怎么改呀

**Comment by yanzhisishui** [comment]
我现在的版本是2.2.1

**Comment by qhysjpw** [comment]
> 我现在的版本是2.2.1

好的谢谢，我去看下更新日志

**Comment by OlayTree** [comment]
我升级之后这个异常没有了，但是出现了新的异常
2021-02-01 15:09:49.709 [http-nio-60013-exec-4] ERROR c.x.j.a.controller.resolver.WebExceptionResolver - WebExceptionResolver:{}
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 665 path $[0].executeResult.msg
	at com.google.gson.Gson.fromJson(Gson.java:942)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.xxl.job.core.util.GsonTool.fromJson(GsonTool.java:53)
	at com.xxl.job.admin.controller.JobApiController.api(JobApiController.java:58)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)


	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)


	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)


	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)


	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:884)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)


	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)


	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)


	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)


	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)


	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)


	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)


	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)


	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)


	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)


	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)


	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)


	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)


	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)


	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)


	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)


	at java.lang.Thread.run(Thread.java:748)
