### ISSUE TITLE
终止任务无法停止

### ISSUE THREAD

**Issue by zdd10010806** [xuxueli/xxl-job#1722]
2.0.1 版本终止任务没反应，也没调用destroy() 方法

com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP@369939aa(l:/10.52.101.99:41023 <-> r:/10.1.38.62:9999,closed=false)[HttpChannelOverHTTP@385ec109(exchange=HttpExchange@3c6152da req=TERMINATED/null@null res=PE
NDING/null@null)[send=HttpSenderOverHTTP@7963cb32(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@6c8e9dd(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1305)
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182)
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129)
at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)

**Comment by nvr-zhangchao** [comment]
是啊  怎么解决的，不然没法优雅关机啊

**Comment by xuxueli** [comment]
新版本已优化处理，建议升级
