### ISSUE TITLE
集成 xxl-job 2.2.0 启动执行器报错NullPointerException

### ISSUE THREAD

**Issue by yinjingjiu** [xuxueli/xxl-job#1729]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
version: XXL-JOB Admin v2.2.0

通过以下方式编写了一个执行器
<details>
<summary>pom.xml:</summary>

```xml
<dependency>
    <groupId>com.xuxueli</groupId>
    <artifactId>xxl-job-core</artifactId>
    <version>2.2.0</version>
</dependency>
```
</details>

<details>
<summary>XxlJobConfig.java:</summary>

```java
@Configuration
public class XxlJobConfig {
    private Logger logger = LoggerFactory.getLogger(XxlJobConfig.class);

    @Value("${xxl.job.admin.addresses}")
    private String adminAddresses;

    @Value("${xxl.job.accessToken}")
    private String accessToken;

    @Value("${xxl.job.executor.appname}")
    private String appname;

    @Value("${xxl.job.executor.address}")
    private String address;

    @Value("${xxl.job.executor.ip}")
    private String ip;

    @Value("${xxl.job.executor.port}")
    private int port;

    @Value("${xxl.job.executor.logpath}")
    private String logPath;

    @Value("${xxl.job.executor.logretentiondays}")
    private int logRetentionDays;


    @Bean
    public XxlJobSpringExecutor xxlJobExecutor() {
        logger.info(">>>>>>>>>>> xxl-job config init.");
        XxlJobSpringExecutor xxlJobSpringExecutor = new XxlJobSpringExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppname(appname);
        xxlJobSpringExecutor.setAddress(address);
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

        return xxlJobSpringExecutor;
    }
}
```
</details>

<details>
<summary>SampleXxlJob.java:</summary>

```java
@Component
public class SampleXxlJob {
    private static Logger logger = LoggerFactory.getLogger(SampleXxlJob.class);


    /**
     * 1、简单任务示例（Bean模式）
     */
    @XxlJob("demoJobHandler")
    public ReturnT<String> demoJobHandler(String param) throws Exception {
        XxlJobLogger.log("XXL-JOB, Hello World.");

        for (int i = 0; i < 5; i++) {
            XxlJobLogger.log("beat at:" + i);
            TimeUnit.SECONDS.sleep(2);
        }
        return ReturnT.SUCCESS;
    }

}
```
</details>

启动我的执行器项目异常如下
```xml
08:50:23.234 logback [main] ERROR c.x.j.c.e.impl.XxlJobSpringExecutor - xxl-job method-jobhandler resolve error for bean[requestProtocolConfig].
java.lang.NullPointerException: null
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.initJobHandlerMethodRepository(XxlJobSpringExecutor.java:92)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterSingletonsInstantiated(XxlJobSpringExecutor.java:39)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java:40002)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:41008)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
```
xxl-job-admin 调度中心后台能发现执行器
![image](https://user-images.githubusercontent.com/8465157/83315831-1a934380-a255-11ea-9ee7-0bf712205887.png)

请问该异常如何解决

**Comment by zwp201301** [comment]
requestProtocolConfig 是你程序里的吗,贴出来看看.
从报错来看, 是@XxlJob注解上的方法有问题,导致了空指针.

**Comment by yinjingjiu** [comment]
```java
@Component
public class SampleXxlJob {
    private static Logger logger = LoggerFactory.getLogger(SampleXxlJob.class);


    /**
     * 1、简单任务示例（Bean模式）
     */
    @XxlJob("demoJobHandler")
    public ReturnT<String> demoJobHandler(String param) throws Exception {
        XxlJobLogger.log("XXL-JOB, Hello World.");

        for (int i = 0; i < 5; i++) {
            XxlJobLogger.log("beat at:" + i);
            TimeUnit.SECONDS.sleep(2);
        }
        return ReturnT.SUCCESS;
    }

}
```
@zwp201301  我像你保证，当我启动执行器会出现这一意外，当我退回到2.0.2版本，采用@JobHandler注解，我的程序完美运行，我用的是springboot1.5.x

**Comment by daiing** [comment]
我也和你启动时候报一样的错误，但是还是正常使用，很奇怪

**Comment by springsupervip** [comment]
14:53:13.539 logback [main] INFO  c.x.j.e.XxlJobExecutorApplication - Started XxlJobExecutorApplication in 1.3090978 seconds (JVM running for 1.839)
14:53:13.542 logback [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
14:53:13.546 logback [SpringContextShutdownHook] ERROR c.p.s.o.j.c.executor.XxlJobExecutor - null
java.lang.NullPointerException: null
	at com.pingan.stock.omm.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)
	at com.pingan.stock.omm.job.core.server.EmbedServer.stopRegistry(EmbedServer.java:262)
	at com.pingan.stock.omm.job.core.server.EmbedServer.stop(EmbedServer.java:124)
	at com.pingan.stock.omm.job.core.executor.XxlJobExecutor.stopEmbedServer(XxlJobExecutor.java:158)
	at com.pingan.stock.omm.job.core.executor.XxlJobExecutor.destroy(XxlJobExecutor.java:85)
	at com.pingan.stock.omm.job.core.executor.impl.XxlJobSpringExecutor.destroy(XxlJobSpringExecutor.java:54)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1091)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1084)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
14:53:13.547 logback [xxl-job, executor JobLogFileCleanThread] INFO  c.p.s.o.j.c.t.JobLogFileCleanThread - >>>>>>>>>>> xxl-job, executor JobLogFileCleanThread thread destory.
14:53:13.547 logback [xxl-job, executor TriggerCallbackThread] INFO  c.p.s.o.j.c.t.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor callback thread destory.
14:53:13.548 logback [Thread-4] INFO  c.p.s.o.j.c.t.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor retry callback thread destory.

求解？

**Comment by xuxueli** [comment]
你好，问题无法复现，需要提供完成复现步骤。
可以对比sample示例，示例能够正常运行。
