### ISSUE TITLE
docker单机部署，执行任务失败，Error writing to server

### ISSUE THREAD

**Issue by a807966224** [xuxueli/xxl-job#1731]
22:25:25.815 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-580106000] ERROR c.x.job.core.util.XxlJobRemotingUtil - Error writing to server
java.io.IOException: Error writing to server
        at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:700)
        at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:712)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1591)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115)
        at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:89)
        at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

之前是connect refused，我在docker里打开了9999端口映射关系后，变为上面的错误信息提示，辛苦博主给一波docker的具体操作！

**Comment by a807966224** [comment]
已经解决了，个人配置问题

**Comment by zhouqizhou** [comment]
> 已经解决了，个人配置问题

什么配置会引起这个问题呢？

**Comment by zhouqizhou** [comment]
@a807966224

**Comment by a807966224** [comment]
由于docker 容器识别网卡错误，导致任务回调无法正常发起网络连接，在配置文件里指定具体的机器ip地址即可### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ip: '192.168.6.102'





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhouqizhou"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 下午5:35
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "安徐正静"<807966224@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] docker单机部署，执行任务失败，Error writing to server (#1731)





  
已经解决了，个人配置问题
  
什么配置会引起这个问题呢？

**Comment by zhouqizhou** [comment]
这边在阿里云k8s环境部署，pod的ip不是固定的，配置文件里指定ip应该不可行？

我在后台admin的pod curl执行器的url也能正常响应，所以有点怀疑不是ip的问题？

**Comment by a807966224** [comment]
网络别名试试呢？可以为容器指定网络环境后确定网络别名，但是不知道框架是支持



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhouqizhou"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 晚上6:44
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "安徐正静"<807966224@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job] docker单机部署，执行任务失败，Error writing to server (#1731)





 
这边在阿里云k8s环境部署，pod的ip不是固定的，配置文件里指定ip应该不可行？
 
我在后台admin的pod curl执行器的url也能正常响应，所以有点怀疑不是ip的问题？
