### ISSUE TITLE
SQLException: interrupt这个错误

### ISSUE THREAD

**Issue by qq649208085** [xuxueli/xxl-job#1744]
最近都发生SQLException: interrupt这个错误，一天报几次，调度2分钟执行一次。
究竟是什么问题
druid是1.1.14版本
xxl-job是1.8.2版本

2020-06-03 23:12:00 [com.xxl.job.core.thread.JobThread]-[run]-[117]-[Thread-1291] 
----------- xxl-job job execute start -----------
----------- Params:null
2020-06-03 23:12:00 [com.freshjn.tms.engine.sys.NotifyTimeoutJob]-[execute]-[34]-[Thread-1291] [BEGIN] 执行NotifyJob
2020-06-03 23:12:00 [com.xxl.job.core.thread.JobThread]-[run]-[127]-[Thread-1291] 
----------- JobThread toStop, stopReason:null
2020-06-03 23:12:00 [com.xxl.job.core.thread.JobThread]-[run]-[135]-[Thread-1291] 
----------- JobThread Exception:org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy98.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy137.selectByExample(Unknown Source)
	at com.freshjn.tms.service.core.BaseService.selectByExample(BaseService.java:114)
	at com.freshjn.tms.service.sys.impl.NotifyServiceImpl.selectTimeoutList(NotifyServiceImpl.java:65)
	at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy138.selectTimeoutList(Unknown Source)
	at com.freshjn.tms.engine.sys.NotifyTimeoutJob.execute(NotifyTimeoutJob.java:35)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:119)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 16 more
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:142)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy259.query(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 21 more
Caused by: java.sql.SQLException: interrupt
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1484)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1326)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5007)
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
	at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:886)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
	at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2746)
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1304)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1296)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	... 33 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1481)
	... 46 more

----------- xxl-job job execute end(error) -----------

**Comment by panchw** [comment]
我们也遇到了这个问题，您那边后来解决了吗？

**Comment by panchw** [comment]
> 最近都发生SQLException: interrupt这个错误，一天报几次，调度2分钟执行一次。
> 究竟是什么问题
> druid是1.1.14版本
> xxl-job是1.8.2版本
> 
> 2020-06-03 23:12:00 [com.xxl.job.core.thread.JobThread]-[run]-[117]-[Thread-1291]
> ----------- xxl-job job execute start -----------
> ----------- Params:null
> 2020-06-03 23:12:00 [com.freshjn.tms.engine.sys.NotifyTimeoutJob]-[execute]-[34]-[Thread-1291] [BEGIN] 执行NotifyJob
> 2020-06-03 23:12:00 [com.xxl.job.core.thread.JobThread]-[run]-[127]-[Thread-1291]
> ----------- JobThread toStop, stopReason:null
> 2020-06-03 23:12:00 [com.xxl.job.core.thread.JobThread]-[run]-[135]-[Thread-1291]
> ----------- JobThread Exception:org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:
> 
> ### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
> ### The error may exist in com/freshjn/tms/dao/sys/NotifyMapper.java (best guess)
> ### The error may involve com.freshjn.tms.dao.sys.NotifyMapper.selectByExample
> ### The error occurred while executing a query
> ### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
> ```
> at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
> at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
> at com.sun.proxy.$Proxy98.selectList(Unknown Source)
> at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
> at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
> at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
> at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
> at com.sun.proxy.$Proxy137.selectByExample(Unknown Source)
> at com.freshjn.tms.service.core.BaseService.selectByExample(BaseService.java:114)
> at com.freshjn.tms.service.sys.impl.NotifyServiceImpl.selectTimeoutList(NotifyServiceImpl.java:65)
> at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
> at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
> at com.sun.proxy.$Proxy138.selectTimeoutList(Unknown Source)
> at com.freshjn.tms.engine.sys.NotifyTimeoutJob.execute(NotifyTimeoutJob.java:35)
> at com.xxl.job.core.thread.JobThread.run(JobThread.java:119)
> ```
> 
> Caused by: org.apache.ibatis.exceptions.PersistenceException:
> 
> ### Error querying database. Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
> ### The error may exist in com/freshjn/tms/dao/sys/NotifyMapper.java (best guess)
> ### The error may involve com.freshjn.tms.dao.sys.NotifyMapper.selectByExample
> ### The error occurred while executing a query
> ### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
> ```
> at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
> at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
> ... 16 more
> ```
> 
> Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLException: interrupt
> at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
> at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
> at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
> at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
> at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
> at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
> at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
> at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
> at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
> at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:142)
> at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
> at com.sun.proxy.$Proxy259.query(Unknown Source)
> at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
> ... 21 more
> Caused by: java.sql.SQLException: interrupt
> at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1484)
> at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1326)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5007)
> at com.alibaba.druid.filter.stat.StatFilter.dataSource_getConnection(StatFilter.java:680)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
> at com.alibaba.druid.filter.logging.LogFilter.dataSource_getConnection(LogFilter.java:886)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
> at com.alibaba.druid.filter.FilterAdapter.dataSource_getConnection(FilterAdapter.java:2746)
> at com.alibaba.druid.filter.FilterChainImpl.dataSource_connect(FilterChainImpl.java:5003)
> at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1304)
> at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1296)
> at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
> at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
> at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
> ... 33 more
> Caused by: java.lang.InterruptedException
> at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
> at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
> at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1481)
> ... 46 more
> 
> ----------- xxl-job job execute end(error) -----------
我们也遇到了这个问题，您那边后来解决了吗？

**Comment by qq649208085** [comment]
> 我们也遇到了这个问题，您那边后来解决了吗？

升级xxl版本呗，升级到了2.2就没有了

**Comment by xuxueli** [comment]
你好，从日志看 ” NotifyMapper.xml“ 是业务表故障，非xxl-job内部问题。可以从相关业务逻辑着手排查下。

**Comment by doolindalton** [comment]
> 升级xxl版本呗，升级到了2.2就没有了

您那边是升级到2.2.0就没有这个问题了吗？我这边也是2.2.0有问题，且使用@scheduled无问题

**Comment by doolindalton** [comment]
> 我们也遇到了这个问题，您那边后来解决了吗？

您这边解决了吗

**Comment by panchw** [comment]
解决了，起了多个调度中心，lock表中的初始化数据没插入进去，导致调度中心并发执行。
执行期端缺少同步措施导致
把lock表中的数据加进去就好了

**Comment by jacky-citic** [comment]
我们只起了一个pod，但也发生同样的问题，还有没有其他解决方案？

**Comment by jacky-citic** [comment]
> 你好，从日志看 ” NotifyMapper.xml“ 是业务表故障，非xxl-job内部问题。可以从相关业务逻辑着手排查下。

@xuxueli 不是业务逻辑报错
