### ISSUE TITLE
xxljob-admin有json解析报错

### ISSUE THREAD

**Issue by wpailn** [xuxueli/xxl-job#1746]
xxljob-admin有json解析报错

`Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('h' (code 104)): was expecting comma to separate Object entries
 at [Source: (StringReader); line: 1, column: 589]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2294)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:918)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 62 common frames omitted
09:54:08.799 logback [http-nio-8090-exec-3] ERROR c.x.job.admin.core.util.JacksonUtil - Unexpected character ('h' (code 104)): was expecting comma to separate Object entries
 at [Source: (StringReader); line: 1, column: 79] (through reference chain: java.util.ArrayList[0]->com.xxl.job.core.biz.model.HandleCallbackParam["executeResult"])
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('h' (code 104)): was expecting comma to separate Object entries
 at [Source: (StringReader); line: 1, column: 79] (through reference chain: java.util.ArrayList[0]->com.xxl.job.core.biz.model.HandleCallbackParam["executeResult"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
`

**Comment by olicu** [comment]
我也有遇到这个问题

**Comment by powerLeePlus** [comment]
这个问题是自己业务报错，里面含有json不支持的字符导致的

**Comment by GK313** [comment]
这个问题应该怎么解决呀

**Comment by xuxueli** [comment]
新版本已优化，建议升级。
