### ISSUE TITLE
执行器启动

### ISSUE THREAD

**Issue by pengbw** [xuxueli/xxl-job#1757]
java.text.ParseException: Unparseable date: "xxl-job"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.xxl.job.core.thread.JobLogFileCleanThread$1.run(JobLogFileCleanThread.java:69)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhangJianxing2011** [comment]
我也有同样的问题

**Comment by zhangJianxing2011** [comment]
我也有同样的问题
![image](https://user-images.githubusercontent.com/37395113/105434836-3d1c1600-5c97-11eb-8b08-2586e333de27.png)

**Comment by xuxueli** [comment]
新版本已优化处理，建议升级
