### ISSUE TITLE
xxl-job 2.1.2 version NullPointerException issues

### ISSUE THREAD

**Issue by huangm59** [xuxueli/xxl-job#1759]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior

2020-06-11 09:51:26.106|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobConfig.xxlJobExecutor():37|====xxl-job config init====
2020-06-11 09:51:26.135|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobExecutor.registJobHandler():211|>>>>>>>>>>> xxl-job register jobhandler success, name:simpleTest, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@7be34063[class com.wep.core.xxl.SimpleTestJobHandler#execute]

希望能注册完成！

### Actual behavior
2020-06-11 09:51:26.106|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobConfig.xxlJobExecutor():37|====xxl-job config init====
2020-06-11 09:51:26.135|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobExecutor.registJobHandler():211|>>>>>>>>>>> xxl-job register jobhandler success, name:simpleTest, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@7be34063[class com.wep.core.xxl.SimpleTestJobHandler#execute]
2020-06-11 09:51:26.223|INFO|RMI TCP Connection(3)-127.0.0.1||PropertySourcedRequestMappingHandlerMapping.initHandlerMethods():69|Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
2020-06-11 09:51:26.341|INFO|RMI TCP Connection(3)-127.0.0.1||ThreadPoolTaskExecutor.initialize():165|Initializing ExecutorService  'threadPoolTaskExecutor'
2020-06-11 09:51:26.896|INFO|RMI TCP Connection(3)-127.0.0.1||RequestMappingHandlerAdapter.initControllerAdviceCache():534|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@cfa9aa: startup date [Thu Jun 11 09:51:10 GMT+08:00 2020]; root of context hierarchy
2020-06-11 09:51:26.981|INFO|RMI TCP Connection(3)-127.0.0.1||SimpleUrlHandlerMapping.registerHandler():362|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2020-06-11 09:51:26.982|INFO|RMI TCP Connection(3)-127.0.0.1||SimpleUrlHandlerMapping.registerHandler():362|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2020-06-11 09:51:27.053|INFO|RMI TCP Connection(3)-127.0.0.1||SimpleUrlHandlerMapping.registerHandler():362|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2020-06-11 09:51:27.798|INFO|RMI TCP Connection(3)-127.0.0.1||AuthenticationManagerConfiguration.configure():173|

Using default security password: 6bd1b644-60e4-4104-8f9e-da24283f3f76

2020-06-11 09:51:27.878|INFO|RMI TCP Connection(3)-127.0.0.1||DefaultSecurityFilterChain.<init>():43|Creating filter chain: OrRequestMatcher [requestMatchers=[Ant [pattern='/css/**'], Ant [pattern='/js/**'], Ant [pattern='/images/**'], Ant [pattern='/webjars/**'], Ant [pattern='/**/favicon.ico'], Ant [pattern='/error']]], []
2020-06-11 09:51:28.014|INFO|RMI TCP Connection(3)-127.0.0.1||DefaultSecurityFilterChain.<init>():43|Creating filter chain: org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration$ApplicationNoWebSecurityConfigurerAdapter$1@2fad1bdd, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@4b3e012b, org.springframework.security.web.context.SecurityContextPersistenceFilter@49fd9f79, org.springframework.security.web.header.HeaderWriterFilter@33d2f8e1, org.springframework.security.web.csrf.CsrfFilter@11ffb335, org.springframework.security.web.authentication.logout.LogoutFilter@7154d82b, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@677cbddc, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@78b1f1c1, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5ec52818, org.springframework.security.web.session.SessionManagementFilter@153b8cb8, org.springframework.security.web.access.ExceptionTranslationFilter@5dd71e35]
2020-06-11 09:51:28.041|WARN|RMI TCP Connection(3)-127.0.0.1||AnnotationConfigEmbeddedWebApplicationContext.refresh():551|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobExecutor' defined in class path resource [com/wep/core/config/XxlJobConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
2020-06-11 09:51:28.042|INFO|RMI TCP Connection(3)-127.0.0.1||AnnotationMBeanExporter.destroy():449|Unregistering JMX-exposed beans on shutdown
2020-06-11 09:51:28.043|INFO|RMI TCP Connection(3)-127.0.0.1||ThreadPoolTaskExecutor.shutdown():202|Shutting down ExecutorService 'threadPoolTaskExecutor'
2020-06-11 09:51:28.047|DEBUG|RMI TCP Connection(3)-127.0.0.1||SpringContextHolder.clearHolder():63|清除SpringContextHolder中的ApplicationContext:org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@cfa9aa: startup date [Thu Jun 11 09:51:10 GMT+08:00 2020]; root of context hierarchy
2020-06-11 09:51:28.049|INFO|RMI TCP Connection(3)-127.0.0.1||SchedulerFactoryBean.destroy():765|Shutting down Quartz Scheduler
2020-06-11 09:51:28.050|INFO|RMI TCP Connection(3)-127.0.0.1||QuartzScheduler.shutdown():666|Scheduler schedulerFactoryBean_$_LAPTOP-OQ3HDHAD1591840281741 shutting down.
2020-06-11 09:51:28.050|INFO|RMI TCP Connection(3)-127.0.0.1||QuartzScheduler.standby():585|Scheduler schedulerFactoryBean_$_LAPTOP-OQ3HDHAD1591840281741 paused.
2020-06-11 09:51:28.051|INFO|RMI TCP Connection(3)-127.0.0.1||QuartzScheduler.shutdown():740|Scheduler schedulerFactoryBean_$_LAPTOP-OQ3HDHAD1591840281741 shutdown complete.
2020-06-11 09:51:28.052|INFO|RMI TCP Connection(3)-127.0.0.1||DruidDataSource.close():1965|{dataSource-1} closing ...
2020-06-11 09:51:28.056|INFO|RMI TCP Connection(3)-127.0.0.1||DruidDataSource.close():2037|{dataSource-1} closed
2020-06-11 09:51:28.066|INFO|RMI TCP Connection(3)-127.0.0.1||AutoConfigurationReportLoggingInitializer.logAutoConfigurationReport():101|

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2020-06-11 09:51:28.079|ERROR|RMI TCP Connection(3)-127.0.0.1||SpringApplication.reportFailure():771|Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobExecutor' defined in class path resource [com/wep/core/config/XxlJobConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:154)
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:134)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5536)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1774)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:618)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:835)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.initJobHandlerMethodRepository(XxlJobSpringExecutor.java:83)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterPropertiesSet(XxlJobSpringExecutor.java:36)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 61 common frames omitted
### Other information
1. 看样子是name是null，这个是XxlJobSpringExecutor的83行代码！
![image](https://user-images.githubusercontent.com/66771354/84358665-0f97c600-abfa-11ea-98b4-f5e5c75503bc.png)

2. 定义XxlJob的类！
![image](https://user-images.githubusercontent.com/66771354/84358801-4241be80-abfa-11ea-9bec-aeb26d0fe44c.png)

应该是bug

**Comment by huangm59** [comment]
more information：
这个模块集成了Quartz ，想平滑的切换到xxl-job，所以同时存在

**Comment by huangm59** [comment]
more info ：XxlJob注解函数指定value="simpleTest"，问题依旧！

![image](https://user-images.githubusercontent.com/66771354/84366368-4cb58580-ac05-11ea-8767-a19cfc7d8943.png)

**Comment by robin536180** [comment]
同问，请问问题解决了吗？

**Comment by robin536180** [comment]
> Please answer some questions before submitting your issue. Thanks!
> 
> ### Which version of XXL-JOB do you using?
> 2.1.2
> 
> ### Expected behavior
> 2020-06-11 09:51:26.106|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobConfig.xxlJobExecutor():37|====xxl-job config init====
> 2020-06-11 09:51:26.135|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobExecutor.registJobHandler():211|>>>>>>>>>>> xxl-job register jobhandler success, name:simpleTest, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@7be34063[class com.wep.core.xxl.SimpleTestJobHandler#execute]
> 
> 希望能注册完成！
> 
> ### Actual behavior
> 2020-06-11 09:51:26.106|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobConfig.xxlJobExecutor():37|====xxl-job config init====
> 2020-06-11 09:51:26.135|INFO|RMI TCP Connection(3)-127.0.0.1||XxlJobExecutor.registJobHandler():211|>>>>>>>>>>> xxl-job register jobhandler success, name:simpleTest, jobHandler:com.xxl.job.core.handler.impl.MethodJobHandler@7be34063[class com.wep.core.xxl.SimpleTestJobHandler#execute]
> 2020-06-11 09:51:26.223|INFO|RMI TCP Connection(3)-127.0.0.1||PropertySourcedRequestMappingHandlerMapping.initHandlerMethods():69|Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
> 2020-06-11 09:51:26.341|INFO|RMI TCP Connection(3)-127.0.0.1||ThreadPoolTaskExecutor.initialize():165|Initializing ExecutorService 'threadPoolTaskExecutor'
> 2020-06-11 09:51:26.896|INFO|RMI TCP Connection(3)-127.0.0.1||RequestMappingHandlerAdapter.initControllerAdviceCache():534|Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@cfa9aa: startup date [Thu Jun 11 09:51:10 GMT+08:00 2020]; root of context hierarchy
> 2020-06-11 09:51:26.981|INFO|RMI TCP Connection(3)-127.0.0.1||SimpleUrlHandlerMapping.registerHandler():362|Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler] 2020-06-11 09:51:26.982|INFO|RMI TCP Connection(3)-127.0.0.1||SimpleUrlHandlerMapping.registerHandler():362|Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2020-06-11 09:51:27.053|INFO|RMI TCP Connection(3)-127.0.0.1||SimpleUrlHandlerMapping.registerHandler():362|Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
> 2020-06-11 09:51:27.798|INFO|RMI TCP Connection(3)-127.0.0.1||AuthenticationManagerConfiguration.configure():173|
> 
> Using default security password: 6bd1b644-60e4-4104-8f9e-da24283f3f76
> 
> 2020-06-11 09:51:27.878|INFO|RMI TCP Connection(3)-127.0.0.1||DefaultSecurityFilterChain.():43|Creating filter chain: OrRequestMatcher [requestMatchers=[Ant [pattern='/css/**'], Ant [pattern='/js/**'], Ant [pattern='/images/**'], Ant [pattern='/webjars/**'], Ant [pattern='/**/favicon.ico'], Ant [pattern='/error']]], []
> 2020-06-11 09:51:28.014|INFO|RMI TCP Connection(3)-127.0.0.1||DefaultSecurityFilterChain.():43|Creating filter chain: org.springframework.boot.autoconfigure.security.SpringBootWebSecurityConfiguration$ApplicationNoWebSecurityConfigurerAdapter$1@2fad1bdd, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@4b3e012b, org.springframework.security.web.context.SecurityContextPersistenceFilter@49fd9f79, org.springframework.security.web.header.HeaderWriterFilter@33d2f8e1, org.springframework.security.web.csrf.CsrfFilter@11ffb335, org.springframework.security.web.authentication.logout.LogoutFilter@7154d82b, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@677cbddc, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@78b1f1c1, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5ec52818, org.springframework.security.web.session.SessionManagementFilter@153b8cb8, org.springframework.security.web.access.ExceptionTranslationFilter@5dd71e35]
> 2020-06-11 09:51:28.041|WARN|RMI TCP Connection(3)-127.0.0.1||AnnotationConfigEmbeddedWebApplicationContext.refresh():551|Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobExecutor' defined in class path resource [com/wep/core/config/XxlJobConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
> 2020-06-11 09:51:28.042|INFO|RMI TCP Connection(3)-127.0.0.1||AnnotationMBeanExporter.destroy():449|Unregistering JMX-exposed beans on shutdown
> 2020-06-11 09:51:28.043|INFO|RMI TCP Connection(3)-127.0.0.1||ThreadPoolTaskExecutor.shutdown():202|Shutting down ExecutorService 'threadPoolTaskExecutor'
> 2020-06-11 09:51:28.047|DEBUG|RMI TCP Connection(3)-127.0.0.1||SpringContextHolder.clearHolder():63|清除SpringContextHolder中的ApplicationContext:org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@cfa9aa: startup date [Thu Jun 11 09:51:10 GMT+08:00 2020]; root of context hierarchy
> 2020-06-11 09:51:28.049|INFO|RMI TCP Connection(3)-127.0.0.1||SchedulerFactoryBean.destroy():765|Shutting down Quartz Scheduler
> 2020-06-11 09:51:28.050|INFO|RMI TCP Connection(3)-127.0.0.1||QuartzScheduler.shutdown():666|Scheduler schedulerFactoryBean_$_LAPTOP-OQ3HDHAD1591840281741 shutting down. 2020-06-11 09:51:28.050|INFO|RMI TCP Connection(3)-127.0.0.1||QuartzScheduler.standby():585|Scheduler schedulerFactoryBean_$_LAPTOP-OQ3HDHAD1591840281741 paused. 2020-06-11 09:51:28.051|INFO|RMI TCP Connection(3)-127.0.0.1||QuartzScheduler.shutdown():740|Scheduler schedulerFactoryBean_$_LAPTOP-OQ3HDHAD1591840281741 shutdown complete.
> 2020-06-11 09:51:28.052|INFO|RMI TCP Connection(3)-127.0.0.1||DruidDataSource.close():1965|{dataSource-1} closing ...
> 2020-06-11 09:51:28.056|INFO|RMI TCP Connection(3)-127.0.0.1||DruidDataSource.close():2037|{dataSource-1} closed
> 2020-06-11 09:51:28.066|INFO|RMI TCP Connection(3)-127.0.0.1||AutoConfigurationReportLoggingInitializer.logAutoConfigurationReport():101|
> 
> Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
> 2020-06-11 09:51:28.079|ERROR|RMI TCP Connection(3)-127.0.0.1||SpringApplication.reportFailure():771|Application startup failed
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobExecutor' defined in class path resource [com/wep/core/config/XxlJobConfig.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
> at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
> at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
> at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
> at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
> at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
> at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
> at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
> at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
> at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
> at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:154)
> at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:134)
> at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87)
> at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
> at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5536)
> at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
> at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
> at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
> at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
> at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1774)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
> at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
> at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
> at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:618)
> at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:565)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
> at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
> at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
> at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
> at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
> at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
> at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
> at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
> at sun.rmi.transport.Transport$1.run(Transport.java:200)
> at sun.rmi.transport.Transport$1.run(Transport.java:197)
> at java.security.AccessController.doPrivileged(Native Method)
> at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
> at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
> at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:835)
> at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
> at java.security.AccessController.doPrivileged(Native Method)
> at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException: null
> at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.initJobHandlerMethodRepository(XxlJobSpringExecutor.java:83)
> at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterPropertiesSet(XxlJobSpringExecutor.java:36)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
> at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
> ... 61 common frames omitted
> 
> ### Steps to reproduce the behavior
> ### Other information
> 1. 看样子是name是null，这个是XxlJobSpringExecutor的83行代码！
>    ![image](https://user-images.githubusercontent.com/66771354/84358665-0f97c600-abfa-11ea-98b4-f5e5c75503bc.png)
> 2. 定义XxlJob的类！
>    ![image](https://user-images.githubusercontent.com/66771354/84358801-4241be80-abfa-11ea-9bec-aeb26d0fe44c.png)
> 
> 应该是bug

同问，请问问题解决了吗？

**Comment by xuxueli** [comment]
新版本移除了quartz，sql等也有变更。建议部署新版，用数据迁移方式升级
