### ISSUE TITLE
k8s 间接性报错

### ISSUE THREAD

**Issue by An0nymous0** [xuxueli/xxl-job#1768]
xxl-job version  2.1.2

都在k8s环境里 异常里的容器ip我有测试过是通的。

error log:
```shell
11:33:00.126 logback [nioEventLoopGroup-19-1] ERROR c.x.r.r.n.i.n.c.NettyHttpClientHandler - >>>>>>>>>>> xxl-rpc netty_http client caught exception
com.xxl.rpc.util.XxlRpcException: xxl-rpc response status invalid.
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:40)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
11:33:03.005 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-782037285] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:10.1.0.171:9999, XxlRpcRequestXxlRpcRequest{requestId='dfa98b1f-b6a0-4c11-81c4-7532bb2884c6', createMillisTime=1592278380004, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=1, executorHandler='robotBreedConsumerJobHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=847037, logDateTime=1592278380002, glueType='BEAN', glueSource='', glueUpdatetime=1541254891000, broadcastIndex=0, broadcastTotal=1}], version='null'}
11:33:03.005 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-10214029] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:10.1.0.171:9999, XxlRpcRequestXxlRpcRequest{requestId='927c302c-1dd8-4fb0-b03a-bc7c9dde07f8', createMillisTime=1592278380005, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=3, executorHandler='ConversationDispatchHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=847038, logDateTime=1592278380003, glueType='BEAN', glueSource='', glueUpdatetime=1573699776000, broadcastIndex=0, broadcastTotal=1}], version='null'}
11:33:03.006 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-782037285] ERROR c.x.j.a.core.trigger.XxlJobTrigger - >>>>>>>>>>> xxl-job trigger error, please check if the executor[10.1.0.171:9999] is running.
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1592278383005, request:XxlRpcRequest{requestId='dfa98b1f-b6a0-4c11-81c4-7532bb2884c6', createMillisTime=1592278380004, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=1, executorHandler='robotBreedConsumerJobHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=847037, logDateTime=1592278380002, glueType='BEAN', glueSource='', glueUpdatetime=1541254891000, broadcastIndex=0, broadcastTotal=1}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242)
	at com.sun.proxy.$Proxy90.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
11:33:03.006 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-10214029] ERROR c.x.j.a.core.trigger.XxlJobTrigger - >>>>>>>>>>> xxl-job trigger error, please check if the executor[10.1.0.171:9999] is running.
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1592278383005, request:XxlRpcRequest{requestId='927c302c-1dd8-4fb0-b03a-bc7c9dde07f8', createMillisTime=1592278380005, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=3, executorHandler='ConversationDispatchHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=847038, logDateTime=1592278380003, glueType='BEAN', glueSource='', glueUpdatetime=1573699776000, broadcastIndex=0, broadcastTotal=1}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242)
	at com.sun.proxy.$Proxy90.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
```

![image](https://user-images.githubusercontent.com/6836030/84731702-45f38d80-afcc-11ea-9441-de60b9ed26ec.png)

**Comment by qhysjpw** [comment]
![image](https://user-images.githubusercontent.com/20807886/86891766-f4a16e80-c131-11ea-8c6a-7c1d0c8e918b.png)
同样是在容器里面，2w次调用 出现16次失败，而且都是在某个时间点，很奇怪

**Comment by qhysjpw** [comment]
我们经过一晚上的监测 节点与节点之间ping ，发现是aws网络不稳定

**Comment by WeiYe-Jing** [comment]
这个问题反馈比较多，能不能监控下这个点的数据库负载情况呢，从最后一张图看确实是网络延迟问题。

**Comment by huangm59** [comment]
问一下，你k8s容器的ip是否发生过变化？变化后有没有调度问题？（即没有被执行的？）

**Comment by liuxihua-liu** [comment]
2.1.2版本同样K8S上一直报错，任务多的时候，错误日志非常多

**Comment by no-f** [comment]
> 2.1.2版本同样K8S上一直报错，任务多的时候，错误日志非常多

把错误贴出来看看，我们跑了快2年了在k8s上，还挺稳定的，检查下pod 之间网络延迟

**Comment by liuxihua-liu** [comment]
> > 2.1.2版本同样K8S上一直报错，任务多的时候，错误日志非常多
> 
> 把错误贴出来看看，我们跑了快2年了在k8s上，还挺稳定的，检查下pod 之间网络延迟

已经简单排查到和执行器配置为域名有关系啦，但是具体的还要详细看下通信过程。
错误日志：和楼主一样的
应用编号：SYS00001
监控ID：1561626488414015488
监控名称：xxljob正式环境服务日志监控-1
监控类型：LOG-XXLJOB
告警时间：2022-10-18 11:31:46
监控主机：
日志文件：/data/applogs/xxl-job/xxl-job-admin.log
日志消息：
2022-10-18 11:31:30,823 ERROR [nioEventLoopGroup-634-1] c.x.r.r.n.i.n.c.NettyHttpClientHandler [NettyHttpClientHandler.java : 62] &gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; xxl-rpc netty_http client caught exception
com.xxl.rpc.util.XxlRpcException: xxl-rpc response status invalid.
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:40)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
... ...
执行器配置示例：sysXXX-cloud.compoXXX.com/xxljob

**Comment by xuxueli** [comment]
新版本已优化处理，建议升级
