### ISSUE TITLE
服务器上运行项目报NullPointException

### ISSUE THREAD

**Issue by zhangyangx** [xuxueli/xxl-job#1777]
java.lang.NullPointerException: null
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117) ~[xxl-job-core-2.2.1-SNAPSHOT.jar!/:na]
	at com.xxl.job.core.server.EmbedServer.stopRegistry(EmbedServer.java:262) ~[xxl-job-core-2.2.1-SNAPSHOT.jar!/:na]
	at com.xxl.job.core.server.EmbedServer.stop(EmbedServer.java:124) ~[xxl-job-core-2.2.1-SNAPSHOT.jar!/:na]
	at com.xxl.job.core.executor.XxlJobExecutor.stopEmbedServer(XxlJobExecutor.java:158) [xxl-job-core-2.2.1-SNAPSHOT.jar!/:na]
	at com.xxl.job.core.executor.XxlJobExecutor.destroy(XxlJobExecutor.java:85) [xxl-job-core-2.2.1-SNAPSHOT.jar!/:na]
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.destroy(XxlJobSpringExecutor.java:55) [xxl-job-core-2.2.1-SNAPSHOT.jar!/:na]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258) [spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579) [spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551) [spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1089) [spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512) [spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1082) [spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061) [spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) [spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) [spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]

**Comment by zhangyangx** [comment]
有人遇到过这个问题吗

**Comment by xuxueli** [comment]
你好，日志不全应该有如下日志信息没有贴出来，可以搜索下。
应该是执行器配置缺失，导致执行器无法正常实例化导致。

xxl-job, executor registry config fail ……

**Comment by wolfmanwoking** [comment]
请查看1799。

**Comment by patience00** [comment]
遇到了,@xuxueli,请问这个是什么原因造成的

**Comment by ChunMengLu** [comment]
同样的这个问题，spring boot 项目，停止的时候出现这个异常。
