### ISSUE TITLE
执行器能注册到调度中心，但调度中心不能调度执行器。

### ISSUE THREAD

**Issue by LiuKaiLuke** [xuxueli/xxl-job#1793]
调度中心和执行器分别部署在不同的网络区域。

调度中心访问不了执行器的ip+port。

但是执行器提供了可访问的域名。

请问，执行器可以用域名形式注册调度中心吗？

**Comment by IAMTJW** [comment]
执行器可以手动注册的，你可以手动设置域名试试

**Comment by LiuKaiLuke** [comment]
> 执行器可以手动注册的，你可以手动设置域名试试

试过这样了，还是报错，是admin和执行器不通吗？
触发调度：
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1594086254255, request:XxlRpcRequest{requestId='1b4983a8-9680-465c-8fd5-99be116c5c1c', createMillisTime=1594086251128, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=18, executorHandler='ProcessBizDataHandler', executorParams='SC0001', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=3934, logDateTime=1594086251126, glueType='BEAN', glueSource='', glueUpdatetime=1592727657000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy106.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by fjc440** [comment]
同样的问题，版本是2.1.2 请问解决了吗？

**Comment by WeiYe-Jing** [comment]
> > 执行器可以手动注册的，你可以手动设置域名试试
> 
> 试过这样了，还是报错，是admin和执行器不通吗？
> 触发调度：
> code：500
> msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1594086254255, request:XxlRpcRequest{requestId='1b4983a8-9680-465c-8fd5-99be116c5c1c', createMillisTime=1594086251128, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=18, executorHandler='ProcessBizDataHandler', executorParams='SC0001', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=3934, logDateTime=1594086251126, glueType='BEAN', glueSource='', glueUpdatetime=1592727657000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy106.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

这个问题是偶发性还是每次调度都会遇到，执行器节点的日志检查了吗？

**Comment by linyongfu2013** [comment]
执行器应用是不是加了context-path，去掉就行了。

**Comment by xuxueli** [comment]
> 执行器应用是不是加了context-path，去掉就行了。

+1，另外可检查下网络是否通畅
