### ISSUE TITLE
springcloud微服务集成xxl-job2.2.0，执行器注册成功，调度时异常报错

### ISSUE THREAD

**Issue by cgy0214** [xuxueli/xxl-job#1796]
版本：
com.xuxueli
xxl-job-core
2.2.0
 springcloud 注册器成功 调度失败报错
 demo spring boot 中调度成功

### error
java.lang.NoSuchMethodError: io.netty.handler.codec.http.FullHttpRequest.uri()Ljava/lang/String;
at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:156)
at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:138)

**Comment by steveNash12** [comment]
应该是jar 版本的问题引起的。

**Comment by wolfmanwoking** [comment]
请查阅 Issues 1799。

**Comment by resuper** [comment]
我的情况是这样的，xxl-job2.2.0 netty-all版本是 4.1.48.Final，自己项目中引入了zookeeper依赖，它依赖的netty-all版本是4.0.36.Final，把自己项目中的netty-all版本改成xxl-job-admin的版本就好使了

xxl-job2.2.0
```xml
		<netty-all.version>4.1.48.Final</netty-all.version>
```
自己的项目中引入了zookeeper的依赖
```xml
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
        </dependency>
```
其依赖的netty-all版本是4.0.36.Final

解决: 将自己项目中netty版本和xxl-job-admin中的netty版本统一
```xml
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.48.Final</version>
        </dependency>
```

**Comment by resuper** [comment]
我的情况是这样的，xxl-job2.2.0 netty-all版本是 4.1.48.Final，自己项目中引入了zookeeper依赖，它依赖的netty-all版本是4.0.36.Final，把自己项目中的netty-all版本改成xxl-job-admin的版本就好使了

xxl-job2.2.0
```xml
		<netty-all.version>4.1.48.Final</netty-all.version>
```
自己的项目中引入了zookeeper的依赖（版本3.5.5）
```xml
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
        </dependency>
```
其依赖的netty-all版本是4.0.36.Final

解决: 将自己项目中netty版本和xxl-job-admin中的netty版本统一
```xml
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.48.Final</version>
        </dependency>
```
