### ISSUE TITLE
nodejs无法使用第三方模块

### ISSUE THREAD

**Issue by ldwnt** [xuxueli/xxl-job#1801]
#!/usr/bin/env node
var LineReaderSync = require("/mnt/logs/jobhandler/gluesource/node_modules/line-reader-sync/index")
let lrs = new LineReaderSync("a")
 while(true){
    var line = lrs.readline()
    if(line === null){
      break
    }
    console.log(line)
}
process.exit(0)

internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module '/mnt/logs/jobhandler/gluesource/node_modules/line-reader-sync/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object. (/mnt/logs/jobhandler/tsync/gluesource/85_1594004446000.js:11:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
2020-07-06 11:00:50 [com.xxl.job.core.thread.JobThread#run]-[158]-[Thread-32] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=500, msg=script exit value(1) is failed, content=null]
2020-07-06 11:00:50 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[176]-[Thread-6] 
----------- xxl-job job callback finish.

**Comment by zhaozhenzzz** [comment]
同样求此功能
