### ISSUE TITLE
执行一个耗时任务,没有配置超时时间,但是报错java.lang.NullPointerException: null 	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)

### ISSUE THREAD

**Issue by patience00** [xuxueli/xxl-job#1811]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2
### Expected behavior
不超时,则该任务正常执行完
### Actual behavior
任务未执行完成
### Steps to reproduce the behavior
执行一个耗时比较久的任务
### Other information

**Comment by patience00** [comment]
ERROR [2020-07-08 14:28:22] [Thread-9] com.xxl.rpc.remoting.net.Server#onStoped - >>>>>>>>>>> xxl-rpc, server stopedCallback error.
java.lang.NullPointerException: null
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)
	at com.xxl.job.core.executor.XxlJobExecutor$ExecutorServiceRegistry.stop(XxlJobExecutor.java:176)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory$2.run(XxlRpcProviderFactory.java:147)
	at com.xxl.rpc.remoting.net.Server.onStoped(Server.java:63)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServer.stop(NettyHttpServer.java:109)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.stop(XxlRpcProviderFactory.java:157)
	at com.xxl.job.core.executor.XxlJobExecutor.stopRpcProvider(XxlJobExecutor.java:201)
	at com.xxl.job.core.executor.XxlJobExecutor.destroy(XxlJobExecutor.java:88)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.destroy(XxlJobSpringExecutor.java:48)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1040)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945)
