### ISSUE TITLE
Cron表达式设置无效

### ISSUE THREAD

**Issue by mallocxw** [xuxueli/xxl-job#1812]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
 <xxl-job.version>2.2.0</xxl-job.version>
xxl-job-admin 2.2.1   

### Expected behavior
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_121]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_121]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_121]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_121]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_121]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_121]
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115) ~[xxl-job-core-2.2.0.jar:na]
	at com.xxl.job.core.biz.client.AdminBizClient.callback(AdminBizClient.java:37) [xxl-job-core-2.2.0.jar:na]
	at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:167) [xxl-job-core-2.2.0.jar:na]
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:242) [xxl-job-core-2.2.0.jar:na]
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:25) [xxl-job-core-2.2.0.jar:na]
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:112) [xxl-job-core-2.2.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

### Actual behavior
配置执行Cron表达式无效，总是每秒执行一次
![image](https://user-images.githubusercontent.com/17708056/86893444-3501ec00-c134-11ea-8948-0595dea83814.png)
![image](https://user-images.githubusercontent.com/17708056/86893513-5236ba80-c134-11ea-99b4-4cc63a967550.png)

### Other information

**Comment by laisengui** [comment]
你这秒的位置是* 可不就是每秒执行一次吗 想要每分钟执行 秒的位置不能是*

**Comment by HFFP** [comment]
0 0/1 * * * ？*

**Comment by YangAnLin** [comment]
> 你这秒的位置是* 可不就是每秒执行一次吗 想要每分钟执行 秒的位置不能是*

明白你的意思,我也遇到相同的问题,这是图片中的表达式是生成的,体验不太好

**Comment by tiaoxixiaoji** [comment]
不要用自带的cron表达式生成器。被坑了一回

**Comment by changingshow** [comment]
自带得cron表达式有点问题。

**Comment by mallocxw** [comment]
确实感觉自带的cron表达式有问题，但是我在网页上面去生成的cron表达式也有问题。

**Comment by 290315636** [comment]
Read timed out 这个超时没人在意么？？
