### ISSUE TITLE
xxl-rpc结果解析失败

### ISSUE THREAD

**Issue by HaiyangLiang** [xuxueli/xxl-job#1814]
Please answer some questions before submitting your issue. Thanks!

### 使用版本 2.2.0
###问题： xxl-rpc json解析失败
2.2.0版本xxl-rpc调用api/registry结果返回json为
`{
	"code": 200,
	"msg": "",
	"content": {}
}`
结果显示xxl-rpc json解析失败。
完整信息是：
`2020-07-09 17:25:01.905 ERROR 21564 --- [rRegistryThread] c.xxl.job.core.util.XxlJobRemotingUtil   : xxl-rpc remoting (url=http://localhost:8400/xxl-job-admin/api/registry) response content invalid({"code":200,"msg":"","content":{}}).

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 33 path $.content
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.xxl.job.core.util.GsonTool.fromJson(GsonTool.java:53)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:131)
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 33 path $.content
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 8 common frames omitted
`
### 可能原因
由于AdminBizClient的registry方法结果json结果参数解析为String.class，导致content为空json解析为String失败
`    @Override
    public ReturnT<String> registry(RegistryParam registryParam) {
        return XxlJobRemotingUtil.postBody(addressUrl + "api/registry", accessToken, timeout, registryParam, String.class);
    }
`
请问这个问题怎么解决 @xuxueli？

**Comment by aileennian** [comment]
同问。

**Comment by cygmris** [comment]
https://github.com/xuxueli/xxl-job/issues/2141#issuecomment-763652374_

**Comment by V-I-C-T-O-R** [comment]
@HaiyangLiang @aileennian 2.2.0版本的代码没问题，查看是否有修改代码访问api/registry被前端拦截重定向了

**Comment by dishpzga** [comment]
同问

**Comment by Tiangel** [comment]
我在2.3.0遇到了同样的问题。。。@xuxueli

**Comment by Tiangel** [comment]
我通过将ReturnT 里的 public static final ReturnT<String> SUCCESS = new ReturnT<String>(null);
改为 public static final ReturnT<String> SUCCESS = new ReturnT<String>(""); 临时解决了

**Comment by xuxueli** [comment]
建议升级最新版
