### ISSUE TITLE
xxl-job执行器不能执行bash问题‘’

### ISSUE THREAD

**Issue by chenhuandong8010** [xuxueli/xxl-job#1830]
1. 执行器dockerfile:
FROM openjdk:8-jdk-alpine
MAINTAINER dannyhdchen

ENV PARAMS=""

ENV TZ=PRC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD module.service.scheduler.xxljobhandler-*.jar /app.jar

ENTRYPOINT ["sh","-c","java -jar $JAVA_OPTS /app.jar $PARAMS"]

2. 执行日志报错（GLue(Shell)原始脚本）
2020-07-17 13:04:22 [com.tencent.idc.xxljob.core.thread.JobThread#run]-[130]-[Thread-13] 
----------- xxl-job job execute start -----------
----------- Param:
2020-07-17 13:04:22 [com.tencent.idc.xxljob.core.handler.impl.ScriptJobHandler#execute]-[80]-[Thread-13] ----------- script file:/data/applogs/xxl-job/jobhandler/gluesource/5_1594962257000.sh -----------
2020-07-17 13:04:22 [com.tencent.idc.xxljob.core.util.ScriptUtil#execToFile]-[112]-[Thread-13] java.io.IOException: Cannot run program "bash": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at com.tencent.idc.xxljob.core.util.ScriptUtil.execToFile(ScriptUtil.java:76)
	at com.tencent.idc.xxljob.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:81)
	at com.tencent.idc.xxljob.core.thread.JobThread.run(JobThread.java:158)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more

2020-07-17 13:04:22 [com.tencent.idc.xxljob.core.thread.JobThread#run]-[170]-[Thread-13] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=500, msg=script exit value(-1) is failed, content=null]
2020-07-17 13:04:22 [com.tencent.idc.xxljob.core.thread.TriggerCallbackThread#callbackLog]-[201]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

[Load Log Finish]

**Comment by fsjwin** [comment]
请问您解决了吗？我也遇到这个问题，但是这个文件是存在的！

**Comment by chengruizi1** [comment]
Windows下同样的问题，求解。

**Comment by xuxueli** [comment]
> 转用power shell可以

+1
