### ISSUE TITLE
报错 打开的文件过多

### ISSUE THREAD

**Issue by yhan219** [xuxueli/xxl-job#1835]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0

### Expected behavior
能正常执行任务

### Actual behavior
执行任务报错

### Steps to reproduce the behavior
正常使用一段时间后就会

### Other information
报错日志
```
2020-07-18 11:06:51.661 [xxl-job, executor TriggerCallbackThread] ERROR com.xxl.job.core.util.FileUtil - /home/devops/soft/xxl-job-v2.2.0/jobhandler/callbacklog/xxl-job-callback-1595041611661.log (打开的文件过多)
java.io.FileNotFoundException: /home/devops/soft/xxl-job-v2.2.0/jobhandler/callbacklog/xxl-job-callback-1595041611661.log (打开的文件过多)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at com.xxl.job.core.util.FileUtil.writeFileContent(FileUtil.java:61)
	at com.xxl.job.core.thread.TriggerCallbackThread.appendFailCallbackFile(TriggerCallbackThread.java:219)
	at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:180)
	at com.xxl.job.core.thread.TriggerCallbackThread.access$200(TriggerCallbackThread.java:25)
	at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:75)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by yhan219** [comment]
自己代码问题
