### ISSUE TITLE
执行器一直报xxl-rpc netty_http client caught exception，不影响任务调度

### ISSUE THREAD

**Issue by muxinzi** [xuxueli/xxl-job#1840]
异常信息见：
ERROR NettyHttpClientHandler:62 - >>>>>>>>>>> xxl-rpc netty_http client caught exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_91]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_91]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_91]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_91]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_91]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.43.Final.jar!/:4.1.43.Final]
	at java.lang.Thread.ru

**Comment by muxinzi** [comment]
执行器一直报上述错误，但是不影响调度。错误日志打印太多，影响查看其他异常信息。

**Comment by muxinzi** [comment]
rpc的包引用的是1.4.2版本

**Comment by wushengju** [comment]
K8s 环境同样的问题 还未解决

**Comment by xuxueli** [comment]
你好，该问题已经修复，升级即可处理。

**Comment by cloudyunfan** [comment]
> 你好，该问题已经修复，升级即可处理。

你好，用的最新版本还是有问题
EmbedServer$EmbedHttpServerHandler : >>>>>>>>>>> xxl-job provider netty_http server caught exception
2021-06-09 21:16:47 
2021-06-09 21:16:47 java.io.IOException: Connection reset by peer
2021-06-09 21:16:47  at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378) ~[?:1.8.0_281]
2021-06-09 21:16:47  at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134) ~[netty-buffer-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]

**Comment by gezhiwei8899** [comment]
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/16362526/180148390-4aa92afe-a4fd-49c8-bc3b-a5a6e006ad95.png">
抓了3天包，终于看到了。确实是服务端发送RST给执行器端。 @xuxueli

**Comment by songlongkuan** [comment]
2024年了，问题依旧存在  ,版本2.4.0
xxl-job provider netty_http server caught exception
java.io.IOException: Connection reset by peer
