### ISSUE TITLE
执行器的ip是否可以是外网ip

### ISSUE THREAD

**Issue by yhb890430** [xuxueli/xxl-job#186]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9

我这边调度中心和执行器均采用同一外网ip，但是在执行器注册时提示注册失败，是执行器必须要采用内网ip吗？

**Comment by xuxueli** [comment]
你好，感谢关注啊！
执行器注册失败，通常有以下几个原因，可以检查下啊：
1、执行器ping不通调度中心；
2、执行器配置的调度中心地址错误。

**Comment by yhb890430** [comment]
因为用的是阿里云服务器，默认禁Ping的
我执行器的端口80，调度中心端口是38082，都在同一台服务器上；
这是我采用外网注册时的异常：
2017-11-09 14:06:13 [Thread-12] WARN  org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED ServerConnector@7c74a107{HTTP/1.1}{106.14.213.62:80}: java.net.BindException: Cannot assign requested address
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_151]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_151]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366) [jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at com.xxl.job.core.rpc.netcom.jetty.server.JettyServer$1.run(JettyServer.java:46) [xxl-job-core-1.9.0-SNAPSHOT.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-11-09 14:06:13 [Thread-12] WARN  org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@a2127cd: java.net.BindException: Cannot assign requested address
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_151]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_151]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) [jetty-util-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at com.xxl.job.core.rpc.netcom.jetty.server.JettyServer$1.run(JettyServer.java:46) [xxl-job-core-1.9.0-SNAPSHOT.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-11-09 14:06:13 [Thread-12] ERROR com.xxl.job.core.rpc.netcom.jetty.server.JettyServer - Cannot assign requested address
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_151]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_151]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_151]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_151]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366) ~[jetty-server-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[jetty-util-9.2.20.v20161216.jar!/:9.2.20.v20161216]
	at com.xxl.job.core.rpc.netcom.jetty.server.JettyServer$1.run(JettyServer.java:46) [xxl-job-core-1.9.0-SNAPSHOT.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by yhb890430** [comment]
改成127.0.0.1就能注册了

**Comment by xuxueli** [comment]
你好，感谢关注！
在指定IP的情况下，Jetty启动时会根据配置绑定IP地址，如果地址不存在时会触发上述异常，导致无法正常启动，可以确认下上述IP地址啊。
