### ISSUE TITLE
频繁出现执行器unexpected end of file频繁报错

### ISSUE THREAD

**Issue by lvjunjie-byte** [xuxueli/xxl-job#1870]
内容如下
类名	com.xxl.job.core.thread.TriggerCallbackThread
方法名	Thread-10
内容
java.io.EOFException: readObject: unexpected end of file
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file
at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238)
at com.xxl.job.core.thread.TriggerCallbackThread.access400(TriggerCallbackThread.java:24)atcom.xxl.job.core.thread.TriggerCallbackThread2.run(TriggerCallbackThread.java:111)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: readObject: unexpected end of file
at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2173)
at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
... 4 more

部署情况是有在同一台服务器部署2哥执行器，而且日志往同样的地方输出

**Comment by appoleo** [comment]
这个问题解决了吗，我也碰到同样的问题，执行器每30秒打印该错误，定时任务执行正常

**Comment by appoleo** [comment]
看源码是解析xxl-job日志目录下callbacklog目录下的文件失败抛出的异常，直接清空了该目录就不会抛异常了，具体原因还不清楚

**Comment by xuxueli** [comment]
你好，不同执行器不要公共日志地址路径，尽量隔离开。
