### ISSUE TITLE
2.1.1版本失败回调重试 序列化 错误

### ISSUE THREAD

**Issue by youbeiwuhuan** [xuxueli/xxl-job#1938]
Please answer some questions before submitting your issue. Thanks!

版本 2.1.1

执行器启动抛出异常
2020-09-01 17:09:24.606 [Thread-6] [ERROR] com.xxl.job.core.util.XxlJobRemotingUtil.postBody Line:81  - java.lang.Integer cannot be cast to java.lang.String (through reference chain: java.util.ArrayList[0]->com.xxl.job.core.biz.model.HandleCallbackParam["executeResult"]->com.xxl.job.core.biz.model.ReturnT["content"])
com.fasterxml.jackson.databind.JsonMappingException: java.lang.Integer cannot be cast to java.lang.String (through reference chain: java.util.ArrayList[0]->com.xxl.job.core.biz.model.HandleCallbackParam["executeResult"]->com.xxl.job.core.biz.model.ReturnT["content"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:45)
	at com.xxl.job.core.biz.client.AdminBizClient.callback(AdminBizClient.java:37)
	at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:171)
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:246)
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:114)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	... 18 common frames omitted

经debug分析，是TriggerCallbackThread.retryFailCallbackFile()方法中下面代码：
List<HandleCallbackParam> callbackParamList = (List)XxlJobExecutor.getSerializer().deserialize(callbackParamList_bytes, HandleCallbackParam.class);
这里序列化回来的HandleCallbackParam对象的ReturnT的content属性实际是Integer型，但xxl-rpc接口callback需要的是String型，这里用List强转躲过了泛型检查。
watch得到XxlJobExecutor.getSerializer()是HessianSerialiser,hessian版本是 com.caucho:hessian:4.0.63.

是否是hessian版本问题？是否该升级hessian?

**Comment by xuxueli** [comment]
你好，高版本改为 restful  方式通讯，检查两端版本是否一致。
