### ISSUE TITLE
xxl-rpc remoting error(no protocol: 192.168.3.12:9000/run), for url : 192.168.3.12:9000/run

### ISSUE THREAD

**Issue by menglongzhizi** [xuxueli/xxl-job#1939]
宿主机ip为192.168.3.12  
docker启动xxl-job 命令如下：
docker run -e PARAMS="--spring.datasource.url=jdbc:mysql://192.168.3.12:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 \
--spring.datasource.username=xxxx \
--spring.datasource.password=xxxx \
--xxl.job.accessToken=xxxxx" \
-p 8010:8080 -v /tmp/xxl-job-data:/data/applogs \
--name xxl-job-admin --restart=always  -d xuxueli/xxl-job-admin:2.1.2

新增调度器为手动录入方式ip和端口如下
192.168.3.12:9000  note：9000为php-fpm的端口
执行任务时输入日志为：

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：192.168.3.12:9000
code：500
msg：xxl-rpc remoting error(no protocol: 192.168.3.12:9000/run), for url : 192.168.3.12:9000/run

打印的log为：
[XxlJobRemotingUtil.java : 139] no protocol: 192.168.3.12:9000/run
java.net.MalformedURLException: no protocol: 192.168.3.12:9000/run
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:69)
	at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:89)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

如果调度器 修改为自动注册
报错为
>>>>>>>>>>>触发调度<<<<<<<<<<<
调度失败：执行器地址为空

请问大神该这是哪里的问题？

**Comment by lastlearner** [comment]
第一个问题是没有加上协议（http）
第二个问题应该先确定是否将执行器注册到调度中心

**Comment by menglongzhizi** [comment]
Hi Dear:

     抱歉今天才看到您的邮件，经过测试目前已经全部ok了，也已经添加上了http，执行器也已经正常启动了。

     非常感谢您的回复!

     再次感谢。！


                                                     致
礼





廖亦浪 <notifications@github.com> 于2020年9月14日周一 下午4:08写道：

**Comment by sinosofti** [comment]
2.3.0版本
任务触发类型：手动触发
调度机器：172.16.101.102
执行器-注册方式：自动注册
执行器-地址列表：[http://172.16.101.102:9999/]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：http://172.16.101.102:9999/
code：500
msg：xxl-rpc remoting error(Read timed out), for url : http://172.16.101.102:9999/run

**Comment by suood** [comment]
请问怎么添加的http协议？
