### ISSUE TITLE
ERROR c.x.job.core.executor.XxlJobExecutor - null

### ISSUE THREAD

**Issue by ericzhao14726** [xuxueli/xxl-job#1966]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
core 2.2.0 admin2.2.1

### Expected behavior
正常运行
### Actual behavior
11:20:25.100 logback [SpringContextShutdownHook] ERROR c.x.job.core.executor.XxlJobExecutor - null
java.lang.NullPointerException: null
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:117)
	at com.xxl.job.core.server.EmbedServer.stopRegistry(EmbedServer.java:262)
	at com.xxl.job.core.server.EmbedServer.stop(EmbedServer.java:124)
	at com.xxl.job.core.executor.XxlJobExecutor.stopEmbedServer(XxlJobExecutor.java:158)
	at com.xxl.job.core.executor.XxlJobExecutor.destroy(XxlJobExecutor.java:85)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.destroy(XxlJobSpringExecutor.java:55)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1091)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1084)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
11:20:25.100 logback [xxl-job, executor JobLogFileCleanThread] INFO  c.x.j.c.thread.JobLogFileCleanThread - >>>>>>>>>>> xxl-job, executor JobLogFileCleanThread thread destory.
11:20:25.101 logback [xxl-job, executor TriggerCallbackThread] INFO  c.x.j.c.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor callback thread destory.
11:20:25.102 logback [Thread-74] INFO  c.x.j.c.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, executor retry callback thread destory.
### Steps to reproduce the behavior
自己的项目正常引入core包，正常添加配置
### Other information

**Comment by upcwxiao** [comment]
遇到同样问题
