### ISSUE TITLE
quartz  ResultSet is from UPDATE. No Data.

### ISSUE THREAD

**Issue by lee5669** [xuxueli/xxl-job#1977]
运行一年多时间，突然报如下错误，导致任务停止执行，请问是什么原因导致的
2020-09-22 12:54:11.168 [QuartzScheduler_schedulerFactoryBean-data_ClusterManager] ERROR o.s.s.quartz.LocalDataSourceJobStore : ClusterManager: Error managing cluster: Failure identifying failed instances when checking-in: ResultSet is from UPDATE. No Data.
org.quartz.JobPersistenceException: Failure identifying failed instances when checking-in: ResultSet is from UPDATE. No Data.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3405)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterCheckIn(JobStoreSupport.java:3455)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3315)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3920)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3957)
Caused by: java.sql.SQLException: ResultSet is from UPDATE. No Data.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6298)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_next(FilterChainImpl.java:917)
	at com.alibaba.druid.filter.FilterAdapter.resultSet_next(FilterAdapter.java:1907)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_next(FilterChainImpl.java:913)
	at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.next(ResultSetProxyImpl.java:882)
	at com.alibaba.druid.pool.DruidPooledResultSet.next(DruidPooledResultSet.java:69)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectSchedulerStateRecords(StdJDBCDelegate.java:2996)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.findFailedInstances(JobStoreSupport.java:3369)
	... 4 common frames omitted
2020-09-22 12:54:30.091 [schedulerFactoryBean_QuartzSchedulerThread] ERROR o.s.s.quartz.LocalDataSourceJobStore : Error retrieving job, setting trigger state to ERROR.
org.quartz.JobPersistenceException: Couldn't retrieve job: ResultSet is from UPDATE. No Data.
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1401)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2864)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3849)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
Caused by: java.sql.SQLException: ResultSet is from UPDATE. No Data.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6298)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_next(FilterChainImpl.java:917)
	at com.alibaba.druid.filter.FilterAdapter.resultSet_next(FilterAdapter.java:1907)
	at com.alibaba.druid.filter.FilterChainImpl.resultSet_next(FilterChainImpl.java:913)
	at com.alibaba.druid.proxy.jdbc.ResultSetProxyImpl.next(ResultSetProxyImpl.java:882)
	at com.alibaba.druid.pool.DruidPooledResultSet.next(DruidPooledResultSet.java:69)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobDetail(StdJDBCDelegate.java:846)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveJob(JobStoreSupport.java:1390)
	... 6 common frames omitted

**Comment by xuxueli** [comment]
你好，这应该是低版本，quartz导致的问题。建议升级最新版本，已经移除了对quartz的依赖，更加稳定可控。
