### ISSUE TITLE
io.netty.handler.codec.http.FullHttpRequest.uri()Ljava/lang/String;

### ISSUE THREAD

**Issue by admlke** [xuxueli/xxl-job#1980]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
spring boot项目无netty依赖，项目报错：
java.lang.NoSuchMethodError: io.netty.handler.codec.http.FullHttpRequest.uri()Ljava/lang/String;
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:156)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:138)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
admin项目：
7:40:00.088 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-1954725956] ERROR c.x.job.core.util.XxlJobRemotingUtil - Unexpected end of file from server
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115)
	at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:89)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------------------
>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：http://127.0.0.1:9999/
code：500
msg：xxl-rpc remoting error(Unexpected end of file from server), for url : http://127.0.0.1:9999/run

请问这是什么原因？

**Comment by ch219318** [comment]
好好检查下项目jar包，应该是jar包版本冲突之类的问题

**Comment by admlke** [comment]
> 好好检查下项目jar包，应该是jar包版本冲突之类的问

从哪能看到jar冲突吗？或者重点要检查哪些方面的？我们这个项目jar比较多

**Comment by zslbb** [comment]
> > 好好检查下项目jar包，应该是jar包版本冲突之类的问
> 
> 从哪能看到jar冲突吗？或者重点要检查哪些方面的？我们这个项目jar比较多

看一下报错的原始日志，应该是可以直接看出来的，我这边是netty 的jar 包冲突，其他的项目引入了netty的分jar包
![image](https://user-images.githubusercontent.com/15669300/98517972-b36cc700-22a9-11eb-8f72-8045df1b229b.png)

netty-all 和分包 引入的版本不一致，一般出现的异常信息为 java.lang.NoSuchMethodError， java.lang.NoSuchClassError 等异常信息，由于我这边涉及的问题比较复杂，不能简单的通过排除jar来解决问题。
所以我直接使用 maven-shade-plugin 将netty相关包进行来重定位来解决问题。

**Comment by wlli-GitHub** [comment]
你好，请问这个问题你现在解决了吗？我也遇到了同样的问题
