### ISSUE TITLE
生产环境上一直报Read timed out，这是啥原因？

### ISSUE THREAD

**Issue by lijinliang83** [xuxueli/xxl-job#2009]
ERROR com.xxl.job.core.util.XxlJobRemotingUtil - Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_261]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_261]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_261]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_261]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_261]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_261]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_261]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[?:1.8.0_261]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_261]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) ~[?:1.8.0_261]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_261]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_261]
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115) [xxl-job-core-2.2.0.jar!/:?]
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42) [xxl-job-core-2.2.0.jar!/:?]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) [xxl-job-core-2.2.0.jar!/:?]
	
服务正常，但是就是日志一直报这个错？这是什么原因呢？

**Comment by RongXiong2016** [comment]
看下httpClient的超时时间配置

**Comment by lijinliang83** [comment]
设置的是3秒。

**Comment by RongXiong2016** [comment]
那可以把时间配的再长一些

**Comment by xuxueli** [comment]
你好，调度请求默认超时 3s，确认下是否网络状况是否正常。

**Comment by bugushi** [comment]
> 你好，调度请求默认超时 3s，确认下是否网络状况是否正常。

这个值后续是否可以支持自定义设置，我看client里是写死的

**Comment by BangByte** [comment]
请问解决了吗，你电话是多少取取经
