### ISSUE TITLE
xxl_job_group 不能更新 address_type，会导致任务被调度到历史的执行器上去，从而导致任务无法执行

### ISSUE THREAD

**Issue by zslbb** [xuxueli/xxl-job#2012]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

V2.2.1

### Expected behavior

执行器列表及时更新

### Actual behavior

执行器列表无法及时更新，

### Steps to reproduce the behavior

执行器数量 > 18 台

### Other information

exception stack info:

```

The error may involve com.xxl.job.admin.dao.XxlJobGroupDao.update-Inline
### The error occurred while setting parameters
### SQL: UPDATE xxl_job_group   SET `app_name` = ?,    `title` = ?,    `address_type` = ?,    `address_list` = ?   WHERE id = ?
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'address_list' at row 1
; Data truncation: Data too long for column 'address_list' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'address_list' at row 1
        at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
        at com.sun.proxy.$Proxy67.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:287)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
        at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:144)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)
        at com.sun.proxy.$Proxy69.update(Unknown Source)
        at com.xxl.job.admin.core.thread.JobRegistryMonitorHelper$1.run(JobRegistryMonitorHelper.java:76)
        at java.lang.Thread.run(Thread.java:748)

```

### 建议：

更改 address_list 为 text 类型

同时对 xxl-job-group 表 增加 create_time, update_time 字段，update_time 字段随当前时间戳更新

**Comment by xuxueli** [comment]
你好，问题已修复并推送master分支，将会跟随下个版本一同发布上线。

**Comment by zslbb** [comment]
ok

**Comment by SevenLM361** [comment]
> 你好，问题已修复并推送master分支，将会跟随下个版本一同发布上线。

这个问题会影响节点注册么，我这里发现节点注册不上时也报了这个错

**Comment by zslbb** [comment]
> > 你好，问题已修复并推送master分支，将会跟随下个版本一同发布上线。
> 
> 这个问题会影响节点注册么，我这里发现节点注册不上时也报了这个错

注册不影响，但是xxl-job 内部将注册到同一个goup的机器整合起来的时候就会报错，导致注册的机器无法被调度到，从意义上来说也影响了注册。
