### ISSUE TITLE
启动成功了，但是一直有问题

### ISSUE THREAD

**Issue by yanhl0326** [xuxueli/xxl-job#2030]
启动执行器的时候一直有如下问题：
2020-10-28 15:33:04,022 INFO [xxl-job, executor TriggerCallbackThread] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='2c5c897d-451b-4f20-85e9-a1b476a739d5', createMillisTime=1603870381022, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=824256, logDateTim=1603870380032, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:05,848 INFO [Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='2f81f886-05f3-4d39-be1d-5e6d7d88bb6b', createMillisTime=1603870382847, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=823879, logDateTim=1603867200036, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:07,023 INFO [xxl-job, executor TriggerCallbackThread] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='c6ba30d5-d9dc-4be8-8fe1-81d5bca39ae2', createMillisTime=1603870384023, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=824253, logDateTim=1603870380027, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=824258, logDateTim=1603870380035, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=824255, logDateTim=1603870380030, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=824259, logDateTim=1603870380037, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:08,848 INFO [Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='ec3fe061-82b8-47c1-b15d-6776df393ff0', createMillisTime=1603870385848, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=712999, logDateTim=1603454400071, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=712984, logDateTim=1603454400058, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713009, logDateTim=1603454400190, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713012, logDateTim=1603454400192, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713020, logDateTim=1603454400204, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713011, logDateTim=1603454400192, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713003, logDateTim=1603454400095, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713010, logDateTim=1603454400190, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713001, logDateTim=1603454400073, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=712988, logDateTim=1603454400061, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713017, logDateTim=1603454400198, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=713023, logDateTim=1603454403015, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=712989, logDateTim=1603454400063, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:10,600 INFO [xxl-job, executor ExecutorRegistryThread] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='73485c25-bd48-47b7-9004-20b8604341d5', createMillisTime=1603870387599, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-boe', registryValue='10.78.193.233:8898'}], version='null'}
2020-10-28 15:33:10,600 INFO [xxl-job, executor ExecutorRegistryThread] c.x.j.c.t.ExecutorRegistryThread [ExecutorRegistryThread.java : 57] >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-boe', registryValue='10.78.193.233:8898'}
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1603870390600, request:XxlRpcRequest{requestId='73485c25-bd48-47b7-9004-20b8604341d5', createMillisTime=1603870387599, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-boe', registryValue='10.78.193.233:8898'}], version='null'}
        at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
        at com.sun.proxy.$Proxy56.registry(Unknown Source)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
        at java.lang.Thread.run(Thread.java:748)
2020-10-28 15:33:11,849 INFO [Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='2ea1ee38-7c3c-4b1a-875c-92547c1e0167', createMillisTime=1603870388849, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=822274, logDateTim=1603853640031, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:14,850 INFO [Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='8a6ae397-de34-4a39-9ed2-e09936cd41eb', createMillisTime=1603870391850, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=823697, logDateTim=1603865640036, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:17,851 INFO [Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='576de825-c050-429f-8242-c36425c9b369', createMillisTime=1603870394850, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=824173, logDateTim=1603869637162, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}
2020-10-28 15:33:20,852 INFO [Thread-3] c.x.r.r.i.r.XxlRpcReferenceBean [XxlRpcReferenceBean.java : 225] >>>>>>>>>>> xxl-rpc, invoke error, address:http://10.78.223.233:8888/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='07ed6cb4-961a-4382-9410-0cd99ba7281e', createMillisTime=1603870397851, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=817620, logDateTim=1603810800087, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817648, logDateTim=1603810800198, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817613, logDateTim=1603810800077, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817647, logDateTim=1603810800197, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817629, logDateTim=1603810800099, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817617, logDateTim=1603810800080, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817643, logDateTim=1603810800187, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817626, logDateTim=1603810800096, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817640, logDateTim=1603810800180, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817639, logDateTim=1603810800180, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817651, logDateTim=1603810800203, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817642, logDateTim=1603810800194, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817652, logDateTim=1603810800205, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817654, logDateTim=1603810800283, executeResult=ReturnT [code=200, msg=null, content=null]}, HandleCallbackParam{logId=817621, logDateTim=1603810800086, executeResult=ReturnT [code=200, msg=null, content=null]}]], version='null'}

**Comment by xuxueli** [comment]
你好，从日志看是回调失败，需要检查下回调地址准确性和网络。

**Comment by yanhl0326** [comment]
> 你好，从日志看是回调失败，需要检查下回调地址准确性和网络。

检查过后发现不是这两个问题，还有没有是其他哪里的错？（采用的是一个调度中心两个执行器）

**Comment by FrankAblert** [comment]
同问，我用2.1.0版本
