### ISSUE TITLE
服务启动后，大量的日志错误

### ISSUE THREAD

**Issue by oceanchow0225** [xuxueli/xxl-job#2031]
2020-10-29 14:22:01.585  INFO 24305 --- [Thread-14] c.x.r.r.i.reference.XxlRpcReferenceBean  : >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.168.188.241:8850/xxl-job-admin//api, XxlRpcRequestXxlRpcRequest{requestId='0740244f-3ecf-4daf-a328-54faba499df0', createMillisTime=1603952521354, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=1015161, logDateTim=1600099200003, executeResult=ReturnT [code=500, msg=java.lang.StackOverflowError
	at java.util.zip.Inflater.<init>(Inflater.java:102)
	at org.springframework.boot.loader.jar.ZipInflaterInputStream.<init>(ZipInflaterInputStream.java:38)
	at org.springframework.boot.loader.jar.JarFileEntries.getInputStream(JarFileEntries.java:217)
	at org.springframework.boot.loader.jar.JarFile.getInputStream(JarFile.java:231)
	at org.springframework.boot.loader.jar.JarURLConnection.getInputStream(JarURLConnection.java:167)
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:725)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:225)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:572)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:570)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:569)
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:58)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1096)
	at org.apache.commons.discovery.resource.classes.DiscoverClasses$1.getNextClass(DiscoverClasses.java:107)
	at org.apache.commons.discovery.resource.classes.DiscoverClasses$1.hasNext(DiscoverClasses.java:88)
	at org.apache.commons.discovery.resource.classes.ResourceClassDiscoverImpl$1.getNextResource(ResourceClassDiscoverImpl.java:116)
	at org.apache.commons.discovery.resource.classes.ResourceClassDiscoverImpl$1.hasNext(ResourceClassDiscoverImpl.java:103)
	at org.apache.axis.configuration.EngineConfigurationFactoryFinder$1.run(EngineConfigurationFactoryFinder.java:120)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.axis.configuration.EngineConfigurationFactoryFinder.newFactory(EngineConfigurationFactoryFinder.java:113)
	at org.apache.axis.configuration.EngineConfigurationFactoryFinder.newFactory(EngineConfigurationFactoryFinder.java:160)
	at org.apache.axis.client.Service.getEngineConfiguration(Service.java:813)
	at org.apache.axis.client.Service.getAxisClient(Service.java:104)
	at org.apache.axis.client.Service.<init>(Service.java:113)
	at com.physicalpoint.fyzx.collection.job.service.impl.YktServiceImpl.getBaseAccInfos(YktServiceImpl.java:321)

请问是什么原因。
工程原来是ok的，不过因为集成了三个数据源，本地服务的启动没有什么问题，但是服务器上就有大量的日志报错

**Comment by xuxueli** [comment]
你好，从日志看报错是业务代码故障导致，检查一下 “YktServiceImpl.java:321” 相关逻辑。
