### ISSUE TITLE
后台一直报这个错

### ISSUE THREAD

**Issue by zqxsober** [xuxueli/xxl-job#2034]
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52) ~[xxl-rpc-core-1.5.0.jar!/:na]
        at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238) ~[xxl-job-core-2.1.2.jar!/:na]
        at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24) ~[xxl-job-core-2.1.2.jar!/:na]
        at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111) ~[xxl-job-core-2.1.2.jar!/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
Caused by: java.io.EOFException: readObject: unexpected end of file
        at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2147) ~[hessian-4.0.63.jar!/:3.1.0]
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49) ~[xxl-rpc-core-1.5.0.jar!/:na]
        ... 4 common frames omitted

**Comment by gogodjzhu** [comment]
似乎有人遇到过类似的问题 #1115

**Comment by tomzhang170** [comment]
执行器的日志目录下callback目录，存在文件大小为0的文件，删除即可。

**Comment by keenancy** [comment]
> 执行器的日志目录下callback目录，存在文件大小为0的文件，删除即可。

哪个目录？

**Comment by mwl2018** [comment]
> > 执行器的日志目录下callback目录，存在文件大小为0的文件，删除即可。
> 
> 哪个目录？

callbacklog目录是 通过属性 xxl.job.executor.logpath 配置的

**Comment by dicklee2002** [comment]
我现在2.1.2版本上也遇过上这段com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file；
在此之前应用程序一直在 之前2.1.1版本满屏乱码还有执行器没有显示成功结果，后来我升一级2.1.2改oracle的admin模块版本可以了。

**Comment by dicklee2002** [comment]
应用启动一直com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file；，估计有以前回退日志造成，删除即可。rm /data/applogs/xxl-job/jobhandler/callbacklog/* -rf

**Comment by lxx0325** [comment]
删除掉映射出来的日志目录中的callback文件夹下大小为0的文件就能解决 亲测
