### ISSUE TITLE
callbak回调诡异报错，执行器能注册能被调度，很久之前的任务被再次调度，尝试删库重来，依然无效

### ISSUE THREAD

**Issue by resuper** [xuxueli/xxl-job#2048]
我遇到了这样一个问题，不知道是因为什么。。。我尽力寻找了一整天，熬到了凌晨2点，依然没赵文问题发生在哪里，希望佬们帮帮我。
单独启动xxl-job-admin时控制台安然无恙，启动执行器之后，执行器能注册成功，任务也能正常调度。
但是xxl-job-admin控制台一直报错，经查看报错信息，貌似是调用了/callbak这个然后解析json字符串一直报错。然而，在我执行器代码中，这段代码早就被我注释了掉了。不知为何一直还是会出现这个报错。
我以为是类没被重新加载导致的，我多次clean依然无用，我寻找jar包冲突也没寻找到,也更换了执行器springboot的版本和xxl-job-admin的版本一样，依然无用。

版本信息
xxl-job-admin 2.1.2。
spring-boot  1.5.22.RELEASE。
执行器依赖 的springboot已经调整为 1.5.22.RELEASE。

断点位置
TriggerCallbackThread.start()    
  triggerRetryCallbackThread  retryFailCallbackFile()方法  doCallback()

AdminBizClient.callback

JobApiController.callback

```java
    /**
     * 根据单位编码找到对应的规则SQL执行xx
     */
//    @RequestMapping("/execsql")
//    public ResponseEntity executeRuleSql(Parameter1 parameter1, HttpServletRequest request) {
//        try {
//            parameter1.setCzrbs(request.getHeader("X-AUTH-RYBS"));
//            Date curr = new Date();
//            curr = sf.parse(sf.format(curr));
//            parameter1.setDzsj(curr);
//            /**
//             * 执行SQL的服务，其中加入了取数逻辑
//             */
//            return yxcwdzServiceImpl.executeRuleSql(parameter1);
//        } catch (SQLException e) {
//            //getSQLState 借助这个拿出抛异常时携带的SQL语句
//            Map<String, String> map = new HashMap<>();
//            map.put("sys_error_msg", e.getMessage());
//            map.put("sql", e.getSQLState());
//            return ResponseEntity.ok(new Result(500, "sql语句执行出错，请检查配置的对账规则SQL", map));
//        } catch (CheckRuleException e) {
//            if (e.getMessage().contains("校验逻辑未通过")) {
//                Map<String, StringBuilder> map = new HashMap<>();
//                map.put("sql", (StringBuilder) e.getData());
//                return ResponseEntity.ok(new Result(500, e.getMessage(), e.getData()));
//            }
//        } catch (ParseException e) {
//            e.printStackTrace();
//        }
//        return ResponseEntity.ok(new Result(500, null, null));
//    }

```

```java
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'Y' (code 89)
 at [Source: [{"logId":13,"logDateTim":1597928742597,"executeResult":{"code":500,"msg":"java.lang.reflect.InvocationTargetException\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)\r\n\tat com.xxl.job.core.thread.JobThread.run(JobThread.java:152)\r\nCaused by: java.lang.RuntimeException: sql语句执行出错，请检查配置的对账规则SQL\nsys_error_msg:\r\n### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '3000001175500013-0-3000001425043528' for key 'PRIMARY'\r\n### The error may exist in file [F:\YDTF-workspace\营销财务对账SQL执行引擎\gitcloen\CheckMarketingFinancial\yxcwdz\target\classes\mapper\YxcwdzMapper.xml]\r\n### The error may involve defaultParameterMap\r\n### The error occurred while setting parameters\r\n### SQL: {    call mysqlexecutor(?)   }\r\n### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '3000001175500013-0-3000001425043528' for key 'PRIMARY'\n; ]; Duplicate entry '3000001175500013-0-3000001425043528' for key 'PRIMARY'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '3000001175500013-0-3000001425043528' for key 'PRIMARY'\nsql:INSERT INTO DZ_DZMX_YX (RWBS,YSZWLSH,SSZWLSH,JLDBH,SSLSH,SSZE,GZBH,HZBS,RJQRBS,SSRBS,ZJLXDM,DWBM,GDDWBM,DQBM) \r\n\t(SELECT '13' RWBS,A.YSZWLSH,A.SSZWLSH,A.JLDBH,A.SSLSH,A.SSZE,B.GZBH,B.HZBS,A.RJQRBS,A.SSRBS,A.ZJLXDM,A.DWBM,A.GDDWBM,A.DQBM \r\n\tFROM ZW_SSDFJL_DZ A,DZ_DZJL B \r\n\tWHERE B.DQBM='050600' AND B.DWBM LIKE CONCAT('0506','%') AND B.GZBH='XYS004' AND B.DZSJ='2020-08-20 21:08:28' AND B.RWBS='13' \r\n\tAND A.SSRBS='5000000001830109' AND A.DQBM='050600' AND A.DWBM LIKE CONCAT('0506','%') AND A.SFRJHZ=1\r\n\tAND A.SSRBS=B.SSRBS AND A.YHKKPCH=B.YHKKPCH AND A.DWBM=B.DWBM AND A.RWBS=B.RWBS)\r\n\tat com.resuper.service.impl.DzJobServiceImpl.sqlExecutionEngineStart(DzJobServiceImpl.java:69)\r\n\tat com.resuper.service.jobhandler.SampleXxlJob.sqlExecutionEngine(SampleXxlJob.java:155)\r\n\t... 6 more\r\n","content":null}}]; line: 1, column: 865]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._handleUnrecognizedCharacterEscape(ParserMinimalBase.java:535)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._decodeEscaped(ReaderBasedJsonParser.java:2536)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString2(ReaderBasedJsonParser.java:2057)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:2030)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:276)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	... 78 common frames omitted
```

xxl-job-admin pom.xml
调整说明：
加入了加密jar包，eureka其他jar包，引入了其他jar包，xxl-job-admin原有依赖版本都没动过
父项目在工程中报错，所以加入了 `<relativePath></relativePath>`

```xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.xuxueli</groupId>
		<artifactId>xxl-job</artifactId>
		<version>2.1.2</version>
		<relativePath></relativePath>
	</parent>
	<artifactId>xxl-job-admin</artifactId>
	<packaging>jar</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.encoding>UTF-8</maven.compiler.encoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.test.skip>true</maven.test.skip>

		<xxl-rpc.version>1.5.0</xxl-rpc.version>

		<spring.version>4.3.25.RELEASE</spring.version>
		<spring-boot.version>1.5.22.RELEASE</spring-boot.version>
		<mybatis-spring-boot-starter.version>1.3.5</mybatis-spring-boot-starter.version>
		<mysql-connector-java.version>8.0.19</mysql-connector-java.version>

		<slf4j-api.version>1.7.29</slf4j-api.version>
		<junit.version>4.12</junit.version>

		<groovy.version>2.5.8</groovy.version>

		<maven-source-plugin.version>3.2.0</maven-source-plugin.version>
		<maven-javadoc-plugin.version>3.1.1</maven-javadoc-plugin.version>
		<maven-gpg-plugin.version>1.6</maven-gpg-plugin.version>
		<maven-war-plugin.version>3.2.3</maven-war-plugin.version>
	</properties>


	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-parent</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<!--<version>Finchley.SR2</version>-->
				<version>Edgware.SR3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>


		<!--openfeign-->
		<!--<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-openfeign</artifactId>
			<version>2.2.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>-->

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
			<exclusions>
				<exclusion>
					<artifactId>rxnetty</artifactId>
					<groupId>io.reactivex</groupId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on -->
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk15on</artifactId>
			<version>1.65.01</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/commons-codec/commons-codec -->
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.14</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.projectlombok/lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.12</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.alibaba/fastjson -->
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.70</version>
		</dependency>









		<!-- starter-web：spring-webmvc + autoconfigure + logback + yaml + tomcat -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<!-- starter-test：junit + spring-test + mockito -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- freemarker-starter -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-freemarker</artifactId>
		</dependency>

		<!-- mail-starter -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>

		<!-- starter-actuator -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- mybatis-starter：mybatis + mybatis-spring + tomcat-jdbc（default） -->
		<dependency>
			<groupId>org.mybatis.spring.boot</groupId>
			<artifactId>mybatis-spring-boot-starter</artifactId>
			<version>${mybatis-spring-boot-starter.version}</version>
		</dependency>
		<!-- mysql -->
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>${mysql-connector-java.version}</version>
		</dependency>

		<!-- xxl-job-core -->
		<dependency>
			<groupId>com.xuxueli</groupId>
			<artifactId>xxl-job-core</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- docker -->
			<plugin>
				<groupId>com.spotify</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.4.13</version>
				<configuration>
					<!-- made of '[a-z0-9-_.]' -->
					<imageName>${project.artifactId}:${project.version}</imageName>
					<dockerDirectory>${project.basedir}</dockerDirectory>
					<resources>
						<resource>
							<targetPath>/</targetPath>
							<directory>${project.build.directory}</directory>
							<include>${project.build.finalName}.jar</include>
						</resource>
					</resources>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>

```
---
执行器 pom.xml

```xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!--<parent>
        <artifactId>market2020</artifactId>
        <groupId>com.resuper</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>-->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <!--<version>2.0.5.RELEASE</version>-->
        <version>1.5.22.RELEASE</version>
        <relativePath></relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>yxcwdz</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <!--<spring-cloud.version>Finchley.SR2</spring-cloud.version>-->
        <spring-cloud.version>Edgware.SR3</spring-cloud.version>

        <!--<xxl-job-core.version>2.2.0</xxl-job-core.version>-->
        <xxl-job-core.version>2.1.2</xxl-job-core.version>
    </properties>


    <dependencyManagement>
        <dependencies>
            <!--<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>-->
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!--openfeign-->
        <!--<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>-->

        <!--<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
        </dependency>-->

        <!--redis依赖，用于存储任务执行进度-->
        <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-redis -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <!--<version>2.3.1.RELEASE</version>-->
        </dependency>

        <!-- https://mvnrepository.com/artifact/com.baomidou/dynamic-datasource-spring-boot-starter -->
        <!-- 执行任务前需要从营销数据库取数，引入动态数据源用于切换数据源 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
            <version>3.2.0</version>
        </dependency>
        <!--oracle 数据库驱动-->
        <dependency>
            <groupId>oracle-driver-ojdbc6</groupId>
            <artifactId>oracle-driver-ojdbc6</artifactId>
            <version>12.1.0.1</version>
            <!-- maven 有时候无法导入oracle驱动，需要手动下载，原因我也是百度知道的 -->
            <scope>system</scope>
            <systemPath>${project.basedir}/src/main/resources/lib/oracle-driver-ojdbc6-12.1.0.1.jar</systemPath>
        </dependency>
        <!--工具包-->
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.3.10</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.70</version>
        </dependency>





        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.belerweb</groupId>
            <artifactId>pinyin4j</artifactId>
            <version>2.5.0</version>
        </dependency>
        <!-- map 转换-->
        <dependency>
            <groupId>commons-beanutils</groupId>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>1.9.3</version>
        </dependency>
        <!--导出文件-->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>4.1.2</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.apache.poi</groupId>-->
<!--            <artifactId>poi-ooxml</artifactId>-->
<!--            <version>3.17</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.4</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.19</version>
        </dependency>

        <!-- 引入mybatis-plus的依赖jar -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>3.3.2</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.3.3</version>
        </dependency>


        <!-- xxl-job补充jar -->
        <!-- xxl-job-core -->
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>${xxl-job-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
            <version>4.2.13.RELEASE</version>
            <scope>compile</scope>
        </dependency>


    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <!-- 处理oraclejar包问题 -->
                <configuration>
                    <includeSystemScope>true</includeSystemScope>
                </configuration>
            </plugin>
        </plugins>

        <!--如果将xml形式的mybatis映射文件放到mappers包下面，maven打包时会忽略改文件-->
        <!--配置该项可以解决问题-->
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.properties</include>
                </includes>
                <filtering>false</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
    </build>


</project>

```

**Comment by resuper** [comment]
本人先前改动过日志路径，有两个日志路径，有种日志回放的感觉，具体我也不知道为啥，把日志删掉重启就好了
