### ISSUE TITLE
生产环境 java.net.SocketTimeoutException: Read timed out 

### ISSUE THREAD

**Issue by fengmingli** [xuxueli/xxl-job#2067]
xxl-job版本:2.2.0

问题截图:
![image](https://user-images.githubusercontent.com/48621224/98829539-48232080-2474-11eb-89e1-53d4b705bdf5.png)

执行器日志:

```
2020-11-11 15:43:42.789 [TID: N/A] [PressureFlag: N/A] [ERROR] [xxl-job, executor ExecutorRegistryThread] [xxl.job.core.util.XxlJobRemotingUtil:]  Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_202]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_202]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_202]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_202]
--
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115) [xxl-job-core-2.2.0.jar!/:?]
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42) [xxl-job-core-2.2.0.jar!/:?]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) [xxl-job-core-2.2.0.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
2020-11-11 15:43:42.789 [TID: N/A] [PressureFlag: N/A] [INFO ] [xxl-job, executor ExecutorRegistryThread] [xxl.job.core.thread.ExecutorRegistryThread:]  >>>>>>>>>>> xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='xxxx', registryValue='http://XXX/'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Read timed out), for url : http://xxl-job-prod.mockuai.net/xxl-job-admin/api/registry, content=null]
```
部署环境使用的阿里云ECS:阿里云那边回复是那段时间网络没有抖动

这个问题半个月内已经出现过两次了

**Comment by shiyuHou** [comment]
同样出现此问题，请问解决了么？

**Comment by konghao1** [comment]
出现此问题+1，楼上有已经解决的大佬吗？

**Comment by konghao1** [comment]
> xxl-job版本:2.2.0
> 
> 问题截图: ![image](https://user-images.githubusercontent.com/48621224/98829539-48232080-2474-11eb-89e1-53d4b705bdf5.png)
> 
> 执行器日志:
> 
> ```
> 2020-11-11 15:43:42.789 [TID: N/A] [PressureFlag: N/A] [ERROR] [xxl-job, executor ExecutorRegistryThread] [xxl.job.core.util.XxlJobRemotingUtil:]  Read timed out
> java.net.SocketTimeoutException: Read timed out
> 	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_202]
> 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_202]
> 	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_202]
> 	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_202]
> --
> 	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115) [xxl-job-core-2.2.0.jar!/:?]
> 	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42) [xxl-job-core-2.2.0.jar!/:?]
> 	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) [xxl-job-core-2.2.0.jar!/:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
> 2020-11-11 15:43:42.789 [TID: N/A] [PressureFlag: N/A] [INFO ] [xxl-job, executor ExecutorRegistryThread] [xxl.job.core.thread.ExecutorRegistryThread:]  >>>>>>>>>>> xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='xxxx', registryValue='http://XXX/'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Read timed out), for url : http://xxl-job-prod.mockuai.net/xxl-job-admin/api/registry, content=null]
> ```
> 
> 部署环境使用的阿里云ECS:阿里云那边回复是那段时间网络没有抖动
> 
> 这个问题半个月内已经出现过两次了

您好，Xxl-job这个问题您已经解决了吗？

**Comment by cicoco** [comment]
同样的问题+1

**Comment by whram** [comment]
同样的问题+1
