### ISSUE TITLE
将执行器的properties文件更改为yml格式后出现 Could not resolve placeholder 异常

### ISSUE THREAD

**Issue by if2018** [xuxueli/xxl-job#2070]
将执行器中的properties文件更改为yml格式后出现 Could not resolve placeholder 'jckz.job.admin.addresses' in value "${jckz.job.admin.addresses}"异常
![1605339008(1)](https://user-images.githubusercontent.com/35320255/99142415-b3950a00-268f-11eb-8fed-65033d43158d.png)
![1605339575(1)](https://user-images.githubusercontent.com/35320255/99142419-bd1e7200-268f-11eb-82ff-1ebe4865ff92.jpg)
![1605339605(1)](https://user-images.githubusercontent.com/35320255/99142421-bee83580-268f-11eb-8c64-35be4639ec18.jpg)
感觉没啥问题啊，为什么会报错呢

**Comment by if2018** [comment]
图片无法上传,放代码吧
--------------------------
@Value("${jckz.job.admin.addresses}")
    private String adminAddresses;
-----------------------------
报错信息
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'jckz.job.admin.addresses' in value "${jckz.job.admin.addresses}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:918)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1248)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	... 20 common frames omitted
------------------------------------------------
yml配置
jckz:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/jckz-job-admin
    executor:
      address: ''

**Comment by oraoraora123** [comment]
遇到的相同的问题，可以将yml中不用的配置注释掉，在config中添加默认值解决
@Value("${xxl.job.admin.addresses:#{null}}")

**Comment by xuxueli** [comment]
> 遇到的相同的问题，可以将yml中不用的配置注释掉，在config中添加默认值解决
> 
> @Value("${xxl.job.admin.addresses:#{null}}")

+1
