### ISSUE TITLE
  调度中心注册成功，执行器定时报错xxl-job registry error

### ISSUE THREAD

**Issue by lyugit** [xuxueli/xxl-job#2094]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.0 springboot版本2.0+
### Expected behavior
执行器注册正常
### Actual behavior
其实能注册正常，调度中心可以正确调用handle，但是执行器后台一直报错注册失败？
### Steps to reproduce the behavior
日志
xxl-rpc , invoke error  address:.....
16:44:16.375 logback [xxl-job, executor ExecutorRegistryThread] INFO c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='127.0.0.1:9999'} com.xxl.rpc.util.XxlRpcException: io.netty.channel.ExtendedClosedChannelException at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227) at com.sun.proxy.$Proxy54.registry(Unknown Source) at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) at java.lang.Thread.run(Thread.java:745) Caused by: io.netty.channel.ExtendedClosedChannelException: null at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
### Other information
不知道跟网络有关没  我是在内网环境跑的  调度中心和执行器都在内网

**Comment by ivanyunxian** [comment]
可能是别的执行器报错 或者你的执行器虚拟端口被禁了？试过执行任务了吗

**Comment by lyugit** [comment]
感谢回复
1 试过执行任务， 执行任务没有问题，可以正常调度和执行。&nbsp;&nbsp;2 没有别的执行器，因为报错信息里就是我注册的那个端口号，但是很奇怪 可以正常调度和执行任务。
3 还能有其他原因吗？
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "linuo"<notifications@github.com&gt;; 
发送时间: 2020年11月27日(星期五) 下午5:21
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com&gt;; 
抄送: "372834991"<372834991@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xuxueli/xxl-job]   调度中心注册成功，执行器定时报错xxl-job registry error (#2094)





 
可能是别的执行器报错 或者你的执行器虚拟端口被禁了？试过执行任务了吗
