### ISSUE TITLE
Nacos1.4.0和xxl-job2.0.0同时使用时，远程配置问题

### ISSUE THREAD

**Issue by wszpwsren** [xuxueli/xxl-job#2108]
环境：nacos 1.4.0，xxl-job 2.0.0 ,springboot
nacos升级到1.4.0之后
远程配置值为空时，启动报错

远程配置
xxx.yaml
```
xxl:
  job:
    admin:
      addresses=: http://xxx.xxx/xxl-job-admin
    executor:
      appname: job-service
      address=:
      ip=:
      port: 5017
```
错误

`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'xxl.job.executor.ip' in value "${xxl.job.executor.ip}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:178) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:175) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:918) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1248) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        ... 26 common frames omitted
`

**Comment by LockiJiang** [comment]
```
xxl:
  job:
    admin:
      addresses: http://xxx.xxx/xxl-job-admin
    executor:
      appname: job-service
      address:
      ip:
      port: 501
```

**Comment by wszpwsren** [comment]
> ```
> xxl:
>   job:
>     admin:
>       addresses: http://xxx.xxx/xxl-job-admin
>     executor:
>       appname: job-service
>       address:
>       ip:xxx.xxx.xxx.xxx
>       port: 5017
> ```

port不写应该也是可以的
现在的做法是将为空的配置写在本地
