### ISSUE TITLE
执行器内存溢出

### ISSUE THREAD

**Issue by xww0219** [xuxueli/xxl-job#2122]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Actual behavior
执行器服务内存溢出
### Steps to reproduce the behavior
任务全部为Glue(Java)模式，执行器每次重启1-2天之后就会内存溢出
### Other information
16:47:22.803 logback [xxl-job, executor ExecutorRegistryThread] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.169.12.102:7006/api, XxlRpcRequestXxlRpcRequest{requestId='9fc63b4b-e6e5-4b0b-9716-d106c2fdbab4', createMillisTime=1607330825383, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.169.12.102:9991'}], version='null'}
16:47:33.950 logback [Thread-5] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.169.12.102:7006/api, XxlRpcRequestXxlRpcRequest{requestId='2dab2020-415c-44c2-b70b-0b71c5c10118', createMillisTime=1607330836529, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='callback', parameterTypes=[interface java.util.List], parameters=[[HandleCallbackParam{logId=10067636, logDateTim=1607244014004, executeResult=ReturnT [code=502, msg=job execute timeout , content=null]}]], version='null'}
Exception in thread "Thread-5" Exception in thread "xxl-job, executor ExecutorRegistryThread" java.lang.OutOfMemoryError: Java heap space
	at java.util.ResourceBundle.putBundleInCache(ResourceBundle.java:1694)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1471)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:890)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:164)
	at sun.util.resources.LocaleData$1.run(LocaleData.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.util.resources.LocaleData.getBundle(LocaleData.java:160)
	at sun.util.resources.LocaleData.getDateFormatData(LocaleData.java:124)
	at java.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:697)
	at java.text.DateFormatSymbols.<init>(DateFormatSymbols.java:146)
	at sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(DateFormatSymbolsProviderImpl.java:85)
	at java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:359)
	at java.text.DateFormatSymbols.getInstanceRef(DateFormatSymbols.java:349)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:603)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
	at com.xxl.job.core.log.XxlJobFileAppender.makeLogFileName(XxlJobFileAppender.java:75)
	at com.xxl.job.core.thread.TriggerCallbackThread.callbackLog(TriggerCallbackThread.java:193)
	at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:180)
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:247)
	at com.xxl.job.core.thread.TriggerCallbackThread.access$4(TriggerCallbackThread.java:227)
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:115)
	at java.lang.Thread.run(Thread.java:745)

**Comment by GavinCruise** [comment]
内存溢出问题需要结合自己的 JVM 配置查看分析。

**Comment by xuxueli** [comment]
无法复现
