### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List

### ISSUE THREAD

**Issue by AllenHu2018** [xuxueli/xxl-job#2129]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.1.2.2
### Actual behavior
服务器持续报错，详情见information，但是本地IDEA启动不报错，版本SpringBoot1.5.13.release，JDK版本本地JDK1.8_202，服务器java version "1.8.0_221"
是否可协助提供排查的思路？
### Other information

2020-12-11 09:22:16.447 ERROR [tms-service,,,] [tms-service,,,,] 1333 --- [      Thread-11] c.x.j.core.thread.TriggerCallbackThread  : java.lang.String cannot be cast to java.util.List

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
        at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238)
        at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24)
        at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111)
        at java.lang.Thread.run(Thread.java:748)

**Comment by AllenHu2018** [comment]
2020-12-11 09:34:16.592 ERROR [tms-service,,,] [tms-service,,,,] 24166 --- [Pool-1113650049] c.x.r.r.n.i.n.s.NettyHttpServerHandler   : xxl-rpc request data empty.

com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:77)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26)
        at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
还有这个错误

**Comment by AllenHu2018** [comment]
任务可以调度成功，并且正常返回
但是如果任务有问题情况 强制停止 也会报类似错误
怀疑和NETTY有关，但是相关依赖均已经升级到最新
![image](https://user-images.githubusercontent.com/37926317/101852421-907b4e80-3b98-11eb-9329-ca9e97a22c7b.png)

**Comment by qingfengtaizi** [comment]
这个问题 楼主解决了吗？我这边也这样
