### ISSUE TITLE
xxl job 2.2.0定时任务失败，报response content invalid(C0.com.xxl.rpc.remoting.net.params.XxlRpcResponse

### ISSUE THREAD

**Issue by ItBeeCoder2020** [xuxueli/xxl-job#2133]
任务触发类型：手动触发
调度机器：10.24.24.87
执行器-注册方式：自动注册
执行器-地址列表：[http://10.24.24.12:9395]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：http://10.24.24.12:9395
code：500
msg：xxl-rpc remoting (url=http://10.24.24.12:9395/run) response content invalid(C0.com.xxl.rpc.remoting.net.params.XxlRpcResponse� requestIderrorMsgresult`NS�com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '62' at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52) at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:81) at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26) at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '62' at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2926) at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2118) at com.caucho.hessian.io.CollectionDeserializer.readLengthList(CollectionDeserializer.java:93) at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2088) at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49) ... 6 moreN).

**Comment by kokonol** [comment]
一样的问题 解决了吗？

**Comment by kokonol** [comment]
执行器和admin版本不一致导致的

**Comment by h2ero** [comment]
> 执行器和admin版本不一致导致的

就是这个原因，搞定
