### ISSUE TITLE
最新版本入参报错

### ISSUE THREAD

**Issue by renanmin** [xuxueli/xxl-job#2140]
1. Bean方式调度，任务参数为String params,
2. 执行任务入参为  value1
以下我执行任务的日志
![image](https://user-images.githubusercontent.com/33210633/102298842-de26fb00-3f8c-11eb-874a-dcacb8ab2cfc.png)
2020-12-16 10:47:01 [com.xxl.job.core.thread.JobThread#run]-[201]-[Thread-27] 
----------- JobThread Exception:java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:27)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)

**Comment by renanmin** [comment]
XxlJobContext xxlJobContext = XxlJobContext.getXxlJobContext();
        String jobParam = xxlJobContext.getJobParam();

获取入参方式发生了变化了，这样可以拿到参数
