### ISSUE TITLE
与springboot devtools集成出错

### ISSUE THREAD

**Issue by qrqhuang** [xuxueli/xxl-job#215]
### Which version of XXL-JOB do you using?
xxl-job-core-1.8.2.jar
### Expected behavior
修改代码后，应用可以正常热部署
### Actual behavior
应用报错：

`Caused by: java.lang.RuntimeException: xxl-job jobhandler naming conflicts.
	at com.xxl.job.core.executor.XxlJobExecutor.initJobHandlerRepository(XxlJobExecutor.java:152) ~[xxl-job-core-1.8.2.jar:na]
	at com.xxl.job.core.executor.XxlJobExecutor.start(XxlJobExecutor.java:75) ~[xxl-job-core-1.8.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
	... 21 common frames omitted`

### Steps to reproduce the behavior
1. spring-boot-1.5.8.RELEASE.jar
2. 开启spring-boot-devtools
3. 修改应用中任意代码
4. exception occured

### Other information

**Comment by cbwleft** [comment]
+1，对springboot不是特别友好啊

**Comment by davichi11** [comment]
同样的问题,我是根本启动不来,没人管了吗?

**Comment by xuxueli** [comment]
针对上述问题做了修复，可以拉取master分支体验下。
