### ISSUE TITLE
version 2.2.0  job执行 报错 xxl-rpc 客户端-服务端 链接失败，但是任务执行日志展示成功

### ISSUE THREAD

**Issue by aaronxu001** [xuxueli/xxl-job#2150]
version 2.2.0

### 客户端服务发布

服务端报错信息：
[xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-2145896848] ERROR com.xxl.job.core.util.XxlJobRemotingUtil - Read timed out
java.net.SocketTimeoutException: Read timed out
	  at java.net.SocketInputStream.socketRead0(Native Method)
	  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	  at java.net.SocketInputStream.read(SocketInputStream.java:171)
	  at java.net.SocketInputStream.read(SocketInputStream.java:141)
	  at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	  at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	  at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	  at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	  at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	  at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115)
	  at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
	  at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
	  at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
	  at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:89)
	  at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	  at java.lang.Thread.run(Thread.java:748)

客户端报错信息：
[xxl-rpc, EmbedServer bizThreadPool-759881112] INFO  com.xxl.job.core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job regist JobThread success, jobId:6, handler:com.xxl.job.core.handler.impl.MethodJobHandler@7b3a6e95[class com.demo.job.XxlJobs#demoJOB]

 [xxl-job, executor ExecutorRegistryThread] INFO  com.xxl.job.core.thread.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry fail, registryParam:RegistryParam{registryGroup='EXECUTOR', registryKey='xxxxxx', registryValue='http://127.0.0.1:12000/'}, registryResult:ReturnT [code=500, msg=xxl-rpc remoting error(Read timed out), for url : http://127.0.0.1:14000/job/api/registry, content=null]

**Comment by tbwtd** [comment]
遇到了同样的问题，自己调整了控制台源码 设置把链接超时时间设置为30s  效果好了很多

**Comment by aaronxu001** [comment]
> 遇到了同样的问题，自己调整了控制台源码 设置把链接超时时间设置为30s 效果好了很多
好的，不过这样治标不治本，连接失败应该把异常抛到上层，用来判断job是否执行成功。
