### ISSUE TITLE
springmvc 集成执行器报错  java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.byteArrayBaseOffset()

### ISSUE THREAD

**Issue by lyn-my** [xuxueli/xxl-job#2185]
Exception in thread "xxl-rpc, EmbedServer bizThreadPool-49424380" java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.byteArrayBaseOffset()J
  at io.netty.buffer.ByteBufUtil.writeUtf8(ByteBufUtil.java:600)
  at io.netty.buffer.ByteBufUtil.reserveAndWriteUtf8Seq(ByteBufUtil.java:573)
  at io.netty.buffer.ByteBufUtil.writeUtf8(ByteBufUtil.java:529)
  at io.netty.buffer.Unpooled.copiedBufferUtf8(Unpooled.java:599)
  at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:582)
  at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.writeResponse(EmbedServer.java:222)
  at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.access$300(EmbedServer.java:138)
  at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler$1.run(EmbedServer.java:172)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

上述报错，在开发环境、windows测试环境都没有问题，但是部署到现场centos 系统中，就会出现上述报错，然后定时任务我看了，是执行的

**Comment by xuxueli** [comment]
Netty版本冲突，需要和core依赖保持一致
