### ISSUE TITLE
ERROR org.util.XxlJobRemotingUtil-read timed out

### ISSUE THREAD

**Issue by ElvisDream** [xuxueli/xxl-job#2197]

**Comment by shiyuHou** [comment]
大量的registry Read timed out，不定时出现，这个问题是网络问题么，ERROR，对业务会有什么影响吗？应该如何解决此问题？？
[xxl-job, executor ExecutorRegistryThread] c.xxl.job.core.util.XxlJobRemotingUtil   : Read timed out

java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115)
        at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
        at java.lang.Thread.run(Thread.java:748)

**Comment by hao69092017** [comment]
您好，解决了嘛，我也遇到了这个问题

**Comment by mxjWilliam** [comment]
> xxl-job-core.version = 2.2.0 大量的registry Read timed out，不定时出现，这个问题是网络问题么，ERROR，对业务会有什么影响吗？应该如何解决此问题？？ [xxl-job, executor ExecutorRegistryThread] c.xxl.job.core.util.XxlJobRemotingUtil : Read timed out
> 
> java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) at java.net.SocketInputStream.read(SocketInputStream.java:171) at java.net.SocketInputStream.read(SocketInputStream.java:141) at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) at java.io.BufferedInputStream.read(BufferedInputStream.java:345) at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115) at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42) at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) at java.lang.Thread.run(Thread.java:748)

me too,but i only occured when i choose FAILOVER routing strategy,the /beat request never success even though my response is {"code":200}.

**Comment by xuxueli** [comment]
感谢反馈，已记录
