### ISSUE TITLE
TriggerTypeEnum加载问题

### ISSUE THREAD

**Issue by wu-xin** [xuxueli/xxl-job#2222]
版本2.2.0，启动报错偶发：
Caused by: java.lang.NullPointerException: null
	at com.sun.job.admin.core.util.I18nUtil.loadI18nProp(I18nUtil.java:32)
	at com.sun.job.admin.core.util.I18nUtil.getString(I18nUtil.java:52)
	at com.sun.job.admin.core.trigger.TriggerTypeEnum.<clinit>(TriggerTypeEnum.java:11)

TriggerTypeEnum:
MANUAL(I18nUtil.getString("jobconf_trigger_type_manual"))

I18nUtil:
String i18n = SunJobAdminConfig.getAdminConfig().getI18n();

此时adminConfig还没有执行afterPropertiesSet,导致没有实例化，报NPE

**Comment by wu-xin** [comment]
已解决: XxlJobScheduler.initI18n 初始国际化资源中，新增TriggerTypeEnum的初始化，原初始化方法去掉
