### ISSUE TITLE
运行过程中不时报错: java.lang.ClassCastException: java.lang.String cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse

### ISSUE THREAD

**Issue by ljyrains** [xuxueli/xxl-job#223]
### Which version of XXL-JOB do you using?
1.8.2

### Expected behavior
no error

### Actual behavior
应用部署到测试环境后，xxl-job不时报错误：

```

192278:2017-11-16 14:32:21.060 [Thread-14] ERROR com.xxl.job.core.rpc.netcom.jetty.client.JettyClient(40) - java.lang.String cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
192279:java.lang.ClassCastException: java.lang.String cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
192280-	at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:37) [xxl-job-core-1.8.2.jar:?]
192281-	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:51) [xxl-job-core-1.8.2.jar:?]
192282-	at com.sun.proxy.$Proxy119.registry(Unknown Source) [?:?]
192283-	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57) [xxl-job-core-1.8.2.jar:?]
192284-	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
192285-2017-11-16 14:32:21.061 [Thread-14] INFO  com.xxl.job.core.thread.ExecutorRegistryThread(66) - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='finance-service-test', registryValue='172.16.16.63:9999'}
192286:java.lang.RuntimeException: Client-error:java.lang.String cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
192287-	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:59) ~[xxl-job-core-1.8.2.jar:?]
192288-	at com.sun.proxy.$Proxy119.registry(Unknown Source) ~[?:?]
192289-	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57) [xxl-job-core-1.8.2.jar:?]
192290-	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
192291-2017-11-16 14:32:51.076 [Thread-14] INFO  com.xxl.job.core.thread.ExecutorRegistryThread(60) - >>>>>>>>>>> xxl-job registry success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='finance-service-test', registryValue='172.16.16.63:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]

```

具体看不到接到的response是什么数据，为什么转化出问题了？

**Comment by xuxueli** [comment]
你好，感谢关注和反馈！
从Log上看执行器回调出现异常，可以检查一下执行器配置的回调地址是否正确，如配置多个地址需要逐个确认。

**Comment by ljyrains** [comment]
回调地址只有一个

spring-xxl-job.xml
```
        <!-- 执行器注册中心地址[选填]，为空则关闭自动注册 -->
		<property name="adminAddresses" value="http://192.168.0.243:8080" />
```

调度中心也是能访问的
http://192.168.0.243:8080/

**Comment by ljyrains** [comment]
最新发现：
如果将adminAddresses 设置成 ip+port地址的情况下，这种错误没有发生
在adminAddresses 设置成 域名地址 的情况下，这种错误才会发生，1个小时内不定时发生好几次。。。

**Comment by Slahser** [comment]
@xuxueli issue没有解决为什么要关闭

**Comment by iceqing** [comment]
INFO 2019-12-05 17:48:39.575 [Thread-71] com.xxl.job.core.thread.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='stone-job-executor', registryValue='xxx.xxx.xxx.xxx:9999'}
java.lang.RuntimeException: Client-error:java.lang.Boolean cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:65)
        at com.sun.proxy.$Proxy56.registry(Unknown Source)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
        at java.lang.Thread.run(Thread.java:748)
