### ISSUE TITLE
com.xxl.job.core.util.XxlJobRemotingUtil - Connection reset

### ISSUE THREAD

**Issue by waveng** [xuxueli/xxl-job#2260]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?

   2.2.0
### Expected behavior

[Thread-17] com.xxl.job.core.util.XxlJobRemotingUtil - Connection reset
java.net.SocketException: Connection reset
  at java.net.SocketInputStream.read(SocketInputStream.java:210)
  at java.net.SocketInputStream.read(SocketInputStream.java:141)
  at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
  at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
  at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
  at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
  at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
  at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
  at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:115)
  at com.xxl.job.core.biz.client.AdminBizClient.callback(AdminBizClient.java:37)
  at com.xxl.job.core.thread.TriggerCallbackThread.doCallback(TriggerCallbackThread.java:167)
  at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:242)
  at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:25)
  at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:112)
  at java.lang.Thread.run(Thread.java:748)

我这边执行器报这个错误，但是同一个机器上的其它服务没有报错，同一个服务器集群的其它服务也没有报这个错误

**Comment by kinggodsun** [comment]
请问有解决么，遇到相同的问题了
