### ISSUE TITLE
XXLJOB 2.2.0 xxl_job_registry  deadlock问题，出现频繁--3个节点

### ISSUE THREAD

**Issue by asdfghhong** [xuxueli/xxl-job#2282]
版本：2.2.0
环境： docker环境
次数： 频繁出现

### Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:267)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy77.update(Unknown Source)

**Comment by Mihawk-lf** [comment]
部署过程中出现的？还是运行一段时间出现的，怎么会出现死锁那。
异常时刻，是否有其他事务对改表操作那。

**Comment by nine-monsters** [comment]
> 

并发下在检查 执行器是否超时 和 注册更新执行器时就会出现死锁
