### ISSUE TITLE
任务一直处于进行中,后台狂报mongo连接超时，然后任务就一直每隔 10 秒钟执行一次。。

### ISSUE THREAD

**Issue by mousycoder** [xuxueli/xxl-job#2283]
任务一直处于进行中,后台狂报mongo连接超时，然后任务就一直每隔 10 秒钟执行一次。。

**Comment by Mihawk-lf** [comment]
呃呃呃。任务描述再清楚些撒。
本来任务是要多久执行一次，任务的重试策略是什么，超时时间怎么设置的。

**Comment by mousycoder** [comment]
一直处于这种状态，没有执行结果，超时时间 0，重试次数 0，为啥一直没有结果？
![image](https://user-images.githubusercontent.com/6722977/109739825-2dcca880-7c05-11eb-8002-77fbe59a345a.png)
[TRACEID:] 2021-03-03 09:47:35,078 ERROR [schedule-task4] c.a.b.c.ScheduleConfiguration:31 schedule task error, cause = Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=47.74.48.112:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=47.74.48.112:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=47.74.48.112:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=47.74.48.112:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
        at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:90) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2902) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2810) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2532) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:2515) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:876) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        at com.amber.backend.service.impl.PdtTreasuryServiceImpl.updateRoleTransfer(PdtTreasuryServiceImpl.java:385) ~[classes!/:1.0.0]
        at com.amber.backend.task.SchedulePdtTreasuryTask.pdtTreasuryTask(SchedulePdtTreasuryTask.java:35) ~[classes!/:1.0.0]
        at sun.reflect.GeneratedMethodAccessor448.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=47.74.48.112:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
        at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:182) ~[mongodb-driver-core-3.11.2.jar!/:?]
        at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41) ~[mongodb-driver-core-3.11.2.jar!/:?]
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:145) ~[mongodb-driver-3.11.2.jar!/:?]
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:100) ~[mongodb-driver-3.11.2.jar!/:?]
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:277) ~[mongodb-driver-3.11.2.jar!/:?]
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:181) ~[mongodb-driver-3.11.2.jar!/:?]
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143) ~[mongodb-driver-3.11.2.jar!/:?]
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92) ~[mongodb-driver-3.11.2.jar!/:?]
        at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:2793) ~[spring-data-mongodb-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
        ... 17 more
[TRACEID:] 2021-03-03 09:47:35,084 INFO [schedule-task4] c.m.d.l.SLF4JLogger:71 Cluster description not yet available. Waiting for 30000 ms before timing out


怎么样判断是 xxl-job调度的线程名是这个？我这个项目混用了 xxl-job 和 @schedule ，在做平滑任务迁移。
最终结果是有个任务不受调度中心控制，自己每隔 10 秒执行一次，调度中心停止任务了也一直执行，代码上的注解也用 @schedule 转到 @xxljob了，也从没设置过 10 秒执行一次的调度

**Comment by mousycoder** [comment]
任务中，异常要自己吃掉？还是抛出去

**Comment by Mihawk-lf** [comment]
异常，要自己吃掉。return FAIL。
调度中心和执行器是分离的。你可以仔细检查下是否有别的地儿下发调度任务。
看你的调度日志是每1s就被调度一次，这个日志是调度中心记录的。如果你停止任务，截图的调度日志还在一直打，那说明你的任务没有正确的终止。

**Comment by mousycoder** [comment]
我其中有个任务是 突然mongo连不上了，mongo就一直重试，然后这些每秒 调度一次的任务，都被阻塞了，都在运行中，此时会导致什么情况。如果我设置了超时时间以及重试几次。或者没设，会发生什么情况。会不会导致我前面说到的。这个任务一直10 秒执行一次

**Comment by Mihawk-lf** [comment]
那是你的任务阻塞的多了，又没有设置超时时间。
调度中心会把任务下发到执行器，假如现在你的执行器已经积攒了1万个任务没有正常执行，即使你把调度中心的任务暂停了。
执行器还是会继续执行这堆积在队列里的1万个任务。
所以就造成了你看的那种现象，调度中心任务已经终止，但是执行器还在执行任务

**Comment by mousycoder** [comment]
明白，谢谢了
