### ISSUE TITLE
2.3.0手动注册执行器机器地址不带网络协议时执行任务报错

### ISSUE THREAD

**Issue by EvianTian** [xuxueli/xxl-job#2291]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0

### Expected behavior
执行任务时报错，原因为机器地址缺少网络协议，机器地址为192.168.15.1，修改为http://192.168.15.1后运行成功，
官网文档中并未说明机器地址如果填写，只是有图片显示机器地址是不带网络协议的，老版本这样配置运行没有问题，升级到2.3.0后运行就会报此错误，建议此bug修复后在官网文档中增加此项配置说明

16:49:20.890 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-609193584] ERROR c.x.job.core.util.XxlJobRemotingUtil - no protocol: 192.168.15.1:9999/run
java.net.MalformedURLException: no protocol: 192.168.15.1:9999/run
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:69)
	at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)

### Other information

**Comment by Mr-zhang-99** [comment]
我也遇到这个问题了。

**Comment by HeyAlaia** [comment]
最新版本也有这个问题

**Comment by HeyAlaia** [comment]
我的问题解决了，是因为client的版本低于server的版本，注册后无法正常显示对应协议头。
临时解决方案：手动执行，指定协议头后可以正确跑任务。
最终解决方案：升级client版本对应到server上

**Comment by xuxueli** [comment]
> 我的问题解决了，是因为client的版本低于server的版本，注册后无法正常显示对应协议头。 临时解决方案：手动执行，指定协议头后可以正确跑任务。 最终解决方案：升级client版本对应到server上

建议follow改方案。
