### ISSUE TITLE
最近项目启动后部分文件流异常

### ISSUE THREAD

**Issue by fanwangge** [xuxueli/xxl-job#2365]
Please answer so

xxl-job版本： 2.1.2
问题1：
 ERROR [Thread-27][FileUtil.java:88] - /log/xxl-job/globallogistics/callbacklog/xxl-job-callback-1617953777968.log (No such file or directory)
java.io.FileNotFoundException: /log/xxl-job/globallogistics/callbacklog/xxl-job-callback-1617953777968.log (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_221]
	at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_221]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_221]
	at com.xxl.job.core.util.FileUtil.readFileContent(FileUtil.java:84) [xxl-job-core-2.1.2.jar!/:?]
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:237) [xxl-job-core-2.1.2.jar!/:?]
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24) [xxl-job-core-2.1.2.jar!/:?]
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111) [xxl-job-core-2.1.2.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

问题2：
 ERROR [Thread-24][TriggerCallbackThread.java:114] - java.io.EOFException: readObject: unexpected end of file
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: readObject: unexpected end of file
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52) ~[xxl-rpc-core-1.5.0.jar!/:?]
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238) ~[xxl-job-core-2.1.2.jar!/:?]
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24) ~[xxl-job-core-2.1.2.jar!/:?]
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111) [xxl-job-core-2.1.2.jar!/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.io.EOFException: readObject: unexpected end of file
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2147) ~[hessian-4.0.63.jar!/:3.1.0]
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49) ~[xxl-rpc-core-1.5.0.jar!/:?]

**Comment by decren** [comment]
是否日志文件共享，被其他实例删除了？

**Comment by keenancy** [comment]
请问找到方法了吗？我的是磁盘满了，我清除了所有callbacklog文件，数据库的log也删除了。但是还是报这个问题
