### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by JackESong** [xuxueli/xxl-job#2394]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Actual behavior
handler:com.xxl.job.core.handler.impl.MethodJobHandler@24c1b2d2[class com.a.oa.jobhandler.BackJob#BackJobHandler]
Exception in thread "xxl-rpc, EmbedServer bizThreadPool-1140824506" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)2021-04-23 18:30:33.394 [com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler][nioEventLoopGroup-3-8] [] [ERROR]  : >>>>>>>>>>> xxl-job provider netty_http server caught exception
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:162)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:138)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
### Other information

**Comment by JackESong** [comment]
定位 报错jobThread类
// just execute
executeResult = handler.execute(triggerParam.getExecutorParams());

**Comment by JackESong** [comment]
应该是任务里开了太多线程导致，关闭了

**Comment by lwl888** [comment]
咋关闭，这不是XXL-JOB的问题吗？跟任务有啥关系

**Comment by JackESong** [comment]
您好！您的邮件已收到！   顺祝            商祺！
