### ISSUE TITLE
com.xxl.rpc.util.XxlRpcException: io.netty.channel.ConnectTimeoutException: connection timed out

### ISSUE THREAD

**Issue by zoucaifeng** [xuxueli/xxl-job#2410]
xxl-job版本是2.1.2
k8s中部署了xxl-job，执行器也是部署在k8s中，问题如下
1手动执行，执行成功，无异常
2定时一分钟一次就会出现失败，报错如下：其中调度机器是一个不存在的k8s的pod ip
后面调整超时时间为20，重试次数为2，每两分钟执行一次，发现定时执行的第一次失败，第一次重试成功，成功的那一次调度机器是正确的，失败的那一次调度机器永远固定是10.42.2.93

任务触发类型：Cron触发
调度机器：10.42.2.93
执行器-注册方式：自动注册
执行器-地址列表：[10.42.6.103:9999]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：10.42.6.103:9999
code：500
msg：com.xxl.rpc.util.XxlRpcException: io.netty.channel.ConnectTimeoutException: connection timed out: /10.42.6.103:9999 at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:250) at com.sun.proxy.$Proxy89.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at

**Comment by zoucaifeng** [comment]
最新发现重新建了一个数据库，名称为xxl_job_dev就可以正常运行了，但是删除xxl_job数据库重新建了xxl_job之后发现还是一样的问题，重试的那次才能成功，定点触发的那一次就执行失败

**Comment by lpc001** [comment]
也碰到了这个问题，请问解决了吗

**Comment by zoucaifeng** [comment]
我重新建了一个数据库，名称变成另外一个就可以了，叫一样的就不行，或者数据库版本换一个也可以



发自我的iPhone


------------------ Original ------------------
From: lpc001 ***@***.***&gt;
Date: Mon,Jul 5,2021 6:25 PM
To: xuxueli/xxl-job ***@***.***&gt;
Cc: zoucaifeng ***@***.***&gt;, Manual ***@***.***&gt;
Subject: Re: [xuxueli/xxl-job] com.xxl.rpc.util.XxlRpcException: io.netty.channel.ConnectTimeoutException: connection timed out (#2410)





 
也碰到了这个问题，请问解决了吗
