### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.util.List

### ISSUE THREAD

**Issue by sscjer** [xuxueli/xxl-job#2438]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
调度中心的版本：2.1.2
任务执行器的版本：2.3.0
### Expected behavior
运行的时候正常，但执行器控制台一直报错ClassCastException
### Actual behavior

java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.util.List (java.lang.Integer and java.util.List are in module java.base of loader 'bootstrap')
	at com.xxl.job.core.thread.TriggerCallbackThread.retryFailCallbackFile(TriggerCallbackThread.java:238) ~[xxl-job-core-2.1.2.jar:na]
	at com.xxl.job.core.thread.TriggerCallbackThread.access$400(TriggerCallbackThread.java:24) ~[xxl-job-core-2.1.2.jar:na]
	at com.xxl.job.core.thread.TriggerCallbackThread$2.run(TriggerCallbackThread.java:111) ~[xxl-job-core-2.1.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by qingfengtaizi** [comment]
我也这样报了，啥问题

**Comment by xuxueli** [comment]
建议版本一致
