### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by cloudyunfan** [xuxueli/xxl-job#2463]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.1-SNAPSHOT

executor always throw exception 
EmbedServer$EmbedHttpServerHandler : >>>>>>>>>>> xxl-job provider netty_http server caught exception
2021-06-09 21:16:47 
2021-06-09 21:16:47 java.io.IOException: Connection reset by peer
2021-06-09 21:16:47  at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_281]
2021-06-09 21:16:47  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378) ~[?:1.8.0_281]
2021-06-09 21:16:47  at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-buffer-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134) ~[netty-buffer-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.55.Final.jar!/:4.1.55.Final]
2021-06-09 21:16:47  at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]

**Comment by cloudyunfan** [comment]
we should set ReadTimeoutHandler in a class named IdleStateHandler in netty to keep TCP connection alive

**Comment by cloudyunfan** [comment]
The main reason is netty can not deal RST package from the route.

**Comment by ConnorLH** [comment]
got the same issue. version 2.2.0 . anybody know which version fix this?

**Comment by xuxueli** [comment]
建议升级新版本
