### ISSUE TITLE
xxl-job-admin 自动死掉

### ISSUE THREAD

**Issue by haifeng-numOne** [xuxueli/xxl-job#2466]
2021-06-15 00:04:35,020 ERROR [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-564004606] c.x.j.a.core.trigger.XxlJobTrigger [XxlJobTrigger.java : 198] >>>>>>>>>>> xxl-job trigger error, please check if the executor[137.12.7.221:9999] is running.
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1623686675016, request:XxlRpcRequest{requestId='1e7bb88b-c045-454b-8c03-a5ee7b84b37f', createMillisTime=1623686670016, accessToken='y2z0b1e2b0i9d1d2icn1gfv161xyxzlb1j2o3b', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=2987, executorHandler='txMessageJobHandler', executorParams='null', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=1453897, logDateTim=1623686670011, glueType='BEAN', glueSource='null', glueUpdatetime=1623654049000, broadcastIndex=0, broadcastTotal=1}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
	at com.sun.proxy.$Proxy81.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

<parent>
	<groupId>com.xuxueli</groupId>
        <artifactId>xxl-job</artifactId>
	<version>2.0.2</version>
</parent>

**Comment by Shawyeok** [comment]
老兄，`issue`不是即时通讯，得到反馈往往需要较长的时间，光这点信息不够呀。

比如问题当时`admin >> executor`的网络有没有问题？另外有没有检查当时`executor`和`admin`服务状态？

**Comment by haifeng-numOne** [comment]
admin 总是宕掉但是 我重现部署安装后 现在 不死掉啦！但是没有看到任何报错信息（在admin自动死掉时）
