### ISSUE TITLE
从2.1.2升级到2.3.0后报Connection reset by peer

### ISSUE THREAD

**Issue by zengxa** [xuxueli/xxl-job#2474]
使用的版本是2.3.0.用2.1.2时是正常的。

报错信息
 [ERROR] [nioEventLoopGroup-8-6] com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler - >>>>>>>>>>> xxl-job provider netty_http server caught exception
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wome789** [comment]
同问 2.3.0没有解决这个问题。我是admin部署在doker中，业务是部署在同台服务器里边 但是没有在docker里边。 并没有使用slb

**Comment by xcw931924821** [comment]
同样的问题，最后业务测一直在报这个错误，是端口关闭吗。
