### ISSUE TITLE
我使用2.20版本的xxl-job, 在jar方式下启动, 不明原因的造成程序退出了. 麻烦您看看是什么原因造成的.谢谢

### ISSUE THREAD

**Issue by onestudy** [xuxueli/xxl-job#2496]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.2.0
### Other information
我使用2.20版本的xxl-job, 在jar方式下启动, 不明原因的造成程序退出了. 麻烦您看看是什么原因造成的.谢谢

11:27:00.018 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-1354052792] ERROR c.x.job.core.util.XxlJobRemotingUtil - 拒绝连接 (Connection refused)
java.net.ConnectException: 拒绝连接 (Connection refused)
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:606)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
    at sun.net.www.http.HttpClient.New(HttpClient.java:339)
    at sun.net.www.http.HttpClient.New(HttpClient.java:357)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
    at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:95)
    at com.xxl.job.core.biz.client.ExecutorBizClient.run(ExecutorBizClient.java:43)
    at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:211)
    at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:164)
    at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:89)
    at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
11:28:27.902 logback [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
11:28:28.000 logback [xxl-job, admin JobScheduleHelper#scheduleThread] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper#scheduleThread stop
11:28:29.000 logback [xxl-job, admin JobScheduleHelper#ringThread] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper#ringThread stop
11:28:29.902 logback [SpringContextShutdownHook] INFO  c.x.j.a.c.thread.JobScheduleHelper - >>>>>>>>>>> xxl-job, JobScheduleHelper stop
11:28:29.903 logback [xxl-job, admin JobLogReportHelper] INFO  c.x.j.a.c.thread.JobLogReportHelper - >>>>>>>>>>> xxl-job, job log report thread stop
11:28:29.904 logback [SpringContextShutdownHook] INFO  c.x.j.a.c.t.JobTriggerPoolHelper - >>>>>>>>> xxl-job trigger thread pool shutdown success.
11:28:29.906 logback [xxl-job, admin JobLosedMonitorHelper] INFO  c.x.j.a.c.t.JobLosedMonitorHelper - >>>>>>>>>>> xxl-job, JobLosedMonitorHelper stop
11:28:29.907 logback [xxl-job, admin JobFailMonitorHelper] INFO  c.x.j.a.c.t.JobFailMonitorHelper - >>>>>>>>>>> xxl-job, job fail monitor thread stop
11:28:29.908 logback [xxl-job, admin JobRegistryMonitorHelper] INFO  c.x.j.a.c.t.JobRegistryMonitorHelper - >>>>>>>>>>> xxl-job, job registry monitor thread stop
11:28:29.910 logback [SpringContextShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP - Shutdown initiated...
11:28:29.923 logback [SpringContextShutdownHook] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP - Shutdown completed.

**Comment by konghao1** [comment]
你好， 问下您这个问题解决了吗？

**Comment by xuxueli** [comment]
无法复现，需要提供进一步日志
