### ISSUE TITLE
2.3.0 sql 错误找不到 xxl_job.XXL_JOB_QRTZ_TRIGGER_LOG

### ISSUE THREAD

**Issue by maodua** [xuxueli/xxl-job#2498]
Please answer some questions before submitting your issue. Thanks!

### 我使用的是2.3.0版本
使用docker images 跑起来以后，进入web 页面 《任务管理》页面，程序报错提示没有找到
```
 Table 'xxl_job.XXL_JOB_QRTZ_TRIGGER_LOG' doesn't exist
```
sql 从此链接拿到 https://github.com/xuxueli/xxl-job/blob/2.3.0/doc/db/tables_xxl_job.sql
![image](https://user-images.githubusercontent.com/35319954/124877163-69391280-dffd-11eb-9bc9-65b351e2bdfd.png)

**Comment by flysoeasy** [comment]
打开【任务管理】菜单，报：
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.xxl.job.admin.core.route.ExecutorRouteStrategyEnum
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

**Comment by xuxueli** [comment]
需要参考文档初始化数据库表
