### ISSUE TITLE
执行器启动失败

### ISSUE THREAD

**Issue by BianChangcai** [xuxueli/xxl-job#2532]
Exception in thread "xxl-job, executor ExecutorRegistryThread" java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.getByte([BI)B
 at io.netty.util.AsciiString.byteAt(AsciiString.java:331)
 at io.netty.util.AsciiString.charAt(AsciiString.java:422)
 at io.netty.handler.codec.http.HttpHeaders.validateHeaderName(HttpHeaders.java:1162)
 at io.netty.handler.codec.http.DefaultHttpHeaders.validateHeaderName0(DefaultHttpHeaders.java:54)
 at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:203)
 at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:104)
 at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
 at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
 at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
 at com.sun.proxy.$Proxy225.registry(Unknown Source)
 at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
 at java.lang.Thread.run(Thread.java:748)

**Comment by yuxiao97** [comment]
NoSuchMethodError基本说明是版本不匹配吧，检查下xxl客户端版本和xxl服务端是否匹配。
