### ISSUE TITLE
docker 部署报错 急！！！

### ISSUE THREAD

**Issue by ysq5202121** [xuxueli/xxl-job#2544]
版本：2.3.0
客户机：windows10
docker: windows10 docker
![image](https://user-images.githubusercontent.com/8586973/128444456-763fd526-2777-4253-8547-abc91f7e4dee.png)
mysql:docker版本 8.1，已经初始化数据库，
![image](https://user-images.githubusercontent.com/8586973/128444182-092f9a41-a6b3-4605-9999-227e0f2a2509.png)

使用命令:
docker run -e PARAMS="--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=zhaoolee --spring.datasource.password=eelooahzpw --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" -p 8080:8080 -v /tmp:/data/applogs --name xxl-job-admin  -d xuxueli/xxl-job-admin:2.3.0
其他错误信息：
登录报错:
![image](https://user-images.githubusercontent.com/8586973/128444058-d853668f-6496-4bf8-a7be-df4ba3aafb68.png)
服务的错误：
Caused by: java.net.ConnectException: Connection refused (Connection refused)

at java.net.PlainSocketImpl.socketConnect(Native Method)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:607)

at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)

at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)

... 41 common frames omitted

09:54:30.970 logback [xxl-job, admin JobScheduleHelper#scheduleThread] INFO com.zaxxer.hikari.HikariDataSource - HikariCP - Starting...

09:54:30.972 logback [xxl-job, admin JobFailMonitorHelper] ERROR c.x.j.a.c.t.JobFailMonitorHelper - >>>>>>>>>>> xxl-job, job fail monitor thread error:{}

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:96)

at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)

at com.sun.proxy.$Proxy70.selectList(Unknown Source)

at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:224)

at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)

at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)

at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152)

at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85)

at com.sun.proxy.$Proxy71.findFailJobLogIds(Unknown Source)

at com.xxl.job.admin.core.thread.JobFailMonitorHelper$1.run(JobFailMonitorHelper.java:41)

at java.lang.Thread.run(Thread.java:748)

Caused by: org.apache.ibatis.exceptions.PersistenceException:

### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)

at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)

at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)

... 9 common frames omitted

Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)

at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)

at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)

at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:337)

at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:86)

at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)

at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)

at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)

at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)

at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:89)

at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)

... 15 common frames omitted

Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)

at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903)

at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)

at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)

at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)

at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)

at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)

at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)

at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)

at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)

at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)

at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)

at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)

at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)

at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)

at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)

... 25 common frames omitted

Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

at sun.reflect.GeneratedConstructorAccessor38.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)

at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)

at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)

at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)

at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)

at com.mysql.cj.NativeSession.connect(NativeSession.java:144)

at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847)

... 39 common frames omitted

Caused by: java.net.ConnectException: Connection refused (Connection refused)

at java.net.PlainSocketImpl.socketConnect(Native Method)

at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

at java.net.Socket.connect(Socket.java:607)

at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)

at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)

... 41 common frames omitted
好像是数据库连接不上，但是不知道为什么老是连接不上

**Comment by ysq5202121** [comment]
完犊子了，没人知道吗

**Comment by XiaoZiShan** [comment]
默认连接本机mysql,  jdbc:mysql://127.0.0.1:3306/xxl_job , 如果本机没有mysql 确实会这样, 如果需要修改为其他 mysql 地址,  加 -e PARAMS l参数即可, mysql版本官方推荐 5.7 !

**Comment by chenguofeng** [comment]
127.0.0.1连的是docker的mysql  连你本机的ip或者是其它主机的db

**Comment by XiaoZiShan** [comment]
@ysq5202121  解决了, 可以把 issue 关闭了

**Comment by duskxiaohefen** [comment]
@XiaoZiShan 你好，你怎么解决的？我用的2.3.0版本的docker镜像部署在k8s中,连接k8s集群外部地址，无法连接到数据库。也使用了-e PARAMS参数指定了外部mysql的地址以及账号密码。

**Comment by XiaoZiShan** [comment]
> 
你先学会有礼貌好伐~

**Comment by duskxiaohefen** [comment]
@XiaoZiShan 你好，虽然你吊炸天了，不想回答我，但是根据你的回答，确实不能解决问题，最终的排查是因为docker镜像每次都是使用的镜像内部的application文件，无法使用自定义。

**Comment by XiaoZiShan** [comment]
> @XiaoZiShan 你好，虽然你吊炸天了，不想回答我，但是根据你的回答，确实不能解决问题，最终的排查是因为docker镜像每次都是使用的镜像内部的application文件，无法使用自定义。

管我屁事, 你谁啊~

**Comment by XiaoZiShan** [comment]
我把回复全部删除了, 我没有义务帮助任何人.

**Comment by ysq5202121** [comment]
@XiaoZiShan  虽然我已经不在使用这个东西，不过随手能够帮助别人何乐而不为呢

**Comment by cuishao23** [comment]
解决了吗，我也遇到了同样的问题

**Comment by XiaoZiShan** [comment]
我没有义务! 因为我没有权利!

**Comment by ysq5202121** [comment]
@xiaoxiong05  感谢
