### ISSUE TITLE
遇到类似情况：执行成功但执行结果失败

### ISSUE THREAD

**Issue by tyebu** [xuxueli/xxl-job#2584]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
版本号是2.3.0

### Actual behavior
使用的是GLUE模式（shell），执行器使用的是手动注册的
超时时间设置的120
查看执行日志发现如下错误：
[com.xxl.job.core.util.ScriptUtil#execToFile]-[112]-[Thread-7] java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:328)
	at java.base/java.lang.ProcessImpl.waitFor(ProcessImpl.java:495)
	at com.xxl.job.core.util.ScriptUtil.execToFile(ScriptUtil.java:104)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:81)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)

2021-09-06 10:54:39 [com.xxl.job.core.thread.JobThread#run]-[176]-[Thread-7] 
----------- xxl-job job execute end(finish) -----------
----------- Result: handleCode=500, handleMsg = script exit value(-1) is failed
2021-09-06 10:54:39 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[197]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

目前还没有对xxl-job做二次开发，执行器是自己写的
这是找不到回调地址导致的吗？

**Comment by ycy1991** [comment]
ScriptJobHandler.execute(ScriptJobHandler.java:81) 明显告诉你是脚本执行错误了

**Comment by ycy1991** [comment]
ScriptJobHandler.execute(ScriptJobHandler.java:81) 明显告诉你是脚本执行错误了

**Comment by xuxueli** [comment]
建议结合日志排查
