### ISSUE TITLE
在docker中使用xxl-job:2.0.1executor执行任务时报错No Such File or directory

### ISSUE THREAD

**Issue by luonianxin** [xuxueli/xxl-job#2602]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.0.1
### Expected behavior
在admin控制后台手动执行任务时，执行器日志输出正常，页面也能看到日志输出
### Actual behavior
2021-09-16 20:03:33.569 - [] - [Thread-77] ERROR com.xxl.job.core.log.XxlJobFileAppender.appendLog(106) - No such file or directory
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
        at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
        at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:124)
2021-09-16 20:03:33.570 - [] - [Thread-77] ERROR com.xxl.job.core.log.XxlJobFileAppender.appendLog(106) - No such file or directory
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
        at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
        at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
        at cn.hsa.xxljobexecutor.jobhandler.LongCostJobHandler.execute(LongCostJobHandler.java:42)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
2021-09-16 20:03:33.609 - [] - [Thread-77] ERROR com.xxl.job.core.log.XxlJobFileAppender.appendLog(106) - No such file or directory
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
        at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
        at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
        at cn.hsa.xxljobexecutor.jobhandler.LongCostJobHandler.execute(LongCostJobHandler.java:49)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
2021-09-16 20:03:33.638 - [] - [Thread-77] ERROR com.xxl.job.core.log.XxlJobFileAppender.appendLog(106) - No such file or directory
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
        at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
        at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
        at cn.hsa.xxljobexecutor.jobhandler.LongCostJobHandler.execute(LongCostJobHandler.java:64)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
2021-09-16 20:03:33.639 - [] - [Thread-77] ERROR com.xxl.job.core.log.XxlJobFileAppender.appendLog(106) - No such file or directory
java.io.IOException: No such file or directory

### Steps to reproduce the behavior
这是我的docker-compose文件配置

version: '3'
services:
# 定时任务后台管理
  xxl-job-executor:
    image: image-xxl-job-executor:1.0
    container_name: cont-xxl-job-executor
    ports:
      - "8901:8901"
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - spring.datasource.url=jdbc:mysql://xxxxxxx:3306/xxl-job?Unicode=true&characterEncoding=UTF-8
      - spring.datasource.username=root
      - spring.datasource.password=pasword
    networks:
      - custom_net
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/log/:/logs/

### Other information
是在手动点击启动任务时报的错
![image](https://user-images.githubusercontent.com/40255650/133610254-f65beca2-2a09-489a-9c72-f703060cbf95.png)

**Comment by luonianxin** [comment]
- /app/log/:/logs/
#我把配置文件中的以下配置改为了docker-compose文件中指定挂载的 `/logs/xxl-job-executor`，并在物理机器对应的目录/app/log中创建了`xxl-job-executor` 后问题解决，多看官方文档
xxl.job.executor.logpath=/logs/xxl-job-executor

这里贴上官方配置中的一段
`### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler`
