### ISSUE TITLE
docker部署，执行任务失败

### ISSUE THREAD

**Issue by jiangzhaoyong** [xuxueli/xxl-job#2687]
我是用docker部署的，执行器和admin在同一网络，端口也是开放了的
调用执行器执行任务后报错：
`2021-11-26 11:12:57 [nioEventLoopGroup-6-1] ERROR c.x.j.c.s.EmbedServer$EmbedHttpServerHandler - >>>>>>>>>>> xxl-job provider netty_http server caught exception
java.lang.NullPointerException: null
	at com.yomahub.tlog.spring.TLogSpringAware.getBean(TLogSpringAware.java:41)
	at com.yomahub.tlog.spring.TLogSpringAware.getProperty(TLogSpringAware.java:54)
	at com.yomahub.tlog.xxljob.enhance.XxlJobBytesEnhance.enhance(XxlJobBytesEnhance.java:14)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.channelRead0(EmbedServer.java:138)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)`

调度日志：
`任务触发类型：手动触发
调度机器：172.30.0.80
执行器-注册方式：自动注册
执行器-地址列表：[http://172.30.0.70:9102/]
路由策略：第一个
阻塞处理策略：单机串行
任务超时时间：0
失败重试次数：0

>>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：http://172.30.0.70:9102/
code：500
msg：xxl-rpc remoting error(Unexpected end of file from server), for url : http://172.30.0.70:9102/run`

**Comment by biuAries** [comment]
你好 怎么解决的
