### ISSUE TITLE
调度成功，执行结果失败，但是我的服务后台并没有程序的报错日志，请问下什么原因呢

### ISSUE THREAD

**Issue by zeng13445** [xuxueli/xxl-job#2696]
### xxl-job页面报错的执行日志：
2021-12-04 10:48:00 [com.xxl.job.core.thread.JobThread#run]-[183]-[Thread-2225] 
----------- JobThread Exception:java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
Caused by: java.lang.StackOverflowError
	at java.util.Collections$UnmodifiableMap.entrySet(Collections.java:1481)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.LinkedHashMap.(LinkedHashMap.java:384)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TracingFeignClient$RequestWrapper.header(TracingFeignClient.java:155)
	at brave.http.HttpClientRequest$1.put(HttpClientRequest.java:34)
	at brave.http.HttpClientRequest$1.put(HttpClientRequest.java:28)
	at brave.propagation.B3Propagation$Format$1.inject(B3Propagation.java:46)
	at brave.internal.propagation.InjectorFactory$RemoteInjector.inject(InjectorFactory.java:282)
	at brave.http.HttpClientHandler.handleSend(HttpClientHandler.java:146)
	at brave.http.HttpClientHandler.handleSend(HttpClientHandler.java:120)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TracingFeignClient.execute(TracingFeignClient.java:74)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.LazyTracingFeignClient.execute(LazyTracingFeignClient.java:60)
	at org.springframework.cloud.sleuth.instrument.web.client.feign.TracingFeignClient.execute(TracingFeignClient.java:81)
----------- xxl-job job execute end(error) -----------
2021-12-04 10:48:00 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[191]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

### Which version of XXL-JOB do you using?
version 2.2.0

### Expected behavior
xxl-job定时器调用我服务A，A服务需要通过Feign调用B服务

### Actual behavior
在调用B服务时xxl-job报错，错误在上面。但我自己的服务A和B后台并没有任何错误日志输出。

### Steps to reproduce the behavior
我重启A服务后，整个流程又正常了，但是跑了几天后，xxl-job又开始报错了，又得重启A服务才能正常。

### Other information

**Comment by songhanlin** [comment]
你们的服务上有zipkin吗?

**Comment by zeng13445** [comment]
> 你们的服务上有zipkin吗?

目前没有

**Comment by Bosencn** [comment]
我也出现同样的问题，请问你的是怎么解决的？

**Comment by turySun** [comment]
这个问题，请问 怎么解决的。

**Comment by xuxueli** [comment]
日志看异常为业务代码，需要结合日志定位分析
