### ISSUE TITLE
java.lang.Long cannot be cast to com.xxl.rpc.remoting.net.params.XxlRpcResponse

### ISSUE THREAD

**Issue by zhangys529** [xuxueli/xxl-job#2800]
springboot和springcloud升级之后出现该报错，xxl-job-core是2.1.0，springboot之前是2.2.7.RELEASE没有问题，升级到2.6.3之后出现问题，无法正常注册，把执行器从自动注册改成手动录入之后仍然报错，但是可以正常执行任务，任务日志则一直显示执行中
java.lang.ClassCastException: java.lang.Long cannot be cast to com.xxl.rpc.remoting.net.params.XxlRpcResponse
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:44)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)

**Comment by Szt-1** [comment]
大佬 怎么解决的

**Comment by zhangys529** [comment]
回退到老版本了，2.1.0



发自我的iPhone


------------------ Original ------------------
From: Szt-1 ***@***.***&gt;
Date: Wed,May 25,2022 10:37 AM
To: xuxueli/xxl-job ***@***.***&gt;
Cc: zhangys529 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [xuxueli/xxl-job] java.lang.Long cannot be cast tocom.xxl.rpc.remoting.net.params.XxlRpcResponse (Issue #2800)

**Comment by xcw931924821** [comment]
有遇到心跳连接偶发性的连接超时问题吗，版本2.3.1
