### ISSUE TITLE
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 33 path $.content

### ISSUE THREAD

**Issue by kevin241123** [xuxueli/xxl-job#2829]
### Which version of XXL-JOB do you using?
Powered by XXL-JOB 2.3.0
### Expected behavior
项目启动后每间隔几秒就报如下错误
2022-04-16 19:11:14.820 ERROR 1500 --- [rRegistryThread] c.xxl.job.core.util.XxlJobRemotingUtil   : xxl-rpc remoting (url=http://192.168.31.71:7009/xxl-job-admin/api/registry) response content invalid({"code":200,"msg":"","content":{}}).

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 33 path $.content
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.xxl.job.core.util.GsonTool.fromJson(GsonTool.java:52)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:131)
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:42)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 33 path $.content
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 8 common frames omitted

**Comment by xuxueli** [comment]
你好，推测双端版本不一致，建议检查一下。
问题无法发现，需要提供复现操作步骤。

**Comment by 308207109** [comment]
XXL-JOB  启动  一直报  ` xxl-job remoting (url=http://127.0.0.1:7009/xxl-job-admin/api/callback) response content invalid({"code":200,"msg":"","content":{}}).

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 33 path $.content`

**Comment by dybeq0660** [comment]
我也遇到了， 执行器其实已经注册上去了，注册机也响应了ReturnT.SUCCESS 
但是序列化出了问题，正常的应该是{"code":200,"msg":null,"content":null}  但是被序列化成{"code":200,"msg":"","content":{}}
导致反序列化时content出了问题，  因为content在注册时是String类型

我的项目会出现这个原因是  框架在序列化过程动了手脚

我的解决方法是不返回ReturnT.SUCCESS   自己new一个ReturnT 给content塞一条message即可
