### ISSUE TITLE
xxl admin 运行几天后 登录界面进不去 一直302重定向

### ISSUE THREAD

**Issue by bossjie** [xuxueli/xxl-job#2846]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
到正常登陆页面
### Actual behavior
不断重定向
### Other information
尝试用chrome纯净模式 仍然无果
![image](https://user-images.githubusercontent.com/8426828/167085098-5b5762a6-685f-4372-bec0-a104c86adead.png)

相关log  看起来是freemarker部分的问题 但我并没有动这些code
`
2022-05-06 07:18:34,242 ERROR [http-nio-8080-exec-9] o.a.c.c.C.[.[.[.[dispatcherServlet] [DirectJDKLog.java : 175] Servlet.service() for servlet [dispatcherServlet] in context with path [/xxl-job-admin] threw exception [Request processing failed; nested exception is org.springframework.context.ApplicationContextException: Failed to load [login.ftl]; nested exception is java.io.IOException: There was an error loading the template on an earlier attempt; see cause exception.] with root cause
java.util.zip.ZipException: invalid stored block lengths
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.read1(BufferedReader.java:210)
        at java.io.BufferedReader.read(BufferedReader.java:286)
        at freemarker.template.Template$LineTableBuilder.read(Template.java:863)
        at freemarker.core.SimpleCharStream.FillBuff(SimpleCharStream.java:116)
        at freemarker.core.SimpleCharStream.readChar(SimpleCharStream.java:198)
        at freemarker.core.SimpleCharStream.BeginToken(SimpleCharStream.java:138)
        at freemarker.core.FMParserTokenManager.getNextToken(FMParserTokenManager.java:8124)
        at freemarker.core.FMParser.jj_scan_token(FMParser.java:5989)
        at freemarker.core.FMParser.jj_3_17(FMParser.java:5091)
        at freemarker.core.FMParser.jj_2_17(FMParser.java:4809)
        at freemarker.core.FMParser.Root(FMParser.java:4660)
        at freemarker.template.Template.<init>(Template.java:252)
        at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:548)
        at freemarker.cache.TemplateCache.getTemplateInternal(TemplateCache.java:439)
        at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:292)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:750)
`

**Comment by xuxueli** [comment]
无法复现
