### ISSUE TITLE
java.lang.IllegalStateException: unknown code for readObject at 0x3c (<)

### ISSUE THREAD

**Issue by pengcao** [xuxueli/xxl-job#288]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v1.9.1
### Expected behavior
xxl-job-executor-sample-spring正常运行
### Actual behavior
部署xxl-job-executor-sample-spring
### Steps to reproduce the behavior
xxl-job-admin部署成功
### Other information
配置：xxl.job.admin.addresses=http://localhost:8080/admin
错误提示：
java.lang.IllegalStateException: unknown code for readObject at 0x3c (<)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:33)
	at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:37)
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
	at com.sun.proxy.$Proxy9.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x3c (<)
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:31)

**Comment by xuxueli** [comment]
你好，感谢反馈！
可以排查下回调地址是否配置正确，对应的调度中心是否运行。

**Comment by xiaosazixian** [comment]
@xuxueli 我的回掉地址一直都是对的，为什么老是报这个错误
