### ISSUE TITLE
ERROR c.x.job.core.util.XxlJobRemotingUtil:146 - connect timed out

### ISSUE THREAD

**Issue by yihoudejintian** [xuxueli/xxl-job#2950]
这个是完整的错误信息：
2022-08-12-18-11-21:972 [] [xxl-job, executor ExecutorRegistryThread] ERROR c.x.job.core.util.XxlJobRemotingUtil:146 - connect timed out
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
	at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:94)
	at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:41)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:750)

表示连接超时，有其他参数可以配置这个超时时间吗？

**Comment by zhangzhif** [comment]
暂时没法配置 默认3秒钟

**Comment by li-congshan** [comment]
我也是这个问题，请问解决这个报错了吗？

**Comment by TinTin-DXQ** [comment]
有反馈吗？也是这个问题

**Comment by arden-yang** [comment]
这个问题有解决吗

**Comment by xuxueli** [comment]
感谢反馈，已记录

**Comment by xuxueli** [comment]
高版本已支持自定义超时时间
