### ISSUE TITLE
您好，请问您这个问题解决了吗

### ISSUE THREAD

**Issue by hao69092017** [xuxueli/xxl-job#2966]
@xuxueli 我用docker部署的，xxl-job版本是2.0.1,   4.29号下午三点还是可以成功执行的，就没去管它了，今天来看，居然发现4.29号下午五点就报错了，错误信息如下：，明晚就要上线了，突然出现这个问题，有点措手不及，大哥有空麻烦帮我优先看下，可以吗？感激不尽
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1589282787500, request:XxlRpcRequest{requestId='74e363b1-6d91-4f19-9b59-14a1406bd784', createMillisTime=1589282777433, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=8, executorHandler='dailySyncBookToDBJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=7681, logDateTim=1589282777424, glueType='BEAN', glueSource='', glueUpdatetime=1588112227000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:105) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:159) at com.sun.proxy.$Proxy78.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748)

_Originally posted by @goAhead2013 in https://github.com/xuxueli/xxl-job/issues/586#issuecomment-627285961_

**Comment by goAhead2013** [comment]
解决了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月1日(周四) 上午10:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [xuxueli/xxl-job] 您好，请问您这个问题解决了吗 (Issue #2966)




 
@xuxueli 我用docker部署的，xxl-job版本是2.0.1,   4.29号下午三点还是可以成功执行的，就没去管它了，今天来看，居然发现4.29号下午五点就报错了，错误信息如下：，明晚就要上线了，突然出现这个问题，有点措手不及，大哥有空麻烦帮我优先看下，可以吗？感激不尽
 msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1589282787500, request:XxlRpcRequest{requestId='74e363b1-6d91-4f19-9b59-14a1406bd784', createMillisTime=1589282777433, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=8, executorHandler='dailySyncBookToDBJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=7681, logDateTim=1589282777424, glueType='BEAN', glueSource='', glueUpdatetime=1588112227000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:105) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:159) at com.sun.proxy.$Proxy78.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748)
 
Originally posted by @goAhead2013 in #586 (comment)

**Comment by hao69092017** [comment]
您是怎么解决的呢 我也遇到这个问题了 非常头疼 @goAhead2013

**Comment by hao69092017** [comment]
> 解决了，谢谢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年9月1日(周四) 上午10:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: [xuxueli/xxl-job] 您好，请问您这个问题解决了吗 (Issue #2966) @xuxueli 我用docker部署的，xxl-job版本是2.0.1, 4.29号下午三点还是可以成功执行的，就没去管它了，今天来看，居然发现4.29号下午五点就报错了，错误信息如下：，明晚就要上线了，突然出现这个问题，有点措手不及，大哥有空麻烦帮我优先看下，可以吗？感激不尽 msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1589282787500, request:XxlRpcRequest{requestId='74e363b1-6d91-4f19-9b59-14a1406bd784', createMillisTime=1589282777433, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=8, executorHandler='dailySyncBookToDBJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=7681, logDateTim=1589282777424, glueType='BEAN', glueSource='', glueUpdatetime=1588112227000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:105) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:159) at com.sun.proxy.$Proxy78.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748) Originally posted by @goAhead2013 in #586 (comment) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

您好，麻烦您能给指点一下是怎么解决的吗，万分感谢

**Comment by Emiya-lhl** [comment]
> 

您好，这个问题我也遇到了，可以麻烦您抽时间提供一下解决方案吗

**Comment by Emiya-lhl** [comment]
> > 解决了，谢谢
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年9月1日(周四) 上午10:06 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: [xuxueli/xxl-job] 您好，请问您这个问题解决了吗 (Issue #2966) @xuxueli 我用docker部署的，xxl-job版本是2.0.1, 4.29号下午三点还是可以成功执行的，就没去管它了，今天来看，居然发现4.29号下午五点就报错了，错误信息如下：，明晚就要上线了，突然出现这个问题，有点措手不及，大哥有空麻烦帮我优先看下，可以吗？感激不尽 msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1589282787500, request:XxlRpcRequest{requestId='74e363b1-6d91-4f19-9b59-14a1406bd784', createMillisTime=1589282777433, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=8, executorHandler='dailySyncBookToDBJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=7681, logDateTim=1589282777424, glueType='BEAN', glueSource='', glueUpdatetime=1588112227000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:105) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:159) at com.sun.proxy.$Proxy78.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748) Originally posted by @goAhead2013 in #586 (comment) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 您好，麻烦您能给指点一下是怎么解决的吗，万分感谢

**Comment by hao69092017** [comment]
> > @hao69092017 @goAhead2013
> 
> 您好，这个问题我也遇到了，可以麻烦您抽时间提供一下解决方案吗

我也还没解决 唉，你是执行器和调度中心是分布的吗，好像单机就没这个问题

**Comment by Emiya-lhl** [comment]
> 

执行器和调度中心是同一个服务器里面起的两个单独的服务，测试环境偶尔出现，但是任务是执行成功了，正式环境就会失败。。

**Comment by goAhead2013** [comment]
你现在碰到什么问题？好久了，有点忘了，是容器化部署？？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月1日(周四) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuxueli/xxl-job] 您好，请问您这个问题解决了吗 (Issue #2966)




  
解决了，谢谢
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年9月1日(周四) 上午10:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: [xuxueli/xxl-job] 您好，请问您这个问题解决了吗 (Issue #2966) @xuxueli 我用docker部署的，xxl-job版本是2.0.1, 4.29号下午三点还是可以成功执行的，就没去管它了，今天来看，居然发现4.29号下午五点就报错了，错误信息如下：，明晚就要上线了，突然出现这个问题，有点措手不及，大哥有空麻烦帮我优先看下，可以吗？感激不尽 msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1589282787500, request:XxlRpcRequest{requestId='74e363b1-6d91-4f19-9b59-14a1406bd784', createMillisTime=1589282777433, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=8, executorHandler='dailySyncBookToDBJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=7681, logDateTim=1589282777424, glueType='BEAN', glueSource='', glueUpdatetime=1588112227000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:105) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:159) at com.sun.proxy.$Proxy78.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748) Originally posted by @goAhead2013 in #586 (comment) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
您好，麻烦您能给指点一下是怎么解决的吗，万分感谢

**Comment by xuxueli** [comment]
基本是网络问题，需要确保双端网络通畅
