### ISSUE TITLE
将xxl_job 后台表改为Oracle 数据库后，在GLUE(Shell)模式调用sh脚本报空指针 

### ISSUE THREAD

**Issue by 172151295** [xuxueli/xxl-job#2984]
报错如下
![2022-09-21_094856](https://user-images.githubusercontent.com/70830248/191396099-b6a3fddd-3755-4b05-ad33-319abd9ce5c3.png)

2022-09-21 08:41:48 [com.xxl.job.core.thread.JobThread#run]-[133]-[xxl-job, JobThread-100000020-1663720896507] 
----------- xxl-job job execute start -----------
----------- Param:null
2022-09-21 08:41:48 [com.xxl.job.core.handler.impl.ScriptJobHandler#execute]-[80]-[xxl-job, JobThread-100000020-1663720896507] ----------- script file:/data/applogs/xxl-job/jobhandler/gluesource/100000020_1663663162000.sh -----------
2022-09-21 08:41:48 [com.xxl.job.core.util.ScriptUtil#execToFile]-[112]-[xxl-job, JobThread-100000020-1663720896507] java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at com.xxl.job.core.util.ScriptUtil.execToFile(ScriptUtil.java:76)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:81)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:166)

2022-09-21 08:41:48 [com.xxl.job.core.thread.JobThread#run]-[179]-[xxl-job, JobThread-100000020-1663720896507] 
----------- xxl-job job execute end(finish) -----------
----------- Result: handleCode=500, handleMsg = script exit value(-1) is failed
2022-09-21 08:41:48 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[197]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.
在任务管理点击执行一次正常运.sh脚本 截图如下
![2022-09-21_095056](https://user-images.githubusercontent.com/70830248/191396317-552c21e8-9484-4ce4-935e-4f1e472cad43.png)

哪位大佬直达如何修改

**Comment by LockiJiang** [comment]
某些数据库默认情况下会将空字符串保存为null，执行脚本任务时EXECUTOR_PARAM为空，导致空指针异常
修改https://github.com/xuxueli/xxl-job/blob/master/xxl-job-core/src/main/java/com/xxl/job/core/util/ScriptUtil.java
![图片](https://user-images.githubusercontent.com/16129287/191403321-104ca64a-be96-4da5-ac56-b855aed4b2c1.png)
https://github.com/WeiYe-Jing/datax-web/pull/439

**Comment by xuxueli** [comment]
可以参考 https://github.com/xuxueli/xxl-job/issues/154
