### ISSUE TITLE
关于2.3版本，任务执行完成后，InvocationTargetException

### ISSUE THREAD

**Issue by Bosencn** [xuxueli/xxl-job#2991]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.0
### Expected behavior
基于springboot的项目
任务执行完成后，返回的任务执行结果为成功
### Actual behavior
任务执行完成后，返回的任务执行结果为失败
### Steps to reproduce the behavior
1、简单的打印任务，在日志中输出日期
2、日期输出
3、任务执行结果为失败
### Other information
有网友说因为没有添加@Component导致异常，我们的项目已正确添加@component注解。

2022-09-25 18:17:33 [com.xxl.job.core.thread.JobThread#run]-[201]-[Thread-71] 
----------- JobThread Exception:java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:163)
Caused by: java.lang.NullPointerException
	at org.jeecg.common.util.SpringContextUtils.getHttpServletRequest(SpringContextUtils.java:40)
	at org.jeecg.common.aspect.AutoLogAspect.saveSysLog(AutoLogAspect.java:96)
	at org.jeecg.common.aspect.AutoLogAspect.around(AutoLogAspect.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.jeecg.modules.quartz.job.EpMsgXxlJob$$EnhancerBySpringCGLIB$$ec568e21.quarterJobHandler()
	... 6 more

----------- xxl-job job execute end(error) -----------
2022-09-25 18:17:33 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[197]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

**Comment by Bosencn** [comment]
![image](https://user-images.githubusercontent.com/18637947/192144293-c231f978-0f58-4efe-95d7-067d971b11c6.png)
我通过添加断点进入查看，发现是在自动保存日志的时候，出现控制住异常。针对这个异常，目前也没有搞懂为什么会出现，水平有限。

**Comment by Bosencn** [comment]
我找到异常原因了，是因为我启用了自动日志，在日志保存的过程中出现问题。

**Comment by xuxueli** [comment]
@Bosencn 👍
