### ISSUE TITLE
java.lang.reflect.InvocationTargetException at sun.reflect.GeneratedMethodAccessor1008.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29) at com.xxl.job.core.thread.JobThread.run(JobThread.java:152) Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by zengan** [xuxueli/xxl-job#3035]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by zengan** [comment]
非常个例
