### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by zw666** [xuxueli/xxl-job#3037]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.3.1
### Expected behavior
每日定时会有报错，无任何操作
### Other information
nioEventLoopGroup-5-5 com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler >>>>>>>>>>> xxl-job provider netty_http server caught exception
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zhipingwu** [comment]
com.xxl.job.core.server.EmbedServer.EmbedHttpServerHandler#writeResponse

**Comment by zhipingwu** [comment]
您好，查看了一下代码，这个函数的最后一句需要添加判断：
com.xxl.job.core.server.EmbedServer.EmbedHttpServerHandler#writeResponse

if (ctx.channel().isActive()) {
                ctx.writeAndFlush(response);
            }


如果您这边方便的话，我可以修改一个测试版本，到您的环境验证观察一下。

**Comment by zw666** [comment]
您好，这边不方便放测试脚本，不好意思，那你这边是否考虑迭代修复，然后升级等你们升级之后 我们用你升级版本。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuxueli/xxl-job"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月16日(星期三) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xuxueli/xxl-job] java.net.SocketException: Connection reset (Issue #3037)





 
您好，查看了一下代码，这个函数的最后一句需要添加判断：
 com.xxl.job.core.server.EmbedServer.EmbedHttpServerHandler#writeResponse
 
if (ctx.channel().isActive()) {
 ctx.writeAndFlush(response);
 }
 
如果您这边方便的话，我可以修改一个测试版本，到您的环境验证观察一下。

**Comment by chimpanlee** [comment]
这个错误现在修复了么？

**Comment by xuxueli** [comment]
建议升级
