### ISSUE TITLE
每隔两天，执行器会断开，但是执行器依旧活着

### ISSUE THREAD

**Issue by nanoixx** [xuxueli/xxl-job#3058]
ERROR org.xnio.listener - XNIO001007: A channel event listener threw an exception
java.nio.channels.ClosedSelectorException: null
	at java.base/sun.nio.ch.SelectorImpl.ensureOpen(SelectorImpl.java:80)
	at java.base/sun.nio.ch.SelectorImpl.implRegister(SelectorImpl.java:239)
	at java.base/sun.nio.ch.SelectorImpl.register(SelectorImpl.java:215)
	at java.base/java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:236)
	at java.base/java.nio.channels.SelectableChannel.register(SelectableChannel.java:260)
	at org.xnio.nio.WorkerThread.registerChannel(WorkerThread.java:731)
	at org.xnio.nio.NioTcpServer.accept(NioTcpServer.java:421)
	at org.xnio.nio.QueuedNioTcpServer2.handleReady(QueuedNioTcpServer2.java:149)
	at org.xnio.nio.QueuedNioTcpServer2.lambda$new$1(QueuedNioTcpServer2.java:58)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.NioTcpServerHandle.handleReady(NioTcpServerHandle.java:65)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
  执行器最后报错为这一段，重复报错

**Comment by ajie-dev** [comment]
解决了吗？
