### ISSUE TITLE
XXL-job 抛出异常unknown code for readObject at 0x3c (<)

### ISSUE THREAD

**Issue by 729234500** [xuxueli/xxl-job#311]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by 729234500** [comment]
以下 为配置信息
### xxl-job db  (use &amp; replace & in xml)
xxl.job.db.driverClass=com.mysql.jdbc.Driver
xxl.job.db.url=jdbc:mysql://10.3.10.75:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8
xxl.job.db.user=root
xxl.job.db.password=root

### xxl-job email
xxl.job.mail.host=smtp.qq.com
xxl.job.mail.port=25
xxl.job.mail.username=729234500@qq.com
xxl.job.mail.password=
xxl.job.mail.sendNick=《任务调度平台XXL-JOB》

### xxl-job login
xxl.job.login.username=admin
xxl.job.login.password=123456

### xxl-job, access token
xxl.job.accessToken=

### xxl-job, i18n (default empty as chinese, "en" as english)
xxl.job.i18n=

applicationContext.xml信息未做任何修改
tomcat8.0启动
抛出如下异常
java.lang.IllegalStateException: unknown code for readObject at 0x3c (<)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:33)
	at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:37)
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
	at com.sun.proxy.$Proxy9.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x3c (<)
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:31)
	... 5 more

**Comment by 729234500** [comment]
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin

### xxl-job executor address
xxl.job.executor.appname=xxl-job-executor-sample
xxl.job.executor.ip=
xxl.job.executor.port=9999

### xxl-job, access token
xxl.job.accessToken=

### xxl-job log path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
### xxl-job log retention days
xxl.job.executor.logretentiondays=-1

**Comment by 729234500** [comment]
发现问题原因 没有对回调请求做出应答 经过网上搜索把xxl-admin方法同时加载到tomcat成功

**Comment by 729234500** [comment]
把xxl-admin工程 与spring工程同时导入到tomcat下 项目就可以正常运行
