### ISSUE TITLE
使用1.9.0版本，使用tomcat部署

### ISSUE THREAD

**Issue by yh700** [xuxueli/xxl-job#3154]
点击新增执行器无响应
![image](https://user-images.githubusercontent.com/58965906/232948162-8eb9e0dd-71a4-4016-be51-c3e2817de82b.png)

查看后台出现  jobgroup.index.1.js:62 Uncaught ReferenceError: I18n is not defined
    at HTMLDocument.<anonymous> (jobgroup.index.1.js:62:13)
    at i (jquery-2.2.3.min.js:2:27151)
    at Object.fireWith [as resolveWith] (jquery-2.2.3.min.js:2:27914)
    at Function.ready (jquery-2.2.3.min.js:2:29707)
    at HTMLDocument.J (jquery-2.2.3.min.js:2:29892)
![image](https://user-images.githubusercontent.com/58965906/232948060-e93a78cb-cdcf-42f1-a0d2-c3eb60ec62b2.png)
如何解决

**Comment by xuxueli** [comment]
建议清空浏览器换错，新js变量未识别导致。
