### ISSUE TITLE
调度失败，提示java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by axxdllw** [xuxueli/xxl-job#3231]
> 版本：2.2.1

问题描述：该任务目标地址部署在A、B上，在机器A上一直执行失败，报错如下，修改url为机器B则可以正常执行，怀疑是本机器阻塞？

> 定时任务配置

![image](https://github.com/xuxueli/xxl-job/assets/49954768/a1c91bd5-34d8-45f5-bf87-5c9b59866d6a)

> 执行日志报错

2023-07-04 14:48:18 [com.ntt.scm.xxl.job.executor.service.jobhandler.SampleXxlJob#httpJobHandler]-[178]-[Thread-694123] java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.ntt.scm.xxl.job.executor.service.jobhandler.SampleXxlJob.httpJobHandler(SampleXxlJob.java:161)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:29)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)

2023-07-04 14:48:18 [com.xxl.job.core.thread.JobThread#run]-[164]-[Thread-694123] 
----------- xxl-job job execute end(finish) -----------
----------- ReturnT:ReturnT [code=500, msg=null, content=null]
2023-07-04 14:48:18 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[191]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

**Comment by axxdllw** [comment]
请求url后跟&objectLock=true参数导致以上调度失败
