### ISSUE TITLE
com.xxl.registry.client.util.json.BasicJsonReader#parseMap 收到html，导致报错

### ISSUE THREAD

**Issue by chrisjiangfeng** [xuxueli/xxl-job#3263]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by chrisjiangfeng** [comment]
java.lang.IllegalArgumentException: Cannot parse JSON
at com.xxl.registry.client.util.json.BasicJsonReader.parseMap(BasicJsonReader.java:25)
at com.xxl.registry.client.util.json.BasicJson.parseMap(BasicJson.java:35)
at com.xxl.job.core.util.XxlJobRemotingUtil.postBody(XxlJobRemotingUtil.java:128)
at com.xxl.job.core.biz.client.AdminBizClient.registry(AdminBizClient.java:41)
at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
已优化处理
