### ISSUE TITLE
c.x.job.core.log.XxlJobFileAppender - No such file or directory

### ISSUE THREAD

**Issue by hequan1994** [xuxueli/xxl-job#3332]
2023-11-04 00:03:23.629 [completable_future_pool_7] []  ERROR c.x.job.core.log.XxlJobFileAppender - No such file or directory
java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1035)
        at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:99)
        at com.xxl.job.core.context.XxlJobHelper.logDetail(XxlJobHelper.java:164)
        at com.xxl.job.core.context.XxlJobHelper.log(XxlJobHelper.java:118)
        at com.cc.rpa.job.core.HighDiveUserConsumer.processTask(XXXConsumer.java:62)
        at com.cc.rpa.job.core.HighDiveUserConsumer.processTask(XXXConsumer.java:33)
        at com.cc.rpa.job.core.BaseConsumer.lambda$run$1(XXXConsumer.java:81)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

文件找不到报错？配置的xxl.job.executor.logpath 路径是有权限的，线上每天目录下也有log文件生成，但是日志还是有很多上述报错，是由于我有些JOB使用的是分片策略吗？共用了日志文件？有大佬遇到类似问题吗？

**Comment by xiaosongshuaa** [comment]
你好,目前有解决这个问题吗,我遇到的问题和你遇到的一样

**Comment by Artanis-c** [comment]
同样遇到了上述问题

**Comment by majinhai0815** [comment]
遇到同样的问题

**Comment by leo43555483** [comment]
个人经历是log文件目录写权限问题，XxlJobHelper.log()写入日志的时候试图创建日志, 文件目录创建失败会报错，我给other加了写权限解决了这个问题

**Comment by jimmyqin** [comment]
请问如何解决？？

**Comment by Artanis-c** [comment]
升级 linux 版本，就可以解决，我这是升级了 linux 之后这个问题就好了




崔嘉庆
***@***.***
