### ISSUE TITLE
javax.annotation.Resource 升级 jakarta.annotation.Resource

### ISSUE THREAD

**Issue by glacier0315** [xuxueli/xxl-job#3395]
使用spring-boot 3 集成 xxl-job 2.4.0，在使用GLUE java 功能时出现错误：
Exception in thread "xxl-job, EmbedServer bizThreadPool-644699874" java.lang.NoClassDefFoundError: javax/annotation/Resource
	at com.xxl.job.core.glue.impl.SpringGlueFactory.injectService(SpringGlueFactory.java:45)
	at com.xxl.job.core.glue.GlueFactory.loadNewInstance(GlueFactory.java:53)
	at com.xxl.job.core.biz.impl.ExecutorBizImpl.run(ExecutorBizImpl.java:93)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.process(EmbedServer.java:193)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler.access$200(EmbedServer.java:130)
	at com.xxl.job.core.server.EmbedServer$EmbedHttpServerHandler$1.run(EmbedServer.java:158)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Resource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 9 more

经排查是：com.xxl.job.core.glue.impl.SpringGlueFactory  用的是javax.annotation.Resource，而新版spring boot的均已迁移到jakarta.annotation.Resource

建议后期版本从javax 迁移到 jakarta

**Comment by fudianchn** [comment]
+1

**Comment by MarchGe** [comment]
+1

**Comment by Crazylychee** [comment]
+1

**Comment by xuxueli** [comment]
已升级
