### ISSUE TITLE
java.lang.IllegalStateException: getOutputStream() has already been called for this response] with root cause

### ISSUE THREAD

**Issue by fxl1561068992** [xuxueli/xxl-job#3404]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
<groupId>com.xuxueli</groupId>
	<artifactId>xxl-job</artifactId>
	<version>2.4.1-SNAPSHOT</version>
	<packaging>pom</packaging>
### Expected behavior
报错信息：
![image](https://github.com/xuxueli/xxl-job/assets/69661392/bcdbdf62-feb9-4198-b5c7-6409fe7cf79a)
 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/admin] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: getOutputStream() has already been called for this response] with root cause
java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:572)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:189)
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:391)
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:304)
	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:255)
	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:181)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1406)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1150)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529
环境：
linuxjar包部署，nginx反向代理

步骤：
域名登陆admin后台，切换一次左侧栏菜单，就报错一次。

**Comment by xuxueli** [comment]
需要进一步提供复现日志
