### ISSUE TITLE
单执行器，某任务单个执行成功，但定时执行必然失败

### ISSUE THREAD

**Issue by HongyiPaulZeng** [xuxueli/xxl-job#3426]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.0

### Expected behavior
任务正常执行

### Actual behavior
单个执行成功，但定时执行必然失败

### Steps to reproduce the behavior
配置单个执行器，配置任务。

### Other information
执行器日志： 
2024-04-12 12:00:00 [com.xxl.job.core.thread.JobThread#run]-[133]-[xxl-job, JobThread-58-1712894400088] 
----------- xxl-job job execute start -----------
----------- Param:null
2024-04-12 12:00:00 [com.xxl.job.core.handler.impl.ScriptJobHandler#execute]-[80]-[Thread-204] ----------- script file:./jobhandler/gluesource/58_1712825335000.sh -----------
2024-04-12 12:00:00 [com.xxl.job.core.util.ScriptUtil#execToFile]-[112]-[Thread-204] java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at java.lang.Runtime.exec(Runtime.java:621)
	at java.lang.Runtime.exec(Runtime.java:486)
	at com.xxl.job.core.util.ScriptUtil.execToFile(ScriptUtil.java:76)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:81)
	at com.xxl.job.core.thread.JobThread$1.call(JobThread.java:146)
	at com.xxl.job.core.thread.JobThread$1.call(JobThread.java:139)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

2024-04-12 12:00:00 [com.xxl.job.core.thread.JobThread#run]-[179]-[xxl-job, JobThread-58-1712894400088] 
----------- xxl-job job execute end(finish) -----------
----------- Result: handleCode=500, handleMsg = script exit value(-1) is failed
2024-04-12 12:00:00 [com.xxl.job.core.thread.TriggerCallbackThread#callbackLog]-[197]-[xxl-job, executor TriggerCallbackThread] 
----------- xxl-job job callback finish.

**Comment by HongyiPaulZeng** [comment]
问题定位，更新描述。
目前发现，定时触发的任务会多出^M 有点莫名其妙
![8EDU6%P}@L6@`79N%WOHMPG](https://github.com/xuxueli/xxl-job/assets/108132590/1aa902af-b2ca-4f18-b7df-54a6f03c060b)

**Comment by syshenyao** [comment]
能否提供一个复现的demo，这里参数是执行器执行的时候入参

**Comment by HongyiPaulZeng** [comment]
> 能否提供一个复现的demo，这里参数是执行器执行的时候入参

复现的demo我还真不知道怎么给你。我观察了日志，执行器收到的参数TriggerParam里，其中的executorParams有时候是null，有时候是空字符串。同样的任务，在手工执行和定时执行可能会是不同情况。但同样的shell脚本在不同的任务里不一定会复现。我自己在执行器加固了一下把这个BUG处理掉。admin那边我没继续追查了。

**Comment by wondywang** [comment]
我想问下，目前该问题，已修复了吗？

**Comment by HongyiPaulZeng** [comment]
> 我想问下，目前该问题，已修复了吗？

刚看了2.5.0，还没有修复
@xuxueli

**Comment by xuxueli** [comment]
确认是不是集群部署任务，两种方式任务触发机器不同
