### ISSUE TITLE
No classes defined at reference '64'

### ISSUE THREAD

**Issue by yingwen330** [xuxueli/xxl-job#3460]
Please answer some questions before submitting your issue. Thanks!

### admin和core用的都是2.30 ,日志一直报 com.xxl.rpc.util.XxlRpcException: No classes defined at reference '64'

2024-05-22 14:41:00,024 ERROR [pool-3-thread-22] c.x.j.a.core.route.ExecutorRouter [ExecutorRouteFailover.java : 28] com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1716360060024, request:XxlRpcRequest{requestId='3ff542c8-0ce5-4b03-9749-dae6121d9df3', createMillisTime=1716360050024, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='beat', parameterTypes=[], parameters=null, version='null'}
com.xxl.rpc.util.XxlRpcException: com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1716360060024, request:XxlRpcRequest{requestId='3ff542c8-0ce5-4b03-9749-dae6121d9df3', createMillisTime=1716360050024, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='beat', parameterTypes=[], parameters=null, version='null'}
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:166)
        at com.sun.proxy.$Proxy78.beat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteFailover.route(ExecutorRouteFailover.java:26)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:130)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76)
        at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1716360060024, request:XxlRpcRequest{requestId='3ff542c8-0ce5-4b03-9749-dae6121d9df3', createMillisTime=1716360050024, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='beat', parameterTypes=[], parameters=null, version='null'}
        at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:102)
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:160)
        ... 8 common frames omitted
2024-05-22 14:41:00,032 INFO [qtp895360505-147] o.e.jetty.client.ResponseNotifier [ResponseNotifier.java : 197] Exception while notifying listener com.xxl.rpc.remoting.net.impl.jetty.client.JettyClient$1@4ae66b79
com.xxl.rpc.util.XxlRpcException: No classes defined at reference '64'
        at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
        at com.xxl.rpc.remoting.net.impl.jetty.client.JettyClient$1.onComplete(JettyClient.java:82)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:454)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:401)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:266)
        at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1426)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1268)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:156)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:117)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)

**Comment by xuxueli** [comment]
问题无法复现，需要进一步提供复现步骤。
