### ISSUE TITLE
springcloud+nacos+openfeign项目集成xxl-job后，历史废弃接口不写请求方式不行了。

### ISSUE THREAD

**Issue by lixinyucode** [xuxueli/xxl-job#3474]
集成xxljob后，我原先模块的一些废弃接口，原先都是把请求方式注释掉的，不让外界访问，集成xxljob后，这些模块都起不来了，提示我那些接口需要加@PostMapping或者@GetMapping之类的注解，我加上这些注解，确实好用，但是我不想这么做，因为他们都是废弃接口，我不想暴露给外界，请求xxljob中是什么组件提供了扫描接口请求方式的功能，我能否避免掉呢？

Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.1

### Other information

**Comment by zhipingwu** [comment]
有具体的日志吗

**Comment by lixinyucode** [comment]
2024-06-12 09:58:31,261 [main] INFO  com.zaxxer.hikari.HikariDataSource:350[NONE] - PRIMARY-192.168.88.7 - Shutdown initiated...
2024-06-12 09:58:31,539 [main] INFO  com.zaxxer.hikari.HikariDataSource:352[NONE] - PRIMARY-192.168.88.7 - Shutdown completed.
2024-06-12 09:58:31,540 [main] INFO  org.apache.catalina.core.StandardService:173[NONE] - Stopping service [Tomcat]
2024-06-12 09:58:31,560 [main] INFO  o.s.b.a.logging.ConditionEvaluationReportLogger:82[NONE] - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-06-12 09:58:31,721 [main] ERROR org.springframework.boot.SpringApplication:822[NONE] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ds.client.settlecenter.api.SettlementApi': FactoryBean threw exception on object creation
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:184)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:120)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1273)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1158)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.initJobHandlerMethodRepository(XxlJobSpringExecutor.java:95)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterSingletonsInstantiated(XxlJobSpringExecutor.java:38)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:984)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.ds.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.IllegalStateException: Method SettlementApi#sumSettlementDTO(SettlementFindRequest) not annotated with HTTP method type (ex. GET, POST)
Warnings:
- 
	at feign.Util.checkState(Util.java:136)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:115)
	at org.springframework.cloud.openfeign.support.SpringMvcContract.parseAndValidateMetadata(SpringMvcContract.java:197)
	at feign.Contract$BaseContract.parseAndValidateMetadata(Contract.java:65)
	at feign.ReflectiveFeign$ParseHandlersByName.apply(ReflectiveFeign.java:142)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:58)
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:50)
	at feign.Feign$Builder.target(Feign.java:197)
	at org.springframework.cloud.openfeign.DefaultTargeter.target(DefaultTargeter.java:30)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.loadBalance(FeignClientFactoryBean.java:398)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getTarget(FeignClientFactoryBean.java:446)
	at org.springframework.cloud.openfeign.FeignClientFactoryBean.getObject(FeignClientFactoryBean.java:421)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
	... 18 common frames omitted
2024-06-12 09:58:31,734 [Thread-6] WARN  com.alibaba.nacos.common.notify.NotifyCenter:136[NONE] - [NotifyCenter] Start destroying Publisher
2024-06-12 09:58:31,734 [Thread-1] WARN  c.alibaba.nacos.common.http.HttpClientBeanHolder:102[NONE] - [HttpClientBeanHolder] Start destroying common HttpClient
2024-06-12 09:58:31,735 [Thread-6] WARN  com.alibaba.nacos.common.notify.NotifyCenter:153[NONE] - [NotifyCenter] Destruction of the end
Disconnected from the target VM, address: '127.0.0.1:4738', transport: 'socket'

Process finished with exit code 1
@zhipingwu 这是具体的日志

**Comment by lixinyucode** [comment]
![image](https://github.com/xuxueli/xxl-job/assets/169958582/67a5e0f0-4972-4be0-a653-1448110709cc)
![image](https://github.com/xuxueli/xxl-job/assets/169958582/d286fb8d-5c77-4339-a87e-8f4bd5b80f4a)
@zhipingwu 这是我那个废弃接口，以前注掉postmapping注解都没问题的，加了xxljob后，就报错了

**Comment by xuxueli** [comment]
已处理，可升级体验
