### ISSUE TITLE
在示例@XxlJob("commandJobHandler")中运行命令报CreateProcess error=2, 系统找不到指定的文件

### ISSUE THREAD

**Issue by AkenClub** [xuxueli/xxl-job#3493]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.1，项目xxl-job-executor-samples

### Expected behavior
win10 正确运行命令

### Actual behavior
报错：
`
2024-07-02 10:10:42 [com.xxl.job.core.thread.JobThread#run]-[133]-[xxl-job, JobThread-3-1719886242914] <br>----------- xxl-job job execute start -----------<br>----------- Param:C:\Windows\system32\cmd.exe /c dir
2024-07-02 10:10:42 [com.xxl.job.executor.service.jobhandler.SampleXxlJob#commandJobHandler]-[104]-[xxl-job, JobThread-3-1719886242914] java.io.IOException: Cannot run program "C:\Windows\system32\cmd.exe /c dir": CreateProcess error=2, 系统找不到指定的文件。
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.xxl.job.executor.service.jobhandler.SampleXxlJob.commandJobHandler(SampleXxlJob.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.xxl.job.core.handler.impl.MethodJobHandler.execute(MethodJobHandler.java:31)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:166)
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件。
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 8 more
`

### Steps to reproduce the behavior
执行过程如果所示：
![image](https://github.com/xuxueli/xxl-job/assets/52781316/bb0b9976-12b9-40bc-acc4-4167490c4a43)
![image](https://github.com/xuxueli/xxl-job/assets/52781316/595704ab-b75a-4c4b-a82c-ae77403484e4)
![image](https://github.com/xuxueli/xxl-job/assets/52781316/1429452b-61e4-431e-92c1-4b0f09224ea8)

### Other information
```
// 来自示例项目：xxl-job-2.4.1\xxl-job-executor-samples\xxl-job-executor-sample-springboot\src\main\java\com\xxl\job\executor\service\jobhandler\SampleXxlJob.java
    @XxlJob("commandJobHandler")
    public void commandJobHandler() throws Exception {
        String command = XxlJobHelper.getJobParam();
        int exitValue = -1;

        BufferedReader bufferedReader = null;
        try {
            // command process
            ProcessBuilder processBuilder = new ProcessBuilder();
            processBuilder.command(command);
            processBuilder.redirectErrorStream(true);
    
            Process process = processBuilder.start();
            //Process process = Runtime.getRuntime().exec(command);
    
            BufferedInputStream bufferedInputStream = new BufferedInputStream(process.getInputStream());
            bufferedReader = new BufferedReader(new InputStreamReader(bufferedInputStream));
    
            // command log
            String line;
            while ((line = bufferedReader.readLine()) != null) {
                XxlJobHelper.log(line);
            }
    
            // command exit
            process.waitFor();
            exitValue = process.exitValue();
        } catch (Exception e) {
            XxlJobHelper.log(e);
        } finally {
            if (bufferedReader != null) {
                bufferedReader.close();
            }
        }
    
        if (exitValue == 0) {
            // default success
        } else {
            XxlJobHelper.handleFail("command exit value("+exitValue+") is failed");
        }
    
    }
```

### 修正
在使用 ProcessBuilder 执行命令时，应该将命令和参数分开提供，而不是作为一个单一的字符串？

```
@XxlJob("commandJobHandler")
    public void commandJobHandler() throws Exception {
        String command = XxlJobHelper.getJobParam();
        if (command == null || command.trim().isEmpty()) {
            XxlJobHelper.handleFail("command is empty.");
            return;
        }
    
        // 拆分命令和参数
        String[] commandArray = command.split(" ");
    
        int exitValue = -1;
    
        BufferedReader bufferedReader = null;
        try {
            // command process
            ProcessBuilder processBuilder = new ProcessBuilder();
            processBuilder.command(commandArray);
            processBuilder.redirectErrorStream(true);
```
或者改造一下
```
ProcessBuilder processBuilder = new ProcessBuilder("cmd.exe", "/c", command);
```

**Comment by xuxueli** [comment]
感谢反馈，master分支已优化
