### ISSUE TITLE
当某个job的glue_updatetime为NULL时，执行会失败

### ISSUE THREAD

**Issue by MakiseSuki** [xuxueli/xxl-job#3536]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.4.1

### Expected behavior
任务执行成功

### Actual behavior
页面提示执行成功，但查看调度日志，调度结果以及执行时间为空，调度备注显示“无”
查看日志提示空指针
```
17:10:00.041 logback [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-2092863364] ERROR c.x.j.a.c.t.JobTriggerPoolHelper - null
java.lang.NullPointerException: null
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:137)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:83)
        at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:95)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

### Steps to reproduce the behavior
通过SQL插入xxl_job_info，但不指定glue_updatetime的值
```
INSERT INTO `xxl_job_info` (`id`, `job_group`, `job_desc`, `author`, `schedule_type`, `schedule_conf`, `misfire_strategy`, `executor_route_strategy`, `executor_handler`, `executor_param`, `executor_block_strategy`, `glue_type`, `trigger_status`)
VALUES
(21, 8, '更新数据', 'makise', 'CRON', '0 0/10 * * * ?', 'DO_NOTHING', 'FIRST', 'updateData', NULL, 'DISCARD_LATER', 'BEAN', 1);
```
无论通过接口调用或者页面上手动执行，都会有问题
去查看这个任务的信息也看不出问题，当点击保存之后，glue_updatetime有了值，就正常了

**Comment by MakiseSuki** [comment]
初始化SQL中，这个字段default NULL，是否可以调整

**Comment by ypforever0719** [comment]
你完全可以自己修改表结构
alter table xxl_job_info modify glue_update_time datetime default CURRENT_TIMESTAMP not null comment 'GLUE更新时间';

> 初始化SQL中，这个字段default NULL，是否可以调整

**Comment by xuxueli** [comment]
你好，这一步 “通过SQL插入xxl_job_info，但不指定glue_updatetime的值” 时定制逻辑吗？在二次开发定制时，主动赋值即可。
