### ISSUE TITLE
xxl-job启动后自动关闭

### ISSUE THREAD

**Issue by longscoop** [xuxueli/xxl-job#358]
启动后spring容器自动关闭，另一个机器是好的
2018-04-18 20:43:17 xxl-job-admin [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping]-[localhost-startStop-1]-[registerHandler]-[362]-[INFO] Mapped URL path [/**/*.html] onto handler 'org.springframework.web.servlet.resource.ResourceHttpRequestHandler#2'
2018-04-18 20:43:17 xxl-job-admin [org.springframework.web.servlet.DispatcherServlet]-[localhost-startStop-1]-[initServletBean]-[508]-[INFO] FrameworkServlet 'springmvc': initialization completed in 827 ms
2018-04-18 20:43:36 xxl-job-admin [org.springframework.scheduling.quartz.SchedulerFactoryBean]-[Quartz Scheduler [quartzScheduler]]-[run]-[665]-[INFO] Starting Quartz Scheduler now, after delay of 20 seconds
2018-04-18 20:43:36 xxl-job-admin [org.quartz.core.QuartzScheduler]-[Quartz Scheduler [quartzScheduler]]-[start]-[547]-[INFO] Scheduler quartzScheduler_$_localhost.localdomain1524055395925 started.
2018-04-18 20:44:02 xxl-job-admin [org.springframework.web.context.support.XmlWebApplicationContext]-[localhost-startStop-2]-[doClose]-[984]-[INFO] Closing WebApplicationContext for namespace 'springmvc-servlet': startup date [Wed Apr 18 20:43:16 CST 2018]; parent: Root WebApplicationContext
2018-04-18 20:44:02 xxl-job-admin [org.springframework.web.context.support.XmlWebApplicationContext]-[localhost-startStop-2]-[doClose]-[984]-[INFO] Closing Root WebApplicationContext: startup date [Wed Apr 18 20:43:14 CST 2018]; root of context hierarchy
2018-04-18 20:44:02 xxl-job-admin [org.springframework.context.support.DefaultLifecycleProcessor]-[localhost-startStop-2]-[stop]-[358]-[INFO] Stopping beans in phase 2147483647
2018-04-18 20:44:02 xxl-job-admin [org.quartz.core.QuartzScheduler]-[localhost-startStop-2]-[standby]-[585]-[INFO] Scheduler quartzScheduler_$_localhost.localdomain1524055395925 paused.
2018-04-18 20:44:02 xxl-job-admin [com.xxl.job.admin.core.thread.JobRegistryMonitorHelper]-[Thread-9]-[run]-[83]-[ERROR] job registry instance error:{}
java.lang.InterruptedException: sleep interrupted
        at java.lang.Thread.sleep(Native Method)
        at java.lang.Thread.sleep(Thread.java:340)
        at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
        at com.xxl.job.admin.core.thread.JobRegistryMonitorHelper$1.run(JobRegistryMonitorHelper.java:81)
        at java.lang.Thread.run(Thread.java:745)
2018-04-18 20:44:02 xxl-job-admin [com.xxl.job.admin.core.thread.JobFailMonitorHelper]-[Thread-10]-[run]-[79]-[ERROR] job monitor error:{}
java.lang.InterruptedException: sleep interrupted
        at java.lang.Thread.sleep(Native Method)
        at java.lang.Thread.sleep(Thread.java:340)
        at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
        at com.xxl.job.admin.core.thread.JobFailMonitorHelper$1.run(JobFailMonitorHelper.java:77)
        at java.lang.Thread.run(Thread.java:745)
2018-04-18 20:44:02 xxl-job-admin [org.springframework.scheduling.quartz.SchedulerFactoryBean]-[localhost-startStop-2]-[destroy]-[765]-[INFO] Shutting down Quartz Scheduler

**Comment by xuxueli** [comment]
你好，感谢反馈！
问题无法复现，可以进一步提供复现流程吗？

**Comment by longscoop** [comment]
感谢回复，这个问题已解决，是系统一个定时器把docker进程关掉了。
