### ISSUE TITLE
Field 'trigger_code' doesn't have a default value

### ISSUE THREAD

**Issue by lycaste** [xuxueli/xxl-job#361]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1 和1.9.2
### Actual behavior
admin为1.9.2的开发者版本正常（task的core的版本1.9.1,1.9.2都没问题），但是admin的版本为1.9.1时候
疯狂报错（task的core的版本1.9.1,1.9.2都有问题）
 报错的堆栈如下
 SQL []; Field 'trigger_code' doesn't have a default value; nested exception is java.sql.SQLException: Field 'trigger_code' doesn't have a default value
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy23.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy24.save(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:127)
	at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
### Steps to reproduce the behavior
版本如上，目前只是测试task和admin都部署在同一台机器 同一个tomcat下面
### Other information

**Comment by xuxueli** [comment]
你好，v1.9.2 底层对部分表字段做了优化，需要使用相应版本的建表脚本初始化DB。
也可以比对下你两个版本的建表脚本的差异，表结构做调整即可。
