### ISSUE TITLE
执行器：xxl-rpc netty response not found

### ISSUE THREAD

**Issue by scofier** [xuxueli/xxl-job#364]
按照说明来跑， 提示： xxl-rpc netty response not found

14:30:20.625 logback [Thread-6] ERROR c.x.j.c.rpc.netcom.NetComClientProxy - >>>>>>>>>>> xxl-rpc netty response not found.
14:30:20.626 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry-remove error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='127.0.0.1:9999'}
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy53.registryRemove(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:86)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: >>>>>>>>>>> xxl-rpc netty response not found.
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:62)
	... 3 common frames omitted

### Which version of XXL-JOB do you using?
1.9.1

### Expected behavior
demo

### Other information

**Comment by xuxueli** [comment]
你好，“xxl-rpc netty response not found.” 并非XXL-JOB内部文案，是不是对源码进行定制修改？

**Comment by xuxueli** [comment]
你好，我们只保证release版本（测试、回归）的稳定性。
自己的定制版本稳定性需要自己保证。如果遇到定制问题，欢迎加群和社区朋友一起探讨交流。
