### ISSUE TITLE
java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by caryyu** [xuxueli/xxl-job#366]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1

### Expected behavior
希望能够稳定执行，另外，如果产生失败之后希望邮件通知只通知一次或任意配置通知次数最好。

### Actual behavior
目前的情况是一段时间之后，邮件会出现大量的任务失败告警提示，查看后台之后发现注册中心没有一个注册的执行器了（猜测：可能由于某些原因执行器 Crush 了），当前后台管理与执行器均在一个 `tomcat` 下面，查看日志没找到具体的错误，发现大量的异常如下：

> 注意：我里面的任务执行均比较频繁，一般 1-3 分钟执行一次；目前任务量也不是很大，只有 2 个任务；这个情况已经是第二次出现了，之前我没太在意，所以之前希望多跟踪看看，但现在又出现了此问题。

```
29-Apr-2018 13:57:02.509 SEVERE [http-nio-8080-Acceptor-0] org.apache.tomcat.util.net.NioEndpoint$Acceptor.run Socket accept failed
 java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:682)
	at java.lang.Thread.run(Thread.java:748)

29-Apr-2018 13:57:02.560 SEVERE [http-nio-8080-Acceptor-0] org.apache.tomcat.util.net.NioEndpoint$Acceptor.run Socket accept failed
 java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:682)
	at java.lang.Thread.run(Thread.java:748)

...
```

### Steps to reproduce the behavior
这个我并没有任何的操作动作，执行一段时间之后自动产生的此问题。

### Other information
告警邮箱次数限制的问题，这个是延伸出来的问题，不停的告警邮件通知，邮箱快爆掉啦。

**Comment by xuxueli** [comment]
你好，可否提供下任务信息，任务类型自己校验业务逻辑？不确定是否是执行器问题还是任务业务代码问题。

告警邮件，因为告警是以任务为纬度，每个任务配置不同，触发时间不同，邮件聚合不太方便。

**Comment by caryyu** [comment]
# GLUE 任务代码 
```
package com.xxl.job.service.handler;

import com.timgroup.statsd.NonBlockingStatsDClient;
import com.timgroup.statsd.StatsDClient;
import com.xxl.job.core.biz.model.ReturnT;
import com.xxl.job.core.handler.IJobHandler;
import com.xxl.job.core.handler.annotation.JobHandler;
import com.xxl.job.core.log.XxlJobLogger;
import org.apache.commons.dbcp.BasicDataSource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

public class DemoGlueJobHandler extends IJobHandler {
	private static JdbcTemplate jdbcTemplate;

    private static StatsDClient statsd;
  
    private String location = "beijing";

    public DemoGlueJobHandler() {
        String hostname = "xxx";
        int port = 8125;
        statsd = statsd == null ? new NonBlockingStatsDClient("",hostname,port) : statsd;

      	if(jdbcTemplate == null) {
        	BasicDataSource ds = new BasicDataSource();
        	ds.setDriverClassName("com.mysql.jdbc.Driver");
	        ds.setUrl("jdbc:mysql://xxx:3306/xxx");
    	    ds.setUsername("xxx");
        	ds.setPassword("xxx");
        	jdbcTemplate = new JdbcTemplate(ds);
        }
    }

    @Override
    public ReturnT<String> execute(String param) throws Exception {
        XxlJobLogger.log("Database Metrics Collection【{0}】", location);

        Long c = jdbcTemplate.queryForObject("SELECT count(1) connections\n" +
            "FROM information_schema.PROCESSLIST where db is not null ",Long.class);
        statsd.count("app,appId=backend.rel.dbconn.total,location=" + location,c);

        List<Map<String,Object>> list = null;

        list = jdbcTemplate.queryForList("SELECT count(db) connections,db\n" +
                "FROM information_schema.PROCESSLIST where db is not null GROUP BY DB ");


        for (Map<String,Object> item : list) {
            String fmtString = "app,appId=backend.rel.dbconn.full,db=%s,location=%s";
            statsd.count(String.format(fmtString,item.get("db"),location), (Long)item.get("connections"));
        }

        list = jdbcTemplate.queryForList("SELECT count(db) connections,substring_index(host,\":\",1) addr,db\n" +
                "FROM information_schema.PROCESSLIST where db is not null " +
                "GROUP BY DB,addr ");

        for (Map<String,Object> item : list) {
            String fmtString = "app,appId=backend.rel.dbconn.detail,addr=%s,db=%s,location=%s";
            statsd.count(String.format(fmtString,
                    item.get("addr"),item.get("db"),location), (Long)item.get("connections"));
        }

        return ReturnT.SUCCESS;
    }

}

```
> 此任务代码内容比较简单主要是利用 `statsd` 采集 `database` 的连接到 `grafana` 统计中，为了后续人员添加任务方便所以连接池等初始化对象都放在其构造函数当中（我想由于构造函数只会被调用一次？）。

@xuxueli

**Comment by caryyu** [comment]
我把这个换成 `BEAN` 模式之后就没有碰到诸如此类的问题了，看来还是别偷懒，重配置还是需要放在初始化的 `Context` 进行处理；先关闭了。
