### ISSUE TITLE
执行启动成功了，但是 注册失败了

### ISSUE THREAD

**Issue by wmatgh** [xuxueli/xxl-job#375]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.1
### Expected behavior
执行器启动成功，注册成功
### Actual behavior
执行器启动成功，注册失败
### Other information

[0507 22:18:43 879 INFO ] [localhost-startStop-1] core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:orderAuditByRiskRuleJob, jobHandler:com.tongbanjie.xd.audit.portal.combi.job.OrderAuditByRiskRuleJob@436f699e
[0507 22:18:43 879 INFO ] [localhost-startStop-1] core.executor.XxlJobExecutor - >>>>>>>>>>> xxl-job register jobhandler success, name:orderAuditStartJob, jobHandler:com.tongbanjie.xd.audit.portal.combi.job.OrderAuditStartJob@477f26a8
[0507 22:18:43 921 INFO ] [Thread-6] jetty.util.log - Logging initialized @15381ms
[0507 22:18:43 995 INFO ] [Thread-6] jetty.server.Server - jetty-9.2.24.v20180105
[0507 22:18:44 044 INFO ] [Thread-6] jetty.server.ServerConnector - Started ServerConnector@7433866e{HTTP/1.1}{192.168.1.212:9999}
[0507 22:18:44 045 INFO ] [Thread-6] jetty.server.Server - Started @15505ms
[0507 22:18:44 045 INFO ] [Thread-6] jetty.server.JettyServer - >>>>>>>>>>> xxl-job jetty server start success at port:9999.
[0507 22:18:44 220 INFO ] [localhost-startStop-1] web.context.ContextLoader - Root WebApplicationContext: initialization completed in 6721 ms
[0507 22:18:44 235 INFO ] [Thread-10] core.thread.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xd-orderaudit-portal', registryValue='192.168.1.212:9999'}
java.lang.RuntimeException: RpcResponse byte[] is null
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:65)
        at com.sun.proxy.$Proxy31.registry(Unknown Source)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jieqiuming** [comment]
检查下执行器配置的xxl.job.admin.addresses是否正确，这个错是执行器jetty客户端调用调度中心的/api接口不通导致的，如果本地工程直接跑的话url为http://127.0.0.1:8080，不需要/xxl-job-admin目录

**Comment by xuxueli** [comment]
你好，这种情况通常因为回调地址配错，或者回调网络有问题。可以针对性排查下。

**Comment by zhangJianxing2011** [comment]
我的天呐  我一个本地项目居然也要回掉?
