### ISSUE TITLE
启动执行器报错

### ISSUE THREAD

**Issue by aooppo** [xuxueli/xxl-job#412]
### Which version of XXL-JOB do you using?
1.9.2-SNAPSHOT
apache-tomcat-8.5.28
jdk 8

启动执行器报错
```
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/ConcurrentArrayQueue
	at org.eclipse.jetty.io.SelectorManager$ManagedSelector.<init>(SelectorManager.java:410)
	at org.eclipse.jetty.io.SelectorManager.newSelector(SelectorManager.java:270)
	at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:255)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at com.xxl.job.core.rpc.netcom.jetty.server.JettyServer$1.run(JettyServer.java:46)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.ConcurrentArrayQueue
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1291)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	... 14 more

```

**Comment by aooppo** [comment]
ignore it, redeploy work fine.
