### ISSUE TITLE
springboot启动时报错，执行时也报错

### ISSUE THREAD

**Issue by fan302959274** [xuxueli/xxl-job#420]
19:56:50.387 logback [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
19:56:50.433 logback [main] INFO  o.s.w.s.h.SimpleUrlHandlerMapping - Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
19:56:50.938 logback [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
19:56:50.953 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8081"]
19:56:50.966 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8081"]
19:56:50.968 logback [main] INFO  o.a.tomcat.util.net.NioSelectorPool - Using a shared selector for servlet write/read
19:56:50.995 logback [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat started on port(s): 8081 (http)
19:56:51.000 logback [main] INFO  com.xxl.job.executor.Application - Started Application in 25.324 seconds (JVM running for 26.261)
19:57:33.211 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.30.9:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
19:58:03.235 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.30.9:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
19:58:33.263 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.30.9:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
19:59:03.290 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.30.9:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
19:59:33.327 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.30.9:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
20:00:03.344 logback [Thread-6] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.30.9:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuxueli** [comment]
你好，从上述log看，执行器注册发生异常。应该是执行器回调地址配置错误或者回调请求不通，请确认下。
