### ISSUE TITLE
注册时，客户端一直报错，提示注册失败，调试时，发现进不去admin中的 JobApiController.api 方法

### ISSUE THREAD

**Issue by A-MDX** [xuxueli/xxl-job#453]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-1.9.1
### Expected behavior
启动 admin, 然后启动执行器事例 springboot, 发现springboot一直报错，后换启动spring也是
### Actual behavior
admin 端：
```
2018-07-25 16:12:02 xxl-job-admin [org.springframework.web.servlet.PageNotFound]-[http-nio-8080-exec-4]-[noHandlerFound]-[1176]-[WARN] No mapping found for HTTP request with URI [/xxl-job-admin/api] in DispatcherServlet with name 'springmvc'
2018-07-25 16:12:02 xxl-job-admin [org.springframework.web.servlet.PageNotFound]-[http-nio-8080-exec-4]-[handleHttpRequestMethodNotSupported]-[215]-[WARN] Request method 'POST' not supported
```

springboot端报错信息：
```
16:11:32.568 logback [Thread-11] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='localhost:9998'}
java.lang.RuntimeException: RpcResponse byte[] is null
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:65)
	at com.sun.proxy.$Proxy54.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:745)
```
### Other information
win7 
java8

**Comment by A-MDX** [comment]
tomcat: 8.5.31
其他配置仅修改 执行器端口号与 本地mysql 信息。

**Comment by A-MDX** [comment]
可以正常调度。

**Comment by A-MDX** [comment]
这个问题主要是我把 admin 单独拿出来部署在tomcat 里面，默认的就是 http://localhost:8080/api 为注册地址，只要改下 application context 为 http://localhost:8080/xxl-job-admin/api 就好
