### ISSUE TITLE
执行器注册失败

### ISSUE THREAD

**Issue by Moving521** [xuxueli/xxl-job#462]
异常信息如下
2018-08-01 18:41:20 INFO  core.thread.ExecutorRegistryThread:66 - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='ai-admin-group-service', registryValue='192.168.21.100:9999'}
java.lang.RuntimeException: Network request fail, RpcResponse byte[] is null
	at core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy153.registry(Unknown Source)
	at core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)

debug进去查看adminBiz 结果是 
Method threw 'java.lang.RuntimeException' exception. Cannot evaluate com.sun.proxy.$Proxy102.toString()
for (AdminBiz adminBiz: XxlJobExecutor.getAdminBizList()) {
                            try {
                                ReturnT<String> registryResult = adminBiz.registry(registryParam);
***}

**Comment by cullenx** [comment]
查看 调度中心服务器 防火墙 是不是不允许 执行器访问了

**Comment by sxyseo** [comment]
默认回调地址是 http://192.168.xxx.xxx:8080/xxl-job-admin
而默认的服务是没有 xxl-job-admin这个名称的。

详情见
https://github.com/xuxueli/xxl-job/issues/352

**Comment by xuxueli** [comment]
你好，心跳注册失败，应该回调地址或网络的问题， 可以参考下 @sxyseo  的案例。

**Comment by itzhulinghai** [comment]
xxl-job registry, RegistryParam:RegistryParam{registGroup='EXECUTOR', registryKey='blueCat-sync', registryValue='192.168.1.186:8039'}, registryResult:ReturnT [code=500, msg=null, content=null] 
您好,找不因为什么原因,执行器注册失败,能帮忙解答一下吗,多谢了

**Comment by itzhulinghai** [comment]
17:00:38.903 logback [http-nio-8080-exec-2] WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/xxl-job-admin/api/registry] in DispatcherServlet with name 'dispatcherServlet' 
这个是注册中心的日志

**Comment by itzhulinghai** [comment]
希望您能出一个排查执行器注册失败的文档或者视频,多谢了
