### ISSUE TITLE
unknown c ode for readObject at 0x3c ( < )

### ISSUE THREAD

**Issue by supercolor007** [xuxueli/xxl-job#468]
- 这是一个偶现问题，生产环境2号3号共出现9次  
```
content : 2018-08-03 23:39:43.060 [etp1647193236-352] ERROR com.xxl.job.core.rpc.netcom.jetty.server.JettyServerHandler - unknown c
ode for readObject at 0x3c ( < )
java.lang.IllegalStateException: unknown code for readObject at 0x3c ( < )
at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:33) ~[xxl-job-core-1.9.3.jar!/ :na]
at com.xxl.job.core.rpc.netcom.jetty.server.JettyServerHandler.doInvoke(JettyServerHandler.java:54) [xxl-job-core-1.9.3.jar!/ :na]
at com.xxl.job.core.rpc.netcom.jetty.server.JettyServerHandler.handle(JettyServerHandler.java:30) [xxl-job-core-1.9.3.jar!/ :na]
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.server.Server.handle(Server.java:531) [jetty-server-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [jetty-server-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [jetty-io-9.4.11.v20180605.jar!/ :9.4.11.v201806
05]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.11.v20180605.jar!/ :9.4.11.v20180605]
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.11.v20180605.jar!/ :
9.4.11.v20180605]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x3c ( < )
at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697) ~[hessian-4.0.51.jar!/ :4.0.51]
at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177) ~[hessian-4.0.51.jar!/ :4.0.51]
at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:31) ~[xxl-job-core-1.9.3.jar!/ :na]
... 18 common frames omitted
```

**Comment by 369431735** [comment]
是不是使用的调度器集群，在执行器配置文件xxl.job.admin.addresses=http://127.0.0.1:8080/,http://127.0.0.1:8082 在8080后面多写了个“/”曾出现过这个问题

**Comment by supercolor007** [comment]
@369431735 不是集群，我们线上部署的也是单点，而且没有多“/”
