### ISSUE TITLE
unknown code for readObject at 0x45 (E)

### ISSUE THREAD

**Issue by backkoms** [xuxueli/xxl-job#49]
之前可以正常使用，后来引入dubbo 2.5.3，将一些基础服务剥离出去后，再由调度任务调用执行器时，出现以上异常，也可能不是dubbo引起的异常，摸不着解决方案，请教作者

2017-04-21 16:46:29,188 - xxl-job-admin - INFO [com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler] - <>>>>>>>>>>> runJob success, jobKey:4.11>
2017-04-21 16:49:21,995 - xxl-job-admin - ERROR [com.xxl.job.admin.core.jobbean.RemoteHttpJobBean] - <>
java.lang.IllegalStateException: unknown code for readObject at 0x45 (E)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:33)
	at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:17)
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:48)
	at com.sun.proxy.$Proxy18.run(Unknown Source)
	at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.runExecutor(RemoteHttpJobBean.java:184)
	at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.doTrigger(RemoteHttpJobBean.java:107)
	at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:69)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x45 (E)
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:31)
	... 9 more

dubbo相关的配置
<dubbo:registry protocol="zookeeper" address="${service.registry.address}" />

跟踪代码显示：
HttpClientUtil.postRequest() 方法  
HttpResponse response = httpClient.execute(httpPost);

HttpResponseProxy{HTTP/1.1 500 Server Error [Connection: close, Server: Jetty(8.2.0.v20160908)] ResponseEntityProxy{[Chunked: false]}}

求教

**Comment by xuxueli** [comment]
你在执行器测debug调试下，看到了 “HTTP/1.1 500 Server Error ” 好像执行器被改坏了

**Comment by backkoms** [comment]
@xuxueli 执行器是debug模式启动的，调度器在调用的时候请求还没到执行器的断点就抛出异常了
