### ISSUE TITLE
偶尔会有这个错误 No such property: logger for class

### ISSUE THREAD

**Issue by zyhui98** [xuxueli/xxl-job#504]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2 快照
### Expected behavior
no error
### Actual behavior
偶尔会有这个错误：
Alarm Job LogId=7686
HandleCode=java.util.concurrent.ExecutionException: groovy.lang.MissingPropertyException: No such property: logger for class: com.xxl.job.service.handler.DemoGlueJobHandlerTrun
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:140)
Caused by: groovy.lang.MissingPropertyException: No such property: logger for class: com.xxl.job.service.handler.DemoGlueJobHandlerTrun
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at com.xxl.job.service.handler.DemoGlueJobHandlerTrun.execute(script1537506000343139189462.groovy:26)
	at com.xxl.job.core.handler.impl.GlueJobHandler.execute(GlueJobHandler.java:26)
	at com.xxl.job.core.thread.JobThread$1.call(JobThread.java:134)
	at com.xxl.job.core.thread.JobThread$1.call(JobThread.java:131)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

### Other information

**Comment by xuxueli** [comment]
你好，该问题无法复现。请进一步提供复现操作步骤及流程。
