### ISSUE TITLE
在与springboot集成过程中报这个错。

### ISSUE THREAD

**Issue by forezp** [xuxueli/xxl-job#51]
在与springboot集成过程中报这个错。
Exception in thread "Thread-19" java.lang.NoSuchMethodError: org.eclipse.jetty.server.Server.setThreadPool(Lorg/eclipse/jetty/util/thread/ThreadPool;)V
	at com.xxl.job.core.rpc.netcom.jetty.server.JettyServer$1.run(JettyServer.java:28)
	at java.lang.Thread.run(Thread.java:745)

**Comment by forezp** [comment]
记录下坑，如果需要用springboot的更高版本，比如1.5.3  ,需要更改下log4j的起步依赖版本，改为	<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j</artifactId>
			<version>1.3.8.RELEASE</version>
		</dependency>

**Comment by xuxueli** [comment]
应该是 jetty 版本冲突问题，保持与core依赖一致即可。
