### ISSUE TITLE
 Network request error: expected integer at 0x74

### ISSUE THREAD

**Issue by lkp123456** [xuxueli/xxl-job#515]
2018-09-29 18:55:20 xxl-job-admin [com.xxl.job.admin.core.trigger.XxlJobTrigger]-[pool-1-thread-8]-[runExecutor]-[191]-[ERROR] >>>>>>>>>>> xxl-job trigger error, please check if the executor[http://192.168.5.174:8080] is running.
java.lang.RuntimeException: Network request error: expected integer at 0x74
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy53.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:189)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:140)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yimi099** [comment]
是xxl-job-core版本不一致造成的，git上最新的用的是Hessian2Input Hessian2Onput，1.9.1-release是HessianInput HessianOnput
解决方案1：执行器工程引用git上xxl-job-core的jar（比如xxl-job-core-1.9.2-SNAPSHOT.jar）
解决方案2：调度中心修改源码（Hessian2Input Hessian2Onput改为HessianInput HessianOnput），重新编译打包

**Comment by xuxueli** [comment]
你好，是的，即将发布的 v1.9.2 其中一项更新为 “底层RPC序列化协议调整为hessian2；”
