### ISSUE TITLE
bug: 注册路径 /api 错误

### ISSUE THREAD

**Issue by tanliwei** [xuxueli/xxl-job#535]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.0-SNAPSHOT

### Expected behavior
2018-10-12 16:23:39 xxl-job-executor-sample-spring [com.xxl.job.core.thread.ExecutorRegistryThread]-[Thread-17]-[run]-[60]-[INFO] >>>>>>>>>>> xxl-job registry success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='10.*.*.*:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]

### Actual behavior
2018-10-12 16:23:03 xxl-job-executor-sample-spring [com.xxl.job.core.thread.ExecutorRegistryThread]-[Thread-17]-[run]-[66]-[INFO] >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='10.*.*.*:9999'}
java.lang.RuntimeException: Network request error: Connect to 127.0.0.1:8088 [/127.0.0.1] failed: Connection refused: connect
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy9.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce the behavior
部署xxl-job-admin

部署xxl-job-executor-sample-spring
    

### Other information
执行器注册失败, 排查发现
执行器使用的注册路径是 /xxl-job-admin/api
管理端 提供的路径是 /api

修复建议：
管理端， 路径修改：

com.xxl.job.core.biz.AdminBiz

    public static final String MAPPING = "/api";

修改为

    public static final String MAPPING = "/xxl-job-admin/api";

**Comment by xuxueli** [comment]
你好，是你部署的问题。“/xxl-job-admin” 是部署项目名，部署在该路径下即可。
