### ISSUE TITLE
新版本调度中心启动没问题，执行器启动时就报错，报错如下

### ISSUE THREAD

**Issue by zenghuabin** [xuxueli/xxl-job#539]
018-10-15 10:29:18 xxl-job-admin [org.springframework.scheduling.quartz.LocalDataSourceJobStore]-[Quartz Scheduler [quartzScheduler]]-[logWarnIfNonZero]-[3629]-[INFO] ClusterManager: detected 1 failed or restarted instances.
2018-10-15 10:29:18 xxl-job-admin [org.springframework.scheduling.quartz.LocalDataSourceJobStore]-[Quartz Scheduler [quartzScheduler]]-[clusterRecover]-[3488]-[INFO] ClusterManager: Scanning for instance "PC-20180719SYML1539570415730"'s failed in-progress jobs.
2018-10-15 10:29:18 xxl-job-admin [org.springframework.scheduling.quartz.LocalDataSourceJobStore]-[Quartz Scheduler [quartzScheduler]]-[logWarnIfNonZero]-[3629]-[INFO] ClusterManager: ......Freed 1 acquired trigger(s).
2018-10-15 10:29:18 xxl-job-admin [org.quartz.core.QuartzScheduler]-[Quartz Scheduler [quartzScheduler]]-[start]-[547]-[INFO] Scheduler quartzScheduler_$_PC-20180719SYML1539570537791 started.
2018-10-15 10:29:20 xxl-job-admin [com.xxl.job.admin.controller.JobApiController]-[http-nio-8080-exec-7]-[doInvoke]-[42]-[ERROR] expected integer at 0x74
java.lang.IllegalStateException: expected integer at 0x74
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:47)
	at com.xxl.job.admin.controller.JobApiController.doInvoke(JobApiController.java:36)
	at com.xxl.job.admin.controller.JobApiController.api(JobApiController.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2943)
	at com.caucho.hessian.io.Hessian2Input.expect(Hessian2Input.java:2891)
	at com.caucho.hessian.io.Hessian2Input.readInt(Hessian2Input.java:825)
	at com.caucho.hessian.io.Hessian2Input.readType(Hessian2Input.java:2438)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2115)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:44)
	... 47 more

**Comment by xuxueli** [comment]
你好，请确认调度中心与执行器是否版本一致，从Log看应该不一致导致的。
