### ISSUE TITLE
xxl-job一般报错解决方案

### ISSUE THREAD

**Issue by lixiangzhi** [xuxueli/xxl-job#546]
在实际项目中，会遇到一些问题，如下：

一、执行任务以后，后台查看任务已完成，但是，页面无法显示 执行结果为成功，一直处于 执行中状态，必须手动停止，且执行结果为失败，

原因： 
xxl-job-admin登陆网址和执行器配置文件xxl-job-executor.properties里面的xxl.job.admin.addresses不相同的原因，页面为：http://localhost:8091/xxl-job-admin/，那配置文件里也应该相同为http://localhost:8091/xxl-job-admi，如果是：http://localhost:8091/，那配置文件里的地址也应该为http://localhost:8091/。 或者有一种处理模式是 串行，导致阻塞，也会造成这种现象。

二、调度结果失败

有以下几种原因： 
1、执行器注册地址错误， 
2、执行器项目没启动或者启动失败， 
3、执行器注册地址为空

--------------------- 
作者：北方小伙_ 
来源：CSDN 
原文：https://blog.csdn.net/weixin_39433171/article/details/81220977?utm_source=copy 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by windlikeman** [comment]
2018-11-15 16:10:55.390 [etp892078499-186] DEBUG org.eclipse.jetty.http.HttpParser - START --> CLOSED
2018-11-15 16:10:55.390 [etp892078499-186] DEBUG org.eclipse.jetty.io.AbstractEndPoint - close SocketChannelEndPoint@224d67ca{/192.168.0.153:57318<->/192.168.0.93:9999,ISHUT,fill=-,flush=-,to=4/30000}{io=0/0,kio=0,kro=1}->HttpConnection@6db787c8[p=HttpParser{s=CLOSED,0 of -1},g=HttpGenerator@240dce83{s=START}]=>HttpChannelOverHttp@2c8a8df3{r=1,c=false,a=IDLE,uri=null,age=0}
2018-11-15 16:10:55.390 [etp892078499-186] DEBUG org.eclipse.jetty.io.AbstractEndPoint - close(null) SocketChannelEndPoint@224d67ca{/192.168.0.153:57318<->/192.168.0.93:9999,ISHUT,fill=-,flush=-,to=4/30000}{io=0/0,kio=0,kro=1}->HttpConnection@6db787c8[p=HttpParser{s=CLOSED,0 of -1},g=HttpGenerator@240dce83{s=START}]=>HttpChannelOverHttp@2c8a8df3{r=1,c=false,a=IDLE,uri=null,age=0}
2018-11-15 16:10:55.390 [etp892078499-186] DEBUG org.eclipse.jetty.io.ChannelEndPoint - doClose SocketChannelEndPoint@224d67ca{/192.168.0.153:57318<->/192.168.0.93:9999,CLOSED,fill=-,flush=-,to=4/30000}{io=0/0,kio=0,kro=1}->HttpConnection@6db787c8[p=HttpParser{s=CLOSED,0 of -1},g=HttpGenerator@240dce83{s=START}]=>HttpChannelOverHttp@2c8a8df3{r=1,c=false,a=IDLE,uri=null,age=0}
2018-11-15 16:10:55.390 [etp892078499-186] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@2fac20ff{IDLE}->null
java.nio.channels.ClosedChannelException: null
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:532)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353)
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
	at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:224)
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:234)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1557)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:360)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lxm1007** [comment]
我也遇到了这个问题 如何解决呢

**Comment by mail6562** [comment]
你们有解决这个问题吗？

**Comment by xuxueli** [comment]
@windlikeman @lxm1007 @mail6562 
你好，新版 v2.0.2 已发布，新版废弃jetty改为netty，上述问题以规避。

可以下载新版体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2

**Comment by windlikeman** [comment]
非常感谢




------------------ 原始邮件 ------------------
发件人: "许雪里"<notifications@github.com>; 
发送时间: 2019年4月20日(星期六) 下午5:20
收件人: "xuxueli/xxl-job"<xxl-job@noreply.github.com>; 
抄送: "李永飞"<1436199880@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [xuxueli/xxl-job] xxl-job一般报错解决方案 (#546)




@windlikeman @lxm1007 @mail6562
 你好，新版 v2.0.2 已发布，新版废弃jetty改为netty，上述问题以规避。
 
可以下载新版体验下：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2
