### ISSUE TITLE
启动的时候注册不了注册中心

### ISSUE THREAD

**Issue by Yyy1231456** [xuxueli/xxl-job#575]
17:18:28.051 [Thread-4] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection manager is shutting down
17:18:28.052 [Thread-4] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
17:18:28.053 [Thread-4] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection manager shut down
17:19:21.243 [Thread-4] ERROR c.x.j.c.r.n.jetty.client.JettyClient - java.lang.Long cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
java.lang.ClassCastException: java.lang.Long cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
	at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:37) ~[xxl-job-core-1.9.2.jar:na]
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57) [xxl-job-core-1.9.2.jar:na]
	at com.sun.proxy.$Proxy7.registry(Unknown Source) [na:na]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57) [xxl-job-core-1.9.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
17:19:21.245 [Thread-4] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-ys', registryValue='10.5.13.23:9999'}
java.lang.RuntimeException: Network request error: java.lang.Long cannot be cast to com.xxl.job.core.rpc.codec.RpcResponse
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64) ~[xxl-job-core-1.9.2.jar:na]
	at com.sun.proxy.$Proxy7.registry(Unknown Source) ~[na:na]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57) ~[xxl-job-core-1.9.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

**Comment by xuxueli** [comment]
你好，确认下执行器回调地址是不是配置正确，回调服务是否启动。

**Comment by likenamehaojie** [comment]
这个就是后升级spring boot2 后rpc组件 报的错 请问作者该问题如何解决

**Comment by Yyy1231456** [comment]
> 这个就是后升级spring boot2 后rpc组件 报的错 请问作者该问题如何解决

这个是由于你执行器用的是springboot2之后的版本,但是你的xxl-core用的是1.9.几的版本,版本不一致造成的

**Comment by likenamehaojie** [comment]
xxl-admin升级的springboot2 执行器在NETTY_HTTP这个客户端注册时超时，现在换成了JETTY，但是作者没有把这个入口做成可设置，
