### ISSUE TITLE
升级到2.0.0版本之后 执行器启动之后jetty停了

### ISSUE THREAD

**Issue by buzzxu** [xuxueli/xxl-job#586]
你好，我使用的版本是1.9.2。将xxl-job-admin做成docker镜像部署，执行器用springboot在宿主机上部署，使用JDK11。当从1.9.2升级到2.0.0之后，执行器启动成功之后,jetty关闭了,导致任务执行失败.
执行器启动日志:

```
2018-11-05 17:39:44.889  INFO 26133 --- [      Thread-18] c.x.j.c.t.ExecutorRegistryThread         : >>>>>>>>>>> xxl-job registry success, registryParam:RegistryParamm
{registGroup='EXECUTOR', registryKey='poster-executor', registryValue='192.168.4.181:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]
                                                                                                                                                    27241,9       95%
2018-11-05 17:37:10.571  INFO 26133 --- [           main] c.m.p.j.c.JobConfig                      : >>>>>>>>>>> xxl-job config init.
2018-11-05 17:37:10.879  INFO 26133 --- [           main] c.x.r.r.p.XxlRpcProviderFactory          : >>>>>>>>>>> xxl-rpc, provider factory add service success. serviceKey = com.xxl.job.core.biz.ExecutorBiz, serviceBean = class com.xxl.job.core.biz.impl.ExecutorBizImpl
2018-11-05 17:37:11.052  INFO 26133 --- [       Thread-6] o.e.j.u.log                              : Logging initialized @39922ms to org.eclipse.jetty.util.log.Slf4jLog
2018-11-05 17:37:11.486  INFO 26133 --- [       Thread-6] o.e.j.s.Server                           : jetty-9.4.12.v20180830; built: 2018-08-30T13:59:14.071Z; git: 27208684755d94a92186989f695db2d7b21ebc51; jvm 11+28
2018-11-05 17:37:12.118  INFO 26133 --- [       Thread-6] o.e.j.s.AbstractConnector                : Started ServerConnector@54e5742a{HTTP/1.1,[http/1.1]}{0.0.0.0:9999}
2018-11-05 17:37:12.118  INFO 26133 --- [       Thread-6] o.e.j.s.Server                           : Started @40989ms
2018-11-05 17:37:12.119  INFO 26133 --- [       Thread-6] c.x.r.r.n.Server                         : >>>>>>>>>>> xxl-rpc remoting server start success, nettype = com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer, port = 9999
2018-11-05 17:37:14.080  INFO 26133 --- [           main] o.s.s.c.ThreadPoolTaskExecutor           : Initializing ExecutorService 'applicationTaskExecutor'
2018-11-05 17:37:14.692  INFO 26133 --- [      Thread-18] c.x.j.c.t.ExecutorRegistryThread         : >>>>>>>>>>> xxl-job registry success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='poster-executor', registryValue='192.168.4.181:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]
2018-11-05 17:37:16.638  INFO 26133 --- [           main] o.s.b.a.e.w.EndpointLinksResolver        : Exposing 2 endpoint(s) beneath base path '/actuator'
2018-11-05 17:37:17.281  INFO 26133 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 8280 (http) with context path '/job'
2018-11-05 17:37:17.330  INFO 26133 --- [           main] c.m.p.j.PosterJobExecutorApp             : Started PosterJobExecutorApp in 36.74 seconds (JVM running for 46.201)
2018-11-05 17:37:42.191  INFO 26133 --- [       Thread-6] o.e.j.s.AbstractConnector                : Stopped ServerConnector@54e5742a{HTTP/1.1,[http/1.1]}{0.0.0.0:9999}
2018-11-05 17:37:44.731  INFO 26133 --- [      Thread-18] c.x.j.c.t.ExecutorRegistryThread         : >>>>>>>>>>> xxl-job registry success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='poster-executor', registryValue='192.168.4.181:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]
```
job-admin日志:
```
2018-11-05 20:40:10,663 ERROR [pool-3-thread-2] c.x.j.a.core.trigger.XxlJobTrigger [XxlJobTrigger.java : 193] >>>>>>>>>>> xxl-job trigger error, please check if the executor[192.168.4.181:9999] is running.
com.xxl.rpc.util.XxlRpcException: com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1541421610663, request:XxlRpcRequest{requestId='91baedc9-c76e-4ef5-929a-7633db5aba57', createMillisTime=1541421600372, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=1, executorHandler='startPresell', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=733234, logDateTim=1541421600351, glueType='BEAN', glueSource='', glueUpdatetime=1539165941000, broadcastIndex=0, broadcastTotal=1}], version='null'}
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:166)
        at com.sun.proxy.$Proxy75.run(Unknown Source)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76)
        at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
```
同样的配置，切换回1.9.2版本就可以。

**Comment by xuxueli** [comment]
你好，从启动日志看执行器已经启动成功 （……xxl-rpc remoting server start success,……），可以浏览器访问这个执行器端口确认是是否有响应。
问题发生在任务触发，任务触发请求超时导致调度失败，可以从调度中心ping一下这个端口服务，确认下网络和服务状况。

**Comment by zhuangsheng** [comment]
我也发现同样情况，自已应用的执行器启动成功后又关闭了， o.e.jetty.server.AbstractConnector       : Stopped ServerConnector@1e39c282{HTTP/1.1,[http/1.1]}{0.0.0.0:9099}，用xxl-job-executor-sample-springboot又不会，怎么排查

**Comment by ZuiSong** [comment]
一样的问题，我也发现了

**Comment by cutehuman** [comment]
正准备升级，本地测试发现了也有同样的问题。

**Comment by xuxueli** [comment]
问题不能复现：我使用springboot版本调度中心与执行器，初始化一套新环境并新建一个一个GLUE任务，10s跑一次，连续运行了 30 分钟并没有复现该问题。

大家执行器启动时，请确保调度中心处于运行状态，否则可能导致心跳注册等报错信息干扰日志分析。

请可以描述复现步骤，并提供一份从启动开始的完整日志编译排错啊！

**Comment by zenghuabin** [comment]
也出现一样的问题，项目重启，第一次调用成功了，然后第二次就这样子了
com.xxl.rpc.util.XxlRpcException: xxl-rpc remoting request error.
        at com.xxl.rpc.remoting.net.impl.jetty.client.JettyClient$1.onComplete(JettyClient.java:67)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
        at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
        at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
        at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
        at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:704)
        at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:256)
        at org.eclipse.jetty.client.PoolingHttpDestination$1.run(PoolingHttpDestination.java:68)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:341)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:676)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:645)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:612)
        at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:550)
        at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
        ... 3 common frames omitted

**Comment by weiwunb** [comment]
我们也遇到了这个问题，回撤到v1.9.2正常了

**Comment by ioiioo** [comment]
我今天也遇到同样的问题：
项目启动不久便会打印出下日志：

> 2018-11-05 17:37:42.191  INFO 26133 --- [       Thread-6] o.e.j.s.AbstractConnector                : Stopped ServerConnector@54e5742a{HTTP/1.1,[http/1.1]}{0.0.0.0:9999}

之后本地就不会在有 任何进程占用9999端口；而 执行器调用admin会一直成功，并注册执行器存活成功，而实际用于与admin进行通程的jetty线程己退出了。 所以后面执行job都会失败，而我本地成功的解决办法：

在执行器springboot 项目的 pom.xml中 手动添加以下jetty有关的pom引用（从xxl-job-executor-sample-springboot里面拷贝过来的），就可以了

`<properties>
        <jetty-server.version>9.2.26.v20180806</jetty-server.version>
</properties>`





        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>${jetty-server.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>${jetty-server.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
            <version>${jetty-server.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>${jetty-server.version}</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-client</artifactId>
            <version>${jetty-server.version}</version>
        </dependency>

**Comment by zhuangsheng** [comment]
还真是，要加jetty-server的POM配置才行，理论上xxl-job-core不是已经包含有了吗？

**Comment by xuxueli** [comment]
经过排查发现，springboot版本执行器需要限制jetty版本与 xxl-job-core 依赖中保持一致（目前为 9.2.x 
 ）。可以先按照这个限制调整执行器jetty版本，问题及可解决。

具体原因仍然在排查（springboot 内部额外嵌入启动 jetty9.4 版本 server 自动销毁问题），感兴趣的可以一起参与排查并探讨。

**Comment by xuxueli** [comment]
具体问题已经定位到，因为 jetty9.4 版本内置的线程池 “ExecutorThreadPool.join”  只会阻塞 30s，随后销毁，从而导致执行器启动后自动销毁。正在紧急修复该问题，即将发布问题修复的小版本。

**Comment by xuxueli** [comment]
已经发布新版本修复这个问题，可以从 v2.0.0 直接覆盖更新：https://github.com/xuxueli/xxl-job/releases/tag/v2.0.1

**Comment by villins** [comment]
@xuxueli 这个是执行器的问题，是不是要更新 ``` xxl-job-core``` 版本？还是 admin 就行了呢？

**Comment by luo1993hao** [comment]
在2.0.2版本中依然存在这个问题。

**不定期失败，频率大概为15次失败一次**
```
# xxl-job的pom文件中jetty版本
<jetty-server.version>9.2.26.v20180806</jetty-server.version>
```
```
# 自定义执行器项目中jetty版本
    <jetty-server.version>9.2.26.v20180806</jetty-server.version>
```
二者完全一样。
错误日志
```
2018-12-03 16:20:00,008 ERROR [pool-3-thread-8] c.x.j.a.core.trigger.XxlJobTrigger [XxlJobTrigger.java : 190] >>>>>>>>>>> xxl-job trigger error, please check if the executor[192.168.1.147:9999] is running.
com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP@7aa130e2(l:/192.168.1.147:34692 <-> r:/192.168.1.147:9999,closed=false)[HttpChannelOverHTTP@13cf2011(exchange=HttpExchange@107ba5b3 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@ebe49(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@735bb88a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1305)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)

	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
	at com.sun.proxy.$Proxy81.run(Unknown Source)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:188)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:141)
	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:75)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

@xuxueli

**Comment by pai01234** [comment]
> 在2.0.2版本中依然存在这个问题。
> 
> **不定期失败，频率大概为15次失败一次**
> 
> ```
> # xxl-job的pom文件中jetty版本
> <jetty-server.version>9.2.26.v20180806</jetty-server.version>
> ```
> ```
> # 自定义执行器项目中jetty版本
>     <jetty-server.version>9.2.26.v20180806</jetty-server.version>
> ```
> 二者完全一样。
> 错误日志
> 
> ```
> 2018-12-03 16:20:00,008 ERROR [pool-3-thread-8] c.x.j.a.core.trigger.XxlJobTrigger [XxlJobTrigger.java : 190] >>>>>>>>>>> xxl-job trigger error, please check if the executor[192.168.1.147:9999] is running.
> com.xxl.rpc.util.XxlRpcException: java.io.EOFException: HttpConnectionOverHTTP@7aa130e2(l:/192.168.1.147:34692 <-> r:/192.168.1.147:9999,closed=false)[HttpChannelOverHTTP@13cf2011(exchange=HttpExchange@107ba5b3 req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@ebe49(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator{s=START}],recv=HttpReceiverOverHTTP@735bb88a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]]
> 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:277)
> 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1305)
> 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:182)
> 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:129)
> 	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:69)
> 	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
> 	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:174)
> 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
> 	at com.sun.proxy.$Proxy81.run(Unknown Source)
> 	at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:188)
> 	at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:141)
> 	at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:75)
> 	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> @xuxueli
我使用xxljob也遇到了

**Comment by Gorgeous29** [comment]
2019-05-16 11:53:13.807|nioEventLoopGroup-15-1|localhost|ERROR|com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler||>>>>>>>>>>> xxl-rpc netty_http client caught exception
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '6d' 这是什么原因导致

**Comment by WangSiYang9** [comment]
2019-11-25 14:17:46.298 ERROR 7311 --- [ntLoopGroup-5-1] c.x.r.r.n.i.n.c.NettyHttpClientHandler   : >>>>>>>>>>> xxl-rpc netty_http client caught exception

com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '6d'

**Comment by WangSiYang9** [comment]
> 2019-05-16 11:53:13.807|nioEventLoopGroup-15-1|localhost|ERROR|com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler||>>>>>>>>>>> xxl-rpc netty_http client caught exception
> com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '6d' 这是什么原因导致

你这个问题解决了吗

**Comment by goAhead2013** [comment]
@xuxueli 我用docker部署的，xxl-job版本是2.0.1,   4.29号下午三点还是可以成功执行的，就没去管它了，今天来看，居然发现4.29号下午五点就报错了，错误信息如下：，明晚就要上线了，突然出现这个问题，有点措手不及，大哥有空麻烦帮我优先看下，可以吗？感激不尽
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1589282787500, request:XxlRpcRequest{requestId='74e363b1-6d91-4f19-9b59-14a1406bd784', createMillisTime=1589282777433, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=8, executorHandler='dailySyncBookToDBJob', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=7681, logDateTim=1589282777424, glueType='BEAN', glueSource='', glueUpdatetime=1588112227000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:105) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:159) at com.sun.proxy.$Proxy78.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:191) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:142) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:76) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$1.run(JobTriggerPoolHelper.java:35) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622) at java.lang.Thread.run(Thread.java:748)

**Comment by siriusfx** [comment]
@xuxueli 我也遇到这个问题，xxl-job版本是2.0.2，以前一直没有出现，最近在一个服务器上频繁出现，错误信息如下：
 >>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：172.19.44.2:9994
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1591374605071, request:XxlRpcRequest{requestId='f3af51ee-baa3-4e43-bc8b-995b460cb23f', createMillisTime=1591374600069, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=53, executorHandler='CommonJobHandler', executorParams='3:1:DEPT_DEPTYCZS,DEPT_DEPTJACZS,DEPT_DEPTASCZS,DEPT_DEPTCSCZS,DEPT_DEPTWCZS,DEPT_DEPTCQWCZS,DEPT_DEPTAQWCZS,DEPT_DEPTDHCAQCZS,DEPT_DEPTDHCCQCZS,DEPT_DEPTSQYQCS,DEPT_DEPTSQHTCS,DEPT_DEPTSQYQS,DEPT_DEPTYQS,DEPT_DEPTSQHTS,DEPT_DEPTHTS,DEPT_DEPTBHS,DEPT_DEPTFGS,DEPT_DEPTFGCS,DEPT_DEPTYJAS,DEPT_DEPTJAS,DEPT_ASJAS,DEPT_CSJAS', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=2894, logDateTim=1591374600034, glueType='BEAN', glueSource='', glueUpdatetime=1568165959000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219) at com.sun.proxy.$Proxy84.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:77) at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source)

**Comment by shinynz** [comment]
@xuxueli >>>>>>>>>>>触发调度<<<<<<<<<<<
触发调度：
address：172.20.5.62:9991
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1598430690030, request:XxlRpcRequest{requestId='a44c6077-2e6b-4c7e-8b1e-1d3b08a5f409', createMillisTime=1598430680029, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=173, executorHandler='ServiceAccountStatGenerateJobHandler', executorParams='', executorBlockStrategy='DISCARD_LATER', executorTimeout=0, logId=61052279, logDateTime=1598430680002, glueType='BEAN', glueSource='', glueUpdatetime=1543307503000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy109.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:203) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:156) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:81) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by shanxi668** [comment]
@xuxueli 我们这边出现这种情况已经达到6.7%，xxl-job 版本是2.1.1,麻烦有空帮忙看下，感谢。
Job trigger type：Cron trigger
Trigger machine address：10.244.5.244
Execotor-Registry Type：Automatic registration
Execotor-Registry Address：[10.244.5.134:9999]
Route Strategy：First
Block Strategy：Serial execution
Job timeout period：0
Fail Retry Count：0

>>>>>>>>>>>Trigger Job<<<<<<<<<<<
Trigger Job：
address：10.244.5.134:9999
code：500
msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1598883693007, request:XxlRpcRequest{requestId='956f4755-2da4-4403-8b2d-02bb36e17769', createMillisTime=1598883690007, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=9, executorHandler='nuccSerialSeqApplyJobHandler', executorParams='', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=20914479, logDateTime=1598883690004, glueType='BEAN', glueSource='', glueUpdatetime=1581619385000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy159.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by Emiya-lhl** [comment]
这个问题有人解决吗。。

**Comment by Emiya-lhl** [comment]
> 任务触发类型：Cron触发 调度机器：172.23.14.41 执行器-注册方式：自动注册 执行器-地址列表：[http://172.23.11.132:9999] 路由策略：第一个 阻塞处理策略：单机串行 任务超时时间：0 失败重试次数：0
> 
> > > > > > > > > > > > 触发调度<<<<<<<<<<<
> > > > > > > > > > > > 触发调度：
> > > > > > > > > > > > address：http://172.23.11.132:9999
> > > > > > > > > > > > code：500
> > > > > > > > > > > > msg：com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1620733803070, request:XxlRpcRequest{requestId='f97228d4-f64a-40f4-9e5d-02bc4cb042de', createMillisTime=1620733800056, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='run', parameterTypes=[class com.xxl.job.core.biz.model.TriggerParam], parameters=[TriggerParam{jobId=562, executorHandler='runTaskHandler', executorParams='{"id":170801}', executorBlockStrategy='SERIAL_EXECUTION', executorTimeout=0, logId=6123685, logDateTime=1620733800049, glueType='BEAN', glueSource='', glueUpdatetime=1620376768000, broadcastIndex=0, broadcastTotal=1}], version='null'} at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117) at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:242) at com.sun.proxy.$Proxy120.run(Unknown Source) at com.xxl.job.admin.core.trigger.XxlJobTrigger.runExecutor(XxlJobTrigger.java:196) at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:149) at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74) at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:90) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

请问这个解决了吗

**Comment by hao69092017** [comment]
同问，有没有人解决了 跪求方案
