### ISSUE TITLE
GLUE模式(NodeJs)运行报错

### ISSUE THREAD

**Issue by zsf513** [xuxueli/xxl-job#602]
执行器部署在linux下，执行glue(nodejs)任务时报错：
Cannot run program "node" (in directory "."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.xxl.job.core.util.ScriptUtil.execToFile(ScriptUtil.java:76)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:63)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:124)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
, content=null]}], callbackResult:ReturnT [code=200, msg=null, content=null]
但是直接在命令行下运行node xxx.js是没有错误的。而且执行器部署在windows下是可以运行这个任务的。

**Comment by xuxueli** [comment]
你好，确认下执行器进程所属用户拥有该命令执行权限。
