### ISSUE TITLE
springboot1.5.12 下，jetty异常停止

### ISSUE THREAD

**Issue by LuTongT** [xuxueli/xxl-job#611]
我们公司有自己的父类pom，springboot依赖版本为2.5.12，当jetty监听端口（默认9999）抛出异常后，几秒后jetty直接停止，可否定位一下原因？
`20:11:18.984 logback [etp1732754850-35] WARN  org.eclipse.jetty.server.HttpChannel - /
com.xxl.rpc.util.XxlRpcException: XxlRpcRequest byte[] is null
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServerHandler.parseRequest(JettyServerHandler.java:69)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServerHandler.handle(JettyServerHandler.java:37)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:11:22.425 logback [Thread-5] INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@3c8da311{HTTP/1.1,[http/1.1]}{0.0.0.0:9999}
20:11:22.547 logback [Thread-18] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='127.0.0.1:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]
`

**Comment by Yanxinwei** [comment]
遇到同样的问题, 不过用的是springboot-2.0.5.RELEASE版本, 求助是怎么解决的

**Comment by Yanxinwei** [comment]
> jetty版本问题，参见#586

感谢, 按照步骤已修复.
