### ISSUE TITLE
GLUE(java)模式开发，不支持lambda表达式吗?

### ISSUE THREAD

**Issue by cutehuman** [xuxueli/xxl-job#659]
Please answer some questions before submitting your issue. Thanks!

### Other information

**Comment by chenghao111** [comment]
我也发现 这个问题了。。。解决了吗

**Comment by xuxueli** [comment]
你好，GLUE（Java）本质上一段运行在执行器测的代码片段（groovy），只要执行器项目内支持lambda就可以正常使用lambda。

**Comment by chenghao111** [comment]
我的 项目是 java8的 。 glue 运行到 lambda 就报错 。 classLoader 的时候 报错的。

**Comment by clay-f** [comment]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
script15806150921601049691827.groovy: 18: unexpected token: -> @ line 18, column 36.
           list.stream().forEach(item -> XxlJobLogger.log("val: {}", item));

**Comment by clay-f** [comment]
使用 lambda job 执行报错.


    public void say() {
        XxlJobLogger.log("使用 lambda 迭代 list");
        List<Integer> list = IntStream.rangeClosed(0, 10).boxed().collect(toList());
        list.stream().forEach(item -> XxlJobLogger.log("val: {}", item));
        XxlJobLogger.log("迭代成功...");
    }

异常信息:

    org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
	script15806150921601049691827.groovy: 18: unexpected token: -> @ line 18, column 36.
	           list.stream().forEach(item -> XxlJobLogger.log("val: {}", item));
	                                      ^

	1 error

		at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:151) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:121) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:133) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:325) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:224) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:192) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:226) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:197) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:960) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:637) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:613) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:590) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338) ~[groovy-2.5.9.jar!/:2.5.9]
		at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:262) ~[groovy-2.5.9.jar!/:2.5.9]
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:272) ~[groovy-2.5.9.jar!/:2.5.9]
		at com.xxl.job.core.glue.GlueFactory.getCodeSourceClass(GlueFactory.java:77) ~[xxl-job-core-2.1.2.jar!/:?]
		at com.xxl.job.core.glue.GlueFactory.loadNewInstance(GlueFactory.java:48) ~[xxl-job-core-2.1.2.jar!/:?]
		at com.xxl.job.core.biz.impl.ExecutorBizImpl.run(ExecutorBizImpl.java:116) [xxl-job-core-2.1.2.jar!/:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
		at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:240) [xxl-rpc-core-1.5.0.jar!/:?]
		at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:91) [xxl-rpc-core-1.5.0.jar!/:?]
		at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:26) [xxl-rpc-core-1.5.0.jar!/:?]
		at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:50) [xxl-rpc-core-1.5.0.jar!/:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
		at java.lang.Thread.run(Thread.java:834) [?:?]


java 版本: jdk 11
xxl-job 版本: 2.1.2

**Comment by 15670600690** [comment]
你好我也遇到这个情况了  你知道他们解决没  或者如何处理一下

**Comment by chenghao111** [comment]
> 你好我也遇到这个情况了 你知道他们解决没 或者如何处理一下

没有。 lambda代码改为普通java6，7能执行的代码即可。
