### ISSUE TITLE
添加php任务执行失败，执行器机器已安装php，php已加入环境变量

### ISSUE THREAD

**Issue by zl214389366** [xuxueli/xxl-job#671]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
v2.0.1
### Actual behavior
2018-12-13 14:33:44 [com.xxl.job.core.handler.impl.ScriptJobHandler#execute]-[81]-[Thread-27] ----------- script file:/home/log/xxl-job/gluesource/2_1544681719000.php -----------
2018-12-13 14:33:44 [com.xxl.job.core.util.ScriptUtil#execToFile]-[83]-[Thread-27] java.io.IOException: Cannot run program "php" (in directory "."): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.xxl.job.core.util.ScriptUtil.execToFile(ScriptUtil.java:80)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:82)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:152)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more

### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现。需要进一步提供操作步骤。
