### ISSUE TITLE
调度中心 docker swarm 启动报错 获取不到org.quartz.scheduler.instanceId

### ISSUE THREAD

**Issue by 617450941** [xuxueli/xxl-job#674]
启动命令
docker service create --with-registry-auth --constraint node.hostname!=docker3 --replicas 2 --network host --name xxl-job --publish "mode=host,target=8760,published=8760" 192.168.1.67/spring-cloud/xxl-job:2.0.1

报错信息如下
`10:03:27.837 logback [main] INFO  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@a8eb1a8: startup date [Mon Dec 17 10:03:27 CST 2018]; root of context hierarchy,
10:03:27.923 logback [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 5.3.6.Final,
10:03:30.911 logback [main] INFO  o.s.b.c.e.t.TomcatEmbeddedServletContainer - Tomcat initialized with port(s): 8760 (http),
10:03:30.941 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8760"],
10:03:30.963 logback [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat],
10:03:30.964 logback [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.34,
10:03:31.110 logback [localhost-startStop-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext,
10:03:31.111 logback [localhost-startStop-1] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 3274 ms,
10:03:31.377 logback [localhost-startStop-1] INFO  o.s.b.w.s.ServletRegistrationBean - Mapping servlet: 'dispatcherServlet' to [/],
10:03:31.387 logback [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'characterEncodingFilter' to: [/*],
10:03:31.389 logback [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'hiddenHttpMethodFilter' to: [/*],
10:03:31.389 logback [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'httpPutFormContentFilter' to: [/*],
10:03:31.390 logback [localhost-startStop-1] INFO  o.s.b.w.s.FilterRegistrationBean - Mapping filter: 'requestContextFilter' to: [/*],
10:03:32.922 logback [main] INFO  o.s.s.quartz.SchedulerFactoryBean - Loading Quartz config from [class path resource [quartz.properties]],
10:03:32.982 logback [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor,
10:03:32.993 logback [main] ERROR org.quartz.impl.StdSchedulerFactory - Couldn't generate instance Id!,
org.quartz.SchedulerException: Couldn't get host name!,
	at org.quartz.simpl.SimpleInstanceIdGenerator.generateInstanceId(SimpleInstanceIdGenerator.java:36),
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1235),
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559),
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:634),
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.prepareScheduler(SchedulerFactoryBean.java:574),
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:474),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1689),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481),
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312),
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230),
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308),
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197),
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742),
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867),
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107),
	at com.xxl.job.admin.XxlJobAdminApplication.main(XxlJobAdminApplication.java:13),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:606),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Caused by: java.net.UnknownHostException: 82baed569bcd: 82baed569bcd,
	at java.net.InetAddress.getLocalHost(InetAddress.java:1498),
	at org.quartz.simpl.SimpleInstanceIdGenerator.generateInstanceId(SimpleInstanceIdGenerator.java:34),
	... 31 common frames omitted,
Caused by: java.net.UnknownHostException: 82baed569bcd,
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method),
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:923),
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1318),
	at java.net.InetAddress.getLocalHost(InetAddress.java:1494),
	... 32 common frames omitted,
10:03:32.995 logback [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getSchedulerFactoryBean' defined in class path resource [com/xxl/job/admin/core/conf/XxlJobDynamicSchedulerConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot run without an instance id.,
10:03:33.000 logback [main] INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat],
10:03:33.042 logback [main] INFO  o.s.b.a.l.AutoConfigurationReportLoggingInitializer - ,
,
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.,
10:03:33.050 logback [main] ERROR o.s.boot.SpringApplication - Application startup failed,
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'getSchedulerFactoryBean' defined in class path resource [com/xxl/job/admin/core/conf/XxlJobDynamicSchedulerConfig.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Cannot run without an instance id.,
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1631),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481),
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312),
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230),
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308),
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197),
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742),
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867),
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543),
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122),
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693),
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118),
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107),
	at com.xxl.job.admin.XxlJobAdminApplication.main(XxlJobAdminApplication.java:13),
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:606),
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87),
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50),
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51),
Caused by: java.lang.IllegalStateException: Cannot run without an instance id.,
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1239),
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559),
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:634),
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.prepareScheduler(SchedulerFactoryBean.java:574),
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:474),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1689),
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1627),
	... 24 common frames omitted,`

**Comment by xuxueli** [comment]
你好，这是quartz内部报错，可以参考quartz文档。
