### ISSUE TITLE
NoClassDefFoundError: io/netty/channel/EventLoopGroup

### ISSUE THREAD

**Issue by caibojian** [xuxueli/xxl-job#756]
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServer.start(NettyHttpServer.java:31)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.start(XxlRpcProviderFactory.java:131)
	at com.xxl.job.core.executor.XxlJobExecutor.initRpcProvider(XxlJobExecutor.java:167)
	at com.xxl.job.core.executor.XxlJobExecutor.start(XxlJobExecutor.java:85)
	at com.xuxueli.executor.sample.frameless.config.FrameLessXxlJobConfig.initXxlJobExecutor(FrameLessXxlJobConfig.java:57)
	at com.xuxueli.executor.sample.frameless.Application.main(Application.java:19)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.EventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

### Which version of XXL-JOB do you using?
master版本，启动job-executor报错

**Comment by xuxueli** [comment]
问题无法复现，可以重新pull master分支编译下。（线上使用建议用Release版本）

**Comment by Yxf005** [comment]
同样的问题，source 运行

**Comment by wucanhong** [comment]
> 

展开说说，我不是很明白
