### ISSUE TITLE
测试环境保Java heap space

### ISSUE THREAD

**Issue by nanshandashan** [xuxueli/xxl-job#767]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2

### Expected behavior

2019-02-26 18:03:55.516 [etp1511235671-233]  WARN org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask:337 -
java.lang.OutOfMemoryError: Java heap space
2019-02-26 17:48:24.796 [etp1511235671-281]  WARN org.eclipse.jetty.server.HttpChannel.handleException:585 - /
java.lang.BootstrapMethodError: call site initialization exception
Caused by: java.lang.OutOfMemoryError: Java heap space
2019-02-26 17:02:53.046 [etp1511235671-989]  WARN org.eclipse.jetty.io.ManagedSelector.failed:724 - java.lang.OutOfMemoryError: Java heap space
2019-02-26 17:46:46.188 [etp1511235671-639]  WARN org.eclipse.jetty.server.HttpChannel.handleException:585 - /
java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.eclipse.jetty.server.HttpChannel.notifyDispatchFailure(HttpChannel.java:947)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:368)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space

### Actual behavior

<img width="903" alt="wechatimg225" src="https://user-images.githubusercontent.com/12545302/53408981-d5051c80-39fa-11e9-94c0-4b7e382d35a3.png">

### Other information

**Comment by xuxueli** [comment]
无法复现。
