### ISSUE TITLE
项目在服务器上运行之后线程会自己挂掉

### ISSUE THREAD

**Issue by ZJH17778383963** [xuxueli/xxl-job#769]
[ERROR] [Thread-12] [2019-02-27 11:30:23] com.xxl.job.core.thread.TriggerCallbackThread [79] - null
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:65)
	at java.lang.Thread.run(Thread.java:748)
[INFO ] [Thread-12] [2019-02-27 11:30:23] com.xxl.job.core.thread.TriggerCallbackThread [93] - >>>>>>>>>>> xxl-job, executor callback thread destory.
[WARN ] [Thread-13] [2019-02-27 11:30:23] com.xxl.job.core.thread.TriggerCallbackThread [114] - >>>>>>>>>>> xxl-job, executor retry callback thread interrupted, error msg:sleep interrupted
[INFO ] [Thread-13] [2019-02-27 11:30:23] com.xxl.job.core.thread.TriggerCallbackThread [117] - >>>>>>>>>>> xxl-job, executor retry callback thread destory.
[INFO ] [gcache shutdown hook] [2019-02-27 11:30:23] redis.gcache.core.ZookeeperWatcher [308] - gcache closed ! 
[INFO ] [Thread-35] [2019-02-27 11:30:23] org.eclipse.jetty.server.ServerConnector [306] - Stopped ServerConnector@116d0d65{HTTP/1.1}{0.0.0.0:15207}
[WARN ] [Thread-25] [2019-02-27 11:30:23] com.xxl.job.core.thread.ExecutorRegistryThread [68] - >>>>>>>>>>> xxl-job, executor registry thread interrupted, error msg:sleep interrupted
[ERROR] [Thread-14] [2019-02-27 11:30:23] com.xxl.job.core.thread.ExecutorRegistryThread [108] - null
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1252)
	at java.lang.Thread.join(Thread.java:1326)
	at com.xxl.job.core.thread.ExecutorRegistryThread.toStop(ExecutorRegistryThread.java:106)
	at com.xxl.job.core.executor.XxlJobExecutor$ExecutorServiceRegistry.stop(XxlJobExecutor.java:167)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory$2.run(XxlRpcProviderFactory.java:105)
	at com.xxl.rpc.remoting.net.Server.onStoped(Server.java:63)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer.stop(JettyServer.java:86)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServer$1.run(JettyServer.java:58)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ZJH17778383963** [comment]
麻烦帮我看看  谢谢

**Comment by ZJH17778383963** [comment]
一天多的时候会报大概4次这个错误，有时候恰好碰到任务执行，就就会直接抛sql异常，生产环境下这个是很致命的

**Comment by xuxueli** [comment]
你好，问题无法复现。可以给应用加监控，确认是否存在内存不足、内存泄露等问题。

**Comment by Emors** [comment]
我也遇到这个问题了。部分报错信息，同问~ 
2019-04-28 22:54:45.119 [Thread-29] INFO  - org.springframework.integration.endpoint.EventDrivenConsumer:154 - stopped _org.springframework.integration.errorLogger
2019-04-28 22:54:45.119 [Thread-29] INFO  - org.springframework.context.support.DefaultLifecycleProcessor:358 - Stopping beans in phase -2147482648
2019-04-28 22:54:45.120 [Thread-24] WARN  - com.xxl.job.core.thread.ExecutorRegistryThread:77 - >>>>>>>>>>> xxl-job, executor registry thread interrupted, error msg:sleep interrupted
2019-04-28 22:54:45.168 [Thread-25] ERROR - com.xxl.job.core.thread.TriggerCallbackThread:79 - null
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:65)
        at java.lang.Thread.run(Thread.java:748)
2019-04-28 22:54:45.169 [Thread-26] WARN  - com.xxl.job.core.thread.TriggerCallbackThread:114 - >>>>>>>>>>> xxl-job, executor retry callback thread interrupted, error msg:sleep interrupted

**Comment by tom055** [comment]
我打包的时候也遇到了 跑到时候不会

**Comment by CodePlayer** [comment]
> 你好，问题无法复现。可以给应用加监控，确认是否存在内存不足、内存泄露等问题。

我这边已经可以复现了，复现常见是：动态修改 Nacos 的配置，从而触发 `ApplicationContext` Refresh，导致原有的 `ApplicationContext`  会被关闭掉，进而触发 `XxlJobSpringExecutor` （ 实现了 `DisposableBean` 接口）的 `destroy()` 方法。
该方法就会关闭当前应用节点的 XXL-JOB。

**Comment by CodePlayer** [comment]
@xuxueli 
只要存在类似的导致 ApplicationContext Refresh 的场景，都可能导致该问题。

解决方法是：`XxlJobSpringExecutor` 不再实现 `DisposableBean` 接口，改为实现 `ApplicationListener<ContextClosedEvent>` 接口。
