### ISSUE TITLE
java.io.IOException: 没有那个文件或目录

### ISSUE THREAD

**Issue by HuboryChen** [xuxueli/xxl-job#794]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
1.9.2
使用Spring执行器

### Expected behavior
正常的写入执行日志

### Actual behavior
18:56:34.885 [Thread-19] ERROR com.xxl.job.core.log.XxlJobFileAppender - 没有那个文件或目录
java.io.IOException: 没有那个文件或目录
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1006)
        at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104)
        at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43)
        at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66)
        at com.xxl.job.core.thread.JobThread.run(JobThread.java:158)
18:56:34.886 [Thread-19] DEBUG com.xxl.job.core.thread.TriggerCallbackThread - >>>>>>>>>>> xxl-job, push callback request, logId:115817

### Steps to reproduce the behavior
xxl.job.executor.logpath={tomcat日志路径}/xxl-job/jobhandler

### Other information

**Comment by anodxy** [comment]
你好，我的项目本来运行正常，突然报你同样的错误，请问是什么原因，怎么解决的 @HuboryChen

**Comment by anodxy** [comment]
log文件目录，权限不对造成的。

**Comment by guotie** [comment]
有啊

**Comment by guotie** [comment]
必须创建/data/applogs目录，这个提示太糟糕了

**Comment by justde** [comment]
> 必须创建/data/applogs目录，这个提示太糟糕了

你对 项目跟这个目录有关联么？创建这个目录就好了么

**Comment by 2a588** [comment]
我的也是macos 在对应的服务里配置对应的 xxljob 的日志路径是本地路径即可。
用的是springcloud-alibaba   用的配置文件是 yml 
在项目对应目录下的 bootstrap-dev.yml  增加对应的logpath  配置

xxl:
  job:
    executor:
      appname: @artifactId@
      logpath: /Users/aaabbbcc/logs
