### ISSUE TITLE
集成springboot2.1.3 报错。

### ISSUE THREAD

**Issue by clverhack** [xuxueli/xxl-job#798]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0.2-SNAPSHO
### Expected behavior

无错正常运行

### Actual behavior
22:53:37.416 logback [nioEventLoopGroup-5-1] ERROR c.x.r.r.n.i.n.c.NettyHttpClientHandler - >>>>>>>>>>> xxl-rpc netty_http client caught exception
java.lang.ClassCastException: java.lang.Long cannot be cast to com.xxl.rpc.remoting.net.params.XxlRpcResponse
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClientHandler.channelRead0(NettyHttpClientHandler.java:43)
### Other information

**Comment by LjxFaighting** [comment]
是啊，求解决. 的admin升级boot为2.1.3-RELEASE后报这个错.

**Comment by likenamehaojie** [comment]
有谁解决了么？Netty组装Http 调用api报 400错误，应该是错误的参数，但是api这个控制口中只有request,和response两个参数，不应该会报错400啊，

**Comment by xuxueli** [comment]
问题合并至：https://github.com/xuxueli/xxl-job/issues/808

该问题已经尝试修复，并发布新版 v2.0.2，可以升级最新Release版本确认问题修复状况：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2

**Comment by Hi-mazhen** [comment]
springboot  2.1.3.RELEASE
xxl-job使用2.0.2版本
`implementation group: 'com.xuxueli', name: 'xxl-job-core', version: '2.0.2'`
报错：（与使用netty和swagger2有关系吗？）
`2019-05-10 17:09:56.678 - INFO  [  restartedMain] edRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
springfox.documentation.service.Contact@130ecdad
springfox.documentation.service.Contact@35e804cd
springfox.documentation.service.Contact@353ae614
2019-05-10 17:09:56.709 - INFO  [  restartedMain] c.l.c.O.x.XxlJobConfig         : >>>>>>>>>>> xxl-job config init.
2019-05-10 17:09:56.747 - INFO  [  restartedMain] .x.r.r.p.XxlRpcProviderFactory : >>>>>>>>>>> xxl-rpc, provider factory add service success. serviceKey = com.xxl.job.core.biz.ExecutorBiz, serviceBean = class com.xxl.job.core.biz.impl.ExecutorBizImpl
2019-05-10 17:09:56.849 - INFO  [      Thread-22] .r.r.n.i.n.s.NettyHttpServer$1 : >>>>>>>>>>> xxl-rpc remoting server start success, nettype = com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServer, port = 9999
2019-05-10 17:09:56.902 - INFO  [rRegistryThread] .r.r.i.r.XxlRpcReferenceBean$1 : >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.168.1.103:8098/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='f7ed159f-c539-4c7f-903a-f13b89c2d768', createMillisTime=1557479396852, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='quartz-xxl-demo', registryValue='192.168.1.103:9999'}], version='null'}
2019-05-10 17:09:56.903 - INFO  [rRegistryThread] j.c.t.ExecutorRegistryThread$1 : >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='quartz-xxl-demo', registryValue='192.168.1.103:9999'}
com.xxl.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /192.168.1.103:8098
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227) ~[xxl-rpc-core-1.4.0.jar:?]
	at com.sun.proxy.$Proxy132.registry(Unknown Source) ~[?:?]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) [xxl-job-core-2.0.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /192.168.1.103:8098
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_191]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_191]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	... 1 more
2019-05-10 17:09:57.018 - WARN  [  restartedMain] b.d.a.OptionalLiveReloadServer : Unable to start LiveReload server
2019-05-10 17:09:57.377 - INFO  [  restartedMain] cumentationPluginsBootstrapper : Context refreshed
2019-05-10 17:09:57.386 - INFO  [  restartedMain] cumentationPluginsBootstrapper : Found 3 custom documentation plugin(s)
2019-05-10 17:09:57.412 - INFO  [  restartedMain] w.s.ApiListingReferenceScanner : Scanning for api listing references
2019-05-10 17:09:57.425 - INFO  [  restartedMain] w.s.ApiListingReferenceScanner : Scanning for api listing references
2019-05-10 17:09:57.487 - INFO  [  restartedMain] w.s.ApiListingReferenceScanner : Scanning for api listing references
2019-05-10 17:09:57.934 - INFO  [  restartedMain] .CachingOperationNameGenerator : Generating unique operation named: testInsertUsingGET_1
2019-05-10 17:09:57.943 - INFO  [  restartedMain] o.a.j.l.DirectJDKLog           : Starting ProtocolHandler ["http-nio-8099"]
2019-05-10 17:09:57.981 - INFO  [  restartedMain] o.s.b.w.e.t.TomcatWebServer    : Tomcat started on port(s): 8099 (http) with context path '/lswdz'
2019-05-10 17:09:58.085 - INFO  [  restartedMain] o.s.b.StartupInfoLogger        : Started DevlabApplication in 8.19 seconds (JVM running for 11.517)
TCP端Netty通信服务端启动成功！端口：2019
2019-05-10 17:09:58.101 - WARN  [      Thread-30] i.n.b.AbstractBootstrap        : Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0xc7c17af9]'
2019-05-10 17:09:58.401 - WARN  [      Thread-30] i.n.b.AbstractBootstrap        : Unknown channel option 'TCP_NODELAY' for channel '[id: 0xc7c17af9]'
2019-05-10 17:10:26.909 - INFO  [rRegistryThread] .r.r.i.r.XxlRpcReferenceBean$1 : >>>>>>>>>>> xxl-rpc, invoke error, address:http://192.168.1.103:8098/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='9c2c346e-f84d-46c2-ba9c-971a7fb6cf07', createMillisTime=1557479426907, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='quartz-xxl-demo', registryValue='192.168.1.103:9999'}], version='null'}
2019-05-10 17:10:26.929 - INFO  [rRegistryThread] j.c.t.ExecutorRegistryThread$1 : >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='quartz-xxl-demo', registryValue='192.168.1.103:9999'}
com.xxl.rpc.util.XxlRpcException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /192.168.1.103:8098
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227) ~[xxl-rpc-core-1.4.0.jar:?]
	at com.sun.proxy.$Proxy132.registry(Unknown Source) ~[?:?]
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48) [xxl-job-core-2.0.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /192.168.1.103:8098
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_191]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_191]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_191]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	... 1 more`
