### ISSUE TITLE
配置都配置上了但还是报错，是不是1.9.2的客户端不能兼容2.0.2的服务端吗

### ISSUE THREAD

**Issue by shinynz** [xuxueli/xxl-job#800]
2019-03-27 13:21:40.231 | INFO |[Thread-12] c.x.j.c.t.ExecutorRegistryThread [66] | &gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='bms-service-biz', registryValue='172.24.2.205:9991'}
java.lang.RuntimeException: Network request error: unknown code for readObject at 0x63 (c)
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:64)
	at com.sun.proxy.$Proxy175.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 13:22:10.242 | ERROR|[Thread-12] c.x.j.c.r.n.jetty.client.JettyClient [40] | unknown code for readObject at 0x63 (c)
java.lang.IllegalStateException: unknown code for readObject at 0x63 (c)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:33)
	at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:37)
	at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
	at com.sun.proxy.$Proxy175.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:57)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.caucho.hessian.io.HessianProtocolException: unknown code for readObject at 0x63 (c)
	at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1697)
	at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1177)
	at com.xxl.job.core.rpc.serialize.HessianSerializer.deserialize(HessianSerializer.java:31)
	... 5 common frames omitted

**Comment by letingoo** [comment]
好像是这样，我用2.0.1都连不上，改成2.0.2才连上

**Comment by willingSi** [comment]
+1

**Comment by bugmeng** [comment]
你用的是一个core么？

**Comment by youbeiwuhuan** [comment]
应该不能，我看到1.9.2通信用的是http，而2.0.2通信用的是xxl-rpc

**Comment by xuxueli** [comment]
你好，是的，高版本通讯方案有调整。
