### ISSUE TITLE
调度中心配https，则执行器无法注册

### ISSUE THREAD

**Issue by letingoo** [xuxueli/xxl-job#802]
使用的版本是2.0.2
调度中心配的是https的url，执行器注册时报错

> 2019-03-28 17:29:59.653 INFO  c.x.r.r.i.r.XxlRpcReferenceBean:165 [Thread-24] - >>>>>>>>>>> xxl-job, invoke error, address:https://abcde.net/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='335d316a-80c4-46a4-83e8-65cc05da613a', createMillisTime=1553765399596, accessToken='null', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='upload-ring-tos-executor', registryValue='10.92.234.78:9994'}], version='null'}
2019-03-28 17:29:59.653 INFO  c.x.j.c.t.ExecutorRegistryThread:57 [Thread-24] - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='upload-ring-tos-executor', registryValue='10.92.234.78:9994'}
com.xxl.rpc.util.XxlRpcException: java.lang.NullPointerException
	at org.eclipse.jetty.io.ssl.SslClientConnectionFactory.newConnection(SslClientConnectionFactory.java:70)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.newConnection(AbstractConnectorHttpClientTransport.java:172)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:208)
	at org.eclipse.jetty.io.ManagedSelector.access$1600(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:650)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)

	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
	at com.sun.proxy.$Proxy78.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bugmeng** [comment]
世间变化太快，作者一个人已经扛不住了

**Comment by xuxueli** [comment]
@letingoo 推荐实用xxl-job内置的通讯方案，采用IP自动注册的方式。不需要采用https的啊。
@bugmeng 0.0

**Comment by zhangqiang-hub** [comment]
@xuxueli  请问上面找个你说的方案 具体怎么实施，我现在是换成https报错：com.xxl.rpc.util.XxlRpcException: java.lang.NullPointerException: Missing SslContextFactory
