### ISSUE TITLE
xxl-job-admin升级为spring-boot 2.0+后 xxl-rpc组件注册handler时超时

### ISSUE THREAD

**Issue by likenamehaojie** [xuxueli/xxl-job#808]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0+
### Actual behavior
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1554270309434, request:XxlRpcRequest{requestId='5eb59239-383a-4429-b8fe-e1f50ff0fede', createMillisTime=1554270254571, accessToken='null', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-example', registryValue='127.0.0.1:9999'}], version='null'}
	at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
	at com.sun.proxy.$Proxy4.registry(Unknown Source)
	at com.xxl.job.adminbiz.AdminBizTest.registryTest(AdminBizTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
13:45:32.658 logback [main] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:http://127.0.0.1:8080/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='5eb59239-383a-4429-b8fe-e1f50ff0fede', createMillisTime=1554270254571, accessToken='null', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-example', 
### Other information

**Comment by likenamehaojie** [comment]
该问题已经解决，代码已经pull到xxl-rpc项目中（该项目中的NettyHttpClient)引起的注册失败，导致超时

**Comment by xuxueli** [comment]
@likenamehaojie 你好，xxl-rpc以合并你的请求并发布新版。xxl-job已经升级最新版xxl-rpc，并尝试修复该问题。

XXL-JOB已经发布新版 v2.0.2，可以升级最新Release版本确认问题修复状况：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2

**Comment by xuxueli** [comment]
@likenamehaojie  期待你的测试结果！

**Comment by likenamehaojie** [comment]
我这边测试已经通过可能正常注册

**Comment by xuxueli** [comment]
@likenamehaojie 感谢反馈啊！
