### ISSUE TITLE
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '63'

### ISSUE THREAD

**Issue by ZeroCheney** [xuxueli/xxl-job#815]
Please answer some questions before submitting your issue. Thanks!

### springboot 2.1.3版本

17:45:49.327 logback [Thread-44] INFO  c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-job, invoke error, address:localhost:8990/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='089cbe43-e4a3-4ff0-9a88-2c568268c87b', createMillisTime=1554803148537, accessToken='', className='com.goteam.core.job.biz.AdminBiz', methodName='registry', parameterTypes=[class com.goteam.core.job.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.1.108:9999'}], version='null'}
17:45:49.332 logback [Thread-44] INFO  c.g.c.j.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='192.168.1.108:9999'}
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '63'
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2943)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2135)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	at com.xxl.rpc.remoting.net.impl.jetty.client.JettyClient$1.onComplete(JettyClient.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:416)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:316)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1165)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1525)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:161)
	at com.sun.proxy.$Proxy159.registry(Unknown Source)
	at com.goteam.core.job.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)

启动时报错。。有遇到的么

**Comment by xuxueli** [comment]
检查执行器注册地址是否配错。

**Comment by xuxueli** [comment]
你好，请升级最新Release版本：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2

**Comment by xuebingchen** [comment]
升级2.0.2后出现这个，问下什原因导致的
Caused by: com.caucho.hessian.io.HessianProtocolException: No classes defined at reference '6d'

**Comment by xuyaokun-github** [comment]
我也遇到这个报错了，No classes defined at reference '6f'。我的xxl版本是2.1.2. 请问是什么问题？

**Comment by xuyaokun-github** [comment]
我也遇到这个报错了，No classes defined at reference '6f'。我的xxl版本是2.1.2. 请问是什么问题？
