### ISSUE TITLE
com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74

### ISSUE THREAD

**Issue by koftt** [xuxueli/xxl-job#822]
xxl-job两台不同服务器
 一个放xxl-job-admin  一个放xxl-job-executor-sample-springboot
定时任务是执行成功了，但是总是报如下错误？？？
2019-04-12 07:11:10,342 ERROR [xxl-rpc, NettyHttpServer-serverHandlerPool-1607113567] c.x.r.r.n.i.n.s.NettyHttpServerHandler [NettyHttpServerHandler.java : 95] com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:52)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:82)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.caucho.hessian.io.HessianProtocolException: expected integer at 0x74
	at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2952)
	at com.caucho.hessian.io.Hessian2Input.expect(Hessian2Input.java:2900)
	at com.caucho.hessian.io.Hessian2Input.readInt(Hessian2Input.java:834)
	at com.caucho.hessian.io.Hessian2Input.readType(Hessian2Input.java:2447)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2124)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)

**Comment by xuxueli** [comment]
你好，master分支为快照版本，请实用release版本；

**Comment by xuxueli** [comment]
你好，请升级最新Release版本：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2

**Comment by koftt** [comment]
好的 感谢


 
---Original---
