### ISSUE TITLE
executor项目 springboot2.0.1RELEASE, xxl-job-core2.0.1启动报错xxlJobExecutor

### ISSUE THREAD

**Issue by bluebig** [xuxueli/xxl-job#827]
Error creating bean with name 'xxlJobExecutor' defined in class path resource [xxljob/ms/allot/XxlJobConfig.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: groovy/lang/GroovyClassLoader
executor项目 springboot2.0.1RELEASE,
 xxl-job-core2.0.1

**Comment by bluebig** [comment]
@Bean(initMethod = "start", destroyMethod = "destroy")
    public XxlJobExecutor xxlJobSpringExecutor() {
        logger.info(">>>>>>>>>>> xxl-job config init.");
        XxlJobExecutor xxlJobSpringExecutor = new XxlJobExecutor();
        xxlJobSpringExecutor.setAdminAddresses(adminAddresses);
        xxlJobSpringExecutor.setAppName(appName);
        xxlJobSpringExecutor.setIp(ip);
        xxlJobSpringExecutor.setPort(port);
        xxlJobSpringExecutor.setAccessToken(accessToken);
        xxlJobSpringExecutor.setLogPath(logPath);
        xxlJobSpringExecutor.setLogRetentionDays(logRetentionDays);

        return xxlJobSpringExecutor;
    }

**Comment by qwe857359351a** [comment]
你这是缺jar包或者jar包的版本不对，也有可能jar包冲突，找不到GroovyClassLoader类

**Comment by bluebig** [comment]
> 你这是缺罐包或者罐子包的版本不对，也有可能罐包冲突，找不到GroovyClassLoader类

springboot 1.5.9的没问题，springboot2.0后就有这个问题

**Comment by xuxueli** [comment]
应该是缺少依赖，可以确认下依赖树里是否包含 groovy 库。

**Comment by xuxueli** [comment]
请升级最新Release版本：https://github.com/xuxueli/xxl-job/releases/tag/2.0.2

**Comment by vasummer** [comment]
sping 2.1.5.RELEASE
xxl-job-core 2.2.0  报同样错误

**Comment by vasummer** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-31 11:36:14 [restartedMain] [ERROR] org.springframework.boot.SpringApplication:858 - Application run failed
java.lang.NoClassDefFoundError: groovy/lang/GroovyClassLoader
	at com.xxl.job.core.glue.GlueFactory.<init>(GlueFactory.java:36)
	at com.xxl.job.core.glue.GlueFactory.<clinit>(GlueFactory.java:20)
	at com.xxl.job.core.executor.impl.XxlJobSpringExecutor.afterSingletonsInstantiated(XxlJobSpringExecutor.java:42)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:860)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.cdeledu.finance.PayApplication.main(PayApplication.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 common frames omitted
