### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by SailfishAAA** [xuxueli/xxl-job#83]
注册方式：手动录入
阻塞处理策略：单机串行
失败处理策略：失败告警
地址列表：[136.64.196.145:9999]
----------------------
触发调度：
address：136.64.196.145:9999
code：500
msg：java.lang.RuntimeException: Client-error:Connect to 136.64.196.145:9999 [/136.64.196.145] failed: Connection refused

linux环境，1.7版本，请教，谢谢

**Comment by xuxueli** [comment]
你好，感谢关注啊！
这种情况有几种可能，你参考一下啊：
1、执行器未启动；
2、执行器9999端口被防火墙拦截，ping不通；

**Comment by SailfishAAA** [comment]
145那台是weblogic部署的，现在换到了146的tomcat部署，
错误变成了Connection reset

注册方式：手动录入
阻塞处理策略：单机串行
失败处理策略：失败告警
地址列表：[136.64.196.146:9999]
----------------------
触发调度：
address：136.64.196.146:9999
code：500
msg：java.lang.RuntimeException: Client-error:Connection reset

Jun 16, 2017 6:32:50 PM com.xxl.job.admin.core.jobbean.RemoteHttpJobBean runExecutor
SEVERE: 
java.lang.RuntimeException: Client-error:Connection reset
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:56)
        at com.sun.proxy.$Proxy780.run(Unknown Source)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.runExecutor(RemoteHttpJobBean.java:199)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.doTrigger(RemoteHttpJobBean.java:122)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:73)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

<Jun 16, 2017, 6:32:50,16 PM CST> <Error> <com.xxl.job.admin.core.jobbean.RemoteHttpJobBean> <BEA-000000> <
java.lang.RuntimeException: Client-error:Connection reset
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:56)
        at com.sun.proxy.$Proxy780.run(Unknown Source)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.runExecutor(RemoteHttpJobBean.java:199)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.doTrigger(RemoteHttpJobBean.java:122)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:73)
        Truncated. see log file for complete stacktrace

**Comment by xuxueli** [comment]
你好，这个地址浏览器直接请求的结果是什么啊？怀疑这个端口的执行器没有正常启动。

**Comment by QinRoc** [comment]
@xuxueli 你好，我也遇到了Connection reset错误。
错误日志：

> 2017-12-20 11:52:51 xxl-job-admin [com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler]-[http-bio-9099-exec-5]-[pauseJob]-[296]-[INFO] >>>>>>>>>>> pauseJob success, triggerKey:4.4
2017-12-20 11:53:23 xxl-job-admin [com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler]-[http-bio-9099-exec-3]-[resumeJob]-[319]-[INFO] >>>>>>>>>>> resumeJob success, triggerKey:4.4
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler]-[http-bio-9099-exec-3]-[triggerJob]-[342]-[INFO] >>>>>>>>>>> runJob success, jobKey:4.4
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.core.util.HttpClientUtil]-[quartzScheduler_Worker-5]-[postRequest]-[67]-[ERROR] Connection reset
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at com.xxl.job.core.util.HttpClientUtil.postRequest(HttpClientUtil.java:60)
        at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:29)
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
        at com.sun.proxy.$Proxy62.idleBeat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteBusyover.routeRun(ExecutorRouteBusyover.java:30)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:165)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.core.rpc.netcom.jetty.client.JettyClient]-[quartzScheduler_Worker-5]-[send]-[40]-[ERROR] Connection reset
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at com.xxl.job.core.util.HttpClientUtil.postRequest(HttpClientUtil.java:60)
        at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:29)
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
        at com.sun.proxy.$Proxy62.idleBeat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteBusyover.routeRun(ExecutorRouteBusyover.java:30)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:165)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.admin.core.route.ExecutorRouter]-[quartzScheduler_Worker-5]-[routeRun]-[32]-[ERROR] Client-error:Connection reset
java.lang.RuntimeException: Client-error:Connection reset
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:65)
        at com.sun.proxy.$Proxy62.idleBeat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteBusyover.routeRun(ExecutorRouteBusyover.java:30)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:165)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.core.util.HttpClientUtil]-[quartzScheduler_Worker-5]-[postRequest]-[67]-[ERROR] Connection reset
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at com.xxl.job.core.util.HttpClientUtil.postRequest(HttpClientUtil.java:60)
        at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:29)
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
        at com.sun.proxy.$Proxy62.idleBeat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteBusyover.routeRun(ExecutorRouteBusyover.java:30)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:170)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.core.rpc.netcom.jetty.client.JettyClient]-[quartzScheduler_Worker-5]-[send]-[40]-[ERROR] Connection reset
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:196)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at com.xxl.job.core.util.HttpClientUtil.postRequest(HttpClientUtil.java:60)
        at com.xxl.job.core.rpc.netcom.jetty.client.JettyClient.send(JettyClient.java:29)
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:57)
        at com.sun.proxy.$Proxy62.idleBeat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteBusyover.routeRun(ExecutorRouteBusyover.java:30)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:170)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2017-12-20 11:53:30 xxl-job-admin [com.xxl.job.admin.core.route.ExecutorRouter]-[quartzScheduler_Worker-5]-[routeRun]-[32]-[ERROR] Client-error:Connection reset
java.lang.RuntimeException: Client-error:Connection reset
        at com.xxl.job.core.rpc.netcom.NetComClientProxy$1.invoke(NetComClientProxy.java:65)
        at com.sun.proxy.$Proxy62.idleBeat(Unknown Source)
        at com.xxl.job.admin.core.route.strategy.ExecutorRouteBusyover.routeRun(ExecutorRouteBusyover.java:30)
        at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:170)
        at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:29)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:114)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

应用日志：

>98 traceid:[][INFO ][11:13:57,180][core.executor.XxlJobExecutor]>>>>>>>>>>> xxl-job register jobhandler success, name:xx, jobHandler:xx@230c3859
     99 traceid:[][INFO ][11:13:57,181][core.executor.XxlJobExecutor]>>>>>>>>>>> xxl-job register jobhandler success, name:xx, jobHandler:xx@77476d08
    100 traceid:[][INFO ][11:13:57,234][jetty.util.log]Logging initialized @62555845ms
    101 traceid:[][INFO ][11:13:57,314][jetty.server.Server]jetty-9.2.22.v20170606
    102 traceid:[][INFO ][11:13:57,345][jetty.server.ServerConnector]Started ServerConnector@731018d0{HTTP/1.1}{0.0.0.0:9999}
    103 traceid:[][INFO ][11:13:57,345][jetty.server.Server]Started @62555961ms
    104 traceid:[][INFO ][11:13:57,345][jetty.server.JettyServer]>>>>>>>>>>>> xxl-job jetty server start success at port:9999.
    105 traceid:[][INFO ][11:13:57,554][core.thread.ExecutorRegistryThread]>>>>>>>>>>> xxl-job registry success, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xx', registryValue='172.20.4.233:9999'}, registryResult:ReturnT [code=200, msg=null, content=null]

浏览器直接请求配置文件中地址和端口显示

> 该网页无法正常运作
172.20.4.233 未发送任何数据。
ERR_EMPTY_RESPONSE

**Comment by QinRoc** [comment]
问题解决了，是tomcat版本的问题。
之前用的tomcat6，会出现说的问题，改到tomcat7就可以了。
可能是依赖tomcat7里面的servlet？
