### ISSUE TITLE
操作XXL_JOB_QRTZ_TRIGGER_REGISTRY表时死锁

### ISSUE THREAD

**Issue by shaojava** [xuxueli/xxl-job#846]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
任务空闲时大量死锁异常 都是操作的XXL_JOB_QRTZ_TRIGGER_REGISTRY表
### Expected behavior
2019-04-28 00:24:59,715 ERROR [http-nio-8081-exec-6] c.x.j.a.service.impl.AdminBizImpl [AdminBizImpl.java : 124] AdminBizImpl registry:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-rank', registryValue='47.99.119.211:29995'}
org.springframework.dao.DeadlockLoserDataAccessException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.xxl.job.admin.service.impl.AdminBizImpl.registry(AdminBizImpl.java:124)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:198)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServerHandler.handle(JettyServerHandler.java:60)
	at com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler.invokeAdminService(XxlJobDynamicScheduler.java:113)
	at com.xxl.job.admin.controller.JobApiController.api(JobApiController.java:30)
2019-04-28 00:25:49,843 ERROR [http-nio-8081-exec-8] c.x.j.a.service.impl.AdminBizImpl [AdminBizImpl.java : 124] AdminBizImpl registry:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-rank', registryValue='47.99.119.211:29996'}
org.springframework.dao.DeadlockLoserDataAccessException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.xxl.job.admin.service.impl.AdminBizImpl.registry(AdminBizImpl.java:124)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:198)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServerHandler.handle(JettyServerHandler.java:60)
	at com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler.invokeAdminService(XxlJobDynamicScheduler.java:113)
	at com.xxl.job.admin.controller.JobApiController.api(JobApiController.java:30)
2019-04-28 00:25:59,866 ERROR [http-nio-8081-exec-10] c.x.j.a.service.impl.AdminBizImpl [AdminBizImpl.java : 124] AdminBizImpl registry:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-rank', registryValue='47.99.119.211:29995'}
org.springframework.dao.DeadlockLoserDataAccessException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.xxl.job.admin.service.impl.AdminBizImpl.registry(AdminBizImpl.java:124)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xxl.rpc.remoting.provider.XxlRpcProviderFactory.invokeService(XxlRpcProviderFactory.java:198)
	at com.xxl.rpc.remoting.net.impl.jetty.server.JettyServerHandler.handle(JettyServerHandler.java:60)
	at com.xxl.job.admin.core.schedule.XxlJobDynamicScheduler.invokeAdminService(XxlJobDynamicScheduler.java:113)
	at com.xxl.job.admin.controller.JobApiController.api(JobApiController.java:30)
2019-04-28 00:26:19,928 ERROR [xxl-job, admin JobRegistryMonitorHelper] c.x.j.a.c.t.JobRegistryMonitorHelper [JobRegistryMonitorHelper.java : 78] >>>>>>>>>>> xxl-job, job registry monitor thread error:{}
org.springframework.dao.DeadlockLoserDataAccessException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
### Other information

**Comment by shaojava** [comment]
执行器监控线程 removeDead锁表操作 与 执行器心跳注册线程 AdminBizImpl registry 操作会造成死锁
我的修改
//XxlJobAdminConfig.getAdminConfig().getXxlJobRegistryDao().removeDead(RegistryConfig.DEAD_TIMEOUT); TODO 删除无索引数据造成锁表 发生死锁异常
							List<XxlJobRegistry> list = XxlJobAdminConfig.getAdminConfig().getXxlJobRegistryDao().findAllDead(RegistryConfig.DEAD_TIMEOUT);
							if (list != null && list.size() > 0) {
								for (XxlJobRegistry item : list) {
									XxlJobAdminConfig.getAdminConfig().getXxlJobRegistryDao().registryDelete(item.getRegistryGroup(), item.getRegistryKey(), item.getRegistryValue());
								}
							}
尽量不要锁表 建立索引 idx_registry_value

**Comment by xuxueli** [comment]
你好，master分支已经为表 "XXL_JOB_QRTZ_TRIGGER_REGISTRY" 默认添加一条索引，如下：
```
KEY `i_g_k_v` (`registry_group`,`registry_key`,`registry_value`)
```
可以先尝试添加下，看下效果。
