### ISSUE TITLE
关于shell脚本任务，找不到shell文件

### ISSUE THREAD

**Issue by haha256290** [xuxueli/xxl-job#86]
`2017-06-23 11:39:31 [com.xxl.job.core.thread.JobThread]-[run]-[123]-[Thread-9] JobThread Exception:java.io.FileNotFoundException: /home/OtherPlatForm/xxlhandergluesource/16_1498189158000.sh (没有那个文件或目录)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.(FileOutputStream.java:213)
	at java.io.FileOutputStream.(FileOutputStream.java:101)
	at com.xxl.job.core.util.ScriptUtil.markScriptFile(ScriptUtil.java:45)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:47)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:111)

2017-06-23 11:39:31 [com.xxl.job.core.thread.JobThread]-[run]-[128]-[Thread-9] ----------- xxl-job job execute end ----------- 
 Look : ExecutorParams:null, Code:500, Msg:java.io.FileNotFoundException: /home/OtherPlatForm/xxlhandergluesource/16_1498189158000.sh (没有那个文件或目录)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.(FileOutputStream.java:213)
	at java.io.FileOutputStream.(FileOutputStream.java:101)
	at com.xxl.job.core.util.ScriptUtil.markScriptFile(ScriptUtil.java:45)
	at com.xxl.job.core.handler.impl.ScriptJobHandler.execute(ScriptJobHandler.java:47)
	at com.xxl.job.core.thread.JobThread.run(JobThread.java:111)
`
的确没有生成shell文件。请问应该如何配置才能正确执行shell脚本？

**Comment by phoenixshen** [comment]
此问题需要配置  执行器属性中的 log path到一个正确的本地路径
xxl-job/xxl-job-executor-example/src/main/resources/xxl-job-executor.properties
中的
xxl.job.executor.logpath=

**Comment by ColorfulGhost** [comment]
執行Web IDE的內容 是保存在xxlhandergluesource下 ，但是我想和自己的其他腳本進行關聯如何关联，对命名有什么要求？

**Comment by xuxueli** [comment]
@haha256290 @phoenixshen  你好，首先需要确认郑培配置了 log路径。除此之外，确认下是否拥有该路径的 读写 权限。

**Comment by xuxueli** [comment]
@ColorfulGhost  XXL-JOB 执行器测的脚本为常规脚本，并没有特殊定制，对命名没有特殊要求，但是会根据时间戳自动变更脚本名称。

**Comment by ColorfulGhost** [comment]
能不能设定针对某路径下的脚本文件执行？只能运行根据时间戳生成的脚本吗？

**Comment by xuxueli** [comment]
@ColorfulGhost 你好，你的意思是不希望通过Web IDE开发shell脚本，希望运行磁盘上的某个脚本？
支持的，可以在Web IDE里通过shell代码做下中转，调用期望调用的指定脚本即可。

**Comment by wukefang** [comment]
windows平台貌似不行，我换成linux 就好了
