### ISSUE TITLE
这个classnotfound是什么造成的

### ISSUE THREAD

**Issue by jaoyina** [xuxueli/xxl-job#868]
系统里我就引用了一个 xxl -job -core的jar包, 最近的2.0.2版本

Exception in thread "xxl-job, executor ExecutorRegistryThread" java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaderNames
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:104)
	at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
	at com.sun.proxy.$Proxy40.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpHeaderNames
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1309)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1138)
	... 7 more

**Comment by xuxueli** [comment]
你好，建议使用release版本，不要使用master快照分支。
