### ISSUE TITLE
偶尔报注册失败 xxl-job registry error

### ISSUE THREAD

**Issue by l36t** [xuxueli/xxl-job#909]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
2.0。2
### Expected behavior
正常注册执行器
### Actual behavior
偶尔报注册失败
16:44:16.375 logback [xxl-job, executor ExecutorRegistryThread] INFO  c.x.j.c.t.ExecutorRegistryThread - >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-executor-sample', registryValue='127.0.0.1:9999'}
com.xxl.rpc.util.XxlRpcException: io.netty.channel.ExtendedClosedChannelException
        at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227)
        at com.sun.proxy.$Proxy54.registry(Unknown Source)
        at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.ExtendedClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
### Other information

**Comment by xuxueli** [comment]
你好，问题不能复现，这种情况推测是网络抖动导致。
