### ISSUE TITLE
执行器持续报错 : xxl-rpc request data empty.

### ISSUE THREAD

**Issue by hylexus** [xuxueli/xxl-job#915]
您好，我们这边遇到一个问题，麻烦您抽空解答一下：
2.0.2版本，部署后任务能正常调度，但是执行器持续报错。报错如下：

```sh
2019-06-03 11:21:30.629 ERROR 1 --- [rPool-886176539] c.x.r.r.n.i.n.s.NettyHttpServerHandler   : xxl-rpc request data empty.

com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:78) [xxl-rpc-core-1.4.0.jar!/:?]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27) [xxl-rpc-core-1.4.0.jar!/:?]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51) [xxl-rpc-core-1.4.0.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by hylexus** [comment]
这是另一个执行器的日志：
```sh
2019-06-03 02:14:30.209 ERROR 1 --- [Pool-1069643970] c.x.r.r.n.i.n.s.NettyHttpServerHandler   : xxl-rpc request data empty.

com.xxl.rpc.util.XxlRpcException: xxl-rpc request data empty.
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:78) [xxl-rpc-core-1.4.0.jar!/:?]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27) [xxl-rpc-core-1.4.0.jar!/:?]
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51) [xxl-rpc-core-1.4.0.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

2019-06-03 02:14:30.477 ERROR 1 --- [ntLoopGroup-3-2] c.x.r.r.n.i.n.s.NettyHttpServerHandler   : >>>>>>>>>>> xxl-rpc provider netty server caught exception

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_131]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_131]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_131]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_131]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_131]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125) ~[netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by hylexus** [comment]
发现是运维同学配置的健康检查导致的非法请求

**Comment by geutopia** [comment]
怎么解决的?  详细说明一下, 我这也有同样的错误

**Comment by hylexus** [comment]
@geutopia 

xxl-core: com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler#process

```
try {
            if ("/services".equals(uri)) {	// services mapping
            	// ....
            } else {

                // valid
                if (requestBytes.length == 0) {
                    throw new XxlRpcException("xxl-rpc request data empty.");
                }

               // ...
            }
} catch (Exception e) {
	// ...
}
```

应该是有个进程不断非法访问9999端口导致的。我这里是docker的健康检查一直访问9999端口，后面改掉了。

**Comment by zzjjff11** [comment]
@hylexus 我也遇到相同的问题了，是这里出的问题，那运维需要怎么配合呢 能不呢具体说一下解决办法

**Comment by hylexus** [comment]
@zzjjff11 就是说有进程在访问9999端口。
比如类似 `curl http://127.0.0.1:9999` 这种用来健康检查的定时执行的脚本。
我这里是把这个端口用来做docker容器的健康检查的时候出的问题……

**Comment by geutopia** [comment]
> @hylexus 我也遇到相同的问题了，是这里出的问题，那运维需要怎么配合呢 能不呢具体说一下解决办法

看看在注册中心是不是有业务使用相同的端口,   大概率是端口冲突.  (虽然另外一个业务没有启动, 但是注册中心并没有把他下架,  而是不断的探测健康状态)
