### ISSUE TITLE
docker部署内存溢出报错

### ISSUE THREAD

**Issue by kervin521** [xuxueli/xxl-job#930]
Please answer some questions before submitting your issue. Thanks!

### Actual behavior
20:13:55.039 logback [getSchedulerFactoryBean_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger - Job (DEFAULT.50 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at com.xxl.job.admin.core.quartz.XxlJobThreadPool.runInThread(XxlJobThreadPool.java:17)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:398)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper.addTrigger(JobTriggerPoolHelper.java:69)
	at com.xxl.job.admin.core.thread.JobTriggerPoolHelper.trigger(JobTriggerPoolHelper.java:127)
	at com.xxl.job.admin.core.jobbean.RemoteHttpJobBean.executeInternal(RemoteHttpJobBean.java:30)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 2 common frames omitted

### Other information

**Comment by youzhanghao** [comment]
Try to run docker with  >>> -e JAVA_OPTS="-Xms512m -Xmx1024m"

**Comment by xuxueli** [comment]
你好，这是底层xxl-rpc v1.4.0的一个小概率问题。可以升级 xxl-rpc到 1.4.1版本。
或者升级xxl-job到v2.1.0版本（即将发布）；
