### ISSUE TITLE
执行器项目Connection reset by peer

### ISSUE THREAD

**Issue by hylexus** [xuxueli/xxl-job#932]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
 xxl-job-core:2.0.2
 xxl-rpc-core:1.4.0
 xxl-registry-client:1.0.2
### Actual behavior

执行器项目每天三四次 Connection reset by peer

2019-06-12 11:09:15.462 ERROR 1 --- [ntLoopGroup-3-4] c.x.r.r.n.i.n.s.NettyHttpServerHandler   : >>>>>>>>>>> xxl-rpc provider netty server caught exception

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_111]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_111]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_111]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_111]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_111]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125) ~[netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:582) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:536) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.35.Final.jar!/:4.1.35.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by xuxueli** [comment]
你好，可以升级 xxl-rpc 到 1.4.1。或者升级 xxl-job 到 2.1.0（即将发布）；

**Comment by hylexus** [comment]
@xuxueli thanks!

**Comment by xuyaokun-github** [comment]
我的xxl版本是2.1.2，springboot是2.7.12，一样会遇到Connection reset by peer
