### ISSUE TITLE
master分支拉取直接部署admin失败

### ISSUE THREAD

**Issue by hyz1994121** [xuxueli/xxl-job#959]
Please answer some questions before submitting your issue. Thanks!

Caused by: java.lang.NullPointerException: null
	at com.xxl.job.admin.core.util.I18nUtil.loadI18nProp(I18nUtil.java:32)
	at com.xxl.job.admin.core.util.I18nUtil.getString(I18nUtil.java:53)
	at com.xxl.job.admin.core.conf.XxlJobScheduler.initI18n(XxlJobScheduler.java:82)
	at com.xxl.job.admin.core.conf.XxlJobScheduler.afterPropertiesSet(XxlJobScheduler.java:42)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)

在ubuntu机器上面启动admin下面打包成的jar包提示启动失败, XxlJobAdminConfig 类中的adminConfig 没有在afterPropertiesSet()之后被赋值,所以导致失败, 在mac上和在centos上都没有问题,请问该如何修复

### Which version of XXL-JOB do you using?
master
### Expected behavior
正常启动
### Other information

**Comment by xuxueli** [comment]
你好，问题无法复现，请进一步提供复现步骤。

**Comment by hyz1994121** [comment]
我就是在master分支下的代码，直接在我的一台ubuntu18的台式机上面执行的操作，mvn clean package，然后到admin模块文件夹下面target目录执行java -jar 对应生成的jar包。同样的代码在mac和centos下面可以运行，在这台机器上面就报启动上述错误

**Comment by wz2cool** [comment]
同样报这个错误 本地执行好的 打包上服务器就不行，  看了别人有同样issue https://github.com/xuxueli/xxl-job/issues/1057

**Comment by morningcat2018** [comment]
表示遇到同样的问题，同一版本（2.1.0），在mac上打包（mvn clean package）部署（java -jar xxl-job-admin-2.1.0.jar）是成功，在Linux上同样的步骤进行打包部署却失败了：


Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
16:40:12.633 logback [main] ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxlJobScheduler' defined in URL [jar:file:/home/app/workspace/services/xxl-job-2.1.0/xxl-job-admin/target/xxl-job-admin-2.1.0.jar!/BOOT-INF/classes!/com/xxl/job/admin/core/conf/XxlJobScheduler.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
        at com.xxl.job.admin.XxlJobAdminApplication.main(XxlJobAdminApplication.java:13)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NullPointerException: null
        at com.xxl.job.admin.core.util.I18nUtil.loadI18nProp(I18nUtil.java:32)
        at com.xxl.job.admin.core.util.I18nUtil.getString(I18nUtil.java:53)
        at com.xxl.job.admin.core.conf.XxlJobScheduler.initI18n(XxlJobScheduler.java:83)
        at com.xxl.job.admin.core.conf.XxlJobScheduler.afterPropertiesSet(XxlJobScheduler.java:43)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
        ... 24 common frames omitted
@xuxueli

**Comment by denghc0607** [comment]
遇到了同样的问题 v2.1.0
