### ISSUE TITLE
com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer

### ISSUE THREAD

**Issue by wuxinyun** [xuxueli/xxl-job#965]
2019-06-21 17:19:36.823 ERROR [xxl-rpc, NettyHttpServer-serverHandlerPool-1374303997] com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler jar:file:/Users/wuxinyun/Downloads/repository/com/caucho/hessian/4.0.60/hessian-4.0.60.jar!/META-INF/hessian/serializers: com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer
com.caucho.hessian.HessianException: jar:file:/Users/wuxinyun/Downloads/repository/com/caucho/hessian/4.0.60/hessian-4.0.60.jar!/META-INF/hessian/serializers: com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer
	at com.caucho.hessian.io.ContextSerializerFactory.initSerializerFiles(ContextSerializerFactory.java:388)
	at com.caucho.hessian.io.ContextSerializerFactory.init(ContextSerializerFactory.java:296)
	at com.caucho.hessian.io.ContextSerializerFactory.<init>(ContextSerializerFactory.java:124)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:149)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:127)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:120)
	at com.caucho.hessian.io.SerializerFactory.createDefault(SerializerFactory.java:151)
	at com.caucho.hessian.io.Hessian2Input.findSerializerFactory(Hessian2Input.java:173)
	at com.caucho.hessian.io.Hessian2Input.readObjectDefinition(Hessian2Input.java:2192)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2131)
	at com.xxl.rpc.serialize.impl.HessianSerializer.deserialize(HessianSerializer.java:49)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:82)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
com.caucho.hessian.HessianException: jar:file:/Users/wuxinyun/Downloads/repository/com/caucho/hessian/4.0.60/hessian-4.0.60.jar!/META-INF/hessian/serializers: com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer
	at com.caucho.hessian.io.ContextSerializerFactory.initSerializerFiles(ContextSerializerFactory.java:388)
	at com.caucho.hessian.io.ContextSerializerFactory.init(ContextSerializerFactory.java:296)
	at com.caucho.hessian.io.ContextSerializerFactory.<init>(ContextSerializerFactory.java:124)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:149)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:127)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:120)
	at com.caucho.hessian.io.SerializerFactory.createDefault(SerializerFactory.java:151)
	at com.caucho.hessian.io.AbstractHessianOutput.findSerializerFactory(AbstractHessianOutput.java:107)
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:463)
	at com.xxl.rpc.serialize.impl.HessianSerializer.serialize(HessianSerializer.java:23)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.process(NettyHttpServerHandler.java:103)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler.access$000(NettyHttpServerHandler.java:27)
	at com.xxl.rpc.remoting.net.impl.netty_http.server.NettyHttpServerHandler$1.run(NettyHttpServerHandler.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-06-21 17:19:59.827 INFO [xxl-job, executor ExecutorRegistryThread] com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean >>>>>>>>>>> xxl-rpc, invoke error, address:http://127.0.0.1:8080/xxl-job-admin/api, XxlRpcRequestXxlRpcRequest{requestId='41c555bf-e664-4219-9b60-315f6cf4b1d8', createMillisTime=1561108799826, accessToken='', className='com.xxl.job.core.biz.AdminBiz', methodName='registry', parameterTypes=[class com.xxl.job.core.biz.model.RegistryParam], parameters=[RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-yunqin-sample', registryValue='30.5.40.43:8889'}], version='null'}
2019-06-21 17:19:59.828 INFO [xxl-job, executor ExecutorRegistryThread] com.xxl.job.core.thread.ExecutorRegistryThread >>>>>>>>>>> xxl-job registry error, registryParam:RegistryParam{registGroup='EXECUTOR', registryKey='xxl-job-yunqin-sample', registryValue='30.5.40.43:8889'}
com.xxl.rpc.util.XxlRpcException: com.caucho.hessian.HessianException: jar:file:/Users/wuxinyun/Downloads/repository/com/caucho/hessian/4.0.60/hessian-4.0.60.jar!/META-INF/hessian/serializers: com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:227)
	at com.sun.proxy.$Proxy133.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.caucho.hessian.HessianException: jar:file:/Users/wuxinyun/Downloads/repository/com/caucho/hessian/4.0.60/hessian-4.0.60.jar!/META-INF/hessian/serializers: com.caucho.hessian.io.LocaleSerializer is invalid because it does not implement com.caucho.hessian.io.Serializer
	at com.caucho.hessian.io.ContextSerializerFactory.initSerializerFiles(ContextSerializerFactory.java:388)
	at com.caucho.hessian.io.ContextSerializerFactory.init(ContextSerializerFactory.java:296)
	at com.caucho.hessian.io.ContextSerializerFactory.<init>(ContextSerializerFactory.java:124)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:149)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147)
	at com.caucho.hessian.io.ContextSerializerFactory.create(ContextSerializerFactory.java:147)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:127)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:120)
	at com.caucho.hessian.io.SerializerFactory.createDefault(SerializerFactory.java:151)
	at com.caucho.hessian.io.AbstractHessianOutput.findSerializerFactory(AbstractHessianOutput.java:107)
	at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:463)
	at com.xxl.rpc.serialize.impl.HessianSerializer.serialize(HessianSerializer.java:23)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:101)
	at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
	... 3 common frames omitted

**Comment by wuxinyun** [comment]
xxl-job-2.0.2-release 版本

**Comment by wuxinyun** [comment]
<dependency>
                <groupId>com.xuxueli</groupId>
                <artifactId>xxl-job-core</artifactId>
                <version>2.0.2</version>
            </dependency>

Hessian 4.0.60

**Comment by xuxueli** [comment]
你好，问题无法复现。请确认调度中心与执行器的xxl-job-core和hessian版本是否一致。

**Comment by DongWeiMa** [comment]
i had the same question

**Comment by DongWeiMa** [comment]
![image](https://user-images.githubusercontent.com/12246952/61690293-92523100-ad5b-11e9-8d4a-6a0b1df1320c.png)

**Comment by DongWeiMa** [comment]
2.1.0

**Comment by hung001** [comment]
dude,have you solved it yet
