### ISSUE TITLE
docker下报错

### ISSUE THREAD

**Issue by kervin521** [xuxueli/xxl-job#973]
Please answer some questions before submitting your issue. Thanks!

### Which version of XXL-JOB do you using?
xxl-job-core v2.0.2
### Actual behavior
java.io.IOException: Not a directory
at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_212]
at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_212]
at com.xxl.job.core.log.XxlJobFileAppender.appendLog(XxlJobFileAppender.java:104) [xxl-job-core-2.0.2.jar!/:?]
at com.xxl.job.core.log.XxlJobLogger.logDetail(XxlJobLogger.java:43) [xxl-job-core-2.0.2.jar!/:?]
at com.xxl.job.core.log.XxlJobLogger.log(XxlJobLogger.java:66) [xxl-job-core-2.0.2.jar!/:?]
at com.xxl.job.core.thread.JobThread.run(JobThread.java:173) [xxl-job-core-2.0.2.jar!/:?]
### Other information
xxl.job.executor.logpath=/dev/null
应用服务集成执行器一直报这个错

**Comment by xuxueli** [comment]
你好，“xxl.job.executor.logpath” 配置为执行器日志路径配置，要确认该路径合法，且存在读写权限。
