### ISSUE TITLE
当心跳和调度同一时刻执行，会报com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at

### ISSUE THREAD

**Issue by jesse-tang** [xuxueli/xxl-job#987]
INFO c.x.r.r.i.r.XxlRpcReferenceBean - >>>>>>>>>>> xxl-rpc, invoke error, address:172.17.30.158:7401, XxlRpcRequestXxlRpcRequest{requestId='908b3f35-e11d-4247-a28d-2956bb0768ad', createMillisTime=1562288400214, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='beat', parameterTypes=[], parameters=null, version='null'}
09:00:10.216 xxl-job-admin [xxl-job, admin JobTriggerPoolHelper-fastTriggerPool-1132169857] ERROR c.x.j.a.core.route.ExecutorRouter - xxl-rpc, request timeout at:1562288410214, request:XxlRpcRequest{requestId='908b3f35-e11d-4247-a28d-2956bb0768ad', createMillisTime=1562288400214, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='beat', parameterTypes=[], parameters=null, version='null'}
com.xxl.rpc.util.XxlRpcException: xxl-rpc, request timeout at:1562288410214, request:XxlRpcRequest{requestId='908b3f35-e11d-4247-a28d-2956bb0768ad', createMillisTime=1562288400214, accessToken='', className='com.xxl.job.core.biz.ExecutorBiz', methodName='beat', parameterTypes=[], parameters=null, version='null'}
at com.xxl.rpc.remoting.net.params.XxlRpcFutureResponse.get(XxlRpcFutureResponse.java:117)
at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:219)
at com.sun.proxy.$Proxy81.beat(Unknown Source)
at com.xxl.job.admin.core.route.strategy.ExecutorRouteFailover.route(ExecutorRouteFailover.java:26)
at com.xxl.job.admin.core.trigger.XxlJobTrigger.processTrigger(XxlJobTrigger.java:137)
at com.xxl.job.admin.core.trigger.XxlJobTrigger.trigger(XxlJobTrigger.java:74)
at com.xxl.job.admin.core.thread.JobTriggerPoolHelper$3.run(JobTriggerPoolHelper.java:77)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

ERROR c.x.r.r.n.i.n.c.NettyHttpClientHandler - >>>>>>>>>>> xxl-rpc netty_http client caught exception
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)收起

**Comment by jesse-tang** [comment]
初步怀疑是ConnectClient这个类的连接的问题：
 // lock
        Object clientLock = connectClientLockMap.get(address);
        if (clientLock == null) {
            connectClientLockMap.putIfAbsent(address, new Object());
            clientLock = connectClientLockMap.get(address);
        }

        // remove-create new client
        synchronized (clientLock) {

            // get-valid client, avlid repeat
            connectClient = connectClientMap.get(address);
            if (connectClient!=null && connectClient.isValidate()) {
                return connectClient;
            }

            // remove old
            if (connectClient != null) {
                connectClient.close();
                connectClientMap.remove(address);
            }

            // set pool
            ConnectClient connectClient_new = connectClientImpl.newInstance();
            connectClient_new.init(address, xxlRpcReferenceBean.getSerializer(), xxlRpcReferenceBean.getInvokerFactory());
            connectClientMap.put(address, connectClient_new);

            return connectClient_new;

**Comment by xuxueli** [comment]
你好，超时发生在 ”XxlRpcFutureResponse.get "，说明RPC请求已经发送出去了，并不是获取连接的时候的发生问题，是在等待远程服务响应的时候超时了。
可以排查下调度地址对应的服务是否启动，网络是否通畅等。
