### ISSUE TITLE
请问下使用V2.1.0的时候 系统报这个

### ISSUE THREAD

**Issue by Jezzlouis** [xuxueli/xxl-job#999]
Exception in thread "xxl-job, executor ExecutorRegistryThread" java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpHeaderNames
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpConnectClient.send(NettyHttpConnectClient.java:104)
	at com.xxl.rpc.remoting.net.common.ConnectClient.asyncSend(ConnectClient.java:45)
	at com.xxl.rpc.remoting.net.impl.netty_http.client.NettyHttpClient.asyncSend(NettyHttpClient.java:18)
	at com.xxl.rpc.remoting.invoker.reference.XxlRpcReferenceBean$1.invoke(XxlRpcReferenceBean.java:216)
	at com.sun.proxy.$Proxy157.registry(Unknown Source)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:48)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpHeaderNames
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by Jezzlouis** [comment]
<dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.1.0</version>
        </dependency>  maven依赖是这个样

**Comment by Jezzlouis** [comment]
###  maven依赖是这样

            <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId>
            <version>2.1.0</version>
        </dependency>

**Comment by zhangbo1201** [comment]
你好，请问后来怎么解决的
